### ISSUE TITLE
Telegram notification error 400 (in logs) when requesting media

### ISSUE THREAD

**Issue by Moerderbeer** [sct/overseerr#1010]
#### Description

Set Application with domain style (**this.ismytitle.com**) will result in a notification error 400 when requesting a media, and not send a notification to Telegram. 
Testing a notification however, still works!

#### Version

develop-5acd91bc8e74eaacdf33dffa07dd10f1e53a9f8c

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Go to General Settings
2. Set Appication Title to this.ismytitle.com
3. Request a media
4. See error 400 in log: [error][Notifications]: Request failed with status code 400. No notification will be received in Telegram channel

#### Expected Behavior

Because testing the notification still works, I would expect to also work when placing a request.

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Synology / docker
- **OS:** Synoloigy DSM 6.2.3-25426 Update 3

#### Additional Context

Setting Application Title to something without periods solves this problem, i.e. **ThisIsMyTitle**

**Comment by TheCatLady** [comment]
I suspect this is because Telegram requires certain characters to be escaped when using Markdown to format messages.  We can simply switch to HTML formatting to solve this issue.

https://core.telegram.org/bots/api#formatting-options

**Comment by bgktmxg** [comment]
Im now getting this error but only with the new notification area in the users account.
![screenshot 4540](https://user-images.githubusercontent.com/51685078/110734291-3f502900-8273-11eb-8a2d-05cb4126e2dd.jpg)
I can log a new fault if required.
Thanks
