### ISSUE TITLE
Telegram Notifications

### ISSUE THREAD

**Issue by bgktmxg** [sct/overseerr#1018]
**Description**
Would love to be able to set multiple instances of a notification, telegram in my case. I currently have a telegram chat with just myself and I have everything ticked on to go there (requested, approved, available, failed etc). Ideally I could create a second telegram notification that only sends approved and available messages, and I could set this to the chat ID that has all the members of my Plex group.

Cheers for all the work on this awesome app

**Comment by costaht** [comment]
I bit different but you'll be able to accomplish the same result. Soon will be able to send notifications to the user who requested the title. #499 
You could set all the users with the same chat Id

**Comment by bgktmxg** [comment]
Ah yeah perfect, so I can just go through and add the chat ID to every user (once the feature is implemented) and all 'approved' messages will go to the one group chat, that works.

Any idea on timeline for the change?

Thanks

**Comment by sct** [comment]
> Ah yeah perfect, so I can just go through and add the chat ID to every user (once the feature is implemented) and all 'approved' messages will go to the one group chat, that works.
> 
> Any idea on timeline for the change?
> 
> Thanks

No real timeline. It will be done when we can get to it. 😄 

Closing this in favor of #499
