### ISSUE TITLE
Requesting 4K does nothing if the Movie / Show already exists on Radarr / Sonarr

### ISSUE THREAD

**Issue by tdeverx** [sct/overseerr#1028]
#### Description

I handle Full HD and Ultra HD all on the same instance of Sonarr / Radarr through different profiles. I requested a Movie in 4K that already exists on Radarr and while the request went through, it didn't update the Movie on Radarr with the new profile and it didn't start searching for it.

#### Version

develop-09b5019e95c5d8392a286d74bf7bec23be5d766b

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Setup regular and 4K Radarr / Sonarr on the same instance.
2. Request 4K for something that's already available.
3. Notice nothing happens.

#### Expected Behavior

Expected behaviour would be to update the existing movie with the new profile and search for a new version of the Movie / Show. This should also update the path (if different) and include an option to not move the old files from the old path to the new one.

#### Screenshots

N/A

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Desktop / NAS
- **Device:** MacBook Pro / Synology DS918+
- **OS:** Mac OS Big Sur / DSM 6.2.3-25426 Update 3 (Docker)
- **Browser:** Safari

#### Additional Context

N/A

**Comment by TheCatLady** [comment]
I believe this is the expected behavior. You need multiple Radarr/Sonarr instances to manage 4K content.

**Comment by tdeverx** [comment]
> I believe this is the expected behavior. You need multiple Radarr/Sonarr instances to manage 4K content.

I have had no issues with running both my Full HD and 4K Movies and Shows from the same instance. While I understand some may say its unconventional, in some cases there's no need to have two instances running. I'll agree that my comment:
> This should also update the path (if different) and include an option to not move the old files from the old path to the new one.
is a bit of a stretch that even I wouldn't benefit from as I only keep 1 version of a Movie / Show regardless of the quality and keep them saved in the same location.

<img width="1080" alt="Screenshot 2021-02-25 at 15 42 18" src="https://user-images.githubusercontent.com/44447832/109178440-c3d57e80-7780-11eb-9249-891eb524e4b6.png">

You can see from the screenshot above how I setup my profiles for control and I'm sure you could agree at the very least, if something already exists it should update the item rather than ignore it, making this a bug?

**Comment by TheCatLady** [comment]
@tdeverx Unfortunately, this is a limitation of how Overseerr works today. We do not support updating/changing requests once they are sent to Radarr/Sonarr.

Also, if an item exists in Radarr/Sonarr and sync is enabled, we update the relevant availability status for either non-4K or 4K based on the server type.  This means that if both your non-4K and 4K services defined in Overseerr point to the same Radarr/Sonarr instance and you enable sync for those services, the media availability in Overseerr will always be the same for both non-4K and 4K.

This may change in the future, but we do not currently support your use case.  Currently, it is a requirement for there to be separate Radarr/Sonarr instances for non-4K and 4K.
