### ISSUE TITLE
High priority checkbox

### ISSUE THREAD

**Issue by WoisWoi** [sct/overseerr#1032]
#### Description

It would be nice to be able to add a "high priority" option for users when making the request.

Why ?
Two cases of figures : 

1) The request is well processed by *arr, but it is at the bottom of the download list, in case the user has checked the "high priority" box and an admin see it (we could also create notifications specific to this type of request), he will be able to pass the download of the torrent in priority. 
2) In the event that *arr does not find anything to download, it is often possible to find the requested media, but manually. In this case, having a notion of interest or priority of the request, would be usefull when it comes to deal with the request as best as possible.

#### Desired Behavior

In the request "menu" add a checkbox "High priority".

**Comment by TheCatLady** [comment]
I don't know how useful this would be... isn't it likely that users would just mark all of their own requests as "high priority"?  We have filters on the request list to enable you to see which requests are available and which are still outstanding. As an admin, can't you simply review those requests and take appropriate actions in response?

I think that a better option would be to wait until voting has been implemented in Overseerr.  We could add additional filtering/sorting to the request list view to make it easier for admins to find processing requests that are of interest to multiple users.

**Comment by WoisWoi** [comment]
> 
> 
> I don't know how useful this would be... isn't it likely that users would just mark all of their own requests as "high priority"? We have filters on the request list to enable you to see which requests are available and which are still outstanding. As an admin, can't you simply review those requests and take appropriate actions in response?
> 
> I think that a better option would be to wait until voting has been implemented in Overseerr. We could add additional filtering/sorting to the request list view to make it easier for admins to find processing requests that are of interest to multiple users.

I’m sorry, I didn’t make myself clear.
Some users do not intend to quickly watch the media for which they have made requests, they just want to see the media in question, for example, next week, while other users, would like to be able to see the media the same day for example. This checkbox, would make the difference between these two categories of request.
That would be an indicator for the administrators, to know whether it’s useful for them to take the time to deal with it quickly.

**Comment by samwiseg0** [comment]
Whats stopping them from clicking that box every time? Why cant they communicate that to the admin through some other means? 

I personally see no point of having a check box for something that provides really no functionality other than some label that says do this now? I see many other ways of accomplishing this that is simpler and or the admin should just review requests in a timely manner?

**Comment by WoisWoi** [comment]
> 
> 
> Whats stopping them from clicking that box every time? Why cant they communicate that to the admin through some other means?
> 
> I personally see no point of having a check box for something that provides really no functionality other than some label that says do this now? I see many other ways of accomplishing this that is simpler and or the admin should just review requests in a timely manner?

Then maybe we could add a "comment section" when doing the request

**Comment by costaht** [comment]
Also, the priority is set in the download client, and Overseerr does not interact with any.

**Comment by sct** [comment]
I don't see a reason for this feature. Comments may come with decline reasons in a future update, but if someone is requesting something, approve it? I don't understand why there needs to be a separate priority.

**Comment by WoisWoi** [comment]
> 
> 
> I don't see a reason for this feature. Comments may come with decline reasons in a future update, but if someone is requesting something, approve it? I don't understand why there needs to be a separate priority.

I'm using auto-approve for all the request.

**Comment by WoisWoi** [comment]
> 
> 
> Also, the priority is set in the download client, and Overseerr does not interact with any.

I know, I'm not asking Overseerr to change it. The idea is to know how much the applicant is in a hurry
