### ISSUE TITLE
Unable to Connect To Sonarr 

### ISSUE THREAD

**Issue by rguinn829** [sct/overseerr#1044]
#### Description

Please provide a clear and concise description of the bug or issue.

When attempting to connect Sonarr server it will fail 

![image](https://user-images.githubusercontent.com/4206745/109396231-37e56300-78f6-11eb-8c45-60423b022aff.png)

#### Version

1.20.0

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Go to [...] Setting
2. Click on [...] Services
3. Scroll down to [...] Sonarr Setting - > You Configured Server - > Test  
4. See error in [...] Failed to Connect to Server

#### Expected Behavior

Please provide a clear and concise description of what you expected to happen.

#### Screenshots

If applicable, please provide screenshots depicting the problem.

see this 
![image](https://user-images.githubusercontent.com/4206745/109396333-96aadc80-78f6-11eb-8625-805ec537c70e.png)

https://forums.unraid.net/topic/100124-support-diamkil-overseerr/page/2/?_fromLogin=1

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Chrome web
- **Device:** Desktop
- **OS:** Windows 10
- **Browser:** Chrome
- SERVER: UNRAID DOCKER 
- 
#### Additional Context

Please provide any additional information that may be relevant or helpful.

https://forums.unraid.net/topic/100124-support-diamkil-overseerr/page/2/?_fromLogin=1

**Comment by rguinn829** [comment]
Hello. I believe this is a Bug as multiple users are experiencing it. and i have reinstalled both applications

**Comment by rguinn829** [comment]
Anyone reviewing this the issue is fixed by upgrading to the BETA version. This seems to be a bug with them accessing the V2 of Sonarr but if you upgrade to the unstable version of Sonarr V3 it does seem to work again. 

I am really liking overseerr but this is a bug that they are not address instead telling people to upgrade to other beta software. and V2 was working till this weeks so you are forced to upgrade to beta Sonarr. 

Keep up the work to improve Overseerr

**Comment by samwiseg0** [comment]
@rguinn829 We have never supported v2 of sonarr or radarr. The recent changes in overseerr change re-enforces this by only using the latest version of the API. The recommended version that sonarr and radarr suggest you install is v3. v3 has been in "testing" for years. It is very stable. If you have any further questions or issues please feel free to stop by the discord server.
