### ISSUE TITLE
Cannot test or enable sonarr service

### ISSUE THREAD

**Issue by carroarmato0** [sct/overseerr#1048]
#### Description

Unable to add Sonaar due to potentially wrong API requests?

#### Version

Overseerr:     1.20.1
Sonarr:          2.0.0.5344

#### Steps to Reproduce

Add Sonarr through Settings -> Services.

Make sure to fill in the necessary options (API key etc...)

Pressing "Test" will result in the:
- Quality Profile
- Root Folder
- Language Profile
- Anime Quality Profile
- Anime Root Folder
- Anime Language Profile

to not be fetched from Sonarr.

#### Expected Behavior

Overseerr able to fetch the missing required information and enable the Sonarr server.

#### Screenshots

not applicable 

#### Device

not applicable

#### Additional Context

In the logs the following is mentioned:

```
2021-02-28T15:30:47.866Z [[31merror[39m][Sonarr API]: Request failed with status code 404
2021-02-28T15:30:47.866Z [[31merror[39m][Sonarr]: Failed to get profiles
2021-02-28T15:30:49.937Z [[31merror[39m][Sonarr API]: Request failed with status code 404
2021-02-28T15:30:49.938Z [[31merror[39m][Sonarr]: Failed to get profiles
```

**Comment by sct** [comment]
We only support Sonarr v3 or higher as of version 1.20.0. You will need to upgrade.

**Comment by carroarmato0** [comment]
Thanks
