### ISSUE TITLE
Abillity to request a movie or show in two qualities HD and 4k

### ISSUE THREAD

**Issue by cyb3rgh05t** [sct/overseerr#1049]
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

Not related to  problem. Only a request.

#### Desired Behavior

Provide a clear and concise description of what you want to happen.

Having the possibiltiy to request a movie or show in two qualities. Like HD and 4K

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

The user could request a movie or show in both qualities (HD and 4K). For now i think we can only choice between both qualtites.

**Comment by sct** [comment]
You can already do this.
