### ISSUE TITLE
Steps for manual updates

### ISSUE THREAD

**Issue by aniqueta** [sct/overseerr#1059]
#### Description

Per #528 there appears to be a pathway to manually update when manually building the app (for those of us who are unable to use Docker). Could we please update the contributing or other read me with the right steps steps?

#### Actual / Desired Behavior

To attempt to manually update, I followed these steps:
1) Shut down Overseerr
2) Cloned repository
3) Copied old /config directory in
4) Ran yarn && yarn build && yarn start

This lagely worked but it led to some random 500 internal server errors and to Overseerr thinking I was running a forked dev build. 

Is that to be expected in this alpha stage, as settings and db structure are changing? Is there something else happening in the Docker updates that we can manually mimic to preserve past settings and db without breaking things? Thank you.

**Comment by samwiseg0** [comment]
Unfortunately, we do not support building the app yourself. You have to use one of the supported install methods. If you want to build and use the app on your own we cannot offer any assistance. We do not offer any documentation for this reason.

**Comment by aniqueta** [comment]
@samwiseg0 Understand. I was able to get the above to work after some fiddling; honestly, not sure what changed. 

Just want to note the supported methods are not an option for everyone. In my case, Linux is not my primary OS on my server and running Docker would then mean taking the performance tax of a virtual machine and storage accessed as shared network drives. 

In the past, I read in the read me that there was a plan to have native executables (like Ombi) once the project matured (not asking for this now of course). I see that mention has been removed from the read me, but hope it's still in the plans. (Note, this build option is still miles better than Ombi, so really appreciate the work here. :)

**Comment by samwiseg0** [comment]
I understand. 

> Linux is not my primary OS on my server and running Docker would then mean taking the performance and energy consumption tax of a virtual machine and storage accessed as shared network drives.

I disagree with this point as we strongly urge folks to use WSL2 to mitigate the issues you mentioned. 
https://towardsdatascience.com/how-to-improve-docker-performance-with-wsl2-3a54402ab0f2

**Comment by aniqueta** [comment]
@samwiseg0 Thanks. I use macOS, and this is a multipurpose machine requiring sticking with this platform. Docker on Mac has storage limitations that are no longer going to be addressed by Mutagen (which is less of an issue for an app like this) and there has never been a pathway to get around needing to virtualize Linux. I'm not versed in how to package this for macOS, but given it builds out of the box with packages from Homebrew, I'm good for now and would ask that when things mature a native macOS build is considered for ease of use and for other folks. Thanks again.
