### ISSUE TITLE
Can't connect to Sonarr

### ISSUE THREAD

**Issue by pg0581** [sct/overseerr#1066]
#### Description

Unable to connect to Sonarr. This could be an issue unique to my environment but since this is in Alpha I would like to see if maybe there is an app issue or something else I can't think of.

#### Version

1.20.1

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1) Open overseerr
2) Navigate to Settings > Sonarr Settings > Click "+Add Sonarr Server"
3) Fill out required fields

#### Expected Behavior

When setting up a Sonarr server for it to connect. Setting up Radarr was successful

#### Screenshots

I've provided the required fields:

If applicable, please provide screenshots depicting the problem.
![image](https://user-images.githubusercontent.com/40769895/109708563-91a19380-7b69-11eb-92b0-d10764eb4a68.png)

Upon testing this error appears:
![image](https://user-images.githubusercontent.com/40769895/109708676-b4cc4300-7b69-11eb-9094-7f5efbbe2840.png)

Checking the overseerr logs I'm getting a 404, but not sure why:
![image](https://user-images.githubusercontent.com/40769895/109708782-d7f6f280-7b69-11eb-9590-5cc73d0c1eaf.png)

#### Device

- **Platform:** Unraid -- Version 6.8.3 

#### Additional Context

- I've tried restarting Sonarr, regenerating the API key (and restarting the server) 
- The Sonarr server is reachable on my local network
- As mentioned above, I have successfully integrated Radarr

**Comment by samwiseg0** [comment]
Only sonarr v3 is supported
