### ISSUE TITLE
Base path?

### ISSUE THREAD

**Issue by y0dase** [sct/overseerr#1091]
Hi, 

Not sure if this should be filed as a bug or feature request... 
I want to have Overseer behind my reverse proxy as domain.com/overseer. But when I do this I'm redirected to domain.com/login which of course does not exist.. For other *arr I can setup a base path for this, so I assume this feature is missing in Overseer? 
Or am I missing something? :P 

//y0da

**Comment by samwiseg0** [comment]
please search in the future. https://github.com/sct/overseerr/issues/274
