### ISSUE TITLE
Add support for multiple Plex servers on a single Overseerr server

### ISSUE THREAD

**Issue by joeydoesthings** [sct/overseerr#1094]
#### Description

My problem is I have multiple plex servers that I'd like to integrate into the same overseer instance, and currently it only supports one plex server, but already has functionality to search for other servers on the account.

#### Desired Behavior

Add functionality to add a second, or more plex servers (libraries) to the Plex tab in Overseerr settings.

#### Additional Context

I separate my 4k server from my 1080p server for transcoding reasons, and also want to add another that I might set up with a google drive mount, which I also want to have separate plex settings for, but don't want to get requests for content I already have on another server.

**Comment by sct** [comment]
There are no plans for supporting more than one Plex server. I recommend either multiple Overseerr instances or combining your libraries and using something like a Tautulli kill stream script to stop people from transcoding 4k.
