### ISSUE TITLE
Approve/Decline/Edit for Available show and under Processing category

### ISSUE THREAD

**Issue by Reddax** [sct/overseerr#1096]
#### Description
A show that I manually approved is still showing the Approve/Decline/Edit and is under the pending category, even though it shows as available. I'm unable to click the buttons.

#### Version

develop-2771376ecc5e80293d9ac6039b90c0fe7719e09d

#### Steps to Reproduce

1. Get a request through that isn't auto-approved that has the status of 'Pending'
2. Manually approve the item
3. It should still show the approve/decline/edit and be under the Pending category, even though it shows as available.

#### Expected Behavior

When manually approved, it should be under the 'Available' Category and not show the approve/decline/edit buttons

#### Screenshots

![image](https://user-images.githubusercontent.com/1349626/110110516-db2af200-7da6-11eb-8d37-7b25e4d99932.png)

#### Device

Desktop - Chrome W10. - tried clearing cache, incognito etc.
Mobile

**Comment by TheCatLady** [comment]
@Reddax Can you provide logs? https://docs.overseerr.dev/support/asking-for-support#how-can-i-share-my-logs

**Comment by Reddax** [comment]
> @Reddax Can you provide logs? https://docs.overseerr.dev/support/asking-for-support#how-can-i-share-my-logs
Here you go :)
https://gist.github.com/Reddax/ce4a6ca229809fe84e98cec1ed709da5

**Comment by Reddax** [comment]
Just had it pop up for another show, this time I didn't manually approve, it did it through an incremental crawl.
![image](https://user-images.githubusercontent.com/1349626/110117246-81c7c080-7db0-11eb-8c4d-35c16ea35db9.png)

New logs to hopefully capture it;
https://gist.github.com/Reddax/80627078d0851586bce66825b8400176

**Comment by TheCatLady** [comment]
@Reddax thanks so much for sharing the logs!  I am looking into this.

**Comment by sct** [comment]
If you refresh the request list this doesn't go away, right?

**Comment by Reddax** [comment]
> If you refresh the request list this doesn't go away, right?

Nah. They're still there, 4 days later. So closing/reopening browsers, using different browsers on different pcs/mobiles, reset cache etc haven't sorted it

**Comment by sct** [comment]
Odd. It's definitely a desync between the request entity and the media entity's status, but I am struggling to reproduce it. 🤔
