### ISSUE TITLE
No notifications when media is requested

### ISSUE THREAD

**Issue by mhbates** [sct/overseerr#1130]
#### Description

Email notifications are set up and test is successful. Media requests do not appear to send a notification, whether for TV (manual approval) or movies (auto-approval). Notifications are enabled for both. The Media Requested notification type is enabled for the email agent.

#### Version

1.20.1

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Server
- **OS:** Debian 10 running the docker

**Comment by mhbates** [comment]
Also, there is nothing in the log indicating the Media Requested notification went out, although the Media Approved notification did.

`2021-03-09T00:57:28.122Z [info][Notifications]: Sending notification for MEDIA_APPROVED`

And it looks like the logs have their own timezone, not following the timezone env variable set in the docker run. But this is a separate issue.

**Comment by TheCatLady** [comment]
@mhbates "Media Requested" notifications are not sent when media is automatically approved.

**Comment by mhbates** [comment]
> 
> 
> @mhbates "Media Requested" notifications are not sent when media is automatically approved. "Media Requested" notifications are only sent for requests which require approval/action from an admin.

Even when the "Enable Notifications for Automatic Approvals" is enabled?

This also happened with a TV show request, which requires approval. There was no media requested notification for that.

**Comment by TheCatLady** [comment]
> Even when the "Enable Notifications for Automatic Approvals" is enabled?

Yes.  Only the "Media Approved" notification will trigger in those cases.

> This also happened with a TV show request, which requires approval. There was no media requested notification for that.

Can you provide logs for this?

**Comment by mhbates** [comment]
Scratch that, apparently it was a TV special movie. Thank you for your help.
