### ISSUE TITLE
Requesting a TV show gives a Sonarr error: Invalid request Language profile does not exist

### ISSUE THREAD

**Issue by GiovanniK** [sct/overseerr#1147]
#### Description
I'm trying to add 'The Brave' to Sonarr, the request starts but after a couple of seconds it says failed.

#### Version
1.20.1

#### Steps to Reproduce
1. Search for 'The Brave'
2. Select all seasons or the first one - there's only one
3. Request it

#### Expected Behavior
Overseerr is expected to add the show to Sonarr

#### Device
Platform: Desktop
OS: Windows
Browser: Chrome

#### Additional Context
I've re-added Sonarr in the settings menu, did not work.
I tried changing the language from English to Dutch, didn't work either.

Sonarr logs show this:
Invalid request Validation failed:
-- LanguageProfileId: Language profile does not exist

I'm running Sonarr v3, requesting shows worked in the past.
I'm not sure when it got broken, I did upgrade the container today.

_This issue got locked in #1146, I am very confused on how this can be a support question. 
I've read my issue twice now and I am not seeing how this can be mistaken for a support question.
The functionality is completely broken for me, which it wasn't before._

**Comment by TheCatLady** [comment]
Hi, please post either in Discussions or in our DIscord server so we can help you out!
