### ISSUE TITLE
TV Shows are not marked as Available

### ISSUE THREAD

**Issue by ZephireNZ** [sct/overseerr#1153]
#### Description

TV Shows are not marked as Available.

#### Version

1.20.1

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Open Discover tab
2. See that TV shows are not marked Available
3. Re-scan Plex library
4. Observe same behaviour

#### Expected Behavior

Shows in Plex library are marked as Available

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Desktop
- **Device:** PC
- **OS:** Windows 10
- **Browser:** Chrome

#### Additional Context

I suspect this may be due to using the new Plex TV Agent.

**Comment by sct** [comment]
Support for the new plex TV agent was just added in the `develop` branch (see: https://github.com/sct/overseerr/commit/a51d2a24d51d092a0c6da608e3322f19a37c2d28). It will be in the next release.
