### ISSUE TITLE
Send email to user when request is Auto-Approved

### ISSUE THREAD

**Issue by johntrask** [sct/overseerr#1185]
#### Description

Is your feature request related to a problem? Not really, Coming from a different tool, my users were accustom to getting an email when they requested something, weather it was auto-approved or manually approved.

#### Desired Behavior

I would like to see an email go to the user no matter if it was auto-approved or manually approved.

**Comment by samwiseg0** [comment]
This has already been implemented. 
![Screen Shot 2021-03-15 at 2 41 39 PM](https://user-images.githubusercontent.com/2241731/111204550-9ec47680-859c-11eb-953b-2ad75553c2de.png)

If you need help feel free to stop by support.
