### ISSUE TITLE
Deleting request doesn't remove from Radarr

### ISSUE THREAD

**Issue by boultonn** [sct/overseerr#1195]
#### Description

After an item has been approved, if it's retrospectively deleted from Overseerr (either because of error or non availability), then it remains in Radarr which might download it in the future.

#### Version

1.21.1

#### Steps to Reproduce

Request and approve a new film.
Check it's been added to Radarr.
Delete request in Overseerr.
It remains in Radarr, where it must be separately deleted.

#### Expected Behavior

Either automatically delete from Radarr when it's deleted in Overseerr, or provide the option on whether to delete.

#### Screenshots

NA

#### Device

Desktop, Macbook Pro, macoOS 11.2.3, Firefox

#### Additional Context

NA

**Comment by samwiseg0** [comment]
This is not a bug. This is by design. Can you please re open this as an enhancement request?
