### ISSUE TITLE
Plex Server invalid csrf token

### ISSUE THREAD

**Issue by goharaziz338** [sct/overseerr#1198]
After last night's update, 1.21.1 I am getting an invalid csrf token when connecting to the Server on Local IP and Port.
Sonarr and Redarr is doing the same as well.

**Comment by TheCatLady** [comment]
The `Enable CSRF Protection` setting requires you to access Overseerr via HTTPS, as noted in the setting description.  You will not be able to access Overseerr via a local IP address if you have this setting enabled.
