### ISSUE TITLE
One click approve link/button in a media requested notification

### ISSUE THREAD

**Issue by samwiseg0** [sct/overseerr#1200]
#### Description

Once overseerr notifies you that there is a pending request. Provide a way for the admin to one click approve the request.

#### Desired Behavior

Provide a method to one click approve from a notification. Email, discord, etc. 

#### Additional Context

N/A

**Comment by samwiseg0** [comment]
Don't do it stalebot!

**Comment by zwimer** [comment]
For telegram, it could be implemented such that responding `/approve` or clicking an `approve` button that pops up or something like that approves the request. I imagine this holds true for other forms of notification that have as much bot support as telegram has.

**Comment by zwimer** [comment]
For things like telegram / instant messaging apps this could be really nice.

**Comment by zwimer** [comment]
This would make things quite a bit easier!

**Comment by schadis** [comment]
Would prefer telegram

**Comment by zwimer** [comment]
Telegram's bots got a large upgrade recently, in case that was holding this back somehow before.
