### ISSUE TITLE
Collapse sidemenu on tablet.

### ISSUE THREAD

**Issue by Zazou89** [sct/overseerr#1203]
#### Description

Hello,
We lost some space on mobile / tablet with sidemenu :

Example on iPad :
![09EB3959-8A73-46A5-A217-AC3C72DB6912](https://user-images.githubusercontent.com/206181/111395695-b9dad780-86bd-11eb-8810-316613e86fa5.jpeg)

#### Desired Behavior

Add an hamburger or collapse icon to reduce width.

**Comment by nicospz** [comment]
@sct Let me take this one!

**Comment by samwiseg0** [comment]
> @sct Let me take this one!

I have assigned this to you. Its all yours!
