### ISSUE TITLE
Image optization and website paint times

### ISSUE THREAD

**Issue by Wh1t3Rose** [sct/overseerr#1207]
#### Description

Please consider optimizing all your images within `/app/public/`. It can take a very long time to fully load the login page as well as load all the images on the Discover tab. 

It would also be nice if you can find a way to speed up the inital loadtime for images on the discover tab, It can take a very long time (sometimes 10+ seconds for all images to load). Maybe there is a way to compress these images as they load in before they are displayed?

#### Additional Context

You can use something like http://jpeg-optimizer.com/ to compress your images and reduce size over 75%. I have tested this with most of the images. 

Before Image Optimization

![image](https://user-images.githubusercontent.com/4251482/111508790-7797b180-8722-11eb-8638-01e3ed7b5461.png)

After Image Optimization (Notice Contentful Paint time adn Speed Index dropped significantly)

![image](https://user-images.githubusercontent.com/4251482/111509307-fa207100-8722-11eb-941a-cd8c619fa1f2.png)

**Comment by Wh1t3Rose** [comment]
I have not noticed a visable loss in quality at all with a compression level of 65 from http://jpeg-optimizer.com/.

I am working on setting up Nginx with redis cache in hopes of speeding up images on Discover Page. Any other ideas of speeding this up? I am already using Cloudflare CDN with caching

**Comment by sct** [comment]
We had the images optimized at some point but I think when I changed which images we were serving I forgot to reoptimize them. It seems that ImgBot also let the ball drop there. I will serve the images using `next/image` to solve the image size problem.

As for caching the rest of the assets, they are all being served by TMDb's CDN which should be fast. I was thinking about offering an option to locally cache the TMDb images as well with `next/image` as well, but it will come in the future.

**Comment by sct** [comment]
If your Discover page is taking over 10 seconds to load, you should probably check your connection to TMDb though? It loads near instantly for most people, I believe.

**Comment by sct** [comment]
I just pushed a fix for images on the login page. They will be served in an optimized format now.

**Comment by Wh1t3Rose** [comment]
Thank you! 

My Discover page takes 22s to load. Not sure why it is so high. 

Now my friend has a similar setup to mine and his takes 12s (A lot faster than mine but still sluggish)

We both have 1GB down connections

**Comment by sct** [comment]
> Thank you! 
> 
> 
> 
> My Discover page takes 22s to load. Not sure why it is so high. 
> 
> 
> 
> Now my friend has a similar setup to mine and his takes 12s (A lot faster than mine but still sluggish)
> 
> 
> 
> We both have 1GB down connections

That's in no way normal. Maybe hop into the Discord and ask in support. Something is going on here but it shouldn't be Overseerr.

**Comment by Wh1t3Rose** [comment]
Well I disabled Proxy Buffering and Request Buffering in my Nginx config and it significantly improved load times. 2.5 seconds with browser cache enabled and 3.1 seconds with browser cache turned off in Developer console. 

Overseer is the only thing this has affected. And I have around a dozen subdomains

**Comment by TheCatLady** [comment]
> Well I disabled Proxy Buffering and Request Buffering in my Nginx config and it significantly improved load times. 2.5 seconds with browser cache enabled and 3.1 seconds with browser cache turned off in Developer console.
> 
> Overseerr is the only thing this setting has affected. And I have around a dozen subdomains. Not sure what that means.
> 
> It may be worth noting I am hosting everything in a local Unraid server. Not a Shared hosting provider or VPS like a lot of people probably are.
> 
> Also I am using Nginx Proxy with Cloudflare CDN caching.

I run Overseerr behind an Nginx reverse proxy with proxy & request buffering both on (the default settings), with no issues with image load times.  My server is also on my LAN.  It seems like there is something else in your setup that is causing these issues.

Either way, we are now optimizing images.  If you continue to have issues, feel free to stop by our Discord server for support!
