### ISSUE TITLE
REQ: More filter option when searching

### ISSUE THREAD

**Issue by JorgenDomlin** [sct/overseerr#1217]
When you search for something like "The Batman" you get a lot of results, it's not clear what the listing filter is set to.
It's not Year and not Name, maybe rating?

It would be nice to be able to set the filter to Year, so you get the latest at the top.
Also would be great to be able to choose to only show Movies or Series

Optimal would be a drop down where you can choose from Year, Name, Rating, Studio, etc.
I don't know what attributes you have available on search but Year would be the one I miss the most.

Thank you for a amazing app, I've let some of my family and friends start to use it and the **LOVE IT** over Tautelli

Keep up the good work.

**Comment by samwiseg0** [comment]
Also this is a duplicate of https://github.com/sct/overseerr/issues/459.

In the future please use the template provided.
