### ISSUE TITLE
Invalid character in header content ["X-Plex-Device-Name"]

### ISSUE THREAD

**Issue by deejayexe** [sct/overseerr#1244]
#### Description
I have a name server with this icon 🎬 and i cant to test it in server name settings, Invalid character in header content ["X-Plex-Device-Name"]

#### Version
What version of Overseerr are you running? (You can find this in Settings → About → Version.)
**Version
    1.21.1** In Docker Container

#### Expected Behavior

In other applications I do not have problems with the icon so it is a small bug of overserr Invalid character in header content i expect it can solve.

**Comment by sct** [comment]
The device name we send to plex.tv has nothing to do with your plex server name. It's whatever your Overseerr application title is set to. You must have some character in there it doesn't support? (We confirmed emojis don't cause an issue)

**Comment by deejayexe** [comment]
Ok it's the App Title in Overseerr, I only have text and emojis:
Overseerr 🎬 🇮🇨
The recover account button of the plex tab only works for me if I delete the emojis in the application title in the general settings tab both one emoji and another, I have tried with other emojis in the title 😀 and it does not work either.
If it can be solved well if not nothing happens.

**Comment by TheCatLady** [comment]
> Ok it's the App Title in Overseerr, I only have text and emojis:
> Overseerr 🎬 🇮🇨
> The recover account button of the plex tab only works for me if I delete the emojis in the application title in the general settings tab both one emoji and another, I have tried with other emojis in the title 😀 and it does not work either.
> If it can be solved well if not nothing happens.

I just verified with an application title of `Overseerr 🎬 🇮🇨` that everything works on my server.

Do you have Overseerr and/or Plex behind a proxy? If so, you'll need to make sure that your proxy supports emoji in HTTP headers.

**Comment by deejayexe** [comment]
> 
> 
> > Ok it's the App Title in Overseerr, I only have text and emojis:
> > Overseerr 🎬 🇮🇨
> > The recover account button of the plex tab only works for me if I delete the emojis in the application title in the general settings tab both one emoji and another, I have tried with other emojis in the title 😀 and it does not work either.
> > If it can be solved well if not nothing happens.
> 
> I just verified with an application title of `Overseerr 🎬 🇮🇨` that everything works on my server.
> 
> Do you have Overseerr and/or Plex behind a proxy? If so, you'll need to make sure that your proxy supports emoji in HTTP headers.

Ok but u verified that if u Retrieved Plex server list u can take it automatically? When I have the emojis put in the name, if I retrieve the list of servers from the plex tab, I get the message Invalid character in header content ["X-Plex-Device-Name"] and dont take automatically.
I try it directly in my lan address:port and in my subdomain (traefik) reverse proxy

**Comment by TheCatLady** [comment]
> Ok but u verified that if u Retrieved Plex server list u can take it automatically? When I have the emojis put in the name, if I retrieve the list of servers from the plex tab, I get the message Invalid character in header content ["X-Plex-Device-Name"] and dont take automatically.

Yes, I verified that the server list is fetched without issue. I believe this is an issue with your setup, and not Overseerr.

**Comment by deejayexe** [comment]
I just did a new installation from docker to another port of my local network, I recover plex credentials, I finish the installation and everything is ok, this is the name of my server
Plex 2.0: -: 🎬 🇮🇨
I change the name from overseerr to Overseerr: -: 🎬 🇮🇨
But when I try to retrieve my server list from plex I get the error Can't connect to Plex!
Error connecting to Plex: invalid character in header content ["X-Plex-Device-Name"]
And it doesn't allow you to connect manually either.

**Comment by sct** [comment]
I can reproduce it with the same server name.
