### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by cdemi** [sct/overseerr#1266]
#### Description

A Progressive Web App (PWA) allows users to install the web application on their home screen. It will look and act close to a native application. You can also submit PWAs directly to app stores such as Play Store, iOS App Store and Microsoft Store for Windows PCs.

Using PWA, you also get access to other native APIs such as:

- Push Notifications, for example you may push notifications to users when the requested content is available
- Local Device caching, for example series or TV Show images
- Shortcut ability (Android)
- Badging for app icons
- Richer offline experiences with the Periodic Background Sync API

To make the app a PWA, to provide an installable web experience it is relatively (compared to the rest of the project) easy. A web app manifest and a simple service worker needs to be added. And users will be able to have a more native feel for this app.

More technical information on PWAs can be found at: https://web.dev/progressive-web-apps/

**Comment by sct** [comment]
We already have a manifest and support several PWA features that make the experience relatively native on mobile devices. You can add Overseerr to your home screen on iOS/Android already, and the app behaves pretty well on both.

To be clear on a few things:

- PWA's cannot be submitted to the app store on iOS. Only the Play Store. (No plans for trying to make the desktop experience anymore native than just clicking install from Chrome)
- Local device caching is already happening automatically with your browser (and with shortcut apps)
- Installing a service worker comes with its own headaches. It needs to be correctly maintained. Deploying a broken service worker will create a lot of issues so it needs to be done right the first time.

We want to add more PWA support going forwards for things like installing a desktop app from Chrome, and things like notifications need to be investigated in the future. None of this is terribly high priority though, so we will get to it when we can.

**Comment by cdemi** [comment]
Thanks for the explanation, very well reasoned
