### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by PhAzE-Variance** [sct/overseerr#1273]
#### Description

Allow admins to customize the logo shown both at the top of the page (by default it shows "overseerr" and also as a custom logo fo email notifications. 

#### Desired Behavior

Add a setting to the settings page to upload a custom log.
Logo should change on home page.
Logo should change on email notifications.  (This might want an option for a different logo than the homepage)

#### Additional Context

This is a feature in competing software, but would also be a perfect fit for Overseerr.

**Comment by TheCatLady** [comment]
Duplicate of #404
