### ISSUE TITLE
The plex users are not imported when 2 servers are avaliable in the same network

### ISSUE THREAD

**Issue by RealKanashii** [sct/overseerr#1276]
#### Description

I have 2 servers in the same network. When I choose the second one (new one) the plex users are not imported.  If I destroy the docker and create it again but selecting the first server I can import the plex users.
I reproduced it running two overseerrs in two dockers. 
It fails also when only one docker and only one account/servers is linked.

#### Version

1.21.1

#### Steps to Reproduce

You need 2 servers in your own plex account and probably in the same LAN (not sure about this)
My servers have names: "Magatzem" and "Magatzem2"
Make the setup process.
Try to import users from plex from the second server (the new one) "Magatzem2".
The import shows "No new users imported from Plex".
Only the main user ( the linked account) is created.

#### Expected Behavior

Import the actual plex users.

#### Screenshots
Account with the first server. Import ok:
![image](https://user-images.githubusercontent.com/9731708/112281396-4a995080-8c86-11eb-812c-28e4ceb6f0f9.png)

Same account with the second server. Import failed:
![image](https://user-images.githubusercontent.com/9731708/112281288-2c335500-8c86-11eb-84d7-1bb77f93d0a0.png)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Docker
- **Device:** Server
- **OS:** Unraid
- **Browser:** Chrome

#### Additional Context

None

**Comment by TheCatLady** [comment]
Overseerr will only import users for the Plex server it is configured to use, and only supports a single Plex server instance (please see #1094).

One possible workaround is to manually add the users from your second server as "local users."

**Comment by RealKanashii** [comment]
No no, it's only one instance of overseerr.

**Comment by RealKanashii** [comment]
Overseerr 1 -> Server1 (ok)
Overseerr 2 -> Server2 (fails)

**Comment by TheCatLady** [comment]
Ah, gotcha.  Sounds like this might be a configuration issue with your second Overseerr instance, then.  Best place to get help with that is our [Discord server](https://discord.gg/PkCWJSeCk7).
