### ISSUE TITLE
Notify for completed partial requests

### ISSUE THREAD

**Issue by scallister** [sct/overseerr#1293]
#### Description

Currently Overseerr does not send notifications for shows unless an entire show is available. For example, a user John requests season 5 of show Foo. Once Season 5 is downloaded, no notification is sent. A notification is only sent if the other 4 seasons are also downloaded. Then and only then does John get a notification.

#### Desired Behavior

If the seasons a user requests are available, a notification that their request has been completed should be sent. In this example above, a notification that Season 5 is completed. If John had requested seasons 2 and 4, then a notification would only be sent once both seasons 2 and 4 were completed.

**Comment by samwiseg0** [comment]
I believe this would fall under https://github.com/sct/overseerr/issues/342 and https://github.com/sct/overseerr/issues/349 as notifications would be able to be set per episode basis.

**Comment by scallister** [comment]
Good catch, I agree. I'll follow those two issues 👍.

**Comment by TheCatLady** [comment]
Actually, if I'm interpreting @scallister's issue description correctly, this is already the current behavior.  When all seasons in a user request become available, they will receive a notification.  We do not, however, send emails for each individual season as it becomes available, only when ALL requested seasons are available.

**Comment by scallister** [comment]
@TheCatLady you're correct.

Hm, given that should already be the intended behavior I will keep an eye out and try to confirm this. If I hit a case where the partial does not properly send I'll reopen this as a bug 👍.
