### ISSUE TITLE
Enable Image Caching for Linux Snap

### ISSUE THREAD

**Issue by 5drH64gDnDJb** [sct/overseerr#1301]
#### Description

For the, "Enable Image Caching," I have it enabled, im using Ubuntu server with snap, but i'm not seeing the /app/.next/cache/images, (images directory) anywhere on my install.

#### Version

develop-bec1d3dde834b9a50e24c5894c362e5982ff3bd5

#### Steps to Reproduce

Enable Image Caching for Linux using Snap.

#### Expected Behavior

I assume directory would be created and imagines would begin to cache.

#### Screenshots

![overseerr](https://user-images.githubusercontent.com/39547014/112704482-c81cb680-8e68-11eb-8b6f-c3beef3b0e2b.png)

#### Device

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:           20.04
Codename:      focal

--------------------------------------

snap    2.49.1
snapd   2.49.1
series  16
ubuntu  20.04
kernel  5.4.0-70-generic

**Comment by samwiseg0** [comment]
I have not looked at this just yet but I do not think you can look at the host file system with snap. The snap itself runs in a vm. Did you search _inside_ the snap itself?

How do you know image caching is not working? Are your images broken when that setting is enabled?

**Comment by 5drH64gDnDJb** [comment]
I'm new to the snap stuff, so not sure if I'm doing it right when searching. Images are not broken, I just didn't see any disk space growth after enabling it and going through a ton of images.

**Comment by TheCatLady** [comment]
> I'm new to the snap stuff, so not sure if I'm doing it right when searching. Images are not broken, I just didn't see any disk space growth after enabling it and going through a ton of images.

Did you refresh/reload the page after enabling image caching? We just fixed this in #1302, but previously in order for the setting to take effect, a page refresh was required.

You can verify if caching is working/enabled by checking the URL of the images, and seeing if they are being served from your server or directly from TMDb.

**Comment by samwiseg0** [comment]
> I'm new to the snap stuff, so not sure if I'm doing it right when searching. Images are not broken, I just didn't see any disk space growth after enabling it and going through a ton of images.

There is not a problem then. You will only see large growth if/when you leave it running for a long time and you start to accumulate a large set of images. Since it was just enabled this will not be the case. Just note that it _can_ use a lot of space.
