### ISSUE TITLE
Trying to build from source

### ISSUE THREAD

**Issue by AliMickey** [sct/overseerr#1328]
#### Description

I am trying to build from source on debian and it fails with some errors.

#### Version

Latest git version

#### Steps to Reproduce
1. git clone 
2. npm install
3. npm run build

#### Expected Behavior

App runs??

#### Screenshots

If applicable, please provide screenshots depicting the problem.
![image](https://user-images.githubusercontent.com/60691199/112984535-bd388d80-91aa-11eb-8fbb-2a517fe12c74.png)

#### Device
Linux, Debian

#### Additional Context

First error was "Error: Cannot find module 'tailwindcss'"

i ran npm install tailwindcss.

the issue error is what happened after

**Comment by sct** [comment]
This is not a bug? Nor will we support this. If you don't know what you are doing, it might be best to not try to do this.

**Comment by AliMickey** [comment]
what do you mean? Whats not the bug? The error or that this app doesnt support building from source like this?

**Comment by sct** [comment]
The app builds from source fine. You are not doing it correctly. Try reading the contribution guide to learn how to set up your environment. https://github.com/sct/overseerr/blob/develop/CONTRIBUTING.md

**Comment by AliMickey** [comment]
i am not doing this for contribution so i did not check that before. 

will try it later. thanks
