### ISSUE TITLE
Movie/Series cards don't scale up on hover

### ISSUE THREAD

**Issue by danshilm** [sct/overseerr#1339]
#### Description

Upon hovering over a movie/series card, the cards don't scale up as from [d524371](https://github.com/sct/overseerr/commit/d524371acedf06026c664064afa5adbe32a55326). 

At `d524371`:

https://user-images.githubusercontent.com/20923978/113179650-e74c8700-9260-11eb-9de0-4eeaf4b0775e.mp4

At `d8bcb99`:

https://user-images.githubusercontent.com/20923978/113180023-5033ff00-9261-11eb-963f-d1258b06502a.mp4

#### Additional Context

Tailwind JIT shenanigans?

**Comment by sct** [comment]
Reverted tailwind-jit change for now.
