### ISSUE TITLE
Filter content by certification

### ISSUE THREAD

**Issue by m-hardwick** [sct/overseerr#1340]
#### Description

A child friendly version of Overseer, this means either limiting by age the content that is suggested within the Trending, Popular, Upcoming & Network sections or the option to disable content from being displayed at all. 

#### Desired Behavior

Option to limit content displayed on Trending, Popular, Upcoming & Networks by Age limit. E.g Only show content 12 or below.
Option to disable the recommendation's in Trending, Popular, Upcoming & Networks completely. The main function of searching for the required show would be enough.

#### Additional Context

I understand that anything can still be searched for, it would be nice to have a limit there as well but the main concern is what is offered or presented to the end user.

**Comment by TheCatLady** [comment]
This is slightly different from #812, in my opinion.  I see this issue as not just filtering based on user or server owner preferences, but restricting viewable/requestable content by age ratings/certifications for specific user accounts (or even globally).

I think it's best to track this as a separate issue.

**Comment by dynamatikzgr** [comment]
Katılıyorum bunu ayrı bir sorun olarak ayrıştırıp denemeliyiz benccede

**Comment by xInsertx** [comment]
Would be nice if the "recently added" filtering matched what is configured for users on Plex (using their inbuilt whitelist/blacklist). This was my suggestion in #1475. This would always use to keep in-sync with Plex's inbuilt permissions.

A short-term solution would be to let us disable the "recently added" either globally or per user.

As for searching/discovery recommendations, you can only really filter that by age and/or gene.

**Comment by SebastianMoyano** [comment]
Yes I would like this feature too, because some media sometimes is too graphic and not for all audience. for example if you search for "slip" you get a very graphic movie, which would not be a problem if the thumbnail didnt show so much.

**Comment by digidomic** [comment]
Is there a workaround to hide „popular movies“ section? Really need this. Thanks in advance

**Comment by samwiseg0** [comment]
> Is there a workaround to hide „popular movies“ section? Really need this. Thanks in advance

Not today. Any and all updates on features will be documented here.

**Comment by pharpe** [comment]
I am interested in this functionality
