### ISSUE TITLE
Use HTTPS for all assets

### ISSUE THREAD

**Issue by aniqueta** [sct/overseerr#1342]
#### Description

I've noticed lately that Overseerr webpages are served with mixed HTTPS/HTTP content. I'm not sure if that has always been the case, and I'm just noticing. 

#### Desired Behavior

Ideally, all assets, such images from TMDB, use HTTPS links. I tested a few that were served using HTTP and they worked with HTTPS, so it could be simple for Overserr to upgrade the links without breaking anything. 

Additionally, the ideal would be that Overseerr caches these assets so that each user is not connecting to TMDB for these assets. This would also improve security. 

#### Additional Context

Thank you for developing this. So great to see the progress here.

**Comment by samwiseg0** [comment]
Can you please provide examples of what is http?

**Comment by TheCatLady** [comment]
Submitting a PR to fix shortly.

**Comment by aniqueta** [comment]
@samwiseg0 Here are examples. I think it's from the new feature to show studio logos:
http://image.tmdb.org/t/p/w780_filter(duotone,ffffff,bababa)/qZCc1lty5FzX30aOCVRBLzaVmcp.png
http://image.tmdb.org/t/p/w780_filter(duotone,ffffff,bababa)/8lvHyhjr8oUKOOy2dKXoALWKdp0.png

Looks like @TheCatLady is already on this though.
