### ISSUE TITLE
Is possible add primary language and add other secondary language in Overseerr TMDB requests?

### ISSUE THREAD

**Issue by dtalens** [sct/overseerr#1350]
Is possible add primary language and add other secondary language in Overseerr TMDB requests?. In this way when the content is not in Catalan could see it in Spanish or English.
Similar of TMDB page:
![image](https://user-images.githubusercontent.com/6631832/113421681-d10f0a00-93cb-11eb-877e-992f496cb4af.png)

_Originally posted by @dtalens in https://github.com/sct/overseerr/issues/1349#issuecomment-812539345_

**Comment by TheCatLady** [comment]
The TMDb API does not support this, unfortunately. It would require making two API calls for every one that we currently do, and I don't think that is a valid option for the entire application.

Your best bet is to contribute to TMDb and help them improve the data available for your desired locale.
