### ISSUE TITLE
Movies Showing Available After Deleted From Radarr

### ISSUE THREAD

**Issue by mous2890** [sct/overseerr#1359]
#### Description

I requested a movie through Overseerr into Radarr which successfully downloaded and showed as Available in Overseerr. After watching the movie, realised it's trash so I deleted the movie directly from Radarr. When going back to Overseerr, the movie remains in an Available state with the "Watch on Plex" button available. When clicking, "Open in Radarr", takes me to the home page which is expected as the content is no longer part of my library. 

#### Version

What version of Overseerr are you running? 

1.22.0

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Request movie into Radarr
2. Wait for movie to download
3. Wait for Overseerr to sync the movie and mark as available 
4. Delete movie from Radarr
5. Check movie in Overseerr

#### Expected Behavior

Overseerr to sync with radarr and remove the movie as available. Possibly mark it as deleted so others know this movie was added and subsequently removed. 

#### Screenshots

If applicable, please provide screenshots depicting the problem.

#### Device

What device were you using when you encountered this issue? 

- smartphone
- Google Pixel 5
- Android 11
- Chrome

#### Additional Context

Please provide any additional information that may be relevant or helpful.

**Comment by sct** [comment]
This is not a bug. We only scan your Plex/Radarr instances currently. We do not sync deletes currently. It's planned though! Follow this issue for updates: https://github.com/sct/overseerr/issues/377

For now, just open the management panel on the movie and hit "Clear all media data" to reset its state.
