### ISSUE TITLE
Modifying Global Permissions has no effect on existing users.

### ISSUE THREAD

**Issue by tdeverx** [sct/overseerr#1367]
#### Description
_Please provide a clear and concise description of the bug or issue._

Currently, when you modify the Global Permissions, your changes aren't reflected / updated for existing users. In _some_ cases, this could be quite useful, but in others.. Quite frustrating. This could just be an oversight and not intended (I hope), but I do have a suggestion on how this could be amended in a _simple_ way..

My suggestion would be a small toggle (per user) to "Follow Global Permissions" which would disable the ability to modify the permissions while its enabled and would allow this user to always follow the Global Permissions.

#### Version
_What version of Overseerr are you running? (You can find this in Settings → About → Version.)_

develop-a306ebc2d18317d8dbe4ccd3f24c22f55ffcd6a6

#### Steps to Reproduce
_Please tell us how we can reproduce the undesired behavior._

1. Modify the Global Permissions
2. Check current users
3. Cry
4. Modify all users manually

#### Expected Behavior
_Please provide a clear and concise description of what you expected to happen._

Have the ability to update users permissions by modifying the Global Permissions

#### Screenshots
_If applicable, please provide screenshots depicting the problem._

N/A

#### Device
_What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug._

- Platform: Desktop / NAS
- Device: MacBook Pro / Synology DS918+
- OS: Mac OS Big Sur / DSM 6.2.3-25426 Update 3 (Docker)
- Browser: Safari

#### Additional Context
_Please provide any additional information that may be relevant or helpful._

Right now, while Overseerr is in alpha, I don't see this being a _major_ issue for anybody but as Overseerr grows and people use this for a larger user base, I see quite a few people getting a tad frustrated by this (myself included).

**Comment by danshilm** [comment]
What you're asking for is achievable with 'Bulk Edit' on the Users page.
![image](https://user-images.githubusercontent.com/20923978/113597597-fe1e1f80-964c-11eb-833e-ab623f442607.png)

**Comment by tdeverx** [comment]
OH, I'm so stupid hahaha! Thank you for that!

**Comment by tdeverx** [comment]
I've just tried to do this, but the options for Auto Approve and requesting in 4K aren't available, perhaps this should be changed to allow that?
