### ISSUE TITLE
MEDIA_AUTO_APPROVED Webhook Notifications do not Include Username and Email

### ISSUE THREAD

**Issue by passibe15** [sct/overseerr#1384]
**Description**

I have an issue with webhook notifications.
If the notification_type is `MEDIA_AUTO_APPROVED`, the notification's json payload leaves the 'username' and 'email' fields empty (i.e. the `{{notifyuser_username}}` and `{{notifyuser_email}}` variables are not populated). Everything else works correctly, though.

**Desired Behavior**

Populate the `{{notifyuser_username}}` and `{{notifyuser_username}}` variables for MEDIA_AUTO_APPROVED notifications.

**Additional Context**

Webhook Config (default):
```
{
    "notification_type": "{{notification_type}}",
    "subject": "{{subject}}",
    "message": "{{message}}",
    "image": "{{image}}",
    "email": "{{notifyuser_email}}",
    "username": "{{notifyuser_username}}",
    "avatar": "{{notifyuser_avatar}}",
    "{{media}}": {
        "media_type": "{{media_type}}",
        "tmdbId": "{{media_tmdbid}}",
        "imdbId": "{{media_imdbid}}",
        "tvdbId": "{{media_tvdbid}}",
        "status": "{{media_status}}",
        "status4k": "{{media_status4k}}"
    },
    "{{extra}}": [],
    "{{request}}": {
        "request_id": "{{request_id}}"
    }
}
```

Received JSON:
```
{
   "notification_type":"MEDIA_AUTO_APPROVED",
   "subject":"Some Movie Title",
   "message":"Some Movie Description",
   "image":"https://image.tmdb.org/t/p/foo/bar",
   "email":"",
   "username":"",
   "avatar":"",
   "media":{
      "media_type":"movie",
      "tmdbId":"11111",
      "imdbId":"",
      "tvdbId":"",
      "status":"PENDING",
      "status4k":"UNKNOWN"
   },
   "extra":[
      
   ],
   "request":{
      "request_id":"1"
   }
}
```

**Comment by TheCatLady** [comment]
This is actually not a bug, as `MEDIA_AUTO_APPROVED` (and certain other notification types) are intended for admin users (or users with the `MANAGE_REQUESTS` permission).

That said, we could expose the `requestedBy` user field in the `media` object.

**Comment by passibe15** [comment]
Nice! Thanks a lot for the clarification and the speedy "fix".
Cheers
