### ISSUE TITLE
BST Time not being used when Europe/London is TZ

### ISSUE THREAD

**Issue by pro4tlzz** [sct/overseerr#1387]
#### Description

Hi, I am running the LSIO image in docker with the env variable TZ Set to Europe/London however the timestamps in the logs are an hour behind stuck on DST time

#### Version

1.22.0

#### Steps to Reproduce

1. Create Docker container with env variable TZ Set to Europe/London
2. Check timestamp in log

#### Expected Behavior

I would expect the timestamps to be in BST

#### Screenshots

![image](https://user-images.githubusercontent.com/22709115/114100245-e9938e80-98bb-11eb-9cd6-d242f05d2530.png)
![image](https://user-images.githubusercontent.com/22709115/114100258-eef0d900-98bb-11eb-904e-897e75ed9375.png)

#### Device

Saw the logs whilst SSHed in

**Comment by TheCatLady** [comment]
If you view the logs on the `Settings > Logs` page, the log timestamps should be displayed in your local time zone.

However, the timestamps in the log file are in UTC.  (The `Z` at the end of the timestamp denotes UTC.)
