### ISSUE TITLE
Back button for navigation in PWA

### ISSUE THREAD

**Issue by aniqueta** [sct/overseerr#1398]
#### Description

The PWA works really well. Because it works so well, it's easy to confuse it as a native app. The missing piece is a back button to replace or supplement swiping back. Swiping back like a web page is not intuitive for me and my users. 

#### Desired Behavior

Ideally, there would be a back button or other interface to make the PWA behave more like a native app. At a minimum this would be for iOS users. I'm not sure how PWAs work on Android, but I suspect it would be useful there too.

**Comment by 338lm** [comment]
As a user of Android gesture navigation (swipe to go back), this would be a much appreciated enhancement for the Android PWA too!

**Comment by sct** [comment]
Related to #1266
