### ISSUE TITLE
Media Available notification sent before importing stage

### ISSUE THREAD

**Issue by cdemi** [sct/overseerr#1400]
I have NZBGet configured to download to local storage. When the download is ready, Radarr/Sonarr get from local storage and move to a Network Share; this process takes some time to complete.

Overseerr triggers the Media available notification as soon as the directory and the first pieces of the file are detected in the Plex Media folder.

I would like to propose to trigger the Media Available notification when Radarr/Sonarr change the state of the media item to be "Downloaded". They will know when the move process has finished and when the media is fully playable.

I think this setup (download to local storage and move to remote storage) is quite common, so I think other people will be happy about this change.

If you don't want to change the functionality of "Media Available" notification, might I suggest a new trigger with a different name. Although, my opinion is that it's better to change the logic of the Media Available trigger, since the media would not be available

**Comment by danshilm** [comment]
I think what's happening here is that you have Plex watching your library folders. Therefore, as soon as a media item shows up in Plex, Overseerr marks that as available within the next 5 minutes (Plex Recently Added Scan job).

This doesn't seem like a bug but instead one of the issues when using remote storage with Plex.

Maybe there can be another job watching Radarr/Sonarr for media being added. Then users would have Plex not watching library folders and Radarr/Sonarr triggering a Plex library update when media is added.

The event component in Radarr responsible for media being made available seems to be `MovieService`.

**Comment by TheCatLady** [comment]
This isn't a bug.  Overseerr simply requests a list of recently added items from Plex, and marks those items as available.

If you don't want those items to be marked as available until they've been moved to the correct location, you should disable the automatic library scanning feature on your Plex server.  You could then [trigger library scans](https://support.plex.tv/articles/201242707-plex-media-scanner-via-command-line/) using a [Sonarr (or Radarr) post-processing script](https://wiki.servarr.com/Sonarr_Tips_and_Tricks#Custom_Post_Processing_Scripts).

**Comment by cdemi** [comment]
Thanks for the tip. I think that would work
