### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by exentler** [sct/overseerr#1402]
#### Description

Seems i having a memory leak. 
Overseerr using 2G of memory overnight

Providing logs and screenshot off htop

#### Version

1.22 / Snap / Ubuntu 20.04

[overseerr-2021-04-12.log](https://github.com/sct/overseerr/files/6294588/overseerr-2021-04-12.log)

#### Screenshots

![Capture](https://user-images.githubusercontent.com/76279565/114354316-5766e100-9b6e-11eb-963c-0cdf9042b608.JPG)

**Comment by sct** [comment]
Can you check if this is happening in the develop branch?

**Comment by exentler** [comment]
Updated to latest edge image now.
Checking status tomorrow or later this week

**Comment by exentler** [comment]
No update yet due automated updates and restarts of Overseerr.

**Comment by exentler** [comment]
My system is running fine now. 5 days uptime on 1.23.2. Only 546MB usage.

**Comment by TheCatLady** [comment]
> My system is running fine now. 5 days uptime on 1.23.2. Only 546MB usage.

Thanks for following up!
