### ISSUE TITLE
Include Inter font with package to remove unnecessary external dependency

### ISSUE THREAD

**Issue by zekesonxx** [sct/overseerr#1415]
#### Description

The current theme uses the Inter font, which it loads from `https://rsms.me/inter/inter.css`. This is an unnecessary external website being loaded, offering the ability for tracking or other potential security issues to take place. The font could and should instead be included from within the Overseerr package, just like any of the other assets in use.

#### Desired Behavior

Include the Inter font within Overseerr builds so that it's not loaded from an external website.

**Comment by TheCatLady** [comment]
We could probably use this NPM package: https://www.npmjs.com/package/@fontsource/inter

**Comment by sct** [comment]
> We could probably use this NPM package: https://www.npmjs.com/package/@fontsource/inter

This does add another 5MB to our bundle though :/

**Comment by exentler** [comment]
What is the issue with 5MB increase ?
I prefer the website can be loaded without an unnecessary external website request and can be optimized by Pagespeed.

**Comment by sct** [comment]
This will actually be done automatically in `next@10.2.x` but as of right now our language extraction tool is broken on that version. Once we can upgrade to 10.2+ we will have this by default :)

**Comment by TheCatLady** [comment]
Reverted Next.js to 10.1.3 in 2254248abc0f2051a9dd28d9663c7ab1d0b547b6 due to CSS import issue.

**Comment by TheCatLady** [comment]
Next.js bumped to 11.0.1 in 25b5c6ebb5fff6299e80de08c2edcca548348c9a
