### ISSUE TITLE
Configure email notification address in UserProfile

### ISSUE THREAD

**Issue by WhatFor** [sct/overseerr#1428]
#### Description

Currently email notifications are always delivered to the email address attached to the User account. It would be great to be able to provide a custom email address for notifications.

#### Desired Behavior

Under `/profile/settings/notifications`, provide an input field to override the destination address for email notifications.

If set, this value will be used as the destination address when sending notification emails to the user - not the email address attached to the account.

This is particularly useful when the Overseerr account (and thus the email address) is tied to a Plex account.

Lots of love, amazing project, keep up the great work! ♥

**Comment by samwiseg0** [comment]
This can be done by creating a local account with the email you want to use and give it the manage requests permissions. I think this should be sufficient and does not requires an additional feature request?

**Comment by WhatFor** [comment]
Thanks for your quick reply. The solutions you've offered would work, they feel like a roundabout way to set it up though.

> Are you asking for this to be per user and not just the admin?

I don't think there's any real distinction - both receive notifications - but for my use case at the moment I'm the admin.

**Comment by sct** [comment]
I don't think we need an option to override the emails notifications are sent to. The account's email address should serve this purpose. Do you expect other websites to behave the same way? Sign up with one email but then override it with another just for mail? Seems like very odd behavior.

You can change a Plex account's email address if it's one that you (or your users) no longer use. I don't plan to provide any way to override the email.
