### ISSUE TITLE
"Something went wrong" message when you try to create a user with a duplicate email address

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#1441]
#### Description
I was trying to create a second user for my own test purposes when I ran into an issue that I can't create multiple accounts on one mail address.
It makes sense that it is only possible to have a unique e-mail address for each user plex/local, but maybe a more friendly error message than "Something went wrong while creating the user." will help the admin to know what is wrong.
Or is it possible to support multiple accounts for 1 e-mail address?

#### Version
1.22.0

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Go to User List
2. Hit the "Create User" button.
3. Try to create a user with an e-mail that is already in use
4. See error: "Something went wrong while creating the user."

Under the development tools, you can see that the response is a 500 code with the following response message:
{"message":"SQLITE_CONSTRAINT: UNIQUE constraint failed: user.email"}

#### Expected Behavior
Can we support multiple account on the same user e-mail address or is it possible to show a friendly error message?

#### Screenshots

If applicable, please provide screenshots depicting the problem.

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** [e.g., desktop, smartphone, tablet]
- **Device:** [e.g., iPhone X, Surface Pro, Samsung Galaxy Tab]
- **OS:** [e.g., iOS 8.1, Windows 10, Android 11]
- **Browser:** [e.g., Chrome, Safari, Edge, Firefox]

#### Additional Context

Please provide any additional information that may be relevant or helpful.

**Comment by TheCatLady** [comment]
Unfortunately we can't support multiple users with the same email address, since the email address is used as a unique identifier for a user.  We should definitely return a more descriptive error message in this case though, to let the user know that the user they are trying to create already exists.
