### ISSUE TITLE
Radarr download sync shows different behaviour to Sonarr download sync for processing animation

### ISSUE THREAD

**Issue by cpt-kuesel** [sct/overseerr#1443]
#### Description

I noticed that there is a difference between how movie requests and show requests show they are being processed.
While movie requests show the Processing badge and animated circle as long as they are in the download queue, show requests only show this when the currently downloaded episode belongs to that show.

My example is:
Movie Request Burn after Reading is the last movie of 10 in my Radarr queue but shows its being processed.
The first episode of the Show request Darkwing Duck is at about position 50 in my Sonarr Queue and doesn't show its being processed.

The current download is an episode of The Mentalist which shows its being processed.

#### Version

What version of Overseerr are you running? (You can find this in Settings → About → Version.)
Stable 1.23.1

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. have sonarr sync and radarr sync enabled
2. request multiple shows and multiple movies and approve if necessary so they are added to the download queue

that should be enough to recreate that every movie request shows as processing, but only when an episode of a requested show is being downloaded this request shows as processing.

#### Expected Behavior

Please provide a clear and concise description of what you expected to happen.

I see two possible solutions:
1. Show requests will also show as processing when being episodes are in the download queue.
2. Movie requests will only show as processing when they are currently being downloaded.

I personally prefer solution 1.

#### Screenshots

If applicable, please provide screenshots depicting the problem.
![image](https://user-images.githubusercontent.com/79487102/115085773-643b5a00-9f0b-11eb-8cfa-497a9d671dcb.png)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

I am running the sctx/overseerr:latest Docker image on an Ubuntu Server LTS 20.0.4 machine.
This behaviour is consistent across Windows 10 Chromium Version 87.0.4280.141 and iPad Pro (iOS 14.4.2) Safari.

#### Additional Context

Please provide any additional information that may be relevant or helpful.

**Comment by sct** [comment]
This is actually working as intended. We only sync the first 10 items in the download queue for displaying the inline progress

**Comment by cpt-kuesel** [comment]
Alright, good to know. Thanks for the explanation!
