### ISSUE TITLE
Add season folders tick box when adding TV series

### ISSUE THREAD

**Issue by Sparkey70** [sct/overseerr#1456]
#### Description

Add season when requesting a TV Show or series

#### Desired Behavior

When adding a TV show there is no selector to add "Seasons" folders when Selecting TV shows or series it shows the season with sliders but no selection to tick for hey create seasonal folders.

#### Additional Context

When adding you cannot choose "Season" the TV show then adds, but downloads everything in to one folder.
Eg. \Some random tv show\Random TV show S01E01    VS.    \Some random TV show\Season01\Random TV show S01E01

**Comment by TheCatLady** [comment]
You can already change this setting in `Settings > Services`?
