### ISSUE TITLE
Allow users to choose server but not the rest, ie tags, path and profiles

### ISSUE THREAD

**Issue by nameproof** [sct/overseerr#1458]
Issue:
I was informed by sct to use the server option as a way to let my users choose a language, this works great. However when I expose my users to this setting, advanced request, they also gain access to tags, path and profiles. Ease of use is critical for me since my users are very non tech savvy. Telling them to change server but don't touch the rest doesn't fly...

Request: 
I'd like a way for my users to be able to select server but hide tags, path and profiles.

Solution: 
There are several way to make this happen, like more granular control of permissions etc, I believe you guys know how you'd like to make it happen according to your vision.

**Comment by sct** [comment]
Please follow the template and don't remove the labels!
