### ISSUE TITLE
Allow users to select individual episodes when requesting TV

### ISSUE THREAD

**Issue by manor7777** [sct/overseerr#1465]
#### Description

Ombi allows you to request individual episodes of series for TV - there are some use cases where this is useful. For example, testing to see if you even like a show, or re-requesting an episode if one has failed and the system hasn't recovered and tried again.

#### Desired Behaviour

When a series is checked, expand the view to also have all of the episodes ticked. A user can then de-select episodes if they wish. Alternatively, allow a "Season X" to be tapped next to the checkbox (i.e on the text) for it to expand the view, so episodes can be checked - this would be more useful when a season has a LOT of episodes, or only a few needed to be checked, and even for space saving reasons.

Grey out any episodes/seasons that are already Fully Available

#### Additional Context

Potential to add a permissions node for this to allow/disallow the feature

**Comment by xFlawless11x** [comment]
This request already exists, please see #342

**Comment by manor7777** [comment]
> This request already exists, please see #342

Thankyou, didn't spot that!
