### ISSUE TITLE
Allow Browser Notification Provider

### ISSUE THREAD

**Issue by manor7777** [sct/overseerr#1466]
#### Description

I have no idea what this is called, but you can push notifications directly from a server - for example, in a browser, YouTube will ask if you would like to allow notifications - and the notifications will appear to be from chrome, but will say YouTube on them

#### Desired Behavior

A user enters settings, Profile, Edit Profile and clicks the notification tab

From there they can allow browser notifications to be enabled

**Comment by TheCatLady** [comment]
Duplicate of #1266
