### ISSUE TITLE
Option to hide ratings in Overseerr

### ISSUE THREAD

**Issue by cpt-kuesel** [sct/overseerr#1468]
#### Description

I would like to have the option to hide ratings by default.
For me they are not very useful because they often do not reflect my taste.
But because they are there I tend to find myself not requesting stuff because of a number.
But at the same time a user on my server might find them useful so a per user toggle would be awesome.

#### Desired Behavior

I as an admin want an option to disable showing ratings in Overseerr.
The option can be toggled globally but overwritten through a users settings.

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by TheCatLady** [comment]
@cpt-kuesel We cannot add settings to hide/customize every little thing in the UI, especially if it does not provide any functional benefit.

If you don't like to see the ratings, the `div` is tagged with the `media-ratings` class, and you can easily hide it with ad blocking software or Nginx `sub_filter`.

**Comment by cpt-kuesel** [comment]
I understand, thanks for the workaround!
