### ISSUE TITLE
App/Service Shortcut Page

### ISSUE THREAD

**Issue by robdplatt** [sct/overseerr#1472]
#### Description

While we do have quasi-shortcuts for Sonarr and Radarr under the services page, it would be super neat to be able to customize a list of other services as well. It's getting to the point where my desktop is cluttered with icons, I don't want bookmarks in chrome, etc. Would love to see Overseerr as close to as a one-stop-shop to manage my media. It also should be a place I check in regularly.

Some of the shortcuts I can think of that I would use: Unraid, Portainer, Sabnzbd, Lidarr, Bazarr, Tautulli, etc.

I run a completely redundant environment (active/passive), so I have double the shortcuts right out of the box.

This could be built in and/or user defined shortcuts with ip, port, icon support.

Bonus points if we can supply two URLs/IPs (one for direct lan access, one for remote access)

**Comment by samwiseg0** [comment]
I think these are the droids you are looking for ;) https://github.com/causefx/Organizr

**Comment by sct** [comment]
As the others said, you have described Organizr, which already has Overseerr SSO integration. Maybe give that a shot!

**Comment by robdplatt** [comment]
Thanks all!
