### ISSUE TITLE
Show TV shows that are continuing and current as current and not as partially available

### ISSUE THREAD

**Issue by HubDuck** [sct/overseerr#1477]
#### Description

A continuing tv show, which still has episodes to air in the future, is labeled "partially available". Sonarr however labels it correctly with a green complete flag and a score (api) of 100.

Partially available is also used to label incomplete tv shows in overseerr. An incomplete season is not the same as an up-to-date and current season. Users might confuse the current labeling as it being incomplete and either not watch it or trying to request more (which is not possible at the moment).

#### Desired Behavior

If the sonarr score is 100, the tv show should be labeled as available (current behavior), but if the show is also still airing, a score of 100 should label the tv show as "Current". The word might be a different one and also the color to signify that it is airing with future episodes, but that it is nevertheless complete. This would also show the users that everything is complete and there is no need to try and request more.

#### Additional Context

Sonarr api v3 endpoint "/series" returns

"percentOfEpisodes": 100.0

as the season being complete. If the season also returns

"nextAiring": "yyyy-mm-ddThh:mm:ssZ",

it is a currently airing show that is complete.

**Comment by sct** [comment]
Partially available actually perfectly describes it thought? It's partially available by definition.

When we add episode requests (#342) and eventually add more season/episode details to the series pages, it will be a lot clearer that more episodes are on the way. For now, no changes for the statuses are planned.
