### ISSUE TITLE
Recently added scan takes too long on a new Plex library. Job gets interrupted after 5 minutes.

### ISSUE THREAD

**Issue by hechacker1** [sct/overseerr#1479]
#### Description

I just rebuilt my Plex library on my Synology device (1520+, 4 core  intel), About 1800 movies, 25 tv shows.

Because the entire library was "Recently added" my entire library gets scanned each time by overseer. Often it gets interrupted by the next 5 minute scan. Sometimes it will complete depending on if TMDB lookups are quick enough.

#### Version

What version of Overseerr are you running? (You can find this in Settings → About → Version.)

1.23.1

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Delete and create a fresh Plex Movies and TV library.
2. This will cause everything to show up in Plex's "Recently added."
3. Now the recently added job will take a while to scan this.

#### Expected Behavior

A quicker scan to finish within 5 minutes? It seems to get stuck when it can't find an item in TMDB. 

Some other caching mechanism to know the files on my disk are actually old and unchanged?

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

Plex  1.21.0.3744 on Synology DSM7.

Synology model 1520+.
Intel Celeron J4125
4-core 2.0 (base) / 2.7 (burst) GHz
8GB RAM

Ovseerr hosted on a separate AMD Ryzen7 laptop in docker on Windows. Plenty fast.

[logs.zip](https://github.com/sct/overseerr/files/6346104/logs.zip)

**Comment by TheCatLady** [comment]
@hechacker1 As recommend in Plex settings and in the setup flow, you should run a full Plex scan.
