### ISSUE TITLE
Overseerr web page becomes unavailable during scan until docker reboot

### ISSUE THREAD

**Issue by Reddax** [sct/overseerr#1484]
#### Description

During a scan of adding new content, a lot of the time in my case the web page goes down, unable to access it at all, but the email notification that it's available is successfully sent. In the logs there's repeated attempts of sending notifications. Only way to fix this is to reboot the docker container. When back up, the series shows as not available, then it re-scans and sends another notification that it's available and successfully changes to available.

#### Version

1.23.1 stable - docker
#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Add new content into plex
2. Allow an incremetal crawl to run
3. Web page is unaccessible
4. Requires a docker reboot to bring it back.

#### Expected Behavior

It should scan the series/film successfully, send a notification and mark it as available.

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Desktop
- **OS:** Windows 10
- **Browser:** Edge

#### Additional Context
Logs:

The show that it got stuck on is LetterKenny. As you can it continually tries to 'Sending notification(s) for MEDIA_APPROVED' and send request to sonarr. Bottom of the logs is where I rebooted the container, it then quickly picked it up and marked as available as it should've in the first place
https://gist.github.com/Reddax/2622094e191df814738f23b2699dc43d

**Comment by samwiseg0** [comment]
Are you using the official docker image? How do you have your data directory set in docker for this image?

**Comment by Reddax** [comment]
> Are you using the official docker image? How do you have your data directory set in docker for this image?

I'm using the official Docker image through the community applications on UNRAID. The paths are automatically set to be outside the docker image. I've been running this docker image for months and has only recently started getting this issue.

**Comment by samwiseg0** [comment]
Can you replicate this issue? Secondly can you enable debug logging?

**Comment by Reddax** [comment]
I'll try to replicate it. How do I enable debug logging?

**Comment by samwiseg0** [comment]
set to `-e LOG_LEVEL=debug`

**Comment by Reddax** [comment]
> set `LOG_LEVEL` to debug `-e LOG_LEVEL=debug`

Thanks. Shall try to replicate

**Comment by Reddax** [comment]
Managed to capture it in debug mode. It was on the F Word tv series. It sent off a successful available notification, then sent me 5 failed notifications then the website crashed. Rebooted the docker, and it scanned the F word again and changed it to available.

https://gist.github.com/Reddax/38ae37666f8ffcb6340fe00455f770bf

**Comment by TheCatLady** [comment]
> Managed to capture it in debug mode. It was on the F Word tv series. It sent off a successful available notification, then sent me 5 failed notifications then the website crashed. Rebooted the docker, and it scanned the F word again and changed it to available.
> 
> https://gist.github.com/Reddax/38ae37666f8ffcb6340fe00455f770bf

Your logs don't have any mention of that series or the notifications though?

**Comment by Reddax** [comment]
Did you click on View full file at the top? as it's truncated;
https://gist.githubusercontent.com/Reddax/38ae37666f8ffcb6340fe00455f770bf/raw/a037e18f82babe48e262a9b8e2ac1afa723d5501/gistfile1.txt

**Comment by Reddax** [comment]
> > Managed to capture it in debug mode. It was on the F Word tv series. It sent off a successful available notification, then sent me 5 failed notifications then the website crashed. Rebooted the docker, and it scanned the F word again and changed it to available.
> > https://gist.github.com/Reddax/38ae37666f8ffcb6340fe00455f770bf
> 
> Your logs don't have any mention of that series or the notifications though?

Did you click on View full file at the top? as it's truncated;
https://gist.githubusercontent.com/Reddax/38ae37666f8ffcb6340fe00455f770bf/raw/a037e18f82babe48e262a9b8e2ac1afa723d5501/gistfile1.txt

**Comment by TheCatLady** [comment]
> Did you click on View full file at the top? as it's truncated;
> https://gist.githubusercontent.com/Reddax/38ae37666f8ffcb6340fe00455f770bf/raw/a037e18f82babe48e262a9b8e2ac1afa723d5501/gistfile1.txt

Ah you're right!  Taking a look now 👀

**Comment by TheCatLady** [comment]
@Reddax Seems like requests to Sonarr are failing:
```
2021-04-29T16:35:30.608Z [info][Notifications]: Sending notification(s) for MEDIA_APPROVED {"subject":"The F Word (2005)"}
2021-04-29T16:35:30.645Z [error][Sonarr API]: Something went wrong while adding a series to Sonarr. {"errorMessage":"Request failed with status code 400","options":{"profileId":6,"languageProfileId":1,"rootFolderPath":"/tv","title":"The F Word","tvdbid":79609,"seasons":[1,2,3,4,5],"seasonFolder":true,"seriesType":"standard","tags":[],"monitored":true,"searchNow":true},"response":[{"propertyName":"TitleSlug","errorMessage":"Title slug 'the-f-word' is in use by series 'The F Word'","attemptedValue":"the-f-word","severity":"error","errorCode":"SeriesTitleSlugValidator","formattedMessageArguments":[],"formattedMessagePlaceholderValues":{"slug":"the-f-word","seriesTitle":"The F Word","propertyName":"Title Slug","propertyValue":"the-f-word"}}]}
2021-04-29T16:35:30.648Z [info][Media Request]: Sent request to Sonarr 
2021-04-29T16:35:30.692Z [error][Sonarr API]: Something went wrong while adding a series to Sonarr. {"errorMessage":"Request failed with status code 400","options":{"profileId":6,"languageProfileId":1,"rootFolderPath":"/tv","title":"The F Word","tvdbid":79609,"seasons":[1,2,3,4,5],"seasonFolder":true,"seriesType":"standard","tags":[],"monitored":true,"searchNow":true},"response":[{"propertyName":"Path","errorMessage":"Path is already configured for another series","attemptedValue":"/tv/The F Word","severity":"error","errorCode":"SeriesPathValidator","formattedMessageArguments":[],"formattedMessagePlaceholderValues":{"propertyName":"Path","propertyValue":"/tv/The F Word"}},{"propertyName":"TitleSlug","errorMessage":"Title slug 'the-f-word' is in use by series 'The F Word'","attemptedValue":"the-f-word","severity":"error","errorCode":"SeriesTitleSlugValidator","formattedMessageArguments":[],"formattedMessagePlaceholderValues":{"slug":"the-f-word","seriesTitle":"The F Word","propertyName":"Title Slug","propertyValue":"the-f-word"}}]}
```

**Comment by Reddax** [comment]
I have auto search in sonarr turned off in overseer settings, so they shouldn't be going into sonarr. If I search on another tv series that's been requested in sonarr, it's not in there as expected. I've just searched for F word in sonarr and saw that it was in it, when it shouldn't have been.

**Comment by TheCatLady** [comment]
> @TheCatLady I have auto search in sonarr turned off in overseer settings, so they shouldn't be going into sonarr. If I search on another tv series that's been requested in sonarr, it's not in there as expected. I've just searched for F word in sonarr and seen that it is in it, when it shouldn't have been.

Regardless of whether or not you have auto-search enabled, Overseerr still sends requests to Sonarr.  The auto-search option just determines whether or not Sonarr performs a search.  If you don't want items to be added to Sonarr, you should not connect your Sonarr server to Overseerr.

**Comment by Reddax** [comment]
> > @TheCatLady I have auto search in sonarr turned off in overseer settings, so they shouldn't be going into sonarr. If I search on another tv series that's been requested in sonarr, it's not in there as expected. I've just searched for F word in sonarr and seen that it is in it, when it shouldn't have been.
> 
> Regardless of whether or not you have auto-search enabled, Overseerr still sends requests to Sonarr. The auto-search option just determines whether or not Sonarr performs a search. If you don't want items to be added to Sonarr, you should not connect your Sonarr server to Overseerr.

I have to connect it, as some requests that aren't properly matched when you click request and it gives you options to choose the correct one, this only works with sonarr connected. Or at least this was the case a few months back.

**Comment by TheCatLady** [comment]
> I have to connect it, as some requests that aren't properly matched when you click request and it gives you options to choose the correct one, this only works with sonarr connected. Or at least this was the case a few months back.

Again, if you aren't trying to process requests with Sonarr, you should NOT connect your Sonarr server in `Settings > Services`.

If items on your Plex server are not matching, see the FAQ for troubleshooting steps: https://docs.overseerr.dev/support/faq#some-media-is-missing-from-overseerr-that-i-know-is-in-plex

**Comment by Reddax** [comment]
> > I have to connect it, as some requests that aren't properly matched when you click request and it gives you options to choose the correct one, this only works with sonarr connected. Or at least this was the case a few months back.
> 
> Again, if you aren't trying to process requests with Sonarr, you should NOT connect your Sonarr server in `Settings > Services`.
> 
> If items on your Plex server are not matching, see the FAQ for troubleshooting steps: https://docs.overseerr.dev/support/faq#some-media-is-missing-from-overseerr-that-i-know-is-in-plex

It's not the plex matching, without sonarr, it's when items are requested that requires a 'Manual Match' and to select the correct match below, It doesn't actually show any items to match. I raised this in the discord support and sct replied with;
```
Intentional. But we should probably handle it gracefully if there is no Sonarr setup.
We use one of your Sonarr instances instead of the tvdb api directly, for several reasons :smile:
```
So I need sonarr because of this.

**Comment by TheCatLady** [comment]
> It's not the plex matching, without sonarr, it's when items are requested that requires a 'Manual Match' and to select the correct match below, It doesn't actually show any items to match. I raised this in the discord support and sct replied with;
> 
> ```
> Intentional. But we should probably handle it gracefully if there is no Sonarr setup.
> We use one of your Sonarr instances instead of the tvdb api directly, for several reasons :smile:
> ```
> 
> So I need sonarr because of this, unless it's now working without the need for sonarr :)

Ah, I see. Unfortunately a connected Sonarr server is still a requirement for this functionality.

**Comment by Reddax** [comment]
> > It's not the plex matching, without sonarr, it's when items are requested that requires a 'Manual Match' and to select the correct match below, It doesn't actually show any items to match. I raised this in the discord support and sct replied with;
> > ```
> > Intentional. But we should probably handle it gracefully if there is no Sonarr setup.
> > We use one of your Sonarr instances instead of the tvdb api directly, for several reasons :smile:
> > ```
> > 
> > 
> > So I need sonarr because of this, unless it's now working without the need for sonarr :)
> 
> Ah, I see. Unfortunately a connected Sonarr server is still a requirement for that functionality.

Is there something that needs to be implemented to help solve this? as its annoying to have to monitor crawls on plex and reboot the docker if it locks up. Such as completely disable sonarr for requests or stop the sonarr errors bringing down the website or something?

**Comment by TheCatLady** [comment]
> Is there something that needs to be implemented to help solve this? as its annoying to have to monitor crawls when content is added to plex and reboot the docker if it locks up. Such as completely disable sonarr for requests or stop the sonarr errors bringing down the website or something?

As you're only using Sonarr for the manual match functionality, I think you would just need to remove your Sonarr server if/when it is no longer a dependency for that feature.

I'm not sure why your Overseerr instance is locking up, however.  Sonarr failures alone wouldn't cause that.

**Comment by Arsur** [comment]
I have a similar behavior. Webpage is not always crashing totally. If i stop "Plex Recently Added Scan" everything gets awaylable again. I think this pr would help for a moment https://github.com/sct/overseerr/pull/1440

**Comment by Vinnpinn** [comment]
@Arsur Try running a full scan, it seems like it has issues with the library if it didn't complete the full scan during setup. If this error happens it constantly tries to rescan the recently added items, however it never finishes since it can't be completed in 5 minutes so it just starts over.
I've just deleted every library except one from overseerr and started a full scan. It seems to work fine, once the first (my biggest, by far) library is done I'll add the others. Looks like it'S updating a lot of entrys that it didn't pick up correctly.

**Comment by danshilm** [comment]
Can this be opened back please?
