### ISSUE TITLE
Upcoming Movies and Shows - Recognize items that are already added in Sonarr/Radarr as "Approved"

### ISSUE THREAD

**Issue by drewwats** [sct/overseerr#1500]
#### Description

Having just switched over from Ombi, I can say Overseerr is much cleaner and less buggy. However, the feature I am missing most is the recognition of upcoming items that have already been added in Sonarr/Radarr that are not yet available for download.

#### Desired Behavior

These items need some sort of indicator similar to how Ombi would show them as "Approved" and a mechanism that prevents them from being requested, since they are already in the system.

#### Additional Context

None, I love the app, it's a game-changer.

**Comment by samwiseg0** [comment]
This already exists. Please verify that you have enabled scanning for your *rrs. If you have any questions feel free to stop by the discord server. 

<img width="319" alt="Screen Shot 2021-04-25 at 3 13 26 PM" src="https://user-images.githubusercontent.com/2241731/116006353-d2051700-a5d8-11eb-93e1-e062c2526b57.png">
<img width="232" alt="Screen Shot 2021-04-25 at 3 11 42 PM" src="https://user-images.githubusercontent.com/2241731/116006322-b6017580-a5d8-11eb-891c-3e990816ede7.png">
<img width="690" alt="Screen Shot 2021-04-25 at 3 11 10 PM" src="https://user-images.githubusercontent.com/2241731/116006323-b6017580-a5d8-11eb-872c-a5fa0f42287f.png">

**Comment by drewwats** [comment]
Ah, it was the 4k checkbox that screwed it up. Thanks for the info!
