### ISSUE TITLE
Use hostname FQDN when sending email

### ISSUE THREAD

**Issue by pro4tlzz** [sct/overseerr#1515]
#### Description

When emails are sent via Overseerr the header contains `Received: from [127.0.0.1].`

This can cause issues with some ESPs marking the email as spam as the sending server has not declared itself properly.

#### Desired Behavior

Ideally the sending server is supposed to specify the FQDN, not doing so leaves the email marked as spam in some ESPs

#### Additional Context

Radarr uses /etc/hosts to provide a unique ID from the container which is enough to actually get around the spam filter but it would be nice to properly specify the hostname.

When using host networking Docker will pull /etc/hosts from the Host OS into the container. Using the FQDN in /etc/hosts would be best way to go imo

**Comment by TheCatLady** [comment]
This is an issue with your email/SMTP provider, not Overseerr...?

The headers of an email from my own Overseerr instance:
```
Received: from <redacted FQDN>. [<redacted IP>])
```

**Comment by pro4tlzz** [comment]
> This is an issue with your email/SMTP provider, not Overseerr...?
> 
> The headers of an email from my own Overseerr instance:
> 
> ```
> Received: from <redacted FQDN>. [<redacted IP>])
> ```

is that from the very bottom of your email?
From the initial header?

**Comment by TheCatLady** [comment]
> is that from the very bottom of your email?
> From the initial header?

I just checked the raw email message and copied the header (removing the sensitive info).  Unsure what you're referring to when you say "the very bottom of [the] email."

**Comment by pro4tlzz** [comment]
> > is that from the very bottom of your email?
> > From the initial header?
> 
> I just checked the raw email message and copied the header (removing the sensitive info). Unsure what you're referring to when you say "the very bottom of [the] email."

Email headers are meant to be read from the bottom to the top.

Towards the top you will see the final hop and authentication results, at the bottom of the email header you will see the initial host.

For example in the email I got about this feature request `Received: from github.com ` is the initial email sender

Thanks

**Comment by samwiseg0** [comment]
@pro4tlzz I think the application URL should be used as the hostname? We should be able to parse the application URL to be the hostname. WE can then set a dummy hostname if that setting is blank?

**Comment by pro4tlzz** [comment]
> @pro4tlzz I think the application URL should be used as the hostname? We should be able to parse the application URL to be the hostname. We can then set a dummy hostname if that setting is blank?

That would be a good idea, it is easier to pull the FQDN from their than trying to locate the host file for each OS
