### ISSUE TITLE
Mark as Available without having to Request

### ISSUE THREAD

**Issue by batty1991** [sct/overseerr#1519]
#### Description

When a title fails to match my existing media it does not show  as available.
If I want to 'Mark as Available' I have to first Request the title and then 'Mark as Available'.

#### Desired Behavior

It would be nice to be able to mark a title as available without having to make a request first.
I do not want to trigger another search and download just to fix an item that failed to match existing content.

**Comment by sct** [comment]
This is something we can definitely add, but I wonder why you are having trouble with content not matching? Have you tried the solutions in our faq? Link: https://docs.overseerr.dev/support/faq#some-media-is-missing-from-overseerr-that-i-know-is-in-plex

**Comment by TheCatLady** [comment]
@batty1991 You can also fix whatever issue is causing matching issues, and then manually run the scans in `Settings > Jobs & Cache`. Manually marking items as available doesn't add the Plex media links to the DB, so you don't get the nice `Play on Plex` buttons in the UI.

**Comment by batty1991** [comment]
@sct I have not done the research in the logs for missing content (didn't realize it was there) but I will do so. Thank you for pointing towards viable breadcrumbs.
