### ISSUE TITLE
Overrride "Automatic Search" for individual request

### ISSUE THREAD

**Issue by Iguana9999phil** [sct/overseerr#1523]
#### Description

Overseerr sonarr / radarr settings got the global "Enable Automatic Search", sometimes I want to approve a request so it goes into the *darrs but will not auto search.

#### Desired Behavior

Have an override in the advanced options when approving a request to disable "Automatic Search" for that request only.

#### Additional Context

For some foreign requests (mostly series) I tend to get the request from a specific source which most of the time does not show up in the *darrs.
In these cases it would be beneficial to have a setting to approve the request so it goes into the darrs but without auto search.

**Comment by TheCatLady** [comment]
This is definitely something we can add, but is there any real benefit to having this option?  The *arrs performing a search doesn't prevent you from fetching the media yourself from a different source.

**Comment by Iguana9999phil** [comment]
I know it's a bit of a edge case but yes for me it does. As an example I had 5 requests for some foreign series. Those are floating around on the sources in the *darrs but in a lower quality, not complete or without subs. On my source I can get them manually in better quality and with internal subs. Adding those 5 to sonarr will make it search on add and fetch those lower / not needed version. I could decline the request and add it manual in sonarr but still, the feature in overseerr would be a +

**Comment by TheCatLady** [comment]
@Iguana9999phil A workaround is to add your *arrs to Overseerr twice -- once with search enabled, and again with search disabled. You can then select the *arr server to which to send each request before approval.

**Comment by Iguana9999phil** [comment]
Good one, I'll try that.
