### ISSUE TITLE
Show more info per request in the main "Requests" overview

### ISSUE THREAD

**Issue by Iguana9999phil** [sct/overseerr#1524]
#### Description

The lack of general info for a pending request makes me click on the "title" to get into the summary overview 99% of the time. These are clicks I would like to avoid.

#### Desired Behavior

Have more general info, which is already available on the summary page of the request, available. Having each request show the "original language, genre(s), season count etc" per request in the "requests" overview will greatly speed up those request which do not need their advanced options adjusted (mostly path)

#### Additional Context

As seen on the screenshot for a typical request were I would need to change the path (foreign content) I need to click on the title to go into summary view to check "original language, genre(s), season count etc" on desktop there is enough free space to show this info on the request itself, for the 90% of request that don't need to be edited I can just click "Approve" or "Decline" and go to the next one.

![Screen Shot 2021-04-28 at 1 39 53 PM](https://user-images.githubusercontent.com/40793267/116352965-93659b80-a828-11eb-8c60-c904c1427c58.png)

**Comment by TheCatLady** [comment]
You can also click on `Edit Request` directly in the request list, which would reveal the data you are interested in AND allow you to make any desired adjustments.

**Comment by Iguana9999phil** [comment]
Yes, doing that now for all of the requests.
For more context, the *darrs are set to default to a path for English content. As 90% of the requests are that, having the info in the overview would make those 90% a "Approve / Decline" thing. Those other 10% I don't mind to use `Edit Request`

**Comment by bbakermmc** [comment]
Id say include everything from the small gird on the overview page, if a movie is requested today for 2023, I might want to just leave it unapproved as to not add to arr until closer to release date.

**Comment by costaht** [comment]
I was about to open a Feature Request, but just so I don't duplicate the request, please also add the release date to this card. Below an example:

![Screenshot from 2021-05-01 23-03-50](https://user-images.githubusercontent.com/50637431/116800772-13625e80-aad2-11eb-9502-dffba78a7386.png)

**Comment by Iguana9999phil** [comment]
Any update? Bot marked it stale.
