### ISSUE TITLE
Database access timeframe is too small

### ISSUE THREAD

**Issue by nadinio** [sct/overseerr#1534]
#### Description

Error: SQLITE_BUSY: database is locked whenever trying to initially setup.

#### Version

What version of Overseerr are you running? (You can find this in Settings → About → Version.)

1.23.2

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Set docker config directory to a network attached storage location
2. Try to start the docker container

#### Expected Behavior

Exponential backoff perhaps? Wait longer on the next response to see if the database responds in increased amounts of time.

#### Screenshots

![2021-04-28 21_38_33-U__overseerr_logs_overseerr-2021-04-28 log - Notepad++](https://user-images.githubusercontent.com/3119027/116492382-1ce98d80-a86a-11eb-8fb5-f1f405a52685.png)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Device:** TrueNAS Storage Server
- **OS:** Debian

**Comment by sct** [comment]
We just the WAL journal mode for SQLite so network storage is simply not possible. Even without WAL, you would still have severe performance issues mounting the DB over a network.

You will have to find a way to get the DB on the same filesystem.
