### ISSUE TITLE
Retrieve and display per user disk usage from radarr and sonarr

### ISSUE THREAD

**Issue by douglasparker** [sct/overseerr#1539]
#### Description

Currently there is no way to see the total disk usage based on a users media requests. If we were able to see this data, we could determine which user needs to purge some media from the server.

This also opens up the option to set per user disk quotas in Overseerr.

#### Desired Behavior

- Calculate per user disk usage during Radarr Scan and Sonarr Scan
- Display per user disk usage on the users profile page (`users/1` endpoint)

#### Additional Context

There is no additional context to provide.

**Comment by douglasparker** [comment]
Bump

**Comment by douglasparker** [comment]
@samwiseg0 Hey, can we have this reopened?

**Comment by douglasparker** [comment]
.

**Comment by douglasparker** [comment]
.

**Comment by sct** [comment]
We don't plan to add per-user disk quotas to Overseerr. In turn, I don't think we ever plan to show per-user disk usage at all. (Tracking this would be nightmarish, I feel)

If you have disk usage issues with your friends, don't give them auto-approve and choose what you approve? Maybe talk with them about it? If anything, I think this primarily benefits resellers, which we would like to avoid.

One more note, #2103 will probably be a great solution in determining if users are actually watching the content they request. Can help make an informed decision about what media is stale and can be removed.

Closing this. Thanks for the request though!
