### ISSUE TITLE
Find In Plex Option

### ISSUE THREAD

**Issue by bbakermmc** [sct/overseerr#1547]
#### Description

Many users can have multiple servers configured in plex, having an option to "Find In Plex" would help, especially because the meta Id used in "Play in Plex" is unique to the system configured in overseerr, which a user might not have access to, especially if you keep a "clean" master for overseerr, and separate instances for users.

#### Desired Behavior

Drop down for the "Play in Plex" to have a option for "Find in Plex" that just calls the "Search" and passing in the Title.
Example:
https://app.plex.tv/desktop/#!/search?query=Dave%20Chappelle%3A%20The%20Kennedy%20Center%20Mark%20Twain%20Prize%20for%20American%20Humor

![image](https://user-images.githubusercontent.com/30090055/116645350-a4ef9600-a943-11eb-9865-343c91b086a6.png)

**Comment by TheCatLady** [comment]
I don't see this being supported, as we have no plans to support multiple Plex servers.

Changing this to a search would result in a less-ideal experience for users with only one Plex server, which what Overseerr was designed for.

**Comment by bbakermmc** [comment]
Who said replace, I said add a 2nd option.  I don't know many users with just 1 instance but that's just me.  Most of mine have their own instances and the shared one.  Plus this option allows you to have dev server to test new version of plex w/out impacting the main server.  If you were testing the new agents you could verify if its matching right before you move the prod instance over.

I don't have 4k configured yet, but if you have a 4k and 1080p I assume there is a toggle to know what one to play, if not this fixes that also.

At the end of day, the option is to give the user the best experience possible, so if they have to wait for it to download on server A, maybe they can "Find On Plex" they have it on Server C already.  All this feature is doing is prevent the user from copy/pasting the title in to the search in Plex, thus saving a few clicks, it adds 0 processing into Overseerr and the user saved some time, win win in my book.

Is the "Play In Plex" toggable?
