### ISSUE TITLE
Cant Request Pending Shows With Higher Permissions

### ISSUE THREAD

**Issue by bbakermmc** [sct/overseerr#1548]
#### Description

User A request shows, requires approval.
User B account is configured to not need approval, is not able to request show.

#### Additional Context

Users who don't require approval should be allowed to request the item w/out admin approving request or needing permission to approve requests.  I think the desired solution would be for users with no approval needed, they don't see "pending", they see as not requested and can just request the show and it would remove/update the pending one.  This way the "power user" wont see all the pending requests and just start approving them, but it does allow for the pending request to be bypassed for power users.

**Comment by TheCatLady** [comment]
The issue that I see here is that it would not be great UX to allow users without request management permissions to delete/replace other users' requests.

We currently plan to support subscribing to existing requests, but doing so would not approve the requests.

**Comment by costaht** [comment]
What about users with auto approve enabled overriding the pending approval request? I think that's not a bad idea.

**Comment by bbakermmc** [comment]
Thats what Im saying?  I just dont want my auto approve users to just see all "pending" shows and start to just approve them thinking they are helping, why I suggested to not show "pending" to auto approve users, and if they happen to request it, it would just ignore the pending request and replace it with the new one or "approve" the first one.  To me its a bug, because it prevents auto approve users from requesting stuff, especially new things that you might not get to for hours because you are sleeping etc, so now the users are upset because you didnt approve it, and the auto approve users cant even request it, and I dont want to give approve permissions to someone who might just approve everything.

**Comment by TheCatLady** [comment]
> What about users with auto approve enabled overriding the pending approval request? I think that's not a bad idea.

It's not so simple, especially with request limits.  And again, it's not great UX to have your request overwritten by someone else's, since it would then disappear from your Overseerr request list if you don't have the `View Requests` permission.

> To me its a bug, because it prevents auto approve users from requesting stuff, especially new things that you might not get to for hours because you are sleeping etc, so now the users are upset because you didnt approve it, and the auto approve users cant even request it, and I dont want to give approve permissions to someone who might just approve everything.

This is not a bug. Things work as they were intended/designed to at this time.  This is a feature request, which may or may not be implemented.
