### ISSUE TITLE
X-Remote-User

### ISSUE THREAD

**Issue by yeyeoke** [sct/overseerr#1555]
#### Description

Not really a problem, more of an enhancement since right now it requires my users to login once to my domain, and once again to Overseerr. A simple fix would be to accept X-Remote-User or something like that. 

#### Desired Behavior

What I would like to be implemented is header based authentication, i.e. I login with my username and password to my domain, my webserver then forwards X-Remote-User to Overseerr and Overseerr accepts this and logs me in to a user with the same username I previously used to login to my domain. 

I.e. User1 logs in to domain/authelia (which im using right now) it forwards X-Remote-User to Overseerr which proceeds to log me in as User1.

**Comment by sct** [comment]
This would be a massive security hole. Won't be adding this.

**Comment by yeyeoke** [comment]
Hi, I'm sorry I was probably unclear in my suggestion. What I'm really asking for is Basic Authentication using a HTTP Header. 

For a better explanation see Grafanas implementation: 

https://grafana.com/docs/grafana/latest/auth/auth-proxy/

I'm essentially asking for a way to outsource authentication to my webserver which instead of letting Overseerr handle it. Is this still a massive security hole? 

If so I very much respect your stance, I'm simply trying to get a better understanding of if and why it's unsafe.

**Comment by lenaxia** [comment]
Hi, I'd like to second this. This isn't a security issue. This is a standard implementation of remote-user. As yeyeoke pointed out, grafana is a huge example.

I would not feel comfortable putting Overseerr on the open internet, however I would be comfortable putting it behind Authelia and Traefik as a reverse proxy setup that provide a layer of security that I can be confident in.

Here is the Authalia documentation on Forward Authentication: https://www.authelia.com/docs/community/using-remote-user-header-for-sso-with-jira.html

And the Traefik forward auth docs: https://doc.traefik.io/traefik/middlewares/forwardauth/

**Comment by sami-shakir** [comment]
I agree with them also. It is not the best user experience to have them authenticate with authelia, then authenticate to overseerr.
