### ISSUE TITLE
Users request marked as "Failed"

### ISSUE THREAD

**Issue by Connor2397** [sct/overseerr#1580]
#### Description

Users are getting random failulars when requesting shows or movies.

#### Version

1.23.2

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

Unable to reproduce my self hwoever, multiple users are having the issue all with TV Shows.

#### Expected Behavior

Request is meant to be submitted. auto-approved by Overseerr then added to Sonarr to download.

#### Screenshots

![image](https://user-images.githubusercontent.com/17101541/117208918-97c42280-aded-11eb-98e6-bbefcd27e4e0.png)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

Unable to say as it's different for each user.

#### Additional Context

The following shows up in the Logs:
May 05, 2021, 9:26:44 PM	ERROR	Sonarr API	Something went wrong while adding a series to Sonarr.
`{
 "errorMessage": "Request failed with status code 400",
 "options": {
  "profileId": 3,
  "rootFolderPath": "/tv/TV Programmes/",
  "title": "Seinfeld",
  "tvdbid": 79169,
  "seasons": [
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9
  ],
  "seasonFolder": true,
  "seriesType": "standard",
  "monitored": true,
  "searchNow": true
 },
 "response": [
  {
   "propertyName": "LanguageProfileId",
   "errorMessage": "Language profile does not exist",
   "attemptedValue": 0,
   "severity": "error",
   "errorCode": "LanguageProfileExistsValidator",
   "formattedMessageArguments": [],
   "formattedMessagePlaceholderValues": {
    "propertyName": "Language Profile Id",
    "propertyValue": 0
   }
  }
 ]
}`

**Comment by samwiseg0** [comment]
This is not a bug. You have a mis configuration in overseerr/sonarr. 

Make sure you have a language profile set. If you need further asistance feel free to stop by the discord server. 

```
"Language profile does not exist"
``

Thanks
