### ISSUE TITLE
PWA: Minor portrait & landscape orientation issues with back button

### ISSUE THREAD

**Issue by aniqueta** [sct/overseerr#1582]
#### Description

UI layout is incorrect when changing device orientation (e.g. landscape to portrait) and navigating using back button.

#### Version

1.24.0

#### Steps to Reproduce

Use a device that has portrait and landscape orientations. (My case was an iPad.)

1. Open Overseerr PWA
2. Switch to landscape orientation
3. Navigate to Settings
4. Navigate to Discover
5. Switch to portrait orientation
6. Use back button to go back to Settings

#### Expected Behavior

UI displays properly in new orientation.

#### Screenshots

![screenshot](https://user-images.githubusercontent.com/65845439/117222720-fb842680-adc0-11eb-949f-0f9394d94d03.jpg)

#### Device

- **Platform:** Tablet
- **Device:** iPad
- **OS:** iOS 14.5
- **Browser:** Safari (for Home Screen PWAs)

#### Additional Context

Thanks for the work on the PWA. Appreciate implementation of the back button. Don't see any other issues other than this.

**Comment by sct** [comment]
Checked on my iPad and this seems to have been fixed in #1667 and will be in the next release.

If you still have issues then, let us know.
