### ISSUE TITLE
PWA: serve site.webmanifest dynamically according to configured application title

### ISSUE THREAD

**Issue by chessmango** [sct/overseerr#1586]
#### Description

Hi! Thanks for the great development and 'full' PWA addition. Looking eeeexcellent!
Just a request here that may be useful: have `site.webmanifest` (and whatever else may be required for PWA use on other platforms - not 100% clear on what standards are) served dynamically and have `name` and `short_name` either configurable or mirror the configured application title by default.
As things stand, my users are pretty used to the name I've given my particular instance, so I'd like to avoid having to rely on 'Overseerr' specifically having to enter their vocabulary, necessarily. :D

#### Desired Behavior
Add app to home screen (or `<insert PWA workflow here>`) and have it use the same name as the configured 'Application Title'

#### Additional Context
https://github.com/sct/overseerr/blob/v1.24.0/public/site.webmanifest
Currently a 'static' `site.webmanifest` file that effectively names the app 'Overseerr'

I'd submit a PR for this behaviour but I'm not entirely sure how this would play out with Typescript :) please let me know if there's anything I can assist with though - can blunder my way through an attempt if it helps :P

Thanks!

**Comment by sct** [comment]
If you would like to try it, please go ahead! Might be a good learning experience. You can bug me about any questions you might have in the discord :) Don't let TypeScript scare you. It's still JavaScript, just with types!

**Comment by chessmango** [comment]
Cool, will do! Thanks for the encouragement :P
