### ISSUE TITLE
Multi-Channel Support for Discord (and possibly other notification services)

### ISSUE THREAD

**Issue by vember31** [sct/overseerr#1588]
#### Description

[note that below, it could be broadened to Slack as well, for example]

As it stands currently (v1.24), Overseerr supports Discord integrations being sent to one channel aka one webhook URL.  That means that notifications about requests, approvals, etc. all can only go to one Discord channel.  I'd love if it was possible to define a Discord webhook URL per notification type.  For example, I'd like to define one webhook for the "media requested" notification type, and define a different Discord webhook URL for "media available".  This could be implemented as an option to override the default webhook URL per notification type, such that if you check a box to "override webhook URL" for a particular notification type, it'll let you enter a different webhook URL for that one.

The reason I want to do this is because I want some notifications to go to only me as the admin in my own personal channel (e.g. when something has been requested) vs. other types of notifications, like when media is available and it mentions them, as well (e.g. writes out '@user' above the notification details).  For those, I would want them to go to a different channel that has all of my users on it.

#### Desired Behavior

Provide optional override URLs for each notification type.  If nothing is overridden per notification type, then it would simply send to the default webhook as it works today.

#### Additional Context

The below screenshot shows kind of what I'm thinking of, but of course it could be implemented in a much more attractive way 😄 

![image](https://user-images.githubusercontent.com/17370796/117305770-b275b600-ae44-11eb-985d-68adbb9d49d3.png)

**Comment by vember31** [comment]
I just came across https://github.com/sct/overseerr/issues/972, which gets at this a bit as well.  I'll keep this open for now to be evaluated, but if it's determined that it's appropriate to manage these overrides outside of overseerr, I'll look more into the use of software outside of overseerr to accomplish this :) 

Thank you all!

**Comment by danshilm** [comment]
This seems like something [`webhook`](https://github.com/adnanh/webhook) can achieve right now.

**Comment by TheCatLady** [comment]
> I just came across #972, which gets at this a bit as well. I'll keep this open for now to be evaluated, but if it's determined that it's appropriate to manage these overrides outside of overseerr, I'll look more into the use of software outside of overseerr to accomplish this :)

I do think that setting up an incoming webhook server and writing your own logic to handle various notification events is the way to go here.

Alternatively, you can take a look at [Requestrr](https://github.com/darkalfx/requestrr), which has Overseerr support!

**Comment by vember31** [comment]
I use Requestrr actually! Moved to overseerr as soon as requestrr supported it :) but I do have some users who are using Overseerr's GUI to request now & then instead of via Requestrr, so that is a motivator for this.

Anyway, the webhook suggestion looks awesome & will be a cool thing to use in any case :) thank you guys for all you do on this project - i love it.  Closing this.
