### ISSUE TITLE
Add Polish language

### ISSUE THREAD

**Issue by orionowy** [sct/overseerr#1604]
Please add Polish language in weblate

**Comment by sct** [comment]
Done: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/pl/

If you need help or have any questions let us know on Discord!

**Comment by sct** [comment]
Do you still plan on translating Polish? You haven't started yet, which is fine, but I want to know you still plan to do it.

I will remove it from Weblate for now so if you want to start translating just let me know and I will add it back.
