### ISSUE TITLE
Add more than one discord notification agent

### ISSUE THREAD

**Issue by AthAshino** [sct/overseerr#1664]
#### Description

I'm using the Discord notification with every notification available. The problem is that I can only choose ONE Webhook (meaning one text channel). With that, everyone must see the request asked to see the rest

#### Desired Behavior

My point is to make possible to create as many discord notification agent as I want. With that, I will be able to associate user notification to a specific channel, and associate the demand notification to another one

another improvment would be to let our users create their own discord notification agent, so they can receive their notification wherever they want

**Comment by sct** [comment]
There are currently no plans to add this type of support to the DIscord agent. I recommend setting up a custom webhook and push it to your own service that can handle splitting it up into any # of discord channel you wish.

**Comment by WoisWoi** [comment]
> There are currently no plans to add this type of support to the DIscord agent. I recommend setting up a custom webhook and push it to your own service that can handle splitting it up into any # of discord channel you wish.

The appearance of the issue system does not change the plans?

**Comment by goldenpipes** [comment]
For anyone who wants a workaround for this you can use the slack notification with discord, to have a separate webhook in discord.

**Comment by yuval-ziv** [comment]
Can we maybe get support for that? Any other ARR service allows that, and needing to have a workaround shouldn't be the preferred way.
I have notifications in telegram, and I want to split requests/issues from the available notifications. 
I can try to implement that myself, but I want to discuss the best way to do that, and if that is something you would accept.

**Comment by EtzBetz** [comment]
I'd also like to have this feature, to be able to post different kinds into different channels. Willing to do the work, if I get some pointers.

**Comment by Piddox** [comment]
I would very much value this being implemented yes, thanks!

**Comment by Kamaad1** [comment]
Agreed, this would be incredibly useful for splitting requests being made and media becoming available, so that users aren't bombared with whenever someone wants something added.
