### ISSUE TITLE
Add Ctrl + F shortcut or keep search bar active

### ISSUE THREAD

**Issue by costaht** [sct/overseerr#1685]
#### Description

I was adding my Netflix watchlist to OS and found myself having to click on the search bar every time I needed to search for a new title. I would like to request the addition of Ctrl + F shortcut for the search bar or a simpler solution, that is to keep the search bar always active.
That would make searching a lot easier when people are adding many titles at once.

#### Additional Context

Discourse forums have shortcuts implemented.
<https://ask.fedoraproject.org/> Crtl + Alt + F
<https://forums.plex.tv/>

**Comment by zwimer** [comment]
I recommend making this a toggle-able setting so that those who make use of the browser find functionality invoked by the ctrl-f key combo can still do so.
