### ISSUE TITLE
Error Deleting Local User

### ISSUE THREAD

**Issue by donovanvanheerden** [sct/overseerr#1713]
#### Description

I have a local user on overseerr that I wish to remove, tried deleting that user and it failed. This user does have 1 media request that was approved.

#### Version

59b2ec11fa8868bf6873ffa80f4999ae10d65637 (develop)

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Create local user
2. Try delete local user

#### Expected Behavior

Local user account should be removed.

#### Screenshots
Screenshot of delete user request response:
![image](https://user-images.githubusercontent.com/13114346/120155604-4c851000-c1f1-11eb-8091-611790dff80b.png)

Screenshot of console for docker container:
![image](https://user-images.githubusercontent.com/13114346/120155918-aa195c80-c1f1-11eb-84e0-6d4650002091.png)

**Comment by sct** [comment]
Can you check if this error is still happening on the latest version? 4a042f12be6510ee47de3a7e025497f8d132d6a1

**Comment by donovanvanheerden** [comment]
Sure, I'll do that.
