### ISSUE TITLE
iOS/Safari browser left on Overseerr sporadically refuses to allow browsing to another page

### ISSUE THREAD

**Issue by citadella** [sct/overseerr#1729]
#### Description

Sometimes, but but always every time, when I page away from Safari, having been using Overseerr, and then come back to Safari, I find I am unable to go to a different page that I type into the URL bar, instead Overseerr reloads ourself no matter what I type or how often. 

#### Version

1.24.0 but this has been present for at least several versions

#### Steps to Reproduce

It's not consistent, but *generally* if I go to Overseerr and then, with Overseerr page still in the foreground of Safari, switch to a different app and then, say an hour or so later, come back to Safari and try to go to, say, Google.com (every website has the same result), Overseerr reloads and my requested page is not shown. The only way I can load the page I want is to switch to a different Safari tab or close Overseerr (thereby switching to a different Safari tab). Brave browser doesn't seem to be affected and I don't know whether Overseerr tabs not in focus are affected. I also don't know how long it takes to cause this error, but it seems if I go back to Overseerr quickly it didn't do this, only being an issue when I was in Overseerr, put down my phone, and come back to browse somewhere else an hour or two later

#### Expected Behavior

I expect the site I've entered to load. They do not. 

#### Screenshots

If applicable, please provide screenshots depicting the problem.

#### Device

- **Platform:** Smartphone only-have not seen this issue on desktop
- **Device:**  iPhone 12
- **OS:** iOS 14.5 (but was present for at least 14.4
- **Browser:** Safari

#### Additional Context

Please provide any additional information that may be relevant or helpful.

**Comment by samwiseg0** [comment]
This sounds like an safari bug? How webpages are handled after being backgrounded is handed by iOS . Brave and every other browser on iOS use the exact same browser engine as safari. There is only one actual browser engine. I can't see how this is an overserr issue.

**Comment by citadella** [comment]
Fair enough, but this occurs on no other page except for Overseerr. And if it was indeed a Safari bug, wouldn't we expect to see it on brave as well?

**Comment by samwiseg0** [comment]
Not necessarily. Safari has its own user interface that is separate but the engine that loads the page and allows user interaction on the page is the same. This is why it seems like more of a safari app specific bug because it works on brave. Meaning the engine that loads and handles the page is the same but for some reason the safari app is doing something different in the user interface that causes this bug. 

Also this maybe happening on other websites you just may not be visiting them. I suspect there is something on the overseerr page that the app is getting hung up on but again if it _only_ happens on safari in iOS then it seems that is the issue.

**Comment by danielkerwin** [comment]
This issue is such a pain! @samwiseg0, this occurs only when on overseerr page and no other website I’ve ever browsed on safari. 

Such an annoying experience, please reopen this issue

**Comment by citadella** [comment]
Only just noticed-is the main project dead?

**Comment by stirlo** [comment]
I'm seeing a similar issue where the www reloads on safari ; I'll try some other browsers and see if that helps ; weirder it seemed fine on an earlier setup on same machine.   

I'll reply with results or if I work out why it's happening

**Comment by stirlo** [comment]
Orion (iOS so it's likely having same issue as safari) will see if I can find a Linux machine or something similar or if brave works / whatever
