### ISSUE TITLE
Notification Spam

### ISSUE THREAD

**Issue by XenosTechLabs** [sct/overseerr#1736]
#### Description

When a user requests something it starts a notification spam.

#### Version

60c3ced9e2466568eecde93c88410c87ff0b796f

#### Steps to Reproduce

Request a Movie or TV Show if auto-approve is turn on. Doesn't seem to be an issue if auto-approve is turn off.

#### Expected Behavior

When someone requests something it should only send out one notification alert.

#### Screenshots

https://discord.com/channels/783137440809746482/789002037529804833/850463226797752360

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

Android, Email, Discord

#### Additional Context

@TheCatLady has narrowed down a3f04b3f3522d46dc65178bddd1e986426e48050 as the issue. The rest of the conversation is on Overserr's Discord support channel

**Comment by TheCatLady** [comment]
a3f04b3f3522d46dc65178bddd1e986426e48050 reverted in 0918b254132b0541999486e1f0679d0c0cd65864.
