### ISSUE TITLE
"latest" docker image tag not being updated

### ISSUE THREAD

**Issue by mous2890** [sct/overseerr#1737]
#### Description

I noticed my Overseerr application hasn't been updated in nearly a month (I use watchtower). Checking dockerhub, I can see the latest tag hasn't been updated for quite some time - nearly a month also. The documentation suggests we use the latest tag rather than specifying. 

Is there a reason why the latest tag isn't being updated?

**Comment by TheCatLady** [comment]
@mous2890 This is not a bug. If you have questions re: development, etc., best to reach out on Discord.
