### ISSUE TITLE
Log file time format is incompatible with the fail2ban filter given in the documentation because of missing timezone information.

### ISSUE THREAD

**Issue by omeryagmurlu** [sct/overseerr#1757]
#### Description

The fail2ban filter for overseerr from https://docs.overseerr.dev/extending-overseerr/fail2ban successfully finds failed authentication attempts using `fail2ban-regex`, while `fail2ban-client` doesn't register any fails. I've looked for the cause of this and it seems that fail2ban is misinterpreting the timestamp in the logs. The logs output timestamps in UTC without any timezone information (no +02:00 etc.), which gets interpreted by fail2ban as local time (presumably).

#### Version

1.24.0

#### Expected Behavior

Either the documentation should be updated with a working filter (I'm a fail2ban noob, sorry) or the log output should include timezone information.

#### Screenshots

Overseerr logs:
![image](https://user-images.githubusercontent.com/8201544/121093679-08e46480-c7f6-11eb-87ca-a331c800c8b9.png)
ISO-8601:
![image](https://user-images.githubusercontent.com/8201544/121093863-595bc200-c7f6-11eb-8956-a3376e679a6b.png)
What fail2ban expects:

    Date template hits:
    |- [# of hits] date format
    |  [14] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
    `-

**Comment by TheCatLady** [comment]
It's pretty standard to print log timestamps in UTC (the `Z` at the end indicates UTC).  I would be pretty surprised if Fail2ban did not support the datetime format used in our logs, as it is quite common.

Unfortunately, Fail2ban's timestamp regex doesn't have any documentation (See https://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Filters).  If you confirm that Overseerr's timestamp format doesn't work with Fail2ban, the correct path forward is to submit a bug report to their repo, as described in their manual.
