### ISSUE TITLE
Popular/Trending Collections

### ISSUE THREAD

**Issue by robdplatt** [sct/overseerr#1775]
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

#### Desired Behavior

Would be nice to have a Popular/Trending Collections similar to Discover, to be able to quickly add entire collections.

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by TheCatLady** [comment]
There is no Collections Discover endpoint in the TMDb API, so this might not be possible.

**Comment by TheCatLady** [comment]
> Maybe an Request/Add Collection button after clicking "View [Name of Movie] Collection"?

There are already request buttons for collections.  (Note that the button does not appear when all movies in the collection are already requested/available.)

**Comment by robdplatt** [comment]
Well then.. Let's just close this issue out then shall we?

Thanks for pointing that out :)
