### ISSUE TITLE
Rocket.Chat Integration

### ISSUE THREAD

**Issue by ados8** [sct/overseerr#1783]
#### Description

I have spent a number of hours trying to get the message platform Rocket.Chat working with Overseerr.
I have has this working with Ombi before switching to Overseerr and still have it working with Sonarr, Radarr and Tautaulli.
However, when working with Overseerr it will not work, there are 2 main issues:

- Using webhook even if its the same URL as other working apps results in a blank notification. If using the attached script then the first line from Overseerr is sent but never any subsequent lines.
- When using other options such as Slack which works as a substitute from Tautaulli to RC without issue.

#### Version

1.25.0

#### Steps to Reproduce

1. Using either webhook or Slack notifications to attempt sending data to Rocket.Chat

#### Expected Behavior

Test will result in empty notification but when content is added, approved, declined or any other state will result in another empty notification. However if you use the script it will allow only the first JSON top text line to be sent and nothing else.

#### Screenshots

If applicable, please provide screenshots depicting the problem.

#### Device

- **Platform:** desktop
- **Device:** PC
- **OS:** Windows 10
- **Browser:** Chrome and Edge

#### Additional Context

SCRIPT:
/* exported Script */
/* globals console, _, s */

/** Global Helpers
 *
 * console - A normal console instance
 * _       - An underscore instance
 * s       - An underscore string instance
 */

class Script {
  /**
   * @params {object} request
   */
  process_incoming_request({ request }) {
    // request.url.hash
    // request.url.search
    // request.url.query
    // request.url.pathname
    // request.url.path
    // request.url_raw
    // request.url_params
    // request.headers
    // request.user._id
    // request.user.name
    // request.user.username
    // request.content_raw
    // request.content

    // console is a global helper to improve debug
    console.log(request.content);

    return {
      content:{
        text: request.content.text
        // "attachments": [{
        //   "color": "#FF0000",
        //   "author_name": "Rocket.Cat",
        //   "author_link": "https://open.rocket.chat/direct/rocket.cat",
        //   "author_icon": "https://open.rocket.chat/avatar/rocket.cat.jpg",
        //   "title": "Rocket.Chat",
        //   "title_link": "https://rocket.chat",
        //   "text": "Rocket.Chat, the best open source chat",
        //   "fields": [{
        //     "title": "Priority",
        //     "value": "High",
        //     "short": false
        //   }],
        //   "image_url": "https://rocket.chat/images/mockup.png",
        //   "thumb_url": "https://rocket.chat/images/mockup.png"
        // }]
       }
    };

    // return {
    //   error: {
    //     success: false,
    //     message: 'Error example'
    //   }
    // };
  }
}

**Comment by TheCatLady** [comment]
Hi @ados8, as Slack and webhook notifications are not broken in their intended use case, this is not a bug.

It sounds like Rocket.Chat does not fully support everything in the Slack message API (Overseerr utilizes Slack "blocks" rather than just plain text).

As for utilizing the webhook agent, you probably need to customize the JSON payload in Overseerr to match whatever Rocket.Chat is expecting.

**Comment by TheCatLady** [comment]
If you find that the webhook agent is not sufficient for your use case and would like built-in support for Rocket.Chat, feel free to open a feature request!
