### ISSUE TITLE
Rocket.Chat Support

### ISSUE THREAD

**Issue by ados8** [sct/overseerr#1785]
#### Description

I have not been successful with webhooks and Rocket.Chat notifications.
Webhooks works perfectly to Rocket.Chat via Sonarr and Radarr, using Slack for Tautualli and Ombi.
Since everything about Overseerr is better than Ombi in my opinion I switched but notifications are a big loss.

#### Desired Behavior

When notifications for media requested, auto approved, approved, declined available and failed are sent to Rocket.Chat they are processed to supported webhook formatting.

However, if the wish for anything is possible it would be API support.
You could then post direct to channels or users as needed based on the notification variables from Overseerr.

#### Additional Context

Rocket.Chat webhooks are like following:
https://domain.com/hooks/the-webhook-url

They are called integrations which info can be found here: https://docs.rocket.chat/guides/administrator-guides/administration/integrations

As for the API I'm not sure and if there are costs involved.

**Comment by samwiseg0** [comment]
I don't see this happening anytime soon as integration with rocket chat should work today with webhooks.

According to their documentation you may need a script in rocket chat to achieve this. I would suggest going this route.

Here is an example for GitHub. 
https://docs.rocket.chat/guides/administrator-guides/administration/integrations/github

**Comment by ados8** [comment]
@samwiseg0 thanks for referencing some examples but I tried many including suggested but didn't work.
I did eventually find a working method via trial and error, its working enough but still will dream of an API 😉

**Comment by delorean02** [comment]
@ados8 any chance you can share your method?

**Comment by ados8** [comment]
@delorean02  which method are you referring to.
I had everything working but Rocket.Chat was too unstable with MongoDB.
It was rebuilt so many times from system crashes or updates I switched aware to more a stable platform.
