### ISSUE TITLE
Add "Join" as notification provider

### ISSUE THREAD

**Issue by PierreDurrr** [sct/overseerr#1786]
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

#### Desired Behavior

Provide a clear and concise description of what you want to happen.

Can you add support for "Join" by joaoapps for notification ?
https://joaoapps.com/join/

It is a great tool, in the spirit of apprise (even if less complete)

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by zanix** [comment]
It would still be nice to have Join as an option
