### ISSUE TITLE
Overseerr only finds partially tv series library on Plex

### ISSUE THREAD

**Issue by BodingClockchian** [sct/overseerr#1795]
#### **Description**

Hi, somehow Overseerr wont see all the series that are available on Plex.
This is after a full scan and a fresh install (docker)
It does find the library itself but just not all the items.

#### **Version**
Overseerr 1.25.0
Plex media server 1.23.1.4602

#### **Steps to Reproduce**

1. Settings > Plex > Start Scan (GUI will show 0 of 18 which is correct)
#### Expected Behavior

For Overseerr to show all the available tv series on Plex

#### **Device**

Both Overseerr and Plex run on Docker. Different devices tho.

#### **Additional Context**

Overseerr will show 3 of the 18 series available. These series are not recently added. 
All the tv series in the library do have an valid link with an imdbid etc.

For the 4k tv series it finds none. Plex does have 3 different series available.

Plex is connected with an direct link (10-1-1-2.xxxxx.plex.direct)
A different port than standard and SSL enabled.

**Comment by TheCatLady** [comment]
Hi @BodingClockchian, please see this FAQ entry for troubleshooting steps: https://docs.overseerr.dev/support/faq#some-media-is-missing-from-overseerr-that-i-know-is-in-plex

If you still run into issues after following those steps, feel free to reach out on Discord!
