### ISSUE TITLE
Ability to permanantly exclude 

### ISSUE THREAD

**Issue by Dulanic** [sct/overseerr#1815]
#### Description

I would like to have the ability to permanently exclude movies from discovery. Maybe a thumbs down or a ⦻ icon or something.

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

No

#### Desired Behavior

See description

#### Additional Context

Nothing really to provide, imagine would just be a exclusion table in the DB.

**Comment by TheCatLady** [comment]
Duplicate of #1744

**Comment by Dulanic** [comment]
Is it though? Thats a blacklist to auto deny.
