### ISSUE TITLE
Simple login if within local network

### ISSUE THREAD

**Issue by 4mirul** [sct/overseerr#1818]
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

#### Desired Behavior

Provide a clear and concise description of what you want to happen.

Add local login that can use simple username or without password login or auto-login if within network/IP/netmask. 
Show/hide user at login page.
Like Emby/Jellyfin/Plex.

Thanks for this great tool!

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by TheCatLady** [comment]
No plans to permit logins without passwords.  You can use Plex Auth if you don't want to keep track of a set of credentials specifically for Overseerr.
