### ISSUE TITLE
IMDB JSON Payload doesn't populate.

### ISSUE THREAD

**Issue by muddro1** [sct/overseerr#1837]
#### Description

imdb JSON payload isnt passing through

#### Version

What version of Overseerr are you running? (You can find this in Settings → About → Version.)

11378549c64c364ba3f0a4effbf4eb16ecd43f51Up 

#### Steps to Reproduce

I use node red for webhook notifications. viewing the payloads for certain notifications, it appears the imdb # doesn't appear to populate. TMDB # does.

#### Expected Behavior

imdb id # to be available in JSON payload

**Comment by TheCatLady** [comment]
There will always be a TMDb ID, but not always an IMDb ID.  The IMDb ID is only present if it has been added to the `External IDs` for the media on TMDb.  If the IMDb ID is missing, you can edit the item on TMDb and it'll get picked up in the future.

**Comment by muddro1** [comment]
Ok this makes more sense than the pre-edited answer. Thanks

**Comment by TheCatLady** [comment]
> Ok this makes more sense than the pre-edited answer. Thanks

Apologies.  I wasn't aware of the changes that were made to the scanner earlier.
