### ISSUE TITLE
Email agent doesn't have notification types like the others

### ISSUE THREAD

**Issue by gstacks13** [sct/overseerr#1839]
#### Description

All the other notification agents have notification type selectors, which allow the user to select what notifications are sent for that agent.  Email had this as well, but in recent updates this was removed.  Now I'm getting emails for notifications where I'd rather I didn't.

#### Version

11378549c64c364ba3f0a4effbf4eb16ecd43f51Up 

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Desktop
- **OS:** Windows 10
- **Browser:** Firefox

**Comment by sct** [comment]
It wasn't removed. It was moved to user settings. It's in the release notes. 

I don't recommend being on the develop tag anymore unless you plan on helping with development or finding bugs. If you aren't going to follow the commit history, stuff like this is going to happen very often 😀
