### ISSUE TITLE
Error requesting a series

### ISSUE THREAD

**Issue by shark2k** [sct/overseerr#1846]
#### Description

One of my users brought up that they are receiving an error when trying to request the series Whitstable Pearl from my instance of Overseer.

This is the error that pops up:
`We couldn't automatically match your request. Please select the correct match from the list below.`

When I check the logs this is what is says:
`No sonarr server has been setup`

I tried other movies/series and the dialog to make the request came up properly.  I don't use sonarr or radarr and haven't had this issue (that I'm aware of before) so it looks like strangely it's just happening with this one series.

#### Version

What version of Overseerr are you running? 1.25.0

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Search for Whitstable Pearl
2. Click on request
3. See error message modal
4. See error in the log

#### Expected Behavior

Be able to request the screenshot

#### Screenshots

Screenshot of the error modal:
![image](https://user-images.githubusercontent.com/37518107/123550411-53913680-d73b-11eb-9e90-b55f243b3662.png)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** All
- **Device:** Laptop, Samsung Galaxy Note10, iPad
- **OS:** Windows 10, Android 11, iOS 12.5.3
- **Browser:** Chrome

#### Additional Context

N/A

**Comment by TheCatLady** [comment]
Sonarr is currently a requirement for the TVDB matching feature.
