### ISSUE TITLE
Login Loop On Mobile Device

### ISSUE THREAD

**Issue by sirk123au** [sct/overseerr#1848]
#### Description
Android or IOS trying to login from any web browser just shows status ring
#### Version
11378549c64c364ba3f0a4effbf4eb16ecd43f51

#### Steps to Reproduce

repeatable with mobile devices only

#### Expected Behavior

Plex login dialog popup

#### Screenshots

https://user-images.githubusercontent.com/6962647/123563312-60736000-d7f7-11eb-87ff-2f07f1f3286b.mp4

#### Device

Chrome IOS Android
Galaxy s20 iPhone

**Comment by sct** [comment]
This is happening on Android because you have the PWA installed. Try using the PWA instead.

Are you sure you can reproduce this on iOS?

**Comment by sirk123au** [comment]
Yes it did the same thing on an iPhone. What is PWA?

**Comment by sirk123au** [comment]
Sorry found what PWA meant and i used it and fixed it. it may be the same on the iPhone too. Thanks for your help

**Comment by sirk123au** [comment]
I found if the plex app is not installed it does not redirect to the login screen.
