### ISSUE TITLE
"Fail if not available" or "Allow any quality above X" options.

### ISSUE THREAD

**Issue by zwimer** [sct/overseerr#1849]
#### Description

Currently if I select a movie in overseerr, my default quality is 4k. When I submit the request, overseerr will either download the movie or set radarr to wait to download the movie when it is available. For some movies that are not out yet this is wonderful. But for some movies, say movies made before 2010, they likely will not have 4k versions so overseerr will create an unfulfillable request that the user will only ever see as "processing". To that end I propose two possible solutions.

#### Desired Behavior

Option 1: Fail if not available
This option is pretty self explanatory. It will fail the request if a movie cannot start downloading immediately. That way I could try: '4k Airplane 1980', and it would fail instantly. Then I could try '1080 Airplane 1980' and it would succeed.

Option 2: 'Allow any quality above X' with a secondary check box 'Prefer quality Y'.
That way I could set my request for Airplane 1980 to be 'Any quality above 720p' and 'Prefer qualities closer to 4k', i.e. higher qualities.

#### Additional Context

The other benefit is this means the admin does not need to routinely inspect requests for these unfufill-able requests, clear them out, check which qualities are available, then recreate the requests on the behalf of the people who made the cancelled ones.

**Comment by TheCatLady** [comment]
You can configure your *arrs to do this.  Overseerr only sends the requests to the *arrs, and it is up to the *arrs to fulfill the requests.
