### ISSUE TITLE
Users with no shared libraries do not import.

### ISSUE THREAD

**Issue by gonecrazy25** [sct/overseerr#1856]
#### Description

I have 2 users on my plex server that I have no shared libraries with.  When I do Import Users from Plex, it imports all the users that I have shared libraries with but not the 2 that have no shared libraries with them.

**Comment by danshilm** [comment]
This seems to be by design; users not present on the owner's Plex account's friends (or shared - not sure of the proper term here) list are not added and can't access Overseerr.

**Comment by sct** [comment]
This is by design.
