### ISSUE TITLE
Cannot save Discord Notification configuration when only Media Requested Notification Type selected.

### ISSUE THREAD

**Issue by emorgoch** [sct/overseerr#1866]
#### Description

With the Discord Notifications, you cannot save the configuration when the only selected Notification Type is "Media Requested". If you select only that option, Overseerr reports an error of "You must select at least one notification type".

#### Version

1.25.0

#### Steps to Reproduce

1. Setup Discord Notifications, setting the WebHook URL and checking "Enable Agent"
2. For "Notification Types", select only "Media Requested"

#### Expected Behavior

You should be able to save this configuration.

#### Screenshots

![image](https://user-images.githubusercontent.com/23462100/124410583-ce001e80-dd18-11eb-9931-b6a0509035cc.png)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Desktop
- **Device:** Custom PC
- **OS:** Windows 10 21H1
- **Browser:** Chrome [Version 91.0.4472.124 (Official Build) (64-bit)]

**Comment by danshilm** [comment]
Not stale
