### ISSUE TITLE
Options for E2E encrypted notifications (e.g., Signal)

### ISSUE THREAD

**Issue by aniqueta** [sct/overseerr#1880]
#### Description

Overseerr has a lot of nice options for notifications, but aside from email with PGP, which is not intuitive to setup for the average user making requests, none are end-to-end encrypted. It would be nice to have an E2E encrypted push notification option. 

#### Desired Behavior

I think there may be a couple options that could provide E2E encrypted notifications and slot into how notifications work already. This would involve collecting messaging identifiers for each user, like done with Telegram or Discord.

Potential options: 
1) Collect Signal phone numbers for each user and send messages through [signal-cli](https://github.com/AsamK/signal-cli)
2) Collect [Simple Push](https://simplepush.io) keys and send messages trough curl

Given that Signal user base is increasing and that it doesn't come at a cost like Simple Push does, I think the first option would be ideal. 

#### Additional Context

I think it could be possible for admins to kludge something together using a [web hook server](https://github.com/adnanh/webhook) that triggers either option above using the existing web hook functionality, but a built in option would be cleaner. :)

**Comment by aniqueta** [comment]
Bump to remove stale

**Comment by aniqueta** [comment]
Just wanted to note that [Simplepush](https://simplepush.io/features) has launched with E2E encryption notifications. So perhaps this could be reconsidered for priority? Thank you.

**Comment by aniqueta** [comment]
Bump to remove stale. But also wondering from the team, if I used the Pushover and Pushbullet implementations as a template to see if I can add Simplepush functionality, would a PR on that be welcomed? Thanks.

**Comment by TheCatLady** [comment]
> But also wondering from the team, if I used the Pushover and Pushbullet implementations as a template to see if I can add Simplepush functionality, would a PR on that be welcomed? Thanks.

Pushbullet is likely the better "template" to use, since it doesn't seem like Simplepush supports any message formatting.  A database migration would also be needed to add the required settings to the `UserSettings` table, though.

That said, I'm not sure if we want to maintain Simplepush support, given lack of interest (only one upvote since this issue was opened 7 months ago) _and_ the limitations of the Simplepush API:
> Freemium users are limited to 100 notifications per month. After those 100 free notifications all following notifications will be dropped.
> 
> Currently iOS users won't be able to receive notifications that were sent while their device was turned off.

Adding new notification agents is not a "once and done" type of deal; we also need to update/maintain that code as we continue to develop Overseerr.  As such, there needs to be sufficient demand/justification, and we just haven't seen that yet.

This is why Overseerr has webhook notification support; you can technically use any notification agent via webhooks.

**Comment by aniqueta** [comment]
Very good points, and indeed does seem I'm an outlier in wanting E2EE notifications (or others haven't thought about how notifications aren't E2EE). 

I was also thinking about webhooks per the original post here. I stopped exploring that since, right now it's only available to the admin, and users wouldn't be able to configure it for their own web hook notifications (or the admin can't configure it for them). The use case I have in mind is E2EE notifications for friends and family when their requests are filled.

**Comment by TheCatLady** [comment]
> I was also thinking about webhooks per the original post here. I stopped exploring that since, right now it's only available to the admin, and users wouldn't be able to configure it for their own web hook notifications (or the admin can't configure it for them). The use case I have in mind is E2EE notifications for friends and family when their requests are filled.

The idea behind the webhook agent is that you would build the logic yourself to send notifications to the desired recipients. But you are correct that the Overseerr UI would not provide any way for users to customize this notification logic; you would need to account for that in some other way external to Overseerr.

**Comment by aniqueta** [comment]
I've had this on my to-do to experiment, so hope it doesn't get marked stale. Thanks.
