### ISSUE TITLE
Add translation Norwegian

### ISSUE THREAD

**Issue by GoByeBye** [sct/overseerr#1902]
#### Description
Title says it all add translation for Norwegian

#### Additional Context

I'm willing to translate most if not all in my spare time 

Edit: Spelling mistake

**Comment by Torkiliuz** [comment]
https://hosted.weblate.org/projects/overseerr/

**Comment by TheCatLady** [comment]
`Norwegian Bokmål` is already on Weblate (thanks for pointing that out @Torkiliuz):
https://hosted.weblate.org/projects/overseerr/overseerr-frontend/nb_NO/

You can create an account on Weblate to contribute to the translation efforts.

Let us know if you need another language added to Weblate, but I'm closing this issue for now.

**Comment by GoByeBye** [comment]
Ah my bad, didn't see it on there yesterday. Thanks for pointing it out @Torkiliuz
