### ISSUE TITLE
Request/Available Flags

### ISSUE THREAD

**Issue by tbonerocketeer** [sct/overseerr#1903]
#### Description

The request/available flags are not changing once an item becomes available from a manually approve request, for both tv and movies from sonarr and radarr. Both items are available in plex but not reflected here. System is running in dockers on ubuntu. 

#### Version

1.25.0

#### Steps to Reproduce
![image](https://user-images.githubusercontent.com/13721723/125741412-6cc049e9-be3e-4135-b415-8802dfcb9317.png)

**Comment by danshilm** [comment]
It seems like there must be something going wrong somewhere when scanning Plex. 

Can you check the logs and the steps in the [FAQ item](https://docs.overseerr.dev/support/faq#some-media-is-missing-from-overseerr-that-i-know-is-in-plex)?
Would also be easier to troubleshoot if you join us over on [Discord](https://discord.com/overseerr).
