### ISSUE TITLE
Plex Scan Issue

### ISSUE THREAD

**Issue by bendini20** [sct/overseerr#1912]
#### Description

Manual library scan *for Movies* results in scan hanging/freezing on a movie

#### Version

1.25.0

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Go to Settings --> Plex --> Plex libraries.
2. Click on Movies toggle, then run manual library scan
3. Wait as the scan proceeds until it hangs at a certain number of movies.
4. Check Plex Scan Progress to see Updating Metadata stuck on one movie 

#### Expected Behavior

TV scans work fast and completely. Movie scans will get caught up on a movie for an unknown reason with the metadata, causing the scan to not proceed at all. To fix, you have to stop the scan, restart the Plex docker, then in overseerr start the manual scan. It will go past the movie if was previously got stuck on and then will get stuck on a new movie until you repeat the restarting process.

#### Screenshots

![image](https://user-images.githubusercontent.com/47575219/126078256-da2092b5-2dae-4355-a76a-0899dd907feb.png)

#### Device

Unraid OS Pro Version 6.9.2
Plex Docker: linuxserver/plex Version 1.23.4.4805

Plex server is connected to Overseerr via the Docker IP address (172.x.x.x/16) on the same docker network.

**Comment by samwiseg0** [comment]
I am very confused? This is plex not overseerr? Overseerr has nothing to do with a plex library scan.
