### ISSUE TITLE
Allow users to delete media files

### ISSUE THREAD

**Issue by Simoneu01** [sct/overseerr#1924]
#### Description

The disk space is not infinite but limited.
Since plex does not allow users to delete media but only the owner, it would be nice to give this possibility through overseerr.

#### Desired Behavior

Allow users to delete media files. 
Create a permission to do so.

**Comment by sct** [comment]
We may offer some tools in the future to help you _decide_ what should be deleted, but actually deleting the files will never be handled by Overseerr.

**Comment by Simoneu01** [comment]
Can I ask why? @sct

**Comment by Simoneu01** [comment]
> We may offer some tools in the future to help you decide what should be deleted

Or the possibility of the user to "Request cancellation?"

As for TV or movie requests, and then the server owner / admin can delete the media.

**Comment by dedworks** [comment]
As an extremely fond user of the project, that strikes me as a bad decision. 

You can't equate deleting from plex/disk with deleting from sonarr. 

Plex deletions can involve destruction of your data. Bad idea to step into that territory, agreed. 

Sonarr entries deal with what will be downloaded in the future. Is this not what overseerr is meant to manage?

What possible goal is there for deleting a request, if it won't stop your free space going to 0?
