### ISSUE TITLE
Anime only auto approve 

### ISSUE THREAD

**Issue by CubeComming** [sct/overseerr#1943]
#### Description

I'm always frustrated when Overseerr addes my Series to Sonarr.

#### Desired Behavior

I only want him to add Anime to Sonarr not "Normal" Series like Suits, etc....

#### Additional Context

Maybe it would be possible to add toggles to the Sonarr settings to diable auto approve for "normal" Series.

**Comment by mokahless** [comment]
I'd like to bump up and reactivate this enhancement request, as it is related to my need to auto-approve everything _except_ anime.

**Comment by absywabsy** [comment]
I'd also like to manually get anime because absolute number searching is a pain in the ass for sonarr to do.

So yes to:
If request = Anime > Do not automatic approve, otherwise, automatic approve
