### ISSUE TITLE
Mark a TVShow or Movie as 'Needs Attention'

### ISSUE THREAD

**Issue by sgiroux** [sct/overseerr#1956]
Description
I have movies and shows that are occasionally of bad quality, contain hardcoded subs, or other issues.  Overseerr could have a feature where a user can mark an item as 'Needs Attention' so the admin/owner can take the appropriate action (remove, re-download, etc).

Desired Behavior
Users are able to mark a TV Show or Movie as 'Needs Attention'.  A notification can then be sent to the admin/owner.

**Comment by sct** [comment]
#635 will solve this.
