### ISSUE TITLE
Add Chinese (simplified) 

### ISSUE THREAD

**Issue by WadeChenn** [sct/overseerr#1957]
#### Description

I've been working on translating to Chinese (simplified) and need the language added on Weblate to share my translations.

#### Desired Behavior

Chinese (simplified) added to allow translations on Weblate

#### Additional Context

N/A

**Comment by sct** [comment]
Added! https://hosted.weblate.org/projects/overseerr/overseerr-frontend/zh_Hans/

**Comment by WadeChenn** [comment]
The Chinese(simplified)  tanslate is done please add to the project .thks
