### ISSUE TITLE
Add per user Tag

### ISSUE THREAD

**Issue by dephcon** [sct/overseerr#1964]
#### Description

I'd like requests to add a tag for the requesting user into *arr, so I can easily filter by that user's tag in *arr.  If I remove a user or I have a user that adds a ton of trash I'd like to specifically target their requests for removal.

#### Desired Behavior

In addition to any tags set in the settings for the *arr apps, I'd like an option in each users' setting to enable a username tag that is applied to any request they make in *arr.

**Comment by derekpurdy** [comment]
Great feature request, +1

**Comment by 2fst4u** [comment]
It would be good if it could add the tag as a label to the media in Plex too.

**Comment by Nindohana** [comment]
> 
> 
> It would be good if it could add the tag as a label to the media in Plex too.

that would be just wonderful.
So that we could hide from one library all the movies requested by a specific user.

**Comment by 2fst4u** [comment]
Bump

**Comment by AdmiralMichael** [comment]
I would love to see this feature for the exact reason OP described.

**Comment by AdmiralMichael** [comment]
+1 this would be an awesome feature. I use tags in Sonarr and Radarr for this reason, having them sync per se would be awesome.

**Comment by TheCatLady** [comment]
Sorry folks, this was discussed internally and isn't going to be implemented.

**Comment by 2fst4u** [comment]
> Sorry folks, this was discussed internally and isn't going to be implemented.

Any reason? Otherwise people will keep asking.

**Comment by dephcon** [comment]
> > Sorry folks, this was discussed internally and isn't going to be implemented.
> 
> Any reason? Otherwise people will keep asking.

yeah seriously, this seems trivial to implement.

**Comment by HStep20** [comment]
Came in to ask for this as well, since using tags to organize media into categories (like a 'removable' section similar to issues I recommended in #2822) would be super beneficial from an admin standpoint

**Comment by Rustymage** [comment]
I've started to see the benefit of this when my users are asking for lots of media and never viewing it.

**Comment by AdmiralMichael** [comment]
So here’s a use case for me. When I want to delete media from my Library I use sonarr/Radarr.

The ability to have overseer add a tag to entries based on what user requested it would be beneficial for filtering the media.  

Sometimes I may want to clear a lot of media that a specific user requested (or stopped sharing with that user and want to see and clear their media). Tags would definitely help in this scenario. 

Since there is already support for tags in other areas would it not be easier to add it here?

**Comment by sleepymatto** [comment]
Yeah I would like to add my vote to this as well. This seems like a great feature to add with plenty of use cases. Hopefully the dev team will come around

**Comment by ftc2** [comment]
i'd love this as well

**Comment by justkorix** [comment]
New year and this is something I'd very much love to have implemented. I have requested movies organized by radarr tags in Plex but that's currently all or nothing. I'd love to have collections for each user in Overseerr.

Please implement this!!!

**Comment by justkorix** [comment]
Would still see this as a huge value add for Overseerr. The whole point is automation of requests, having to manually tag each movie or tv show in their *arr is not a good experience

**Comment by Brandoskey** [comment]
This really needs reconsidered. Ombi recently made some big updates that are very reminiscent of what overseerr is doing. One change that Overseerr doesn't have was adding tags for users to radarr and sonarr.

This is a no brainer to me, the competing software has it, users want it, overseerr is already capable of tagging media in sonarr and radarr.

I'd hate to ask all my users to switch back to ombi, but knowing who requested what within radarr and sonarr is a huge quality of life improvement

**Comment by mattkbach** [comment]
100% agree. This really needs to be implemented

**Comment by dephcon** [comment]
Awesome to see this feature getting some traction!

**Comment by radian23** [comment]
This would absolutely be a helpful thing to have.  Being able to filter out people that have differing media needs would be a great addition.

**Comment by moimeme81** [comment]
Not implementing this even though it's probably one of the most requested feature, makes total sense and on top of it not give any reason more than "we just don't want to" sounds like the reasons I would give my mom not to clean my room as teenager ¯\_(ツ)_/¯

**Comment by nosut** [comment]
Just going to add my +1 to this idea. 
Not only would it make it much easier to sort it would also allow me to create notification rules within sonarr/radarr for specific people based on tags since overseerr doesnt really support things like discord multi channel.

**Comment by Brandoskey** [comment]
Piping in again, is there any chance if and when this does get implemented overseerr can add per user tags for already added requests?

**Comment by Grenwalls** [comment]
I just switched from ombi to overseer too, but honestly considering switching back only because of the lack of user tag support. 
Really disappointed to see this, because I love it otherwise.

**Comment by Bokaii** [comment]
+1 for me. This would be useful for several reasons:
- In Plex(using tags with Plex Meta Manager): automatically creating collections per users (some people only want to see their own stuff)
- In radarr/sonarr: to follow up/filter/delete per user

And also, if this is not something everyone wants, why not my it a toggle?
