### ISSUE TITLE
TV Show / Overview

### ISSUE THREAD

**Issue by cm86** [sct/overseerr#1970]
#### Description

It would be nice to have an overview of the TV shows.
So that you can see which series you already have in your media library.
Currently, can only see what seasons are available.
But not which episodes in the individual seasons.
Sometimes it happens that just one series is missing. So that you don't have to use other tools here, a brief overview can be found here

#### Desired Behavior

Search for a TV-Show (Maybe one that is already in the library), look wich season is available, request just the one episode wich is missing.

#### Additional Context
Just a screenshot of a show and the "request more" menu....
![grafik](https://user-images.githubusercontent.com/14919688/128625811-ef2becc3-8079-4c4c-8de4-259d2a32ed0d.png)

**Comment by danshilm** [comment]
Once we have the ability to request individual episodes, this kind of issue will be a lot easier to deal with.
Refer to issue #342 for being able to request individual episodes.

**Comment by danshilm** [comment]
This is a bit confusing actually.

@cm86 when you talk about 'series' in: "so that you can see which series you already have in your media library" and "sometimes it happens that just one series is missing", are you referring to a TV Show there? I think that perhaps you meant that you might have an incomplete season and you need to use Sonarr to find out which episode is missing from that season. Would that be accurate?

**Comment by cm86** [comment]
Hi there, I mean I have a tv show (Friends) Here we have 10 seasons, and in season 9 and 10 I'm missing a series each ... Here as an example pictures from ombi ...
![Screenshot_20210914-190250_Chrome.jpg](https://user-images.githubusercontent.com/14919688/133302570-4d059ef1-4852-46ad-9fea-928a454e003c.jpg)

![Screenshot_20210914-190321_Chrome.jpg](https://user-images.githubusercontent.com/14919688/133302615-22f9d881-1059-407f-af79-0341a80b72a1.jpg)

if not desired, please delete...

Mfg
Chris

**Comment by danshilm** [comment]
Gotcha. We already have an issue for this feature request, so I'll close this issue in favour of the issue #342.
Please follow that issue for updates on this.
