### ISSUE TITLE
Request no longer available and images missing (corrected)

### ISSUE THREAD

**Issue by derekcentrico** [sct/overseerr#1971]
#### Description

Firstly, none of this template texted showed on my mobile device when creating my first report.  

Upon opening for a first instance, Overseerr the user is greeted with blank cards in the request section which state:  "The associated title for this request is no longer available."  Additionally, all cards for new/trending/suggestions show up blank on this first instance of loading the website.  

First instance means during a browsing session.  

Refreshing permits the content to load and for incorrect error messages about availability to self-correct.

#### Version

1.25.0

#### Steps to Reproduce

1. Open up web app
2. See the problem.
3. Refresh to make it go away

#### Expected Behavior

All cards to load properly on the first instance.

#### Screenshots

![Screenshot 2021-08-08 8 35 43 AM](https://user-images.githubusercontent.com/1930094/128632272-80db0cd3-f6af-4072-b064-1d59763ae4b9.png)
![Screenshot 2021-08-08 8 36 49 AM](https://user-images.githubusercontent.com/1930094/128632271-3290a7fe-059a-4a28-a33f-bdeb169dfa57.png)

#### Device

I was simply loading the web app to check on content.

- **Platform:** [e.g., desktop, smartphone, tablet]   affected on desktop, chromebook, iPad, and Pixel 5
- **Device:** [e.g., iPhone X, Surface Pro, Samsung Galaxy Tab]  custom PC, Pixelbook, iPad Pro 2019, Pixel 5
- **OS:** [e.g., iOS 8.1, Windows 10, Android 11]  Windows 10 / Ubuntu 20.04, ChromeOS 91, iPad OS 14.7, Android 11
- **Browser:** [e.g., Chrome, Safari, Edge, Firefox]  Chrome, Firefox

#### Additional Context

Please provide any additional information that may be relevant or helpful.

**Comment by samwiseg0** [comment]
Please provide your browser console logs and network logs. It seems like you have an issue with your container network/docker. I do not believe this is an overseerr issue. 

Also are you using a reverse proxy?

**Comment by derekcentrico** [comment]
Ah, valid point.  Yes using reverse proxy and routing WAN data through VPN.  I'll check the logs next time it errs.

Only Overseerr logs are a bunch of errors when scanning

{
 "errorMessage": "getaddrinfo ENOTFOUND 192-168-1-49.592debcd3f1d42dfb07fb437f3886c7f.plex.direct",
 "title": "Do the Right-est Thing"
}

**Comment by derekcentrico** [comment]
Wow this happened again quite fast.  Unexpected.

:9070/api/v1/discover/genreslider/movie:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:9070/api/v1/discover/genreslider/tv:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by samwiseg0** [comment]
> Ah, valid point. Yes using reverse proxy and routing WAN data through VPN. I'll check the logs next time it errs.
> 
> Only Overseerr logs are a bunch of errors when scanning
> 
> {
> "errorMessage": "getaddrinfo ENOTFOUND 192-168-1-49.592debcd3f1d42dfb07fb437f3886c7f.plex.direct",
> "title": "Do the Right-est Thing"
> }

This indicates that there is an issue with your docker network. 

I will close this and if you need further assistance please use our Discord server for support.

Thanks
