### ISSUE TITLE
Prowl Integration

### ISSUE THREAD

**Issue by dpickard39** [sct/overseerr#1979]
#### Description

The notifications settings has a lot of options but it would be nice to have Prowl

#### Desired Behavior

I would like to request integration with the Prowl notification service.

#### Additional Context

None

**Comment by Qstick** [comment]
Hasn’t Prowl been dead as a project for 5+ years now? There are so many better alternatives

**Comment by dpickard39** [comment]
I am probably just old. It is still integrated into Radarr, Sonarr, Sabnzbd and Plex. The app still works. I signed up for Push bullet but there IOS app does not exist anymore.  I can look at the others. I just figured I would ask since I had it setup on all the others. I am open to recommendations.
________________________________

**Comment by dpickard39** [comment]
I am exploring more options now. I was off about Plex.
