### ISSUE TITLE
Hide content that a user can't request

### ISSUE THREAD

**Issue by AnysSido** [sct/overseerr#1988]
#### Description
Users can see content that they can't request. For example on my server most users cannot request tv shows, nor can they see the tv show library in plex, but in Overseerr they see lists of trending tv shows as well as tv shows recently added to the server.
The UI for these users is currently a mix of requestable and non-requestable items.

#### Desired Behavior
An option to only show items to a user that they can request. This would simplify the UI for users to a list of items that are either available or requestable, instead of items that are neither available nor requestable.

#### Additional Context
N/A

**Comment by danshilm** [comment]
Closing this in favour of #812. Follow that issue for updates.
