### ISSUE TITLE
Mark content as "Broken"

### ISSUE THREAD

**Issue by AnysSido** [sct/overseerr#1989]
#### Description

Every now and again a broken copy of a movie or tv show is downloaded via automation. It could be unable to play, might have dodgy audio, sometimes even the wrong movie.

#### Desired Behavior

An option for a user to select an item in Overseerr and mark it as "Broken" which would notify the admin.

#### Additional Context

Every so often family members will message me telling me a download is broken for one reason or another. It would be nice if they could do this via Overseerr instead.

**Comment by sct** [comment]
Duplicate of #635
