### ISSUE TITLE
Lidarr Support

### ISSUE THREAD

**Issue by brandon-dacrib** [sct/overseerr#1990]
#### Description
I love overseerr however I cannot use it to completely replace ombi without lidarr support. My understanding is that the lidarr api is very similar to the radarr and sonarr apis https://lidarr.audio/docs/api/

#### Desired Behavior
I would like to be able to use overseerr to search for movies, tv, and music. 

#### Additional Context
lidarr is a radarr/sonarr alike except for music. My understanding is that the api is very close. I think we should be able to enable it as an option and be able to search that content.

**Comment by danshilm** [comment]
Duplicate of #352. Follow that issue for updates.
