### ISSUE TITLE
Language filter not working correctly (stable 1.25.0)

### ISSUE THREAD

**Issue by erwintwr2** [sct/overseerr#1991]
#### Description

Enabling language filter (to english ), still results in movies/tv shows of other languages to show under Trending ,Popular Movies and Popular Series

#### Version

Stable v 1.25.0 (via docker)

#### Steps to Reproduce

Via Settings,Gerneal settings, Change discover language option from all languages to English, Apply.
Back from Main screen, select trending and check if media specifically from other languages is shown - for example , Shershaah from below is strictly a Hindi language film and should not be visible

#### Expected Behavior

Only content from my selected language to be available.

#### Screenshots

![image](https://user-images.githubusercontent.com/1496359/129477770-71c155b9-a4cc-46c3-994d-581d98fcc353.png)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** desktop

- **OS:** Windows 10
- **Browser:** Chrome

#### Additional Context

None

**Comment by samwiseg0** [comment]
Did you try and clear your browser cache after changing the language?

**Comment by sct** [comment]
Trending does not support language filtering. This is a limitation on TMDb's side.

**Comment by lukepolo** [comment]
not sure what api your using but it seems it is supported?

https://developers.themoviedb.org/3/discover/movie-discover

![Capture](https://user-images.githubusercontent.com/2066668/129479861-70d3d7db-8f72-4764-a2ed-a7935b4c5917.PNG)

**Comment by erwintwr2** [comment]
> Did you try and clear your browser cache after changing the language?

Attempted a browser force refresh, and seems like Pouplar Movies and Series now is English only -> THX


> Trending does not support language filtering. This is a limitation on TMDb's side.

Seems to be the case  - ouch! :(

> not sure what api your using but it seems it is supported?
> 
> https://developers.themoviedb.org/3/discover/movie-discover
> 
more relevant option i guess is  :
with_original_language

challenge is probably secondary/translated languages. will still prefer to have an option to view original language  items only
