### ISSUE TITLE
Introduce support for Polish language

### ISSUE THREAD

**Issue by azulu** [sct/overseerr#1994]
#### Description

I would like _Overseerr_ to be available in Polish.

#### Desired Behavior

Currently, Polish version does not exist and there are no plans for translation on Weblate. I am willing to start this process and help with some translations. I would like Polish to be added in Weblate to allow community translations for the project.

#### Additional Context

N/A

**Comment by sct** [comment]
Added to Weblate: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/pl/

If you have any questions please reach out in our Discord! We can also give you the translator role there. Just let us know who you are.

Thanks for wanting to help!
