### ISSUE TITLE
REQUEST: Recently added newsletter

### ISSUE THREAD

**Issue by BobOkisama** [sct/overseerr#2008]
This is looking great so far!

Before I can move over from ombi one of the largest things I see missing is the ability to create and send out a newsletter for recently added materials on an automated schedule.

A couple other things missing I would love to see:
1. A notes field in the user's profiles
2.  Lidarr support
3.  Readarr support
4.  Login splash page with server status and ability to leave a message to users
5.  Server watch and notifications (if my server goes down or there is an update available)
6. Reporting system. Allow users to leave a ticket in to report an error with a movie or tv episode.

I know this is beta, but it really is looking great, hope to see it grow quickly!

**Comment by samwiseg0** [comment]
@BobOkisama Your request can be accomplished with Tautulli(https://github.com/Tautulli/Tautulli). Our goal is to no duplicate efforts that other projects already do really well. 

It would be best to track your list separately. Please subscribe to the issues you already mentioned for updates. 

1) Please file a new enhancement and use the template provided. 
2) https://github.com/sct/overseerr/issues/352
3) https://github.com/sct/overseerr/issues/605
4) https://github.com/sct/overseerr/issues/619
5) This can be accomplished with Tautulli(https://github.com/Tautulli/Tautulli)
6) https://github.com/sct/overseerr/issues/635
