### ISSUE TITLE
API query params should use `+` not `%20` for spaces

### ISSUE THREAD

**Issue by kiranshila** [sct/overseerr#2010]
#### Description

Currently, hitting the API with a properly encoded query parameter will return a 400 when spaces are encoded as `+`. This is not only valid encoding, but the [preferred](https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4) encoding as per the current HTTP spec. The official Java [URLEncoder](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URLEncoder.html), for which I am using to build out a program that interacts with the API, follows this spec for `application/x-www-form-urlencoded` and only encodes spaces as `+`.

#### Version

Commit: 4f654b98c31c33cafc50785d0c0a7fb4a7dbe859

#### Steps to Reproduce

Hit the api with something like `http://localhost:5055/api/v1/search?query=Matrix+Reloaded`

#### Expected Behavior

I expect to get search results and not an error

**Comment by sct** [comment]
What you are seeing is two different RFC's fighting over a similar resource. [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) which describes that a `+` is a reserved character for URI's and [RFC1738](https://www.ietf.org/rfc/rfc1738.txt) which says you should use a `+`. Our validator follows RFC3986, thus there error you are getting back is saying the `+` is a reserved character:

```json
{
  message: "Parameter 'query' must be url encoded. Its value may not contain reserved characters.",
  errors: [
    {
    path: ".query.query",
    message: "Parameter 'query' must be url encoded. Its value may not contain reserved characters."
    }
  ]
}
```

I need to assess the side effects of allowing reserved characters on our search endpoint. Until then, you can do a replace on the string (`+` -> `%20`) before sending it to us. That will at least resolve the issue for now.

**Comment by djeis97** [comment]
Wouldn't URLs be more correct here than URIs though? i.e. shouldn't RFC1738 take precedence for a web API over RFC3986?

**Comment by kiranshila** [comment]
That would imply also that the error message is incorrect. RFC1738 is indeed URL encoding, that error should note incorrect URI encoding.

**Comment by sct** [comment]
The error message comes from https://github.com/cdimascio/express-openapi-validator which we use for our API validation. There is a similar discussion about this in their issues: https://github.com/cdimascio/express-openapi-validator/issues/241

I can allow reserved characters on the search endpoint, but I would like to make sure it doesn't cause any issues in doing so.

**Comment by kiranshila** [comment]
Interesting. Reading the argument from the tagged issue from axios, this seems like a huge can of worms. It seems as though while the w3c recommends spaces to be encoded as per 1738, many applications ignore their recommendation for the sake of compatibility.

The funny part though is that `+` is completely valid, even per 3986. It's apart of the sub-delims grammar, which is exactly the use case of query params. That's why `+` is reserved, it's reserved for query params.

**Comment by sct** [comment]
> Interesting. Reading the argument from the tagged issue from axios, this seems like a huge can of worms. It seems as though while the w3c recommends spaces to be encoded as per 1738, many applications ignore their recommendation for the sake of compatibility.
> 
> The funny part though is that `+` is completely valid, even per 3986. It's apart of the sub-delims grammar, which is exactly the use case of query params. That's why `+` is reserved, it's reserved for query params.

Yep. Since %20 is backwards compatible it seems to be the go-to.

If this was only the space it would be easy to just turn it on, but the validator either allows all reserved characters or none which is why I am a bit hesitant.

**Comment by kiranshila** [comment]
> If this was only the space it would be easy to just turn it on, but the validator either allows all reserved characters or none which is why I am a bit hesitant.

Totally understand. I keep reading and it just keeps getting worse, https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20

I hate the web sometimes haha. I'm perfectly content doing the str/replace on my end by the way, I thought this was something way simpler, but obviously isn't. We can close this issue if you decide to not mess with the validator.

**Comment by sct** [comment]
> > If this was only the space it would be easy to just turn it on, but the validator either allows all reserved characters or none which is why I am a bit hesitant.
> 
> Totally understand. I keep reading and it just keeps getting worse, https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20
> 
> I hate the web sometimes haha. I'm perfectly content doing the str/replace on my end by the way, I thought this was something way simpler, but obviously isn't. We can close this issue if you decide to not mess with the validator.

It might be some time before I can take a look at this so that would probably be best for now :) Ill reference this issue if we make a change.
