### ISSUE TITLE
Add "Notify me when approved/completed" to requests made by others

### ISSUE THREAD

**Issue by Jabster28** [sct/overseerr#2031]
#### Description

If you want a movie, and someone's already, overseerr just says "requested"

#### Desired Behaviour

It would be nice if there was a button that would send you notifications along with the requester when it's approved and/or available

#### Additional Context

What it looks like now:
![IMG_20210828_162000_079.jpg](https://user-images.githubusercontent.com/29015942/131222723-a8eafb15-90b7-4daf-befc-386357b66b73.jpg)

Simple source change of what it could look like:
![IMG_20210828_161958_103.jpg](https://user-images.githubusercontent.com/29015942/131222735-37911cce-1303-428a-be5a-1e8c57ff74dd.jpg)

Or maybe it'd be a toggle per season, like the first column.

**Comment by samwiseg0** [comment]
Duplicate of https://github.com/sct/overseerr/issues/789

**Comment by Jabster28** [comment]
oh, didn't see that sorry 😅
