### ISSUE TITLE
Add support for Czech as a display language

### ISSUE THREAD

**Issue by OnlyC0RE** [sct/overseerr#2055]
Please add Czech language to Weblate

**Comment by OnlyC0RE** [comment]
Hey, I was just wondering about a status of this request. Or is this something for later stages of development?

**Comment by TheCatLady** [comment]
> Hey, I was just wondering about a status of this request. Or is this something for later stages of development?

Sorry to keep you waiting, but please just be patient.  @sct is the only one who can make the required change in Weblate, and he's been really busy.  Any updates will be reflected here in this issue.

**Comment by sct** [comment]
Added to Weblate: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/cs/

Let us know if you have any questions in Discord!
