### ISSUE TITLE
On-behalf feature

### ISSUE THREAD

**Issue by thu3n** [sct/overseerr#2080]
#### Description

It would be awsome to create a request on-behhalf of a user. So the users gets notifications about their request

#### Desired Behavior

A extra button that asks if i would request on-behalf, and then it would have all my users in a scroll menu. After selecting the user, it would send a notification to  the user when the desired movie or series are available 

#### Additional Context

-

**Comment by thu3n** [comment]
Nevermind, saw that this have been requested and are on the roadmap

**Comment by sct** [comment]
@thu3n This is already a feature though? You can do this today in the request modal.
