### ISSUE TITLE
Ability to choose the default login type

### ISSUE THREAD

**Issue by chibomorto** [sct/overseerr#2089]
#### Description

Is it possible to add a “remember me” option to local accounts login?
Is it possible to allow admin todecide which login menu would be the default (local user ou plex user).

#### Desired Behavior

I believe It would also be more user-friendly if the default login menu would be for local accounts, or if the admin could decide which login menu would be the default (local user ou plex user).

**Comment by danshilm** [comment]
When you say a "remember me" option, would that mean that only the username/email of the user who was logged in previously would already be filled on the login page?

**Comment by benhoIIand** [comment]
>I believe It would also be more user-friendly if the default login menu would be for local accounts, or if the admin could decide which login menu would be the default (local user or plex user)

This would be really useful. With a blend of Plex and local users, I find the local users constantly click on the big orange button rather than the more discrete "local user" login.

In its simplest form, giving both the buttons the same hierarchy would help users.

**Comment by amadotejada** [comment]
This would be great! This PR also seems to be related and a deff welcome change 🙏🏽

**Comment by mcmasterp** [comment]
It's a shame this was never implemented. My users find it hard to even notice option for local login. It's the currently the only friction point for users

**Comment by opentree27** [comment]
> It's a shame this was never implemented. My users find it hard to even notice option for local login. It's the currently the only friction point for users

Agreed. It is so simple to implement as well.

**Comment by mcmasterp** [comment]
I wish it was for me I'd gladly do the coding if I had the skill. This project is the "killer app" of this media app stack
