### ISSUE TITLE
Overseerr pulling wrong image/name for series

### ISSUE THREAD

**Issue by uofirob** [sct/overseerr#2091]
#### Description
I just installed Overseerr and connected it to Sonarr and Radarr. Overseerr is adding a series called "くの一牡丹 (2019)" in my "Recently Added" tab with an extremely inappropriate image.  When I click "Play on Plex" it loads a series called "Trapped in A Closet".  

#### Version

1.25.0

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Log In
2. Look at "Recently Added"
3. See inappropriate image
4. ... Profit?

I've tried removing metadata, but since it exists in my system, it gets re-added. I checked and have no such series name on my server.

I should be able to remove a record from "recently added" or at least update the metadata to correct the mistake.

#### Expected Behavior

Overserr should use the correct image/metadata for the item or at least allow the user to remove it from the Recently Added list or modify the metadata.  It displays correctly in Plex.

#### Screenshots
(I covered up the inappropriate parts of the image with an orange box)
![image](https://user-images.githubusercontent.com/1754842/133318471-2fb418a7-db16-4ddd-bc8f-764273984003.png)
![image](https://user-images.githubusercontent.com/1754842/133318688-efc09556-181c-4491-bec8-21499e12b8ef.png)
![image](https://user-images.githubusercontent.com/1754842/133318813-f8d7957d-8eae-4e55-9b1d-2e268f3ce23b.png)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- Desktop [e.g., desktop, smartphone, tablet]
- PC
- Windows 10
- Chrome

**Comment by danshilm** [comment]
Come over to our Discord please, we need some more information, but this doesn't look like a bug. Just some missing/incorrect metadata.
