### ISSUE TITLE
Tautulli Integration with Overseerr

### ISSUE THREAD

**Issue by hansenc0705** [sct/overseerr#2103]
#### Description

Watch statistics for media and users from Tautulli would be very beneficial when it comes to managing media within Overseerr.

#### Desired Behavior

A link to the Tautulli page for the media/user or showing statistics from Tautulli directly in Overseerr.

#### Additional Context

The goal of the integration would be to help understand what media is getting watched and what media users are requesting vs. what they are actually watching.

**Comment by arjanterheegde** [comment]
Is het mogelijk om een pagina in het menu toe te voegen zodat gebruikers kunnen zien wat er momenteel wordt bekeken door gebruikers binnen Plex? Een integratie met tautulli daarvoor zou geweldig zijn.

**Comment by arjanterheegde** [comment]
Is it possible to add a page in the menu so that users can see what is currently being watched by users within Plex? An integration with Tautulli for that would be fantastic.
