### ISSUE TITLE
Telegram Notifications always fail

### ISSUE THREAD

**Issue by jacauc** [sct/overseerr#2123]
#### Description

Telegram Notifications always fail, even with correct chat ID exactly as per instructions. I had this set up in 1.25 and it worked, since the upgrade to 1.26 it stopped working.

#### Version

What version of Overseerr are you running? 1.26.1

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Set up telegram notifications as per instructions.
2. Test telegram - Fails

#### Expected Behavior

Message sent to Telegram

#### Screenshots

If applicable, please provide screenshots depicting the problem.

#### Device

Chrome

#### Additional Context

Log file output:
{
 "type": "TEST_NOTIFICATION",
 "subject": "Test Notification",
 "errorMessage": "Request failed with status code 400",
 "response": {
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: chat not found"
 }
}

**Comment by TheCatLady** [comment]
`Bad Request: chat not found` suggests that there's an issue with the provided chat ID.

If you need further support, please ask in our Discord server.
