### ISSUE TITLE
Telegram Notification Bug

### ISSUE THREAD

**Issue by jacauc** [sct/overseerr#2124]
Description
Telegram Notifications always fail, even with correct chat ID exactly as per instructions. I had this set up in 1.25 and it worked, since the upgrade to 1.26 it stopped working.

This is not a support request. It is a bug.

Version
What version of Overseerr are you running? 1.26.1

Steps to Reproduce
Please tell us how we can reproduce the undesired behavior.

Set up telegram notifications as per instructions.
Test telegram - Fails
Expected Behavior
Message sent to Telegram

Screenshots
If applicable, please provide screenshots depicting the problem.

Device
Chrome

Additional Context
Log file output:
{
"type": "TEST_NOTIFICATION",
"subject": "Test Notification",
"errorMessage": "Request failed with status code 400",
"response": {
"ok": false,
"error_code": 400,
"description": "Bad Request: chat not found"
}
}

**Comment by TheCatLady** [comment]
There were no changes to the Telegram agent in 1.26, and the error message suggests that your Telegram agent configuration is incorrect.

Again, please reach out on Discord if you need further support with this issue.
