### ISSUE TITLE
Request: Add "Trending Actors" row to the show discovery homepage

### ISSUE THREAD

**Issue by millercentral** [sct/overseerr#2152]
#### Description

It would be nice to be able to see trending/popular actors on the home page, and when selecting one display the movies/shows they are in (same as when selecting actors displayed in details pages).

#### Desired Behavior

On the Discovery homepage, have a row labeled "Popular Actors" or "Trending Actors" with a list of trending actor cards in it. Selecting an actor card would show that actors appearences.

#### Additional Context

I've seen another new requesting app do this and thought it was a nice feature. Not sure where to source "trending" actor lists, but hopefully that data is available somewhere.

**Comment by TheCatLady** [comment]
So, people can already trend and will appear in the "Trending" slider.

However, it is totally possible to add a `Popular People` slider to the Discover page as well using [this TMDb API endpoint](https://developers.themoviedb.org/3/people/get-popular-people).

**Comment by millercentral** [comment]
Interesting, I've never seen a person appear in trending, but "Popular People" slider is what I was trying to describe. Thanks for considering.
