### ISSUE TITLE
Gotify Notifications

### ISSUE THREAD

**Issue by hackmoore** [sct/overseerr#2183]
#### Description

Could we have gotify added as a notification provider, this was previously somewhat requested on [reddit](https://www.reddit.com/r/PleX/comments/kcp703/comment/gfsu7re/?utm_source=share&utm_medium=web2x&context=3) thread

#### Desired Behavior

Would like the ability to add a gotify server and key to allow overseerr to push notifications using that.

#### Additional Context

N/A

**Comment by schambers** [comment]
I looked over the other notifications and this looks fairly straight forward. Could I take this one? I could spend time on it this weekend. 

Thanks!
