### ISSUE TITLE
Request more button for shows not working as intended.

### ISSUE THREAD

**Issue by OwsleyJr** [sct/overseerr#220]
**Describe the bug**
When you click the request more button, there is heavy slow down on the pop up. It will take a long time to open and sometimes will close itself automatically.
**To Reproduce**

1. Go to requests and then click on show.
2. Click on request more
3. See error

**Screenshots**

![Screenshot 2020-12-09 125706](https://user-images.githubusercontent.com/8635678/101669013-53d81780-3a1f-11eb-8650-4dcae22f38fc.png)

**Comment by sct** [comment]
I am unable to reproduce this issue on Windows or Mac in any browser.

However, I am doing a rewrite of the way we show these modals anyways which should prevent strange behavior like this in the future.
