### ISSUE TITLE
recommendations based on prior user requests / "you might also like" on start page

### ISSUE THREAD

**Issue by h3rb1n4t0r** [sct/overseerr#2215]
### Description

a user has brought to the attention that when wanting to browse for new stuff similar to requested media, one has to open up media requested in prior

### Desired Behavior

below/above the sections "recently added", "trends", "popular" and upcoming" there should be a section displaying recommendations to the user according its respective prior media requests

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Unfortunately, there's no good way to do this currently.  The recommendations are from TMDb's **Get Recommendations** movies/series endpoints, which only support a single movie/series ID.
