### ISSUE TITLE
notification for request not handled within x

### ISSUE THREAD

**Issue by h3rb1n4t0r** [sct/overseerr#2217]
### Description

overseerr does only show the option to have a notification message on media requests or completion and therefore does not update me whether the automated processing works explicitely

### Desired Behavior

overseerr should notify me of requests which were not handled within a user-specified time frame, e.g. 24h so I can intervene when automated processing does not work

### Additional Context

refer to idea #2131

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Rustymage** [comment]
I just popped in to raise a question on this exact issue.

It'd be useful for the admin to manually intervene if automatic processing fails for any reason. A quick notification would be useful.
