### ISSUE TITLE
Feature Request: add Anime as genre to Movies and Series

### ISSUE THREAD

**Issue by SkalCore** [sct/overseerr#2256]
### Description

filter by anime not possible

### Desired Behavior

it would be nice to be able to select anime as a genre for movies and series. The animation genre tends to look for children's content but not anime. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Genres are not defined by Overseerr, but by TMDb.
