### ISSUE TITLE
Searching with/without accented greek characters does not find the same results.

### ISSUE THREAD

**Issue by Senjar** [sct/overseerr#2257]
### Description

Searching: Αμελί
Brings up: Amelie (2001)

Searching: Αμελι
Brings up: *No Results*

Searching should be more flexible like other languages (like French) and should ignore accented characters.
Vietnamese: **Cuộc Đời Của Amelie Poulain**
and: **Cuoc Doi Cua Amelie Poulain**
show the same results

### Version

1.27.0

### Steps to Reproduce

1. Search a movie using it's Greek name without using accented characters
2. No results found

### Platform

desktop

### Device

PC

### Operating System

Windows

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Looking into this, this unfortunately seems to be a limitation of searching using TMDb; using the examples you provided above yield the same results as you provided when searching on TMDb directly, so I'm afraid we can't do anything about this. We also don't manipulate the query that's made to TMDb when searching for media on Overseerr.
