### ISSUE TITLE
Allow Users to "Request" Notifications for Media Already Requested

### ISSUE THREAD

**Issue by Nealon01** [sct/overseerr#2262]
### Description

When one user requests a show/movie, it get's marked as "Requested", and no one else can request it.  This isn't really an issue, except that if users wanted to receive an email notification when the show/movie was added, they can no longer get that.

### Desired Behavior

Could there be a way for users to "watch" an existing request, or even allow multiple users to request the same item?

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #789
