### ISSUE TITLE
Email Notifications via Amazon SES do not work

### ISSUE THREAD

**Issue by donslice** [sct/overseerr#2266]
### Description

Email Notifications using Amazon SES do not work.. Overseerr reports Success, but email does not go through.

### Version

1.27.0

### Steps to Reproduce

1. Settings > Notification > Email
2. Fill in SES information
3. Click "Test"
4.

### Screenshots

![image](https://user-images.githubusercontent.com/460311/140562329-d9bfb89c-eb5c-4047-9944-4473b268d4bc.png)

### Logs

```shell
2021-11-05T18:41:04.068Z [debug][Notifications]: Sending email notification {"recipient":"donslice","type":"TEST_NOTIFICATION","subject":"Test Notification"}
```

### Platform

desktop

### Device

Windows Laptop

### Operating System

Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
If overseerr is successfully sending the email then the issue is at your provider. Please seek support from them or use #tech-chat in discord. I do not see how this is a bug in Overseerr.
