### ISSUE TITLE
Currently Streaming On data is incorrect

### ISSUE THREAD

**Issue by jeremysherriff** [sct/overseerr#2271]
### Description

Currently Streaming On shows incorrect information for me. This is likely a region-specific thing (I'm in New Zealand).

Overseer:
![image](https://user-images.githubusercontent.com/1082213/140875664-61bed233-5c06-4a06-9c65-c03570b6cb47.png)

Ombi:
![image](https://user-images.githubusercontent.com/1082213/140875694-8d977540-8016-462b-906c-2c1f357bc09c.png)

I have confirmed, and the series is indeed available on my local "Neon" streaming service.

### Version

1.27.0

### Steps to Reproduce

Search for "A Night Of"
Observe the Currently Streaming On data
Contrast with the same results in Ombi

### Platform

desktop

### Device

Not a UX issue

### Operating System

Windows 10

### Browser

Chrome v95

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
"Currently Streaming On" data is provided by TMDb / JustWatch.

It should return region-specific results if `Discover Region` is set to your region... but if the data is incorrect, there isn't much we can do.

**Comment by jeremysherriff** [comment]
I've altered the setting "Discovery Region" from All to New Zealand, and the streaming data is now correct:
![image](https://user-images.githubusercontent.com/1082213/140876533-fbbc9cbd-1696-46c0-85bd-822a2a0d2dab.png)

Can I suggest the Discovery Region is incorrectly labelled? Or perhaps is used for two purposes, and the label isn't clear?  I took Discovery Region to mean "the region for which movies and series are shown in the Discover page", whereas this appears to be a "Streaming Region" or something similar.

**Comment by TheCatLady** [comment]
> Can I suggest the Discovery Region is incorrectly labelled? Or perhaps is used for two purposes, and the label isn't clear? I took Discovery Region to mean "the region for which movies and series are shown in the Discover page", whereas this appears to be a "Streaming Region" or something similar.

I agree the label needs updating.  The setting was originally introduced as a way to restrict media items to those with releases in a specific region, but it has since become a more general region setting.
