### ISSUE TITLE
Auto Approve after set Duration

### ISSUE THREAD

**Issue by jimmy-ungerman** [sct/overseerr#2275]
### Description

With many users and requests coming in daily, I'd love to see a Auto Approve duration that will auto approve all requests made after a set duration if an Admin doesn't log in and explicitly deny them.

That way if someone requests a Movie or something while I'm on a flight, or just away from my phone or laptop, they aren't just waiting.

### Desired Behavior

Request gets made, timer starts, if I do not deny the request before the set "auto approve duration" the media is approved.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
I don't see the point of this, honestly. It seems a bit too niche. If you trust your users enough to have a feature like this, just give them auto-approve?
