### ISSUE TITLE
Request Filters

### ISSUE THREAD

**Issue by mfields05** [sct/overseerr#2280]
### Description

Would like the ability to filter request based on user, network, etc...

Only my fiance and myself get auto approved when requesting media, but would like to filter request based on users such as my brother/sister-in-law

### Desired Behavior

Would like the ability to filter request based on user, network, etc...

Only my fiance and myself get auto approved when requesting media, but would like to filter request based on users such as my brother/sister-in-law

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
What do you mean by "filter request based on users such as my brother/sister-in-law"?  Can't you just assign auto-approve perms to yourself and your fiance, and not grant auto-approve permissions to other users as desired?  I'm not really understanding your request here.

As for filtering based on network, there is already an existing feature request (#835).

**Comment by mfields05** [comment]
So my fiance and I already have auto-approve.

So if my brother in law request something, in the request section I would like if there was a filter that could be set by user, like there is for request status.

Basically a filter so I can see what needs to be approved based on non-auto approvers

**Comment by TheCatLady** [comment]
You can view a specific user's request by going to their profile and clicking the `Recent Requests` slider.  Or, by opening the user list and clicking their request count.  You can then filter based on the status using the dropdown at the top.
