### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by Moonlight63** [sct/overseerr#2287]
### Description

I don't know how feasible it would be, but I would like to see complete keyboard navigation implemented so that the entire interface can be used without ever touching the mouse.

### Desired Behavior

Mostly using arrow keys for navigation, similar to how you navigate inside of plex media player for example. Focus would start on the nav bar, up and down arrows would automatically switch the active page between Discover, Requests, etc. Right arrow from there would switch focus to the first title card. On the Discover page, if you are focused in a slider, then left and right arrow would select the next/prev card, up and down would switch to next/prev slider. If you are already at the top, then pressing up again moves you to the search bar. In a ListView, the arrow keys should focus the TitleCard in the next/prev row/column. etc etc. I don't see a need for this function to be added to management pages like users and settings.

### Additional Context

Having this level of navigation would make integrating into a tv centric control system far better, especially for family members that just want to add shows to watch, but don't really understand the software backend that is making it all possible. 

I am currently building an HTPC for family, and the setup is like this: Kodi running in libreelec, with embuary skin and plexkodiconnect. PMS, Sonarr, Raddar, Prowlarr, Overseerr, Transmission all running in docker on the same system. Embuary has support for adding custom menu items, so I have a menu item titled Request that opens chrome in kisok mode browsing to localhost:5055. Everything can be fully navigated with a simple remote, except overseerr you have to use the airmouse to interact. In this case I am just using plex because it offers better media management and specifically because overseerr requires it, but all of the media is staying local (but that doesn't really matter). So basically I am looking for ways to make this an overall more cohesive experience for non-techheads. A kodi plugin would be great, but it has been tried before and this seems like a far better solution.

I started looking at ways to add this functionality myself and submit it as a pull request, but I am by no means a react developer and I am having a hard time understanding where I would even begin. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Unfortunately, the effort to make this work is too substantial for us to add this. The best we can do is offer practical accessibility for built-in browser keyboard navigation. Directional-based controller navigation is a whole other beast.
