### ISSUE TITLE
Prevent Request if already in Plex?

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#2289]
### Description

Apologies if this has already been asked but couldn't find it here or on the Overseerr site. I installed Overseerr tonight and it's great so far. One of the first requests I received though was for a movie I already had in Plex. Is there a way to replace the Request button in that situation (or perhaps give a message when clicked) that what is being requested is already there?

### Desired Behavior

Replace 'Request' button with a label that says 'Already available' or something similar.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Available media items are not requestable in Overseerr.  Try running a full Plex scan, and see this FAQ entry if there are items not being marked as available: https://docs.overseerr.dev/support/faq#some-media-is-missing-from-overseerr-that-i-know-is-in-plex
