### ISSUE TITLE
Add Link to 'Open in Radarr/Sonarr' from the Requests list

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#2301]
### Description

To reduce the number of clicks into the Request, then to the Gear on top right (manage movie)

### Desired Behavior

Add another link from the Requests list. There appears to be plenty of real estate.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
As of v1.27.0, the badge for processing or requested items already links to the relevant *arr instance.  (Badges for available items link to Plex.)

**Comment by winbatch** [comment]
Ah- didn’t even realize that was a link. Thanks!
