### ISSUE TITLE
Hide "popular movies" on startpage

### ISSUE THREAD

**Issue by digidomic** [sct/overseerr#2311]
### Description

I installed overseerr not only for friends but also for my family. Therefore I would really like to hide the section "popular movies" because it showes adult content. 

### Desired Behavior

Option to hide "popular movies" section as it exists for "available".
"hideAvailable": false,

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
Duplicate of https://github.com/sct/overseerr/issues/1340
