### ISSUE TITLE
Provide more information when 'title' is no longer available

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#2323]
### Description

Without more information, it's hard to search for a new title that matches the original request.

### Version

1.27

### Steps to Reproduce

Not sure.

### Screenshots

![image](https://user-images.githubusercontent.com/2419795/144714800-897241c1-12fc-4f58-a48f-ded52db76d43.png)

### Platform

desktop

### Device

N/A

### Operating System

N/A

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
There's already a pull request to display more data about the content is no longer available: #2181 
So that should be available sometime.
