### ISSUE TITLE
Any plan for automatically add new releases to Sonarr&Radarr?

### ISSUE THREAD

**Issue by OliverGrace** [sct/overseerr#2326]
### Description

The app is absolutely a gorgeous. I can pick movies and TVs very easily and they are all well categorized. However, picking new things and add them manually can be a troublesome thing to do. 

### Desired Behavior

Any plan on auto adding new releases?(with setting on how many new seasons, new movies to auto request). I would be better if it collects a list of latest release and archive them per week and we can easily access those saved list and those being automatically requested.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
Have you looked at lists in Radarr and Sonarr? This sounds like the same feature they already provide.

**Comment by OliverGrace** [comment]
> Have you looked at lists feature in Radarr and Sonarr? This sounds like the same feature they already provide.

Yes, I did. The problem is that those provided content in those lists sometimes are not as good as those in overseerr, especially foreign movies and TVs. BTW, I think adding a SPORTS category would be good too(Formula one for example).

**Comment by samwiseg0** [comment]
> > Have you looked at lists feature in Radarr and Sonarr? This sounds like the same feature they already provide.
> 
> Yes, I did. The problem is that those provided content in those lists sometimes are not as good as those in overseerr, especially foreign movies and TVs. BTW, I think adding a SPORTS category would be good too(Formula one for example).

Those lists are completely customizable and can be tailored to be anything you would like. Radarr can even import from the same source as Overseerr. Overseerr uses [TMDb](https://www.themoviedb.org/) for its source data.

**Comment by OliverGrace** [comment]
> > > Have you looked at lists feature in Radarr and Sonarr? This sounds like the same feature they already provide.
> > 
> > Yes, I did. The problem is that those provided content in those lists sometimes are not as good as those in overseerr, especially foreign movies and TVs. BTW, I think adding a SPORTS category would be good too(Formula one for example).
> 
> Those lists are completely customizable and can be tailored to be anything you would like. Radarr can even import from the same source as Overseerr. Overseerr uses [TMDb](https://www.themoviedb.org/) for its source data.
 Thank you so much. I will check that.

**Comment by OliverGrace** [comment]
> > > Have you looked at lists feature in Radarr and Sonarr? This sounds like the same feature they already provide.
> > 
> > Yes, I did. The problem is that those provided content in those lists sometimes are not as good as those in overseerr, especially foreign movies and TVs. BTW, I think adding a SPORTS category would be good too(Formula one for example).
> 
> Those lists are completely customizable and can be tailored to be anything you would like. Radarr can even import from the same source as Overseerr. Overseerr uses [TMDb](https://www.themoviedb.org/) for its source data.

Thank you so much. I will check that out.
