### ISSUE TITLE
Add Approve button to Edit Request Modal

### ISSUE THREAD

**Issue by Syco54645** [sct/overseerr#2328]
### Description

When editing a request I am doing so to get it ready for approval. Currently I edit a request then click approve then go on and edit the next request. If using the filter to show only pending requests then it can cause the UI to jump a bit when it refresh the list.

### Desired Behavior

Add the "Approve" button to the "Edit Request" modal.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Already implemented in #2067
