### ISSUE TITLE
user with Manage Requests but without Manage Users unable to edit requests

### ISSUE THREAD

**Issue by Iguana9999phil** [sct/overseerr#2331]
### Description

I've made a local test user with minimal permissions to approve / deny / edit requests.
Permissions for this user which are enabled aside from the normal requests permissions are all options under "Manage Requests" With this user I'm able to see the requests of other users, I see the "Edit Request" button and get the modal to change the advanced settings. When setting the "Root Folder" and then doing an "Edit Request" I get an error message (something went wrong editing this request) nothing shows up in the logs though. 

Comparing the local test user against a full admin I see that the local test user misses the "Tags" and "Request As" options as well.

Tested on both the latest develop as the latest release versions.

### Version

93b5ea20ca590996f6dc90713a76800180d0621c

### Steps to Reproduce

Create local user with Full Manage request permissions. Edit request on an existing request from another user. Set Root Folder and see error.

### Logs

```shell
Nothing in the logs.
```

### Platform

desktop

### Device

iMac M1

### Operating System

macOS 11.6.1

### Browser

Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Fixed in #2338
