### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by darnov01** [sct/overseerr#2339]
### Description

Implement a way to import users from LDAP backends.
User accounts can be granted roles based on LDAP group, and can have one username and password that goes across a site that includes Overseerr.

### Desired Behavior

Create and manage users from LDAP backend, allow login to Overseerr with LDAP credentials so that SSO solutions like Authelia can work across multiple sites in a domain.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
Duplicate of https://github.com/sct/overseerr/issues/1638
