### ISSUE TITLE
Overseerr crashes during download sync if radarr/sonarr is not running

### ISSUE THREAD

**Issue by clintkev251** [sct/overseerr#2356]
### Description

I've noticed over the last few weeks that overseerr has been periodically crashing. On further investigation this seems to happen when it tries to attempt the download sync job when any of the radarr or sonarr instances are not available. This occurs for me when either of these applications are being updated, and as such are temporarily unavailable. Overseerr doesn't seem to know how to handle this exception

### Version

1.27.0

### Steps to Reproduce

1. Stop sonarr/radarr
2. Run update job
3. Overseerr crashes

### Logs

```shell
2021-12-21T19:47:45.411Z [debug][Jobs]: Starting scheduled job: Download Sync 
/app/dist/api/servarr/base.js:48
                throw new Error(`[${this.apiName}] Failed to retrieve queue: ${e.message}`);
                      ^

 PMError: [Sonarr] Failed to retrieve queue: getaddrinfo ENOTFOUND sonarr
    at SonarrAPI.ServarrBase.getQueue (/app/dist/api/servarr/base.js:48:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/dist/lib/downloadtracker.js:96:36
    at async Promise.all (index 0)
 PMerror Command failed with exit code 1.
```

### Platform

desktop

### Device

N/A

### Operating System

Unraid 6.9 (docker)

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
Going to re open this as we cant catch the error but as for the container crashing that is not something we can reproduce? We suspsect since its not our container it is crashing and restarting. Our official container does not crash.

**Comment by mrhotio** [comment]
```
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
My container runs with a newer version of Node, therefor it is following the above deprecation warning.
