### ISSUE TITLE
User Space Quotas

### ISSUE THREAD

**Issue by Renegade605** [sct/overseerr#2378]
### Description

Currently requests can only be limited to x series/movies per y days. Request limits are nice, but don't stop the server storage from filling up over time without manual intervention from the server owner. Allowing users to request content up until a certain amount of disk space is taken up instead would lessen workload on the server owner and allow more autonomy for other users.

### Desired Behavior

User A is assigned 1TB of space to use for series and movies as they see fit. Requests are auto-approved until this space is full.

Ideally, the user could delete some of their previously requested content to free up space (likely requires implementing per-user tags issue #1964).

More advanced implementation could see users warned as they are approaching their quota and/or the ability to unmonitor previous requests to prevent higher quality/larger version upgrades.

Other users could potentially see that a series/movie was added by a quota user and request it as well. The content isn't downloaded again but it's now counted against both User A and User B's quota and if either user deletes it, it stays on the server but is no longer counted against the deleting user's quota.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
How would this be managed? We have decide that overseerr will not implement deletions. https://github.com/sct/overseerr/issues/1924

Given that the user or the admin will not be able to delete the data. Users could get into a situation where they are unable to request content because they have maxed their quotas and managing this from overseerr will not be possible. 

I personally do not see the benefit of this since quotas in its current form will allow the same level of control. Once individual episode requests and quotas are implemented I can’t see the benefit in this request.

**Comment by Renegade605** [comment]
Without the ability to delete content, this would have limited value.

I'm not sure what you mean in your second paragraph. Admin will always have the ability to delete data, even if it's not through overseerr, either through Sonarr/Radarr or directly from the filesystem.

I now see the issue about individual episode requests, but I haven't found anything about more advanced quotas. Could you point me towards where this is or will be implemented?

**Comment by samwiseg0** [comment]
Adding this functionality has no gain and would appear half baked if it were implemented 

> I'm not sure what you mean in your second paragraph. Admin will always have the ability to delete data, even if it's not through overseerr, either through Sonarr/Radarr or directly from the filesystem.

I mean solely in the context of overseerr.

> I now see the issue about individual episode requests, but I haven't found anything about more advanced quotas. Could you point me towards where this is or will be implemented? 

The "advanced" would be per episode control vs season only.

You can easily set space requirements in your quality profiles by limiting the size of the the release. You can then extrapolate the requests limits from there.
