### ISSUE TITLE
Issue notification settings not available in discord notifications setting page

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#2380]
### Description

First of all, thank you for the great new update! It's fantastic :)
In the patch notes, there was a line that was saying that every notification provider has integrated notifications for issue notifications.
But I discovered that the discord option does not have this option available.
Is this by design or is it a small bug?

### Version

1.28.0

### Steps to Reproduce

1. Go to users
2. Click on edit on one of your plex users
3. Click on the Notifications tab
4. Click on the discord tab
5. See the missing settings

### Screenshots

![image](https://user-images.githubusercontent.com/2944704/147849607-01759efd-8d4c-4d0b-b68e-67c15a4e668d.png)

### Logs

```shell
not applicable
```

### Platform

desktop

### Device

Computer

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
The users need issue permissions to see the settings.
