### ISSUE TITLE
Adding Arabic Translation

### ISSUE THREAD

**Issue by Fhd-pro** [sct/overseerr#2381]
### Description

Hello there , I’m interested in adding my own language “ Arabic “ would be glad to translate it

I have no idea in how or what the needed tools but simple guidance would be cool 

it’s important to note that Arabic is right to left language not as English or most languages this is an important factor to note

### Desired Behavior

Would be glad to help in adding the Arabic language to the list

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Please see the comment from @sct on #2033:
> I am not sure we have great RTL support (if any) so it may not look great translated. Is that okay?

If this is okay, please let us know and we will get the language added to Weblate.

**Comment by sct** [comment]
Okay well, if you come back and can give us feedback on this, we would be happy to add the language. Until then, closing this issue.

**Comment by UA3** [comment]
I would suggest we add Arabic translation project and start making some progress. 

As for the RTL compatibility, I don’t think it would cause major issues, to tackle any incompatibility we would need to avoid having sentences with both Arabic and Latin letters or LTR punctuations. 

FWIW, this will pave the way for RTL compatibility by attracting more users from communities with RTL languages.

**Comment by Fhd-pro** [comment]
> .

It's done , waiting for the developers response

You may look at it and improve it of needed.

https://hosted.weblate.org/projects/overseerr/overseerr-frontend/ar/

**Comment by Fhd-pro** [comment]
Hello @sct & @TheCatLady 

Not sure if you are receiving notifications from the translation website or you need to manually check for updates so figured I should just update you here.

I have updated the Arabic language with the new strings and fixed some mistakes from my previous translation.

Once more thank you for your phenomenal work on overseerr and sorry if you find this comment unnecessary.

https://hosted.weblate.org/projects/overseerr/overseerr-frontend/ar/

**Comment by sct** [comment]
Thank you so much for the contribution @Fhd-pro. Changes made in Weblate make their way into the #3258 PR and will be merged before too long!
