### ISSUE TITLE
Issue with HOST environment variable set to 127.0.0.1

### ISSUE THREAD

**Issue by aniqueta** [sct/overseerr#2385]
### Description

Per https://github.com/sct/overseerr/issues/273 I set my HOST=127.0.0.1, as I'm also running Overseerr without Docker. This creates an Internal Server Error when connecting to the web endpoint. The API endpoint continues to work. I recognize addressing this will not be a high priority, as non-Docker is not supported. I'm filing this in case this is worth addressing eventually. 

The reverse proxy in front of Overseerr is connecting correctly, and the issue in the Overseerr logs, per below, suggests that even when HOST=127.0.0.1, internally, Overseer is trying to connect to ::1 instead to render the website. ::1 does not exist, given HOST=127.0.0.1. Thus, changing to HOST=::1 works to workaround this, and achieves the same result to bind to localhost only and be exposed only through the reverse proxy.  

### Version

1.28.0

### Steps to Reproduce

1. Set HOST=127.0.0.1 and PORT=5055 environment variables
2. Start Overseerr
3. Connect to https://overseerr-domain-here/api/v1/status to confirm Overseerr running
4. Connect to https://overseerr-domain-here/ to see Internal Server Error

### Logs

```shell
Error: connect ECONNREFUSED ::1:5055
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5055,
  config: {
    url: 'http://localhost:5055/api/v1/settings/public',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v1/settings/public',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '5055',
      nativeProtocols: [Object],
      pathname: '/api/v1/settings/public'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [Socket],
      _header: 'GET /api/v1/settings/public HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: localhost:5055\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v1/settings/public',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://localhost:5055/api/v1/settings/public',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

### Platform

desktop

### Device

All

### Operating System

All

### Browser

All

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
I do not believe this has anything to do with overseerr. 

The network stack is managed by your host system. Since ipv6 is enabled on the system. `::1` will be the loopback. I suspect if you look at your other services they will be listening on `::1`. In this case using `127.0.0.1` would be incorrect for your setup thus causing your problem. If anything this would be something with how node handles "loopback".

**Comment by aniqueta** [comment]
Thanks for the quick reply. This is on macOS, and indeed IPv6 is enabled. All other services on this machine are bound to 127.0.0.1 and work though, and for Overseerr, I didn't see anything amiss in the nginx logs in front of it. When HOST=127.0.0.1, the API endpoint works, just not the web frontend. So, I guess the issue is like you say, node defaults to loopback to ::1 in this setup? I don't have issues using ::1, but for future maintenance, it will be easier to remember that everything is setup on 127.0.0.1. Is there anyway to change node's behavior on this? Thanks.

**Comment by samwiseg0** [comment]
> Thanks for the quick reply. This is on macOS, and indeed IPv6 is enabled. All other services on this machine are bound to 127.0.0.1 and work though, and for Overseerr, I didn't see anything amiss in the nginx logs in front of it. When HOST=127.0.0.1, the API endpoint works, just not the web frontend. So, I guess the issue is like you say, node defaults to loopback to ::1 in this setup? I don't have issues using ::1, but for future maintenance, it will be easier to remember that everything is setup on 127.0.0.1. Is there anyway to change node's behavior on this? Thanks.

Not sure. It is not something we have had to explore since the way you are running the app is unsupported. Thus not something we have tested or have the bandwidth to look into.
