### ISSUE TITLE
Ability to limit sending test email to selected user(s)

### ISSUE THREAD

**Issue by grigsby** [sct/overseerr#2402]
### Description

In Settings -> Notifications -> Email there is a "Test" button at the bottom of the page to test SMTP functionality. I believe the test email is sent to all users, which is undesirable behavior. For example, I need to change the SMTP password and just want to make sure it still works, I don't want to bother all users with a test email.

### Desired Behavior

It would be better if we could select one (or more than one) email address from the user database -- or even just enter it manually -- to whom we want to send the test email. Most of the time, I would only need to send it to myself to make sure the SMTP settings are correct. I generally don't need to send test emails all users. Or maybe one specific user is reporting not receiving emails and I want to test sending an email just to that one person. In any case, having more fine-grained control over the email recipient(s) for the test email would be a welcome feature.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
Test notifications are only sent to the Plex server owner.  Testing if your email settings are correct is only for the admin. It is unnecessary to send test emails to users.

**Comment by TheCatLady** [comment]
To be more exact, test notifications are only sent to the user who initiated the test (not necessarily the server owner).

**Comment by samwiseg0** [comment]
Correct, I always assume there is only one admin ;)

**Comment by grigsby** [comment]
Ah, okay! That's great. Thank you. I was afraid to click the "Test" button because I didn't want to spam my users. But the current behavior is good. Thank you for the great software!
