### ISSUE TITLE
Connect to Plex not working 

### ISSUE THREAD

**Issue by fireheadman** [sct/overseerr#2412]
### Description

YOu closed my request 34 seconds before I could add this... which would make it a feature request.
If you can append this to my BUG issue or make it a feature request... then you would have what you need and what I need

### Desired Behavior

Was able to correct this....  seems my plex token expire or changed.
Had to edit the settings.json and change this to "false" and restart

```
 "public": {
  "initialized": true
```

Then I was able to re-enter my plex creds and problem solved.
### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
This falls under support and is not a feature request.
