### ISSUE TITLE
External URLs require URLs with a valid tld

### ISSUE THREAD

**Issue by LudvigHz** [sct/overseerr#2418]
### Description

External URLs, f.ex. radarr, sonarr external url use `yup`s `string.url()` validation. This validator requires a tld (see also https://github.com/jquense/yup/issues/224). I'm assuming this is why it was not used for f.ex hostname.

However, there are a lot of use cases where the external url just consists of a single hostname as well. My networking setup might not be the most widespread, but in addition to the local docker network (used for hostname), I have services exposed on a secured private network (tailscale, zerotier, any wireguard network) where I can access all my services using a specific hostname (f.ex. my server has hostname `server` and just `http://server` points to `:80` on this host.)

I know it's probably not the most common networking setup, but I feel like more error-prone and less restrictive is better than strict error-checking but too limiting :slightly_smiling_face:.

### Version

1.28.0

### Steps to Reproduce

1. Use a pricate wide area network setup with custom dns.
2. Try to set `External url` to a url without a TLD in radarr settings.

### Platform

desktop

### Device

any

### Operating System

GNU/Linux

### Browser

Firefox

### Additional Context

I'd be happy to remove the validator from the affected spots in a PR if this feature/fix is approved.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
I can't see a use case where the full FQDN cannot be used?

**Comment by TheCatLady** [comment]
This is by design; the `External URL` fields are for external-facing URLs (similar to the `Application URL` setting) and thus require a TLD.

You can configure your Radarr and Sonarr servers without setting the external URLs; it is an optional field.

**Comment by LudvigHz** [comment]
> This is by design; the `External URL` fields are for external-facing URLs (similar to the `Application URL` setting) and thus require a TLD.
> 
> You can configure your Radarr and Sonarr servers without setting the external URLs; it is an optional field.

Sure, but in my case the external URL _is_ one without a top-level domain. It's not external to the entire world, but it is external to anyone on the network (f.ex. tailscale). By design, I have limited access to radarr, sonarr to those devices on the tailscale network. So it's quite sad not being able to use the linking feature in overseerr and having to open radarr, sonarr and search for the item manually.


> I can't see a use case where the full FQDN cannot be used?
>
> Internal docker hosts can use host.docker.internal

Sure, at least for tailscale, I could use the full domain, but I'd rather not, considering it's uglyness :upside_down_face:: `example-server.examplename.mail.com.beta.tailscale.net` (redacted url here).

I'm not sure how it is for other similar networks though.

If this is not something that affects anyone else I understand, i can change it manually for myself. I was guessing if anyone has a similar setup this would be quite annoying (most I know running sonarr, radarr, overseerr has similar networking at least)
