### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by 19wolf** [sct/overseerr#243]
**Describe the bug**
Nothing loads, internal server error
**To Reproduce**

1. Docker run ((command from readme here))
2. Visit ip:5055
3. Internal Server Error

**Expected behavior**
The app to work

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Safari

**Additional context**
https://www.reddit.com/r/PleX/comments/kcp703/introducing_overseerr_a_request_management_and/gfs6ud1/

**Comment by sct** [comment]
This is fixed in the latest `develop` tag. `latest` tag is building now.

**Comment by sct** [comment]
`latest` release now also has this fixed.
