### ISSUE TITLE
Series shown as partially available because of extras

### ISSUE THREAD

**Issue by mkools** [sct/overseerr#2435]
### Description

Series that have extras (which almost every serie has) are shown as partially available.

Perhaps something can be made to ignore the extras (and yes they are unmonitored in Sonarr).

### Version

1.28.0

### Steps to Reproduce

Add any serie with extras, It will always be partially available.

### Platform

desktop

### Device

Linux

### Operating System

Linux

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
That's not actually the case. Specials are filtered out when determining the availability of a tv show in Overseerr.
Closing as a support request. Do come on Discord and we can see why your content is not showing up as Available as you expect it to.
