### ISSUE TITLE
Logs give 500 error

### ISSUE THREAD

**Issue by dhicock** [sct/overseerr#2451]
### Description

When attempting to view the logs, I get a 500 error. When calling the API directly, I get the following: 
`{"message":"Something went wrong while fetching the logs"}`

### Version

1.28.0

### Steps to Reproduce

1. Go to Settings 
2. Go to Logs
3. Error appears

### Screenshots

![2022-01-20 16_55_57-Internal Server Error - StormWind Auction House](https://user-images.githubusercontent.com/5377881/150435255-ed68e4ec-6224-40fe-964d-0b692dc42bc3.png)

### Logs

```shell
I can't upload logs. That's the issue haha
```

### Platform

desktop

### Device

Desktop PC

### Operating System

Windows 10

### Browser

Chrome

### Additional Context

I am running in a docker container hosted in Unraid

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Fixed in #2399
