### ISSUE TITLE
`TypeError: Cannot read property 'forEach' of undefined` during Plex sync

### ISSUE THREAD

**Issue by samwiseg0** [sct/overseerr#246]
**Describe the bug**
Exception is thrown when scanning the Plex library

**To Reproduce**

Scan the Plex library

**Expected behavior**
The scan should complete without errors

**Additional context**
Logs: https://gist.githubusercontent.com/samwiseg0/3c7cfb254eebdc94eb1c7993d59674ab/raw/b2d0df1c93a3e40845be1792a6583bcb60ba6ac7/overseerr_plex_scan_log_error

**Comment by sct** [comment]
This should be resolved on the latest `develop` tag. If you are still running into an issue, please re-open the ticket and let us know!

**Comment by samwiseg0** [comment]
This was resolved. Thanks!
