### ISSUE TITLE
"Add Radarr Server" window vanishes unexpectedly

### ISSUE THREAD

**Issue by Bothari** [sct/overseerr#247]
**Describe the bug**
"Add Radarr Server" window vanishes unexpectedly

**To Reproduce**
1. Navigate to Settings > Services
2. Click "Add Radarr Server" (same happens with Sonarr)
3. Press "Cancel"
4. Click "Add Radarr Server"
5. Click in "Hostname" text entry field (same happens with any entry field)

UNEXPECTED RESULT: 

Dialog window closes. 

**Desktop (please complete the following information):**
- Ubnuntu
- Intel CPU
- Latest Docker image

**Comment by sct** [comment]
This should be fixed on the latest `develop` tag.
