### ISSUE TITLE
Unable to add Radarr or Sonarr servers

### ISSUE THREAD

**Issue by Bothari** [sct/overseerr#248]
**Describe the bug**
Completely unable to add either a Radarr or Sonarr server.

**To Reproduce**
Try to enter info for a Radarr server. I use the IP of the host machine, the correct port and API key. Clicking "Test" then brings up the failure notification.

**Desktop (please complete the following information):**
- Ubnuntu
- Intel CPU
- Latest Docker image

**Comment by sct** [comment]
This should be fixed on the latest `develop` tag
