### ISSUE TITLE
Customized search with film/TV tittle in media information view

### ISSUE THREAD

**Issue by befantasy** [sct/overseerr#2488]
### Description

In the media information view, I am able to jump to TMDB, TVDB, IMDB and Rotten Tomatoes for current Movie/TV. That's an amazing feature. And there is no doubt they are the most popular movie/TV recommendation sites in the world. 
But sometimes, I also want to search current movie/TV with another search engine such as google, or another recommendation site such as [douban](http://douban.com), the most popular recommendation site in China. 
As you know, there are lots of localized movie/tv recommendation site for different users from all over the world. So, it will be useful if users are able to add some customize search engine or call the other API here.

[![HSI7wt.png](https://s4.ax1x.com/2022/01/29/HSI7wt.png)](https://imgtu.com/i/HSI7wt)

### Desired Behavior

1, add an option to create a customize search with Var.
2, add an option for API call.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
None of those links are to search engines.  Those links are to the pages for the specific media, constructed from IDs returned by TMDb when we fetch media data.

I don't see us adding links to perform text searches on search engines.
