### ISSUE TITLE
Self-host fonts instead of using Google Fonts

### ISSUE THREAD

**Issue by aniqueta** [sct/overseerr#2497]
### Description

Given that using Google Fonts can be a [privacy risk](https://www.thecybersecuritytimes.com/court-orders-websites-to-stop-embedding-google-fonts-for-gdpr-violation/), would it be possible to add functionality to self-host the used fonts? Thanks.

### Desired Behavior

Mirror assets from Google Fonts (gstatic.com) and load from same host as Overseerr instance.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
That link discusses GDPR, which "does not apply to the processing of personal data by a natural person in the course of a purely personal or household activity and thus with no connection to a professional or commercial activity."

Overseerr is designed for use with family/friends only.  So, as long as you aren't violating the Plex ToS and profiting off of users in the EU, you should be fine?

I don't really like the idea of maintaining a copy of the font and its CSS declarations in Overseerr, or further increasing the already large image sizes.  Overseerr is built upon external APIs and all of the media poster image assets are loaded from TMDb anyway...

**Comment by aniqueta** [comment]
Thanks for the quick reply. All good points. The link re: GDPR was just illustrative and topical. I think the difference between Google Fonts and other external resources is that Google is in the business of using their services to track and build profiles, whereas the others (hopefully) aren't. Practically, it could put a Overseerr instance on Google's radar for crawling, etc. when one is trying to keep it semi-private for family and friends. Understand if you decide the cost-benefit isn't worth it though. Thanks for considering.

**Comment by TheCatLady** [comment]
> I think the difference between Google Fonts and other external resources is that Google is in the business of using their services to track and build profiles, whereas the others (hopefully) aren't.

TMDb definitely does track and analyze usage of its API (and the data they collect includes IP addresses, etc.). This is the price of using an external API.

> Practically, it could put a Overseerr instance on Google's radar for crawling, etc. when one is trying to keep it semi-private for family and friends.

The `X-Robots-Tag` HTTP response header exists for this purpose :)

Also, FWIW -- Overseerr no longer fetches the `font-face` CSS declarations from Google Fonts, but inlines them at build time using [Next.js font optimization](https://nextjs.org/docs/basic-features/font-optimization).  Only the font file itself is fetched from Google Fonts, and your browser caches that font file for a year.  (Requests for CSS assets from Google Fonts are only cached for one day.)  As such, I don't see this as much of a concern.
