### ISSUE TITLE
Initial Scan Stalls: "SQLITE_CONSTRAINT: NOT NULL constraint failed: media.tmdbId"

### ISSUE THREAD

**Issue by extrobe** [sct/overseerr#250]
On initial library scan, it hangs on item 190 and doesn't progress. Cancelling the scan and restarting the scan results in a hang at the same point.

Logs shows...

 ```
2020-12-14T07:21:03.084Z [[34mdebug[39m][Plex Sync]: Title exists and is already available The Art of Racing in the Rain
(node:27) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: media.tmdbId

at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:11:28)

at Statement.handler (/app/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:76:38)

(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

2020-12-14T07:21:03.099Z [[34mdebug[39m][Plex Sync]: Title exists and is already available Armageddon
``` 

Running latest pull, on unRaid 6.8.3 (can't check overseerr version, as about page 404's)

Sounds similar to https://github.com/sct/overseerr/issues/244 but don't think it's the same

**Comment by sct** [comment]
Similar but not exactly. I will be pushing a fix soon that will at lesat continue processing instead of crashing out like this. Then we can pull out logs of which plex items are failing exactly and why.

**Comment by sct** [comment]
This should be resolved on the latest `develop` tag. If you are still running into an issue, please re-open the ticket and let us know!
