### ISSUE TITLE
Search on IMDb/TMDb/TVDb tag 

### ISSUE THREAD

**Issue by Hollander-1908** [sct/overseerr#2504]
### Description

I'm always frustrated when I cannot find the movie or tv show I'm looking for when I can easily find it on IMDb.

### Desired Behavior

The ability to search on tags, for example if I want to search for Halo TV Series (2022), search on it with `imdb://tt2934286`, `tmdb://52814` or `tvdb://366524`.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Already implemented in #2082, will be in the next release.
