### ISSUE TITLE
Multiple BOT Discord

### ISSUE THREAD

**Issue by WoisWoi** [sct/overseerr#2507]
### Description

Allow the use of multiple Discord bot, to refine and customize the use of notifications.

### Desired Behavior

Well, I think the description is straight forward. The purpose of this idea is to be able to send different types of notifications in different channels.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #1664

**Comment by WoisWoi** [comment]
My bad, (I forgot) I saw it last year... I thought the need had changed with the issue system :)
