### ISSUE TITLE
Increase clarity when title already available

### ISSUE THREAD

**Issue by kmlucy** [sct/overseerr#2512]
### Description

I have had multiple users try to request movies/shows that are already available, but they don't notice the small `Available` badge and just hit the `Request in 4K` button that replaces the `Request` button. I'd like it to be more clear when a title is available, as right now I have to explain to each user that `Request in 4K` means `Available`, which isn't very intuitive. 

![image](https://user-images.githubusercontent.com/13952475/152821141-a76804b8-95df-4c46-a1d6-c60e0b2a0629.png)

### Desired Behavior

My initial thought would just be to move the available badge so it is equal size and next to the request button, or possible combine the available badge with the watch in plex button and make it green.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Do you maintain two copies of each media, both non-4K and 4K?

If so, is the issue that you don't want users requesting media in 4K? If so, you can simply not grant users 4K request perms?

**Comment by kmlucy** [comment]
I want users to be able to request in 4K, I don't want users requesting 4K when they just want normal and don't realise the media is already available.

**Comment by TheCatLady** [comment]
> I only maintain one copy of the media.
> 
> I want users to be able to request in 4K, I don't want users requesting 4K when they just want normal and don't realise the media is already available.

https://docs.overseerr.dev/using-overseerr/settings#services
