### ISSUE TITLE
Adding Sonarr Tags when requesting Anime

### ISSUE THREAD

**Issue by XenosTechLabs** [sct/overseerr#254]
**Describe the solution you'd like**
- If a user requests an anime, the anime will auto-set a tag so it searches within the restriction in Sonarr. For example, Attack on Titan will search both sub, dub, and raw files. If the server admin sets the restriction in Sonarr, it will download only dub. 

**Additional context**
- https://prnt.sc/w2a6pj - Within Sonarr Setting
- https://prnt.sc/w2a7dx - Show Setting

Edit
- https://prnt.sc/w2aegv - Something like this, but with tag selection.

**Comment by 19wolf** [comment]
Not sure if this belongs here or in a separate request but- Can we also have it set different release profiles and root folders for Anime/TV?

**Comment by sct** [comment]
Let's use #290 as the main issue for this since it covers Sonarr as well.
