### ISSUE TITLE
Hide already monitored media

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [sct/overseerr#2540]
### Description

Hi,

Great project, thanks for your work on it.

### Desired Behavior

My feature request is simple: if a media item is already being monitored in Sonarr/Radarr, it should not appear as a recommendation on the discovery screen.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by paulo-erichsen** [comment]
not stale

**Comment by zwimer** [comment]
This should be reopened- there is a pending PR about it.
