### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by jansengorilla** [sct/overseerr#2552]
### Description

No sorting options available.

### Desired Behavior

I would like to sort by popularity, rating, release date etc.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #459

**Comment by jansengorilla** [comment]
Hi, i found that one a bit complicated. Wouldn't users appreciate a simple sort by date or rating function? Especially when browsing genres etc. I'm fine sharing this issue under the other one :)

**Comment by cparello** [comment]
I agree sorting by release date is a must have, if i click on showtime, i want to see the newest shows.
