### ISSUE TITLE
Add Albanian Language in Weblate

### ISSUE THREAD

**Issue by deniscerri** [sct/overseerr#2562]
### Description

I made a pr yesterday about adding the language file and found out that i need to contribute through weblate. Sorry about that.
Weblate doesnt have the language as an option.

### Desired Behavior

I want Weblate to add Albanian so i can continue translating. I have reached 10% so far locally.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Added: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/sq/

Thanks for helping translate! If you have any questions about strings please feel free to join our Discord and ask there!
