### ISSUE TITLE
Request film collections

### ISSUE THREAD

**Issue by westdom** [sct/overseerr#2570]
### Description

I think the ability to request "Collections" of films would be a real nice to have feature.

For example; I'd like to be able to request all the Star Wars films within a click or two after a search.

### Desired Behavior

- An additional row on the "Discover" page for a list of popular collections.
- The ability to search for collections via the searchbar.
- Clicking on a collection could display all the collections films (in the same way they appear when searching for films), a main request button & a collection description.
- The main request button could either request all the films individually or:
   - Package it in a single request so that only the collection appears in the "Requests" page

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
We already have collection requests. You can find collections on movie detail pages that are part of a collection. if you check any star wars movie, you should see a link to go to the collection page on the right side.

We can't show a slider of collections due to a limitation on TMDb's side.

**Comment by westdom** [comment]
Oh perfect I had no idea! Thanks :)
