### ISSUE TITLE
Translation Romanian language

### ISSUE THREAD

**Issue by Lulu195** [sct/overseerr#2594]
### Description

No

### Desired Behavior

As mentioned in Webplate i have to make a feature request in order for you to prepare the new language first on the application side to prevent merge issues in the future.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
I have added Romanian to Weblate here: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/ro/

Please let us know if you have any questions about the translations in our Discord. Thanks!
