### ISSUE TITLE
Request only the first episode / pilot of a new series

### ISSUE THREAD

**Issue by Snorezor** [sct/overseerr#2595]
### Description

I enjoy watching the first episode (pilot) of a series to decide if I want to download and store the rest of the series / season. Requesting the first season to learn that I dislike the pilot is a waste of bandwidth.

### Desired Behavior

When requesting a new series, present an option to only request the pilot. This will add the series to Sonarr with only the first episode being tracked.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #342
