### ISSUE TITLE
Requesting already existing movies is possible

### ISSUE THREAD

**Issue by danshilm** [sct/overseerr#260]
**Describe the bug**
Movies in libraries that use the TMDB agent are not parsed properly and don't show up as `Available`.
This results in being able to request movies that are already present in Radarr and the Plex library which in turn results in an error in Overseer and a `Invalid request Validation failed: -- TmdbId: This movie has already been added` in Radarr.

**Are you on latest or develop branch?**
sctx/overseerr:latest

**To Reproduce**

1. Request a movie that's already present in Radarr.
2. Check the logs.

**Expected behavior**
Ideally, the movie shouldn't be able to be requested if it's already present in Radarr/Plex since the Plex Library Scan would mark the movie as already `Available`.

**Comment by azoitos** [comment]
We currently do not have Radarr/Sonarr sync so we have updated the logging to make things a little bit more clear for the user. 

If your Plex sync is working, Overseerr should mark it as `Available` and a user should not be able to request a movie that already exists.

**Comment by sct** [comment]
I believe this is a non-issue at this point. Going to close this for now.
