### ISSUE TITLE
Ability to set friendly names for users, Alias

### ISSUE THREAD

**Issue by samwiseg0** [sct/overseerr#264]
**Is your feature request related to a problem? Please describe.**
It would be ideal to be able to set friendly names per user as it is difficult to remember every user's username.

**Describe the solution you'd like**
The ability to set friendly names for each user.

**Comment by shark2k** [comment]
Also, having friendly names would allow showing other users who made the request without possibly giving away another users email address (if they never set a username up in Plex then their email address is what's displayed).  I'm going through enhancement request as I have a few ideas and don't want to duplicate but I have a couple of ideas I thought of that would make this much appreciated if they got implemented.

-Shark2k

**Comment by sct** [comment]
Only admins can see other users emails so this shouldn't be an issue. (Unless you have some very tech savvy users digging through certain api calls)

**Comment by sct** [comment]
But either way, this feature is coming 👍

**Comment by shark2k** [comment]
Awesome.  Good to know.
Thanks for the update on that.

-Shark2k
