### ISSUE TITLE
Media API Endpoint returns empty result set

### ISSUE THREAD

**Issue by cpt-kuesel** [sct/overseerr#2646]
### Description

I wanted to use the API to get a list of all media in Overseerr and expected a result set with 1738 items.
When accessing the endpoint http://<overseerr_instance>/api/v1/media I instead get an empty result set.
Other endpoints like http://<overseerr_instance>/api/v1/request return an expected result of 282 items.

### Version

1.28.0

### Steps to Reproduce

Using Postman to test out API requests:
1.) Create new GET request
2.) Add URL "http://<overseerr_instance>/api/v1/media" to the request
3.) Add API Key Authorization to the request
4.) Send request
5.) Get empty response

### Screenshots

About Page in Overseerr:
![image](https://user-images.githubusercontent.com/79487102/160247741-f926668d-d7a4-4798-9300-bc8131c918b9.png)

Empty result from /media-Endpoint:
![image](https://user-images.githubusercontent.com/79487102/160247801-5ae236c1-cdf0-478f-a8e4-608417c6b843.png)

Expected result from /request-Endpoint:
![image](https://user-images.githubusercontent.com/79487102/160247816-cb884b84-00cc-42ed-9bf0-c6cd9bb91b1c.png)

### Platform

desktop

### Device

PC

### Operating System

Fedora Server 34

### Browser

Chromium

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Thanks for reporting this!

**Comment by cpt-kuesel** [comment]
Thank you for fixing it!
