### ISSUE TITLE
Different number of seasons between Overseerr and Sonarr

### ISSUE THREAD

**Issue by hwwilliams** [sct/overseerr#2648]
### Description

I noticed that for a show that was requested recently Overseerr shows that it only has 1 season with 2289 episodes instead of the 29 seasons that Sonarr shows, the only thing I can tell is that Sonarr primarily uses TVDB for its information which does list this show has having 29 seasons whereas TMDB has the show listed with only 1 season.

I'm not sure if Overseerr uses TMDB or it gets the season list from somewhere else but I thought I'd mention it in case is a bug because it'll cause issues if someone only wants to request one season out of the several available.

### Version

1.28.0

### Steps to Reproduce

1. Search `Shin Chan` on Overseerr.
2. Select the series starting in 1992.
3. Notice that the series is listed as having only 1 season.
4. Search `Shin Chan` on Sonarr.
5. Select the series starting in 1992.
6. Notice that the series has 29 seasons.

### Screenshots

![image](https://user-images.githubusercontent.com/20447447/160264063-50c87b41-2202-47de-9bd9-0cdd0665a810.png)
![image](https://user-images.githubusercontent.com/20447447/160264079-3c608562-ec81-4a2e-8134-c12e17b737a4.png)

### Platform

desktop

### Device

Desktop

### Operating System

Windows 10

### Browser

Firefox 98

### Additional Context

Links to TVDB and TMDB for the show:

* https://thetvdb.com/series/crayon-shin-chan
* https://www.themoviedb.org/tv/30623-crayon-shin-chan?language=en

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Overseerr uses TMDb while Sonarr uses TVDB. Unfortunately, there isn't much we can do about this.

**Comment by Niborian** [comment]
Hi Ive also noticed this on a few Anime shows one of them are Bleach.

https://thetvdb.com/?tab=series&id=74796
https://www.themoviedb.org/tv/30984-bleach?language=en

If overseerr could use the TVDB episode group then it would be just fine for this show: 
https://www.themoviedb.org/tv/30984-bleach/episode_group/663fb548c10d4be3e80b2f6d

so having a setting to set default.. secondare etc or use default if not available ask... and a way to compare would be really nice
