### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by UA3** [sct/overseerr#2656]
### Description

Thanks for this great project.

I would like to participate in translating it to Arabic, I understand from #2381 and #2033 that there is a concern about RTL compatibility.

I don’t think RTL incompatibility would cause major issues, to tackle any incompatibility we would need to avoid having sentences with both Arabic and Latin letters or LTR punctuations.

I suggest we add Arabic translation project to Weblate and start making some progress.

FWIW, this will pave the way for RTL compatibility by attracting more users from communities with RTL languages.

### Desired Behavior

Adding Arabic to Weblate.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
We can give it a try! Let's see how it looks with some of the translation work done. I added Arabic to weblate here: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/ar/

Hop in Discord if you have any questions or need help with anything!

**Comment by Fhd-pro** [comment]
> questions

Hello , I have translated few strings very quickly and wondering how they look before continuing , if things are OK will continue and revise what ever is nedeedd

**Comment by Fhd-pro** [comment]
It's done , waiting for the developers response

https://hosted.weblate.org/projects/overseerr/overseerr-frontend/ar/

**Comment by Fhd-pro** [comment]
> !

 Done. 100%

https://hosted.weblate.org/projects/overseerr/overseerr-frontend/ar/
