### ISSUE TITLE
Separate media type and root folder for anime

### ISSUE THREAD

**Issue by PrincessLuna2253** [sct/overseerr#266]
I absolutely love what I've seen of Overseerr so far, but my Plex server is mostly anime, and as far as I can tell there is currently no way to set different root folders for anime and tv shows. That's honestly the only thing keeping me from switching over.

Ombi's settings: https://i.imgur.com/RLhlqeF.png

**Comment by samwiseg0** [comment]
Wouldn't this be part of this request which has already been made?

https://github.com/sct/overseerr/issues/254

**Comment by PrincessLuna2253** [comment]
This is the same as what 19wolf in the comments is asking for but I thought this deserved its own request. It's not the same thing as release tagging, that is a separate feature.

**Comment by sct** [comment]
Please try to use the feature request template when making a feature request!

This is a planned feature with fairly high priority. Should see it soon.

**Comment by PrincessLuna2253** [comment]
Excellent, glad to hear it! And my apologies, I couldn't figure out how to do that, or how to add the enhancement label. I'm probably just dumb lol
