### ISSUE TITLE
[Bug] Emails have a white border around them

### ISSUE THREAD

**Issue by Gartonious** [sct/overseerr#2666]
### Description

When receiving emails from Overseerr, I have noticed there is a white border around the request information. I am guessing this is not shown when your phones theme is set to light but within the dark theme you can see the outline around the request which really stands out and could do with been changed so it perhaps matches the dark blue colour of the email.

### Version

1.29.0

### Steps to Reproduce

When the now available emails send to the end user, it has the white border around the request information.

### Platform

smartphone

### Device

iPhone 12 Pro Max

### Operating System

iOS 15.1

### Browser

Safari, Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
This is not a bug, the emails feature a "request card" that imitates the Overseerr UI.

**Comment by Gartonious** [comment]
> This is not a bug, the emails feature a "request card" that imitates the Overseerr UI. (Also, not sure why your emails are dark blue?)

![image](https://user-images.githubusercontent.com/36725136/161437979-ad73f903-0d8f-42e5-a016-338e91c73204.jpeg)

This is what it appears like for me

**Comment by TheCatLady** [comment]
Oh, interesting. What email provider or app?

**Comment by Gartonious** [comment]
> Oh, interesting. What email provider or app?

I use outlook.com for my emails and this is within the mail app on the iPhone

**Comment by Gartonious** [comment]
I just wanted to check if there was any update to this one? Do you require anymore information? :)

**Comment by Gartonious** [comment]
This is not stale, no one else has bothered to comment since posting.

**Comment by Gartonious** [comment]
This is not stale, just no developer has bothered to action. Issue still stands.
