### ISSUE TITLE
Request to have movies also in the netflix, disney etc section 

### ISSUE THREAD

**Issue by Gartonious** [sct/overseerr#2668]
### Description

It would be nice to have the Netflix and Disney etc sections to have movies in there too so everyone can see as a whole what is on netflix and what is on disney without having to buy / login to those services to see what is currently on there movie wise. It is already a fantastic feature to have all the tv shows on there but would be nice to be extended to movies too with possibly a toggle so you can only view movies, only view tv shows or view all at once

### Desired Behavior

When you go onto the Netflix / Disney etc section of Overseerr, it would be nice to be greeted with everything currently playing on those services including movies and tv shows with the ability to be able to toggle between view all, view movies only and view tv shows only.

Thank-you in advanced :) 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
There is no Netflix or Disney "section" of Overseerr. It appears that you are viewing network results, and networks are only associated with series in TMDb.

To see movie results, you would need to view the relevant studio / production company instead.

**Comment by Gartonious** [comment]
> There is no Netflix or Disney "section" of Overseerr. It appears that you are viewing network results, and networks are only associated with series in TMDb.
> 
> To see movie results, you would need to view the relevant studio / production company instead.
> 
> (Unfortunately we don't have a way to retrieve media available on a particular streaming service. Overseerr is only able to tell you where a media item is currently available to stream.)

Thank-you for your quick reply. I know on a few movies it does say now streaming on within the description, maybe that information be used in order to incorporate  movies into the netflix / disney sections?

**Comment by TheCatLady** [comment]
Again, there is no Netflix/Disney "section."  Movies don't have networks and thus do not appear in network-filtered views.  Please see my above comment.
