### ISSUE TITLE
[Request] Play stats for users

### ISSUE THREAD

**Issue by Gartonious** [sct/overseerr#2669]
### Description

It would be nice to be able to add in permissions to allow standard users to be able to view how many times something has been played stats from Tautulli but not to be able to click the launch Tautulli button for non admins.

### Desired Behavior

When signed in as an admin, they have the ability on an item to be able to view the Tautulli played stats, it would be good for non admins to be able to view this too by permissions applied to a user account but for them not to be able to see the launch in Tautulli option ( this could perhaps be a separate permission to grant a user to see this too)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by bpodolak** [comment]
Wondering if this could go one step further and add additional features/statistics like “most watched” or “most popular”. Creating overseerr as a homepage for both stats and requests for end users. Similar to another project homebase: https://github.com/tylerforesthauser/Homebase

**Comment by Gartonious** [comment]
Not stale bump.

**Comment by Gartonious** [comment]
This is not stale, just no developer has bothered to action / reply.
