### ISSUE TITLE
Send Discord notifications on all requests, including auto-approved requests

### ISSUE THREAD

**Issue by TheChrisK** [sct/overseerr#267]
**Is your feature request related to a problem? Please describe.**
Discord push does not happen when a title requested is from an auto-approve user.

**Describe the solution you'd like**
I noticed that Overseerr does not push to Discord when a user who has auto-approve permissions requests an item. I can see a need for server owners to want a notification on all requests.

**Describe alternatives you've considered**
The alternative is to not set users to auto-approve. This forms a limitation

**Additional context**
None.

**Comment by kurterik** [comment]
Also the ability to choose which notifications are sent.  For example, I would like a notification for all requests (even auto approved ones) but I don't want a notification for items becoming available.

**Comment by samwiseg0** [comment]
Please go back and fill out the template provided.

**Comment by TheChrisK** [comment]
Updated original post.

**Comment by sct** [comment]
This is something I want to implement. Do we want a global "send notifications to users with auto approve permission" or granular per notification type? Or both?

**Comment by TheChrisK** [comment]
I don't think it needs to be too complicated. You could do notifications for requests, approvals, denials and available and maybe have the option to exempt a user's actions from triggering notifications. Personally, I don't need user specific notification exemptions. I like to see all requests and when they become available, even if I request it.

**Comment by XenosTechLabs** [comment]
> This is something I want to implement. Do we want a global "send notifications to users with auto approve permission" or granular per notification type? Or both?

> I don't think it needs to be too complicated. You could do notifications for requests, approvals, denials, and available and maybe have the option to exempt a user's actions from triggering notifications. Personally, I don't need user-specific notification exemptions. I like to see all requests and when they become available, even if I request it.

![Screenshot_225](https://user-images.githubusercontent.com/8203095/102806285-d5ae3600-4379-11eb-8080-97c661a5a046.png)

Probably some similar to this. This can apply to all notification services.
