### ISSUE TITLE
Local user cannot login

### ISSUE THREAD

**Issue by erdalgns** [sct/overseerr#2675]
### Description

I created a local user but the user cannot log in. The log is the following.
```
Something went wrong authenticating with Overseerr password {"errorMessage":"Cannot read properties of undefined (reading 'find')","ip":"::ffff:192.168.1.241","email":"xxx@gmail.com"}
```

### Version

1.29.0

### Steps to Reproduce

1. Create a local user from admin's `Users` panel
2. Click on `Use your Overseer account` while signing in
3. Enter the auth details of the created local user

Expected Result:
User logs in successfully

Observed Result:
User gets `Something went wrong while trying to sign in.` error.

The logs show:
```
Something went wrong authenticating with Overseerr password {"errorMessage":"Cannot read properties of undefined (reading 'find')","ip":"::ffff:192.168.1.241","email":"xxx@gmail.com"}
```

### Platform

desktop

### Device

Macbook

### Operating System

Mac Os 11.6

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by McLavish** [comment]
I have the exact same error, local users are no longer working.
Probably line 214 in server/routes/auth.ts ?

**Comment by donslice** [comment]
I also have this issue. Noticed that in the GUI, my 2 Local users have switched to "Plex User" with no way to switch back.

**Comment by donslice** [comment]
I was able to fix this with a SQLite command. The login script is looking for a PlexID. Somehow in an update this must have gotten set? 

This worked for me. Please back up your installation before doing this. I take no responsibility if your install is broken.

**Steps to fix:**
1. Log in to server.
2. Navigate to Overseerr's "db.sqlite3" file.
3. `sudo cp db.sqlite3 db.sqlite3.bak`
4. `sudo sqlite3 db.sqlite3`
5. `UPDATE main.user SET plexUsername=null, userType=2, plexId=null WHERE id=**<ID OF LOCAL USER>**;`
