### ISSUE TITLE
Add a "From your Plex Watchlist" Row to Overseerr Discovery Page for Plex-authenticated users

### ISSUE THREAD

**Issue by millercentral** [sct/overseerr#2678]
### Description

For users who use authenticate with their Plex credentials, it would be great to show their Plex Watchlist as a row in Discovery with the ability to request items not currently available on the server.

Here is an example query builder for the API (from Sonarr):
```
var requestBuilder = new HttpRequestBuilder("https://metadata.provider.plex.tv/library/sections/watchlist/all")
                    .Accept(HttpAccept.Json)
                    .AddQueryParam("clientID", clientIdentifier)
                    .AddQueryParam("context[device][product]", BuildInfo.AppName)
                    .AddQueryParam("context[device][platform]", "Windows")
                    .AddQueryParam("context[device][platformVersion]", "7")
                    .AddQueryParam("context[device][version]", BuildInfo.Version.ToString())
                    .AddQueryParam("includeFields", "title,type,year,ratingKey")
                    .AddQueryParam("includeElements", "Guid")
                    .AddQueryParam("sort", "watchlistedAt:desc")

if (!string.IsNullOrWhiteSpace(authToken))
{
       requestBuilder.AddQueryParam("X-Plex-Token", authToken);
}
```

### Desired Behavior

On the Discovery page, show a row called "From Your Plex Watchlist" that shows media items for everything you have added to your Plex Watchlist, with the same status and actions as Media Items in other rows (ie, Trending).

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by iterexet** [comment]
Why stop there, I think it would be a dream to make it a permission & user settings option to auto-request anything that shows up on any plex user's watchlist, then users would be able to effectively request things without leaving the plex app... set it and forget it

**Comment by Gartonious** [comment]
I second this, it would be a cool feature to incorporate into the discovery in plex - it must come through from the user who is requesting it though and not just a generic add - need to keep on top of what is been required / request limits per person etc :)

**Comment by rijsab** [comment]
Yes, agree would be awesome to have this feature. Add an item to Plex Watchlist and Overseerr will pick up as request if not available on server.

**Comment by dr3am37** [comment]
This is probably my most wanted addition, it made me switch to Ombi for now, please let us know if you plan on adding it!

Cheers

**Comment by Vansmak** [comment]
Thats why im stuck on ombi until they add this on overseer.  There are scriots you can use to import plex watchlist to sonarr and radarr directly too

**Comment by tdeverx** [comment]
Plex just added an option to generate an RSS feed for your watchlist, this would essentially allow users to add this "URL" to their profile. This should remove the need to implement a way to scan all users Plex profiles and give users a choice if they want this or not. I also believe scrubbing an RSS feed should be 100x easier to implement.

https://app.plex.tv/desktop/#!/settings/watchlist

**Comment by snown** [comment]
It looks like a similar feature was [recently added to Ombi](https://docs.ombi.app/settings/plex/), I came here specifically looking if it had been implemented in Overseerr yet. I too would like to see it set-up so that a users "watch-list" was automatically added as a request.

**Comment by tdeverx** [comment]
When this gets implemented may I suggest that the logic includes a quick reference at what the user has watched first?

Now that the watch status' sync between Plex / Discover, it would prove super useful to cross reference what somebody has watched first, before the request is triggered. A Perfect example for this would be a show that has 9 seasons, it would be 10x more efficient to only request say, season 9 if the user has already watched season 1-7.

Ideally I would like to personally enable the ability to auto request media through Plex on a per user basis, and let them know that I can enable it, but they MUST mark what they have already seen before adding it to their watchlist.. if that makse sense?

**Comment by Gartonious** [comment]
It is about time this feature was added to the software. It has to be the most requested feature now but it seems there wasn't been any updates at all recently from the developers? I hope this isn't something to be worried about?
