### ISSUE TITLE
Add separate permissions to auto-approve TV and Movies

### ISSUE THREAD

**Issue by TheChrisK** [sct/overseerr#268]
**Is your feature request related to a problem? Please describe.**
Currently auto-approve is all inclusive to TV and movie titles. Allowing users to auto-approve TV shows can be a problem if a user requests a series with dozens of seasons. 

**Describe the solution you'd like**
Can the auto-approve permission be split to include the option for TV and Movies separately?

**Describe alternatives you've considered**
Not to set auto-approve at all which is a limitation. I trust users to auto-approve movies but TV shows are not something I would like to have auto-approve

**Additional context**
Just an additional permission option.

**Comment by dcomnimda** [comment]
Would love this as well. Some users I am all right with auto requesting movies but not tv shows

**Comment by theradiostar** [comment]
Ditto on this one.

**Comment by PotatoQuality** [comment]
Maybe as additional: A permission setting for requesting 4k movies/tv shows?

**Comment by ctrlaltd1337ed** [comment]
+1 as well, auto approving TV shows can be a pain in the ass if it's a massive show, but auto approving movies is fine.
