### ISSUE TITLE
TV Show Partially Available Notifications

### ISSUE THREAD

**Issue by olliecorbin** [sct/overseerr#2690]
### Description

When using notification, if a TV show updates its status to 'partially available' there is no notification sent. This would be useful I believe. 

So for example, if I request a show, which has 3 seasons. Seasons 1+2 have already been released, however, season 3 isnt available for a few months (but is available to request, which makes sense), so this means, once season 1+2 have been made available, the request is only 'partially available' even though everything which is currently possible to be available is. 

### Desired Behavior

I understand the need for the partially available status, makes sense, but I would like to be able to send a notification when this is the case.

At the moment, if a user requests a series which is like the above example, they will not get a notification until all 3 seasons have been made available. It would be great for users to be told "everything which is currently released for this show is now available" which I think we could do with a notification type of 'MEDIA_PARTIALLY_AVAILABLE'.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by MariusGGS** [comment]
Really?

**Comment by ljunglex** [comment]
Guess this is somewhat solved by the option to 'Mark all seasons as available'.

Problem is if not all seasons are requested, or just the last one. 
You can't send any notification due to 'Partially Available', and you also can't mark all seasons as available, since they aren't.

**Possible to add option for 'Mark season as Available'?** Either in Advanced settings or as a button within the Season rows.

**Comment by barrelltitor** [comment]
A notification for each new episode toggle-able per series would be useful and it would fix this issue

**Comment by saucedge** [comment]
This phenotype appears in multiple issues... but I can't find one that seems to be driving any activity.  A way to send an availability notification when all released episodes are available seems important to me.  If a user requests a movie, they get notified as soon as they can watch it.  If they request a TV show, the user experience is the same, but only for finished shows.  If they request a show that's in-progress, they get no notification until the season finishes.  I understand the logic to notify once the request is fully satisfied... but my users want notifications for when they can start watching the current released content.

**Comment by MFYDev** [comment]
Really need this function as most of my TV Shows are not all seasons available and sometimes any user who is using my service will need to receive notification when their requested seasons are available instead of the whole 10 - 20 seasons
