### ISSUE TITLE
[Request] Media Timeout / auto delete feature

### ISSUE THREAD

**Issue by Gartonious** [sct/overseerr#2691]
### Description

It would be nice to be able to request something but have the control and ability to control how long it would be available for.

### Desired Behavior

It would be nice to be able to request something but for the system to ask or be pre-set with how long the item would be available for.

For a movie example, to be able to pick 3, 6, 9, 12 months then after that time has expired, it would archive off the request and delete the content allowing users to request it again if required but also to save space on your plex media server.

For a TV Show example, it would be nice to be able to remove the previous season after the new one has finished. For example if you have last years Briton's got Talent, once the latest season is completed, it would then automatically delete the previous season to keep it current allowing users to check back through the archive requests to request it back if it is required to again help with reducing storage automatically.

### Additional Context

Additionally to this, it could also be integrated into Tautulli so if something has not been played in a pre-set amount of time then it could archive off the request into a separate area allowing users to request it again easily and deleting the content to save space on the hard drives.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Media deletion by Overseerr will not be implemented. See #1924
