### ISSUE TITLE
Error requesting series Fallout (amazon)

### ISSUE THREAD

**Issue by nmbrg** [sct/overseerr#2703]
### Description

If i try to request the serie "Fallout" that amazon is doing (yet to be released) it fails with errors.

as far as i can tell overseerr, for some reason, has the wrong ID. Overseerr seem to think its ID 384859. But that ID does not exist on thetvdb. in thetvdb, the serie "fallout" has the ID 416744.

### Version

1.29.1

### Steps to Reproduce

1. Search for fallout
2.  choose fallout series made by amazon, that is in "planning". 
3. request it
4. a popup appears saying "fallout requested successfully" but not even a second later i get a notification on pushover saying that the request has failed
5. check requests and see that fallout has the status "failed" there.
6. and check sonarr to see that it hasnt been added there.

### Logs

```shell
`{
 "errorMessage": "Series not found",
 "tvdbId": 384859
}`

`{
 "errorMessage": "Series not found",
 "options": {
  "languageProfileId": 1,
  "monitored": true,
  "profileId": 5,
  "rootFolderPath": "/data/media/tv",
  "searchNow": true,
  "seasonFolder": true,
  "seasons": [
   1
  ],
  "seriesType": "standard",
  "tags": [],
  "title": "Fallout",
  "tvdbid": 384859
 }
}`

`{
 "mediaId": 295,
 "requestId": 174,
 "sonarrSeriesOptions": {
  "languageProfileId": 1,
  "monitored": true,
  "profileId": 5,
  "rootFolderPath": "/data/media/tv",
  "searchNow": true,
  "seasonFolder": true,
  "seasons": [
   1
  ],
  "seriesType": "standard",
  "tags": [],
  "title": "Fallout",
  "tvdbid": 384859
 }
}`
```

### Platform

desktop

### Device

PC and iphone

### Operating System

Windows and iOS

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Magikarplvl4** [comment]
This is not a overseer issue but a upstream metadata issue.

You can fix it by yourself with editing the tvdb id reference on:

https://www.themoviedb.org/

**Comment by nmbrg** [comment]
Oh ok. And the it will take some hours before overseerr sees the new ID?
