### ISSUE TITLE
Add username to local user deletion confirmation dialog.

### ISSUE THREAD

**Issue by jtrosper** [sct/overseerr#2706]
### Description

The local user deletion confirmation dialog currently prompts: "Are you sure you want to delete this user? All of their request data will be permanently removed."  There is currently no information presented to the person initiating the deletion which user for which they've clicked the delete button.

### Desired Behavior

Modify the deletion confirmation dialog with language similar to: "Are you sure you want to delete **User X**?"

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This is a good idea! We can definitely add this.

**Comment by ankarhem** [comment]
Could have the user confirm the deletion by typing the username, similar to when deleting a repo
