### ISSUE TITLE
a field: "reason" in requests

### ISSUE THREAD

**Issue by Blazzycrafter** [sct/overseerr#2728]
### Description

![image](https://user-images.githubusercontent.com/39300111/166158411-e825e376-45ba-4d5d-89a6-6418aa2894c4.png)

### Desired Behavior

write a reason or leave it

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
I'm a little bit confused, can you give me an example of what someone would put as a reason when requesting something? Or is this a way to give some context to a request instead?

**Comment by Blazzycrafter** [comment]
> I'm a little bit confused, can you give me an example of what someone would put as a reason when requesting something? Or is this a way to give some context to a request instead?

yeah context....

user requesting season 2 and provided a reason:
"done with season 1"

i made 2 request for the same series...
first season 1
now season 2

**Comment by sct** [comment]
Isn't the fact they are requesting it reason enough? The request itself is "I want to watch this thing/." I don't think we need a more detailed reason here.
