### ISSUE TITLE
New Series Notification - "S01E01 - is available to watch!"

### ISSUE THREAD

**Issue by Dystaxia** [sct/overseerr#2735]
### Description

Would like to be able to be notified when a new series is available to watch.  Currently you only receive a notification when the whole season is finished.

### Desired Behavior

When a new series is started and available, S01E01.mkv, a notification would be sent out to the requester (and maybe others?) that a newly started series is available to watch.

Hey Overseerr Users, S01E01 of "It's a brand new show" is available to watch!

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by NSempsrott** [comment]
Yes please! I know there are issues with TVDB not having all the episodes and such, but just adding an optional notification for the first episode being available (or maybe even an option for users to get notified for every episode that shows up?) would be great for requests of still airing shows, especially ones with seasons that are spread out over a long time where people might not get notified for months after the episodes start being added to Plex. This would be a wonderful enhancement!

**Comment by Bokaii** [comment]
Completely agree. Approximately 90% of my requests are for series/movies being released in the future. Having to wait until the whole season is available is not what the users want.

This means I have to manually "mark season as available" when the first episode is available, which is not optimal.
