### ISSUE TITLE
Defined root paths on a per-user basis

### ISSUE THREAD

**Issue by oenu** [sct/overseerr#2736]
### Description

My users are not savvy about checking the correct arr client when making requests, I have set up the system so that it tags content based on the arr service selected and handles multiple plex libraries accordingly. 

### Desired Behavior

A user makes a request, the only option they have for a download server is one specified in settings to which all of their requests will be sent. Preferably they should be able to select from a sub-set of options in the case of 4k and 1080p, but this is not a blocking feature request. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by barrelltitor** [comment]
This would be a great feature to have, hope it can be reopened
