### ISSUE TITLE
See what profile/language a request was made with

### ISSUE THREAD

**Issue by Bokaii** [sct/overseerr#2757]
### Description

I have profiles for movies and language profiles for series setup to let mys users request specific language for the requested media. As it is now, I cant tell if a user has requested a series/movie in one or the other profile/language without going to Radarr/Sonarr.

### Desired Behavior

Show what profile/language profile the request was made with. I would at least like to see it in the "manage request" pane when you have clicked a request(under the cog wheel).

Preferably it should also be made visible in the requests list and in notifications when approved/available.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Right now, the ID of the quality profile used is shown on the manage request pane, so I'm assuming you want the name of the quality profile to be shown too/instead?

**Comment by Bokaii** [comment]
> Right now, the ID of the quality profile used is shown on the manage request pane, so I'm assuming you want the name of the quality profile to be shown too/instead?
> 
> Edit: also, the overrides are only shown when they differ from the default settings for the Radarr/Sonarr server

First off:
1. Yes, the name of the profile would be great to have. "Id 07" doesn't tell me much. Also, would it be possible to include this name in notifications for approved/available requests as well?

Secondly, Radarr handles language differently than Sonarr. For Radarr, there is an "original" language profile, which is great. However, if I want a dubbed version(for animated movies for my kids for example), I need to create a new Quality profile that specifically uses language "X" instead of "Original". So with Radarr, the solution mentioned in 1 works.

However, quality profile in Sonarr does not control languages, they instead use the separate "Language profile". This is not currently shown anywhere in Overseer?

2. Could we add the requested Sonarr "Language profile" to the manage request pane and notifications(same place as 1.)?
