### ISSUE TITLE
Unable to Set Up with Non-Default Plex Port

### ISSUE THREAD

**Issue by zZebrahz** [sct/overseerr#276]
**Describe the bug**
When setting up through the http://[ip]:5055/setup dialogue, I can log in with Plex to link it, however when I attempt to enter in a hostname/IP as well as a Port number, I receive an error stating Failed to connect to Plex: connect ECONNREFUSED 127.0.0.1:32400.  No matter which port I enter in the Port field before clicking save, the error always reports that it can not connect to [ip]:32400. Indicating that either the logging message is incorrect, or the custom port is not being entered when Save Changes is selected

**Are you on latest or develop branch?**
I have been able to reproduce this error on Docker  Latest and Docker Develop tags

**To Reproduce**

1. Change the plex port to a non-standard port. 
2. Start a brand new docker instance of the app
3. Navigate to the setup dialogue at http://[IP]:5055
4. Proceed through the Login with Plex Step
5. At step 2, enter the hostname/IP as well as the non-standard port.
6. Click Save Changes and proceed with the rest of setup.

**Expected behavior**
If successful, this should allow for the setup process to continue with plex at the non-standard port.

**Screenshots**
![image](https://user-images.githubusercontent.com/11633690/102136835-ccb7e480-3e0e-11eb-8fcb-b31fa6347440.png)

**Desktop (please complete the following information):**

- OS:  Windows 10 20H2, 19042.685
- Browser: Microsoft Edge 87.0.664.60 (Official build) (64-bit), Google Chrome 87.0.4280.88 (Official Build) (64-bit)

**Comment by lochstar** [comment]
Are you sure you need to use localhost/127.0.0.1 ? That would refer to the Docker container Overseerr is running in. You most likely need the host IP.

**Comment by darknessgp** [comment]
I run into the same issue. Not matter what I try to set the Port to, it always tries to use 32400.

![image](https://user-images.githubusercontent.com/1521243/102142397-f3cee000-3e27-11eb-851d-0d69766d2078.png)

**Comment by zZebrahz** [comment]
I tried with with my host IP but did not show that here for privacy concerns, I had the same issue with the IP of the host.

**Comment by darknessgp** [comment]
I've created a PR for this. Looks like it is just a bad parameter name with calling to plex-api, so plex-api is always using the default 32400.
