### ISSUE TITLE
Custom Web App URL adds server path

### ISSUE THREAD

**Issue by denis-ev** [sct/overseerr#2764]
### Description

When enabling the Web App URL and I try to press "Play on Plex" it forwards me to my domain but it keeps the server path for the plex.tv website.

Example: `https://custom.domain.com/#!/server/38ef338d96448a6e0dcd7791e54a22bf3fbt6f60/web/index.html`

it should just forward to `https://custom.domain.com/web/index.html`

### Version

1.29.1

### Steps to Reproduce

see description

### Platform

desktop

### Device

MacOS

### Operating System

12.3.1

### Browser

Firefox 100.0.1

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
It might not be needed for the homepage of your Plex server, but for linking to media on your Plex server it is afaik.

Here's the difference between when I have a web app url set in Overseerr and when I don't for the same movie:
- `https://plex.domain.com/web/index.html#!/server/<server id>/details?key=%2Flibrary%2Fmetadata%2F55577`
- `https://app.plex.tv/desktop/#!/server/<server id>/details?key=%2Flibrary%2Fmetadata%2F55577`

The only difference (the `index.html` part) is added automatically by the Plex web app, so I can't find anything that can be removed.

**Comment by denis-ev** [comment]
@danshilm 
that's interesting when I'm using my plex domain in web app url it shows up as:
 - `https://plex.evers.sh/#!/server/<server id>/web/index.html`
and plex as:
 - `https://app.plex.tv/desktop/#!/server/<server id>/details?key=%2Flibrary%2Fmetadata%2F3972`
so the part you are having with the web app url doesnt even get generated for me.
I just get a 401 Unauthorized because plex cannot find the url

I just tried it and if it would be 
`https://plex.evers.sh/web/index.html#!/server/<server id>/details?key=%2Flibrary%2Fmetadata%2F3972` 
that would work, but its not showing up like that.

**Comment by danshilm** [comment]
I think you might not have the `/web` part set in the web app URL. I get a similar 401 error when I remove that part from mine (which is set to `https://overseerr.domain.com/web`).

**Comment by denis-ev** [comment]
That's it! 
I did not set the `/web` part. 

Thanks a lot!
