### ISSUE TITLE
Pull up for page refresh on PWA

### ISSUE THREAD

**Issue by sambartik** [sct/overseerr#2785]
### Description

Hello! The mobile experience feels nice, however I am missing one thing - being able to refresh a page on a PWA. There's no refresh button as in a browser, so in order to see new data on screen the user needs to navigate to a different page and back, which is quite annoying. 

### Desired Behavior

1. Check for PWA
2. If the user pulls down to a certain threshold and let's go, refresh the current page or trigger a new data 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
You should just be able to pull to refresh like in a normal browser (works in Chrome for example).

Curious what pages you're talking about that don't show new data though, because most of the web app should show new/updated data as it comes in/is updated.

**Comment by sambartik** [comment]
> You should just be able to pull to refresh like in a normal browser (works in Chrome for example).

What I meant is when you install the PWA to mobile device (add to home screen). Does the pull to refresh work for Chrome then? Unfortunately, it does not work on iOS with Safari.

However, solving the need for refresh in the first place is a better approach. What I have noticed is that the Recent requests section on homepage does not refresh automatically, not even locally - for the user that submitted a new request. The data only gets updated when the window's focus changes back into focus (switching tabs back and forth, etc).
