### ISSUE TITLE
Ability to enter the character : when specifying the server URL

### ISSUE THREAD

**Issue by SagaXI** [sct/overseerr#2786]
### Description

Currently, when adding the informations for a Radarr or Sonarr server, the field http(s):// is pre-constructed. While this is not the safest practice, I need to enter credentials in the form of User:Password@domains.com/radarr.

However, the field is deemed unvalid as soon as I enter the character : 

### Desired Behavior

Either let the http field accept the : or set a box, or a set of boxes to enter credentials, and append them to the url of the server. Another way would eb to document how to edit those configurations VIA cli, in my case on linux.

Would eb greatly appreciated, but I have the feeling this is part of your conception, and not a design error, am I right?

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
You should be able to just use the hostname, port, and base URL without having to specify the HTTP auth username and password.

**Comment by SagaXI** [comment]
In the case of a local install of Radarr or Sonarr, yes. In the case of a remote host behind a reverse proxy, well, it depends.
