### ISSUE TITLE
Cannot login with Plex

### ISSUE THREAD

**Issue by ericm** [sct/overseerr#2788]
### Description

I can no longer sign via Plex on Firefox. Issue doesn't seem to occur on Chrome.

### Version

1.29.1

### Steps to Reproduce

1. Sign in with Plex
2. Sign in

### Screenshots

![image](https://user-images.githubusercontent.com/29894839/170772122-9e364341-0de7-4e26-a6ac-5b1f336aea51.png)

### Logs

```shell
[error][API]: Something went wrong authenticating with Plex account {"errorMessage":"Cannot read properties of null (reading 'toLowerCase')"
```

### Platform

desktop

### Device

desktop

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ericm** [comment]
Signing out of plex on the browser and signing in manually on the popup seems to resolve the issue.

**Comment by ericm** [comment]
It seems it's a problem with signing into overseerr if you're already signed into plex

**Comment by filigor94** [comment]
I got the same error, but only when I try to login as a managed user. If I use my primary user, then it signs me in without problems. Shouldn't Plex's managed users also be able to log in?

**Comment by jnanes** [comment]
I cannot signin with Plex users in 1.29.1 via mobile Safari or Chrome on iOS.

If I sign in via a Overseerr local user, the signin button flashes but does not proceed. If i reload the page, I am then signed in. I reproduced in a private tab. I also tested after clearing cache in my non-private tab, the issue persists.

**Comment by danshilm** [comment]
@ericm You have to sign-in in the pop up window, being signed in to plex.tv beforehand is not enough to access your Overseerr instance.

@filigor94 Managed users can't log in to Overseerr, you'd have to make local users for them.

@jnanes Can you reach out to us on Discord and if possible also include a video so we can take a look. The behaviour you describe does seem weird. Else, feel free to open up another issue on GitHub.
