### ISSUE TITLE
unlimited requests, but auto aprove limitation

### ISSUE THREAD

**Issue by Dodoooh** [sct/overseerr#2805]
### Description

i would like to give the users unlimited requests, but i would like to limit the auto aproves, which are put on a waiting list and are processed per day/ limit. 

### Desired Behavior

The following example: 

A user has 20 requests, but an auto aprove limit of 5 movies/day 
So every day 5 more requests would be auto approved. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by jon4hz** [comment]
This would be awesome to have!
