### ISSUE TITLE
Import all users from Plex

### ISSUE THREAD

**Issue by samwiseg0** [sct/overseerr#281]
**Is your feature request related to a problem? Please describe.**
Currently, once a user logs in then you can change their permissions. I believe a better workflow would be to import all the users and be able to set permissions ahead of time. 

**Describe the solution you'd like**
Be able to manage users before they log in. I believe a sync job to Plex to collect all the users will be needed and should be ran periodically.

**Comment by zZebrahz** [comment]
Importing the users before their initial login could also be used to allow or deny certain users to be able to use the app which would be helpful.

**Comment by XenosTechLabs** [comment]
> Be able to manage users before they log in. I believe a sync job to Plex to collect all the users will be needed and should be ran periodically.

It would be nice to automatically remove users when they leave a Plex Server as well.

**Comment by TheChrisK** [comment]
This would be a nice option. I had a friend test out the interface and he only showed up as a user after he logged in. Only then was I able to edit his profile.

**Comment by samwiseg0** [comment]
How would should re shares be handled? Meaning let's say a user is shared with the server. We remove them but now they are re shared with the server.

**Comment by samwiseg0** [comment]
> This would be a nice option. I had a friend test out the interface and he only showed up as a user after he logged in. Only then was I able to edit his profile.

This is the current workflow. I do agree this list should be all the active shared users.

**Comment by XenosTechLabs** [comment]
> How would should re shares be handled? Meaning let's say a user is shared with the server. We remove them but now they are re shared with the server.

Probably the safe bet is to disable the user instead of removing them.

**Comment by samwiseg0** [comment]
I like that idea. Same as how Tautulli handles it,

**Comment by douglasparker** [comment]
> > How would should re shares be handled? Meaning let's say a user is shared with the server. We remove them but now they are re shared with the server.
> 
> Probably the safe bet is to disable the user instead of removing them.

I agree, this is the best way to handle this.

**Comment by fenixjr** [comment]
Currently a user's permissions can not be set until they have logged in, but in addition there is only the default "request" permission enabled upon creation. Being able to alter the default would save time from individually editing each user if you know you want every user to have "auto-approve" or "vote" settings etc.

**Comment by sct** [comment]
> Currently a user's permissions can not be set until they have logged in, but in addition there is only the default "request" permission enabled upon creation. Being able to alter the default would save time from individually editing each user if you know you want every user to have "auto-approve" or "vote" settings etc.

Great idea. We can have a configurable default.

**Comment by sct** [comment]
Referencing #388 here

**Comment by doob187** [comment]
```
var plexWrapper = require("plex-wrapper");
var client = new plexWrapper.PlexAPIClient("clientId", "username", "password");
 
client.getUsers().then(result => {
    // The result contains a JSON array with all the shared library users
    console.log(result);
});
 
client.getPendingUsers().then(result => {
    // The result contains a JSON array with all the pending shared library users
    console.log(result);
});
 
client.getAllUsers().then(result => {
    // The result contains a JSON array with both shared and pending shared users (Keep in mind that the properties may vary from the 2 types of user)
    console.log(result);
})

var plexWrapper = require("plex-wrapper");
var client = new plexWrapper.PlexAPIClient("clientId", "username", "password");
 
client.removeUser("userId");
client.removePendingUser("userId");


```
