### ISSUE TITLE
Add 'failed' to filter on Requests page

### ISSUE THREAD

**Issue by matijaerceg** [sct/overseerr#2814]
### Description

Would be helpful to have one more entry in the filter dropdown on the Requests page to easily find Requests that have failed and have a 'retry' button. 

### Desired Behavior

A new entry here: 
![image](https://user-images.githubusercontent.com/4306199/173409274-5ea38274-9152-4cb3-af52-0d2413163661.png)

### Additional Context

On a server with many users and requests, it can be easy to missed failed requests that need to be retried.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by adx74** [comment]
such a great idea!
