### ISSUE TITLE
A 'Ready for Removal' tracking system like the 'Issues'

### ISSUE THREAD

**Issue by HStep20** [sct/overseerr#2822]
### Description

Itd be great if users could mark stuff as complete as a centralized system for me to know what I can clear out when It comes time to free up space. I DO NOT WANT Overseerr to do any deleting, and know that its a hard limit of the dev team ( #1924).

With the implementation of the 'issues' tracker, it seems like Overseerr aiming to be the 'centralized communication hub' of your hosted server, so naturally having a 'completed/finished' section akin to the issues tracker would be a good line of communication from user -> admin. I cant remember what someone told me they finished watching 6 months ago and was good to delete, but having a running list for when the time comes to delete things implemented as a centralized communication solution would solve that problem.

### Desired Behavior

Now, I will say this is close to a duplicate of #1948, but it should never touch files. Just like the issue tracker doesn't automatically search for a new version of a broken movie file, the 'finished/ready to delete' section should not touch my files.

Instead, just like the issue tracker, It should act as a centralized reporting station for the admin to have a running list of things that are 'safe' to delete when the time to clear space finally arises. 

The suggested workaround in the thread mentioned above is to use scripts in the [JBOPS repo](https://github.com/blacktwin/JBOPS) that are pretty close to this: [remove_watched_movies](https://github.com/blacktwin/JBOPS/blob/master/utility/remove_watched_movies.py) and [delete_watched_TV](https://github.com/blacktwin/JBOPS/blob/master/utility/delete_watched_TV.py). However, these don't take into account the human aspect of why media is requested. 

If I request a movie for movie night, finish it, and don't plan to watch it again, it's safe for deletion and I can submit a request to remove it. However, if I request Futurama, I may want to rewatch it in the background a few nights a week. I can't really use those automated scripts for deleting since I plan to use it the episodes I watch again in the future.

-----

An alternative solution could be the addition of 'types' under Issues, so I could filter issues down to 'Finished' types (as opposed to 'corrupted video' type or 'subtitle issue' type), and use it as a running list of what to purge when I need to clear stuff out and free up space.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by HStep20** [comment]
After some more thought about how to approach the 'interaction' between sonarr/radarr and Overseerr on this, it would be great if items could use the Sonarr/Radarr API to add 'tags' based on the user input here. Again, I do not ever want Overseerr removing my content, but at the same time I dread the idea of switching to overseerr, scrolling through a list of content that is 'safe' for me as the admin to remove at the request of my users, and switching back to sonarr/radarr to search and destroy. 

If Overseer was able to tag each item marked as ready for removal, then I could add a filter into sonarr/radarr to show me 'removable' items, select all, and delete them. No back and forth between apps. 

Of course, people should be able to only reqest for deletion things they have personally requested, since I dont want them tagging items others have requested, or things I have set up that I keep on my server for me to watch.

**Comment by Rustymage** [comment]
Awesome idea. I can't help at all but wanted to lend my appreciation to such a useful feature request!
