### ISSUE TITLE
Tabs in docs don't appear to work

### ISSUE THREAD

**Issue by pww217** [sct/overseerr#2823]
### Description

Looking at the installation docs, the first instance of a tab is at the docker run/docker-compose section.

Also observed in the reverse proxy section here: https://docs.overseerr.dev/extending-overseerr/reverse-proxy

I tried to click the docker-compose section on Firefox, Chrome, and Safari - the latter of which has no script or ad blocking.

### Version

Docs

### Steps to Reproduce

Go to https://docs.overseerr.dev/getting-started/installation

Click on 'docker-compose' tab, or further down the 'swizzen' tab. I'd be interested to know if this is just me, or if others can reproduce.

### Platform

desktop

### Device

Macbook Pro

### Operating System

MacOS X 12.4

### Browser

Chrome, Firefox, Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Can you check for this again? The docs website is powered by Gitbook. They've recently switched to this new version of their docs page and it was pretty buggy at the start, but this issue you're referring to might have been dealt with by now. 

I couldn't reproduce it at the time of the bug report, and still can't now unfortunately.

**Comment by pww217** [comment]
Seems they've resolved it! Thanks for looking into it!
