### ISSUE TITLE
don't hide "request more" under "request 4k"

### ISSUE THREAD

**Issue by Terebi42** [sct/overseerr#2826]
### Description

Users don't understand how to request additional seasons of existing shows, because the "request more" button is buried under the drop down of the "request 4k"

either show both buttons up front, or make "request more" the parent, and "request 4k" the child. Or put the 4k/non-4k choice into the dialog that comes up later. 

### Desired Behavior

users can more easily request seasons of existing shows

### Additional Context

Direct quote from user "X was asking about the first season of the flight attendant. Since you have the 2nd season on plex that url isn't allowing me to request it"

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by pkloehn41** [comment]
This confused me for a few months, as my structure is to maintain an HD and 4K Radarr instance for specific content to reduce the file size hit.

What confused me is if it exists in 4K, it generally showed as not available.

I've just re-built my radarr stack and will recheck it once I have the 4K instance configured again.
