### ISSUE TITLE
Make it easier to distinguish between movies and series in request list

### ISSUE THREAD

**Issue by rcdailey** [sct/overseerr#2829]
### Description

As a user, when I am viewing requests in Overseerr, I wish to be able to more easily distinguish between Movie and Series requests.

### Desired Behavior

I think a good solution would be to have the Movie & Series overlays visible in the request quick view (on the main home page) and in the Requests list page. Like below.
![image](https://user-images.githubusercontent.com/1768054/174821227-61f18365-890e-4389-9e27-ee954d6de04f.png)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by rcdailey** [comment]
Actually, in the Request list, the poster image is probably too small for this. So maybe the overlay can go here?

![image](https://user-images.githubusercontent.com/1768054/174822504-8f759d5f-7afb-4937-8b94-e4787274bfbe.png)

Just throwing ideas around. I honestly don't have a strong opinion on where it should go. I just need a clearer indication as to if this is a movie or series. Yes, I realize in some views I can see a season listing, but I do not feel this is good enough.

**Comment by hirenshah** [comment]
Interested in this Enhancement as well please :)

**Comment by vallezw** [comment]
Hey @sct could I try and solve this issue?

**Comment by sct** [comment]
> Hey @sct could I try and solve this issue?

We are looking into it but haven't found a place for it yet. So far everything we have tried has looked pretty bad.

It's something we still want to do but it's not very high priority.

**Comment by rcdailey** [comment]
This is not stale :)
