### ISSUE TITLE
Movie and TV Show Trailers

### ISSUE THREAD

**Issue by Fiala06** [sct/overseerr#283]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would love to see trailers added to the Movie and TV Show pages. 

Should make it easier to decide to add a new movie/show or not :)

**Describe alternatives you've considered**
N/A

**Additional context**
Would prefer a embedded solution rather than a link to a website.

**Comment by samwiseg0** [comment]
Please fill out the provided template.

**Comment by Fiala06** [comment]
> Please fill out the provided template.

Fixed
