### ISSUE TITLE
Snap's most recent Overseerr version is old.

### ISSUE THREAD

**Issue by swcrazyfan** [sct/overseerr#2830]
### Description

I installed Overseerr using the suggested Snap method on the website, but my install is saying it's out of date. Apparently, the snap version of Overseerr has not been updated since January.

### Version

1.28.0

### Steps to Reproduce

1. Installed using snap on Ubuntu.
2. Go to About page in Overseerr.
3. Overseerr says it's on an old version.

### Platform

desktop

### Device

Unraid VM

### Operating System

Ubuntu 20.04

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Please see the release notes: https://github.com/sct/overseerr/releases/tag/v1.29.0
