### ISSUE TITLE
Add hindi to translations

### ISSUE THREAD

**Issue by akashkj** [sct/overseerr#2832]
### Description

Add hindi to translations

### Desired Behavior

Support for hindi at https://hosted.weblate.org/projects/overseerr/#languages

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Thank you for your patience. I added Hindi to Weblate here: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/hi/
