### ISSUE TITLE
Lithuanian language support

### ISSUE THREAD

**Issue by PovilasID** [sct/overseerr#2833]
### Description

Overseerr UI in Lithuanian language

### Desired Behavior

Having an option to set Overseerr UI to Lithuanian language  (maybe pull descriptions in LT if available too )

### Additional Context

**Guidance on date formatting**

Month names

English - Lithuanian short (with the dot at the end)
January - sausis - saus.
February - vasaris - vas.
March - kovas - kov.
April - balandis - bal.
May - gegužis - geg.
June - birželis - birž.
July - liepa - liep.
August - rugpjūtis - rugp.
September - rugsėjis - rugs.
October - spalis - spal.
November - lapkritis - lapkr.
December - gruodis - gruod.

In Lithuanian language nouns have forms that change the end of the word so 'sausis' == 'sausio' == 'sausį' == 'sausyje' each word transforms differently. The two most common ways to list month names is in form I named in the way they are listed in https://www.localeplanet.com/icu/lt-LT/index.html
Regarding the date format, the most widely used short date format would be y-MM-dd and long format y 'm'. MMMM d 'd'. ('m' is short for 'metai' 'year' and 'd.' is short for 'diena' 'day'
Lithuania also uses 'military time' 18:00 

P.S. I would contribute to translation efforts too if needed

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Added to Weblate here: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/lt/
