### ISSUE TITLE
Show movies for each network

### ISSUE THREAD

**Issue by r4f4w** [sct/overseerr#2836]
### Description

Today, when you select to see content from a network, it only show series and not movies. There should be a way to be able to filter movies from each network. Maybe show in the same place with series, or maybe create a filter whitin.

### Desired Behavior

Show movies **and** series for each network.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #2668
