### ISSUE TITLE
FR : Reverse sonarr/radarr sync

### ISSUE THREAD

**Issue by Terebi42** [sct/overseerr#2837]
### Description

Sync existing monitored series in sonarr/radarr as either requested or "already monitored" as a communication method to users that they don't need to request. 

### Desired Behavior

series which are monitored in multiple instances of sonarr/radarr are marked as monitored in overseer. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Overseerr already does this; please reach out in Discord if you need support.
