### ISSUE TITLE
Library set up - can't choose Quality or Root folder until 'Test' complete

### ISSUE THREAD

**Issue by jhelmink** [sct/overseerr#284]
**Describe the bug**
Completing the new Library form will give you errors for the Quality or Root folders because a connection needs to be made to the Library server to retrieve the possible options. This means the library needs to be successfully "Tested" to make the connection before being able to select these options.
This isn't obvious to the user.

**Are you on latest or develop branch?**
Latest branch

**To Reproduce**
Add a new Library
Enter Name, Hostname, Port, API Key.
Try to set Quality or Root folder, you'll get an error.
Test the connection.
Now you can set the Quality/Root

**Expected behavior**
Automatically "Test" the server after the minimum required fields are completed, or make it a two step process.
After entering minimum fields, user should select "Next" which will do the test, if successful then show the Quality/Root options to choose.

**Comment by samwiseg0** [comment]
This is fixed in develop
