### ISSUE TITLE
Custom notifications for release dates

### ISSUE THREAD

**Issue by pavelzw** [sct/overseerr#2842]
### Description

It would be nice to have more advanced notification types like when a requested tv show/movie releases in cinema/streaming/BluRay. 

### Desired Behavior

Add more notification types in the setting that look something like this:

- Movie released in cinemas
- Movie released on streaming platforms
- Movie released as a BluRay
- TV Episode released

### Additional Context

This should be not that hard to implement since the release dates are already saved in the system.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Actually, release dates are not saved anywhere. They are fetched on demand. As such, to implement such notifications, we'd need to pull the data from TMDb for each individual item on a regular interval to check if a notification should be sent. Further complicating things, these dates vary based on the selected region/locale.

I don't really understand the use case here. Why would users want notifications of releases for already requested content? All the user cares about is when the media becomes available for them to watch on Plex, at which time they would receive a notification from Overseerr already. This availability will often coincide with the release dates, meaning that users would essentially be receiving duplicate notifications.

**Comment by TheCatLady** [comment]
Overseerr is designed to be used as a part of a stack including Radarr/Sonarr, though the *arrs are not a requirement.

You will notice that some other features (e.g., modal of TV show results to select from when there is no TVDB ID associated with a TMDb entry) also require the *arrs (the feature just described only works if there is a linked Sonarr server).

We do of course need to put some polish on the experience when things aren't fully automated, but I personally don't see us adding a notification type for this case especially given the factors in my previous comment.
