### ISSUE TITLE
Request movie or show add access to that in plex 

### ISSUE THREAD

**Issue by encor50** [sct/overseerr#2843]
### Description

Hello, 

thanks for all your works 
My question is 

I don’t share my whole library with everyone 
But when someone request a show or movie after its available i have to go to plex and grant access to watch that show 
Can this be automated ? 
When user dont have access to available show or movie can it also grant access by requesting from overseerr ? 

Thank you ! 

### Desired Behavior

Grant access to plex users to requested media 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Rustymage** [comment]
I'm curious, why can't your users see the entire library under Movies? Why do you need to grant individual movie access?

**Comment by encor50** [comment]
Okey thank you !
