### ISSUE TITLE
Add Hebrew translation

### ISSUE THREAD

**Issue by tallevi1000** [sct/overseerr#2848]
### Description

Add Hebrew translation
https://hosted.weblate.org/projects/overseerr/#languages

### Desired Behavior

Hebrew translation

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Added Hebrew to Weblate here: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/he/
