### ISSUE TITLE
Aprrove or deny a request from the notification.

### ISSUE THREAD

**Issue by ComputerComa** [sct/overseerr#2868]
### Description

I was wondering if it were possible to set up notifications to be "rich" ie:
in Telegram when a new request comes in that needs approval have a buttion that you can press to approve it and another button to deny it. 

### Desired Behavior

When a new notification comes through have buttons to approve or deny it directly from the notification.
Example in Telegram.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/68386555/180629738-54d8ce83-670f-40a3-8751-82dcf2d35ace.png">

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by hirenshah** [comment]
Is this actually done?
