### ISSUE TITLE
No data is saved in the mapped /config folder

### ISSUE THREAD

**Issue by jhelmink** [sct/overseerr#287]
**Describe the bug**
I expected to see a configuration file(s) of some sort stored in my mapped /config folder.
There are no files present. I guess this means my current Overseerr Plex/Library/Notifications configuration is stored internally in the Docker container and will not survive an upgrade.

**Are you on latest or develop branch?**
Latest branch

**To Reproduce**
Create new Overseerr Docker container with a mapped /config folder.
Browse to the mapped folder on your system.

**Expected behavior**
Any configuration settings to be stored in the mapped location, so they can be retrieved by a new container instance.

**Comment by samwiseg0** [comment]
The mapping should be `/app/config` for the container

**Comment by jhelmink** [comment]
Thanks @samwiseg0 we need to update the Docker compose docs

**Comment by jhelmink** [comment]
https://registry.hub.docker.com/r/sctx/overseerr/

**Comment by samwiseg0** [comment]
It was an error in the documentation that just has not been fixed there just yet.

**Comment by sct** [comment]
Went ahead and updated the docs there.
