### ISSUE TITLE
Auto-approval messages dont go to users

### ISSUE THREAD

**Issue by bgktmxg** [sct/overseerr#2873]
### Description

When users make a request that gets auto-approved, I get a message but they don't. I have my server setup so TV shows need to be manually approved, so users are largely used to getting some sort of alert to say the request was successful. 

When they request a movie, they receive nothing until its available. 

### Desired Behavior

I would love to see the 'Request Pending Approval' and 'Request Automatically Approved' options from the admin settings added to each users profile options.

### Additional Context

If memory serves me right they used to get these alerts. Maybe something got changed along the way that has broken the way I have mine set up?

Thanks in advance

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
This is by design and has always been the behavior.

Users are alerted to the fact that the request will automatically be approved in the request dialog, so there's no need to send a notification.
