### ISSUE TITLE
Separation between animation and anime

### ISSUE THREAD

**Issue by Mezhona** [sct/overseerr#2877]
### Description

For people who watch anime, having it mixed in the "animation", makes it so messy to locate the shows in discovery.

Would be better to have a separate category for "anime" & "animation"

### Desired Behavior

Split Anime and Animation into separate categories
Makes it easier for anime fans to find what they are looking for.

### Additional Context

got complaints from people requesting that it was difficult for them to use the discovery part because they had to sift through alot of disney/pixar stuff to find anything of value.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Genre data is from TMDb.
