### ISSUE TITLE
Use the Plex API to pre-populate the server information

### ISSUE THREAD

**Issue by samwiseg0** [sct/overseerr#289]
**Is your feature request related to a problem? Please describe.**
Plex.tv has an API call that can be made to get a list of servers a user has access to. Pulling this list would make the initial setup for users much easier since it is the same method the players use to discover the server. 

**Describe the solution you'd like**
Use the Plex API to pre-populate the Plex server information. 

Additional details can be found here. 
https://support.plex.tv/articles/206721658-using-plex-tv-resources-information-to-troubleshoot-app-connections/

**Comment by flying-sausages** [comment]
Is this not the behavior in the latest release?

**Comment by sct** [comment]
It's not. What this would be is loading all the plex servers on an account and allowing it to pre-populate the host/port settings automatically on the plex setup page.

**Comment by chriscpritchard** [comment]
I'll try and work on this!

**Comment by samwiseg0** [comment]
@chriscpritchard Would you like me to assign this to you?

Also, if we include `includeHttps=1` in the call it will return the plex.direct urls.  `https://plex.tv/api/resources?X-Plex-Token=-TOKENHERE&includeHttps=1`

**Comment by chriscpritchard** [comment]
Happy for this to be assigned to me!
