### ISSUE TITLE
Empty entry in Recently Added and this is not dissapearing after a restart of the software

### ISSUE THREAD

**Issue by NepBlanc** [sct/overseerr#2898]
### Description

There is an empty Entry in there and I suspect something more is not working correctly.

### Version

Docker V1.29.1

### Steps to Reproduce

No idea just use the software and suddenly this appeared.

### Screenshots

![chrome_2022-08-11_08-54-58](https://user-images.githubusercontent.com/9048484/184079883-0074f604-7a61-488d-af84-f5baf1018963.png)

### Logs

```shell
I could provide logs but only directly to the developer, this also applies to Database files.
I don't want any information to be publicly accesible
```

### Platform

desktop

### Device

computer, samsung galaxy s21 ultra, etc 

### Operating System

all does not matter

### Browser

Chrome, Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
There shouldn't be anything private in your logs. Please share them so we can help you.

**Comment by NepBlanc** [comment]
[overseerr-logs.zip](https://github.com/sct/overseerr/files/9308745/overseerr-logs.zip)
Here are the logs

**Comment by sct** [comment]
We aren't going to download a zip file and extract it. You could paste the logs in here using gist or something equivalent.

Either way, I believe this was an issue related to the new I Am Groot series released on Disney+. It looks like TMDb decided to switch it to a set of movies instead. I'm not sure the best course of action here to fix this yet. Give me some time to look into it.

**Comment by NepBlanc** [comment]
[overseerr-2022-08-09.log](https://github.com/sct/overseerr/files/9333288/overseerr-2022-08-09.log)
[overseerr-2022-08-10.log](https://github.com/sct/overseerr/files/9333289/overseerr-2022-08-10.log)
[overseerr-2022-08-11.log](https://github.com/sct/overseerr/files/9333290/overseerr-2022-08-11.log)

**Comment by lukepolo** [comment]
this is caused when a title has changed it's id after requested and approved and added. 

this happened to me recently , to fix it it I went and found the request and deleted the metadata.
