### ISSUE TITLE
Discovery does not filter by language

### ISSUE THREAD

**Issue by ozdeadmeat** [sct/overseerr#2900]
### Description

After turning this feature on, I seem to get more movies in foreign languages than in English

### Version

1.29.1

### Steps to Reproduce

Set Discovery language to english

### Screenshots

![image](https://user-images.githubusercontent.com/11052863/184282761-00e3564b-f859-40a5-9b21-ebede53bf8c9.png)

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This is a limitation of the TMDb api.
