### ISSUE TITLE
Automatic Dowloading?

### ISSUE THREAD

**Issue by lsultana98** [sct/overseerr#292]
I have added Radarr and the testing worked. However nothing happens after the movie has been requested. Is there something I am missing.
Other than that, the UI is amazing.

**Comment by douglasparker** [comment]
I'm actually having the same issue. The movie / tv shows are not even added to radarr / sonarr. I don't see any errors in the logs either. I'm still trying to figure out what the root cause is.

**Comment by samwiseg0** [comment]
Check for this. https://github.com/sct/overseerr/issues/282

If you are v2. Overseerr was only developed on v3

**Comment by douglasparker** [comment]
> Check for this. #282
> 
> If you are v2. Overseerr was only developed on v3

I'm using the latest version of v3 for both Sonarr and Radarr. I originally gave that post a thumbs up because I thought it was for v3.

**Comment by samwiseg0** [comment]
You will have to verify in the logs of Radarr to see what is going on. Try enabling Debug logging in radarr.

**Comment by douglasparker** [comment]
I want to add that my issue was resolved by pulling the latest dev image `docker pull sctx/overseerr:develop` and recreating the container based on that image.
