### ISSUE TITLE
Impossible to connect to Tautulli with HTTP auth

### ISSUE THREAD

**Issue by NansMM** [sct/overseerr#2929]
### Description

The input validation of the tautulli hostname prevents us from using HTTP auth.

### Version

1.29.1

### Steps to Reproduce

Go to Settings -> Plex -> Tautulli settings -> try to enter an hostname like https://xx:xx@xx.com

### Platform

desktop

### Device

Computer

### Operating System

Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
It is possible to connect with HTTP auth, but not with basic auth.

Tautulli removed the basic auth setting in v2.7.5: https://github.com/Tautulli/Tautulli/releases/tag/v2.7.5

**Comment by NansMM** [comment]
My tautulli server is hosted on my seedbox (swizzin) which uses basic auth 😅
