### ISSUE TITLE
Related/Recommended Actors

### ISSUE THREAD

**Issue by prattable** [sct/overseerr#294]
**Is your feature request related to a problem? Please describe.**
I love the way the user is kept in the Overseerr environment by being served Related/Recommended titles and cast members pages when looking at a film/TV shows page.
An example of the issue would be that if someone were to look at the Night at the Museum page in Overseer and then want to look at movies the main cast has been in, say for instance Ben Stiller, they go to that actors page and then in order to look at the next cast member's related movies they would have to go back to the Night at the Museum page.

**Describe the solution you'd like**
I would like there to be a similar category as Related/Recommended as there is for films/TV shows when looking at an Actors page in terms of other Actors that are related, in terms of Degrees of Kevin Bacon style, to that Actor. It would give the user an easier way to flow to the next desirable item.

**Comment by sct** [comment]
TMDB does not provide any information like this, so it's not currently possible.
