### ISSUE TITLE
During Library Scan a few items fail to process and a RatingKey is presented for those items

### ISSUE THREAD

**Issue by prattable** [sct/overseerr#296]
**Describe the bug**
During a Library Scan some items fail to process and a RatingKey

**Are you on latest or develop branch?**
The pull was done in the afternoon of 12-14-2020

**To Reproduce**
One such show is Archer (2009). When a Manual Library Scan is run I am presented with the following error:
[error][Plex Sync]: Failed to process plex item. ratingKey: 7958
The actual show when looked up in Overseerr is marked as Available.

**Expected behavior**
No Error

**Screenshots**
![image](https://user-images.githubusercontent.com/9043593/102173236-9444f480-3e68-11eb-8170-30a1b8304766.png)

**Desktop (please complete the following information):
**

- OS: Windows 10
- Browser: Chrome
- Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**

**Comment by samclam23** [comment]
I'm having a similar issue with movies and quite a few TV shows. The TV shows have an additional "SQLITE_CONSTRAINT: UNIQUE constraint failed" error message attached

**What version of Overseerr are you running?**
1.11.0

**Desktop (please complete the following information):**
OS: 11.1
Browser Chrome
Version 87.0.4280.88 (Official Build) (x86_64)

**Screenshot**
<img width="1438" alt="Screen Shot 2020-12-20 at 10 59 10 AM" src="https://user-images.githubusercontent.com/4596461/102721903-7afdd700-42b2-11eb-8c09-8e198521fcc0.png">

**Comment by RedSpid3r** [comment]
Also having this issue on `1.14.1`

**Comment by erwintwr2** [comment]
Encountering same issue
https://pastebin.pl/view/1aae5420
happens with close to 10% of shows in library (~280 /4500)

**Comment by sct** [comment]
> Encountering same issue
> https://pastebin.pl/view/1aae5420
> happens with close to 10% of shows in library (~280 /4500)

https://docs.overseerr.dev/support/faq#some-media-is-missing-from-overseerr-that-i-know-is-in-plex

**Comment by sct** [comment]
I think we have worked out most of the issues with the scanner at this point so I will close this issue. If you are still having problems, refer to the docs I posted above. If that still doesn't work, come talk to us on discord and we can try to figure out whats going on.
