### ISSUE TITLE
See the quality of the movie in the poster.

### ISSUE THREAD

**Issue by wilotas** [sct/overseerr#2986]
### Description

Hi,

I would like yo peopose to have anothee badge close to the "movie" one in the poster thhumn in order to difference movies quality. 

I do not know if we could have the profile selected or go deeply with the quality but it should be great in order to evaluate play capabilitiess for each item. In addition, bitrate should help as well.

Thanks for this amazing project!!!

### Desired Behavior

See the quality/bitrate in rhe poster.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
We don't store any information about your actual media files and there are currently no plans to start doing so.
