### ISSUE TITLE
SQLITE_CONSTRAINT: UNIQUE constraint failed: media.tvdbId

### ISSUE THREAD

**Issue by othyn** [sct/overseerr#3004]
### Description

When trying to add "The Great British Bake Off" I get the error:

> Something went wrong while submitting the request.

To try and gather some more information, the following appears in the network inspector as the JSON response from the backend API:

```json
{
    "message": "SQLITE_CONSTRAINT: UNIQUE constraint failed: media.tvdbId"
}
```

### Version

1.29.1 (stable) (latest)

### Steps to Reproduce

1. When trying to add "The Great British Bake Off", the url slug being `/tv/87012`, it firstly asks which TV series to link to as there are multiple results, on the popup presented when clicking 'request', it shows:

> We couldn't automatically match your request. Please select the correct match from the list below.

3. I then select the first top-left result "The Great British Bake Off" and proceed to select the seasons.
4. Upon hitting request, I get the following error message:

> Something went wrong while submitting the request.

5. To then debug further, and out of habit, I went snooping in the network inspector and confirmed the following `500` error response from the POST request to `/api/v1/request`:

Request:

```json
{
    "mediaId": 87012,
    "tvdbId": 184871,
    "mediaType": "tv",
    "is4k": false,
    "seasons": [
        6
    ],
    "serverId": 0,
    "profileId": 1,
    "rootFolder": "/data",
    "languageProfileId": 1,
    "userId": 1,
    "tags": []
}
```

Response:

```json
{
    "message": "SQLITE_CONSTRAINT: UNIQUE constraint failed: media.tvdbId"
}
```

### Screenshots

N/A

### Logs

```shell
N/A
```

### Platform

desktop

### Device

MacBook M1 Pro

### Operating System

macOS 12.5

### Browser

Firefox 104.0.1 (64 bit)

### Additional Context

Service is running as a Docker container.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by othyn** [comment]
Ah, it was partly confusion I think.

I double checked the series air date on the 

> We couldn't automatically match your request. Please select the correct match from the list below.

And selected a different series that aligned with the original show selected. Its a bit complicated as the show changed hands from BBC to Channel 4 in 2016/17 and so has two entries. The release I was selecting originally was the 2010 (BBC) original release _for_ the 2017 version of the show (Channel 4), which I'd already added as that appears as its own entity on the parent search list UI.

Once I selected the correct entry it was fine.

Although could the UX experience or error message for this scenario be improved, perhaps:

> You've already requested this version of the show.

And grey out that option, or hide it entirely, from the UI on the popup window?

**Comment by rory-brenan** [comment]
I am also having trouble with this series. It does seem to be because different metadata sources treat the 2017 switch differently.

Sonarr and Plex both treat this as a single show - I believe based on TVDB as the metadata source.

However Overseerr treats it as two separate shows (based on TMDB?). As a result the season numbers are all mismatched compared to Sonarr/Plex.

Is it possible for Overseerr to align metadata source with the connected Plex and Service(s)?
