### ISSUE TITLE
Availability confusion with 4k support configured

### ISSUE THREAD

**Issue by Codelica** [sct/overseerr#3009]
### Description

Hello,

I'm new to Overseerr -- excellent work! :)  Overall it's been working great, with the exception of some quirks (or maybe misunderstandings?) related to 4K support, availability and recently added.  While they are seperate issues, I feel like they are all related enough to 4K support be put in one issue for discussion to start.

So, starting at the beginning.  When initially setting up Overseer, you begin by giving it Plex information and then trigger a libraray scan.  At this point, no Radarr or Sonarr servers are setup, so 4K support is unknown and thus not enabled.  Because of this all media scanned is given the general "Available" status regardless if it's 4K or not.  

Then after proceeding to configure Radarr and Sonarr with both standard and 4K servers, 4K support becomes enabled.  During the next full Plex scan, any 4K media is now marked with an additional "4K Avaiable" status.

So at this point you basically have:

- All media without a 4K version marked as "Available"
- All media with a 4K version marked as "Available" AND "4K Available"

Which seems seems a little odd (vs having media marked with just one or the other), but it is consistent to start. 

But now, when you start using the system and make a 4K request for a new title, after complete, it ends up just being marked as "4K Available" rather than "Available" and "4K Availble" like all the initial 4K only media. 

I'm guessing this is purely due to that initial scan that's done before it can even know if 4K will be enabled. 

So if that's the case, that's fine, but I can't seem to find any way to completely clear the Plex/availability info to start a fresh initial scan now that it is configured?  So the system becomes sort of a mess availability-wise.

Also for some reason, once a 4K request for a new title is complete and available, the Plex "recently added" scan doesn't seem to pick it up -- although I can see the new 4K only title in Plex's recently added list.  This only happens with new completed 4K only requests.

Anyway, sorry for the rambling here, but I'd love to help get this sorted out.  I'm guessing that media should be marked *either* "Available" or "4K Available", both of which should trigger the green available check on the cover art.  And that only titles that are only marked "Available" should then have a "Upgrade to 4K" option. Does that sound like what is intended?

Any insight would be greatly appreciated. Thanks for reading!

### Version

Hotio Docker images both 1.29.1 and nightly 

### Steps to Reproduce

- Start a new Overseerr instance
- Configure it for a Plex server that has non-4K and 4K media
- Let it run the scan
- Configure Radarr and Sonarr with normal and 4K configuration

After the next Plex scan, 4k media with be both "Available" and "4K Available"

### Platform

desktop

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This will be solved when we sync availability status: https://github.com/sct/overseerr/issues/377

**Comment by Codelica** [comment]
Thanks!  I think there are few small bugs related to 4k that won't be covered by that availability sync, so I'll just add them separately.
