### ISSUE TITLE
"4K Availbable" *only* media is not given the circular green checkmark icon on cover art views

### ISSUE THREAD

**Issue by Codelica** [sct/overseerr#3010]
### Description

The circular green availability checkmark icon found on the cover art views seems to only be shown on "Available" media, and does not display on "4K Available" only media.   I'm assuming that green checkmark is to indication some version of the media is available.

### Version

1.29.1 and nightly

### Steps to Reproduce

- Add a new 4K only title to Plex
- Let a Plex scan run to pick up the media as "4K Available"
- Browse the Discover pages for the title or search it and notice it doesn't the circular green checkmark

### Screenshots

![checkmark](https://user-images.githubusercontent.com/386101/189286332-5b79f76e-86a9-43cb-ae8c-a141b9998550.jpg)
This checkmark is missing on any 4K Available only media.

### Platform

desktop

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This is by design since we never found a way to effectively show the standard and 4K status on a single cover art image. Unless someone comes up with some great UI/UX for this, it will remain this way.

**Comment by stevendarby** [comment]
Hi, personally I don't think you need to differentiate at that level. Once user can see it's available, they can go in to it and see the breakdown. 

So for example, a user browsing here has no idea that Mufasa is actually available. It doesn't appear in the Recently Added list at the top (even though recently added) and when you tap on it, it gives you the option to request. This is all heavily suggesting that Mufasa is not available, and if the user wants it they'll request it. 

However, if they simply tap into it again, they'll see it's available in 4K, which might be fine for them. If not, they'll request can request non-4K, but they're making a fully informed decision at this point. 

I would say, if the item is available _in some form_ simple mark it as available and don't present that Request option on the tile. Let them tap into it to see the full breakdown and options.

**Comment by UncleBabyBilly** [comment]
I agree this is very confusing. The main tile should show the movie as available. It shouldn't matter whether it is 4k or 1080p. That should only show up once the tile is expanded.

**Comment by stevendarby** [comment]
@sct any thoughts on the UI/UX suggestions here? Essentially, don't think there is really a problem to solve. Just mark it as available in the same way. 

My library is mostly 4K and I get requests for movies that I already have because it's not obvious I already have them. This is from users capable of playing 4K.
