### ISSUE TITLE
Newly added "4K Available" *only* media is not picked up on Plex Recently Added Scan and list in Discover

### ISSUE THREAD

**Issue by Codelica** [sct/overseerr#3011]
### Description

Any newly added 4K only media doesn't seem to get picked up by the Plex Recently Added scan, and is not shown in the Recently Added list in Discover.  Yet you can see it in Plex's recently added list.

### Version

1.29.1 and nightly

### Steps to Reproduce

- Add new 4K only media title to Plex
- Run Plex Recently Added scan
- Look for the title in the Discover Revently Added list -- not listed
- Look for the title in Plex's revently added lists - it's listed

### Platform

desktop

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
You probably don't have that library toggled on in the Plex settings for Overseerr, hence the scans not scanning that library.
