### ISSUE TITLE
Fulfilled seasons still show the show as partially available.

### ISSUE THREAD

**Issue by muddro1** [sct/overseerr#3012]
### Description

When someone requests a season of a show, the show will remain partially available in the requests. Technically the request has been fulfilled and should be shown as available with a notification being sent.

### Desired Behavior

A request should be shown as filled if a user requested a particular season and the whole show is not fulfilled. So either show the request as available, or list the show as partially available and have a separate tag showing the show as partially available and the request as filled and available. In the latter case it would move it to available under requests.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
This is a known issue. The issue is that we need to match each requested season to media season and check availability with the DB query. I was fiddling with this ages ago but didn't get it to work before I moved onto more interesting things. 😅

**Comment by TheCatLady** [comment]
Duplicate of #2565
