### ISSUE TITLE
Support for Raspberry Pi

### ISSUE THREAD

**Issue by pluusla** [sct/overseerr#302]
**Is your feature request related to a problem? Please describe.**
I would very much like to try overseerr on a raspberry pi, however the architecture is currently not supported. Error:
"standard_init_linux.go:219: exec user process caused: exec format error"

**Describe the solution you'd like**
Support for Raspberry Pi 3 + 4

**Comment by cjohnson481** [comment]
I too would like this. Have a Pi 4.

**Comment by sasagr** [comment]
me too.. thanks

**Comment by ankarhem** [comment]
Could solve this by building multi arch images.
https://github.com/docker/setup-buildx-action

**Comment by sct** [comment]
I believe @hotio is already building arm images: https://hotio.dev/containers/overseerr/

**Comment by sct** [comment]
You can now install Overseerr on a raspberry pi using our snap build. https://docs.overseerr.dev/getting-started/installation#linux
