### ISSUE TITLE
Disable NSFW content in popular/trending

### ISSUE THREAD

**Issue by kirsch33** [sct/overseerr#3021]
### Description

Lately when browsing Overseerr there has been an alarming amount of NSFW content that shows up in the trending and popular categories. For whatever reason, specifically, this happens to be Japanese adult movies (not sure if that is relevant in how to fix). 

Some of my users scroll thru these categories with their family so I would prefer to have a way to disable this content from being visible. 

### Desired Behavior

See description

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Overseerr simply returns TMDB data. NSFW content is filtered out if it is properly tagged on TMDB. If it appears, you can edit the entry on TMDB.

**Comment by kirsch33** [comment]
Okay it sounds like there is already a way to fix, and I apologize but can you be a little more specific in how I should address ?

**Comment by TheCatLady** [comment]
> Okay it sounds like there is already a way to fix, and I apologize but can you be a little more specific in how I should address ?

You can make an account on TMDB and correct the problematic entries. Note that data is cached and will take some time to reflect in Overseerr.
