### ISSUE TITLE
Filter button / Hide already existing

### ISSUE THREAD

**Issue by saschabrockel** [sct/overseerr#3025]
### Description

It would be very nice when searching for movies of an actor to have an option not to show the movies that are already there. As it is now you possibly do not see a movie/series without the green hook icon, which is easily to overlook with the design.

![image](https://user-images.githubusercontent.com/33376463/190833374-97bffd03-da83-4366-bcf1-aafd52e9b2a1.png)

### Desired Behavior

Add a button or something similiar to hide the already downloaded movies/series.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
This is already possible via the settings.
<img width="314" alt="image" src="https://user-images.githubusercontent.com/52870424/190834860-6d7a7ab3-de37-46f7-8e69-f5cb706f91cc.png">

**Comment by saschabrockel** [comment]
Nope. Its either a bug then or the functionality is not implemented for actors. Try it yourself. It works fine for trends for example but not actors.

**Comment by TheCatLady** [comment]
> Nope. Its either a bug then or the functionality is not implemented for actors. Try it yourself. It works fine for trends for example but not actors.

Hm, this would be a bug then.
