### ISSUE TITLE
[Bug] Plex Watchlist Auto Request

### ISSUE THREAD

**Issue by Gartonious** [sct/overseerr#3031]
### Description

I have noticed in order for the Plex Auto Request to work you must enable "Auto-Request Movies" and or "Auto-Request Series" for each user manually under the users General User Setting tab but also they must have permissions to Auto-Request too under the permissions tab?

Why is there two permissions you have to grant to auto request?
I would have thought as soon as you enable Auto-Request under the user permissions tab, this would then auto request things from plex but it seems you have to toggle both for this to work? Why in two places?

There is also not a global setting for "Auto-Request Movies" and or "Auto-Request Series" so you have to ensure this is enabled for each user?

### Version

1.30.0

### Steps to Reproduce

When granting auto requests via plex watchlists

### Platform

desktop

### Device

Desktop

### Operating System

Windows Server 2022

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
One is the permission allowing a user to change the setting and the other is the setting itself. Permissions only give the user the ability to decide whether they want movies/shows to be auto-requested or not.

There's no global setting for it, but you can use the bulk edit functionality on the Users page to set it for multiple users at a time (though bulk editing the permissions this way will overwrite the current users' permissions)

**Comment by sct** [comment]
This is not a bug. This is the intended behavior.

There is already an open issue for bulk editing the auto-request setting for users (#3034), but as I said in a discord thread about it, it's unlikely to come soon. You will just need to set each user manually or teach them how to do it on their own.
