### ISSUE TITLE
[Bug] Unable to view logs within Settings > Logs

### ISSUE THREAD

**Issue by Gartonious** [sct/overseerr#3032]
### Description

When trying to view the logs under Settings > Logs, I am getting a "500 - Internal Server Error" error message.

I have tried to delete all the log files under ./logs/ apart from the overseerr.log link file and restarted the app but I still get the same error? It has created a new log file when you look under the directory but it does not show on the website.

### Version

1.30.0

### Steps to Reproduce

Unable to see logs under Settings.

### Platform

desktop

### Device

Desktop

### Operating System

Windows Server 2022

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Can you get the Overseerr container's logs and put that in a [gist](https://gist.github.com/) so we can take a look?
