### ISSUE TITLE
Duplicate results on trending page

### ISSUE THREAD

**Issue by ShlomiPorush** [sct/overseerr#3040]
### Description

On the trending page there are many many duplicate results

### Version

1.30.0

### Steps to Reproduce

I just click in to trending page and you can usually immediately see duplicate results.

### Screenshots

![image](https://user-images.githubusercontent.com/5992161/191511365-5aeac803-d257-41fa-8723-316d8266381c.png)

### Platform

desktop

### Device

Desktop PC

### Operating System

Windows 10

### Browser

Chrome 105.0.5195.127

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ShlomiPorush** [comment]
The issus is also on mobile
![Screenshot_20220921-195517__01.jpg](https://user-images.githubusercontent.com/5992161/191565952-39a3708f-be55-437e-a543-a2598e2d19f1.jpg)
![Screenshot_20220921-195546__01.jpg](https://user-images.githubusercontent.com/5992161/191565978-4a48745a-27c7-4edb-931e-32462bbd32c6.jpg)

**Comment by sct** [comment]
This is due to the nature of how TMDB caches their api responses. Nothing we can really do about it.
