### ISSUE TITLE
v1.30.0 and nginx subfolder remote access issue

### ISSUE THREAD

**Issue by leifi76** [sct/overseerr#3042]
### Description

Hi, I appreciate this isn't officially supported as per your own [overseerr nginx subfolder documentation ](https://docs.overseerr.dev/extending-overseerr/reverse-proxy#nginx) so **this is more of a heads up for anyone else facing the same issue.**

After my snap package updated from v1.29.0 to v1.30.0 automatically on monday 19th Sep, neither I, nor my friends/family have been able to access overseerr remotely, with the page simply hanging after loading the login screen or the content page with the posters/art missing if the user was logged out/in respectively. Myself and a couple users tried different browsers and chrome incognito mode to no avail.

Everything appears to work as expected under localhost direct on the server itself so I assume the issue is with the nginx subfolder workaround. For now i've [reverted the update via snap](https://snapcraft.io/docs/getting-started#heading--revert) using:

`sudo snap revert overseerr
`

and all is working remotely (and locally) again (as it has done for the last few months). 

Perhaps there's someone with a little more nginx know-how who can whip up another workaround - if not, as mentioned above this was a simply "heads up".

Eventually i'll probably get round to setting up traefik, but as everything plays nice for now on an older version, that's tomorrow me's problem :)

Thanks for the software! It's awesome :

### Version

1.30.0

### Steps to Reproduce

1. sudo snap refresh (to update from 1.29.0 to 1.30.0)
2. try to access overseerr via _mysite.com/overseerr_ (nginx subfolder workaround set up as per [documentation](https://docs.overseerr.dev/extending-overseerr/reverse-proxy#nginx))
3. see that site hangs
4. access overseerr locally vis localhost:5055 
5. see that all works as expected

### Platform

smartphone

### Device

Pixel 4a 5G, Samsung S22 Ultra, Iphone 11

### Operating System

Linux Mint 20.3 Cinnamon, Android 12 / 13

### Browser

Chrome (both desktop and android), Firefox (desktop only), Safari (mobile)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
There's a workaround posted on Discord. (We should get our docs updated, I can review if someone wants to PR the changes.)
