### ISSUE TITLE
Display problem in Users 1.30.0

### ISSUE THREAD

**Issue by RedBull01** [sct/overseerr#3043]
### Description

Since 1.30.0. I try Edge and Chrome... see picture pls.
Edit: Over 10 users

[https://ibb.co/pw1Bj7k](url)

### Version

1.30.0

### Steps to Reproduce

Go to User

### Screenshots

![aaaaaaa](https://user-images.githubusercontent.com/47831034/191675238-9f25c0cb-56dd-4acc-9ef1-50c17d93ec39.png)

### Platform

desktop

### Device

No device tested

### Operating System

Windows 10, Ubuntu 

### Browser

Edge, Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This is already fixed in the develop branch and we will get a patch out to stable soon!
