### ISSUE TITLE
Stream down after movie's scan

### ISSUE THREAD

**Issue by Leemahongh** [sct/overseerr#3049]
### Description

As I scan my movie library, Plex is disable for every stream on every device/app.
=> Windows Home Theater
=> Android App
=> Plexamp for Win and Android
=> Web
It's looking for, but as a time out : "Something went wrong".

Movie's scan seems to be done (according to activity), but no addition.
"Library scan complete: Extra information may still be downloading from the Internet "

I have to restart my server.

No problem when I scan Music or TV librarys. 

### Version

1.29.0.6244.6000

### Steps to Reproduce

Go to Settings --> Plex --> Plex libraries.
Click on Movies toggle, then run manual library scan
Wait as the scan proceeds.
=> Plex can't launch anything at this time and after, on every platform.

### Platform

desktop

### Device

PC, Samsung 20

### Operating System

Windows 10, WIndows 11, Android 10

### Browser

Firefox, Chrome

### Additional Context

no problem before upgrade to 1.29.0.6244.6000

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Im confused. Is this when you scan your library in Plex? This has nothing to do with Overseerr?

**Comment by Leemahongh** [comment]
My Bad !
I opened issue at the wrong place. Please forgive me.
I'll look for the good section.
Thank for your time.
