### ISSUE TITLE
Drop-down boxes not opening in PWA

### ISSUE THREAD

**Issue by krrishsgk** [sct/overseerr#3055]
### Description

Hello, 

Just setup Overseerr and everything is working great except one thing - none of the drop downs open on the PWA. I’m unable to go through Settings, or change the quality profile on a request, or any other actions that involve a drop-down. 

### Version

1.30.0

### Steps to Reproduce

1. Open Overseerr and go to settings
2. Click on “General” intending to open the drop-down box
3. Nothing happens, except the drop-down box is highlighted 
4. Similarly, after clicking “request” on a movie, the pop up for “Request Movie” has three drop down boxes - quality profile, root folder and request as. Here the drop-down for first two don’t open, but works fine for ‘request as’

### Platform

smartphone

### Device

iPhone 

### Operating System

iOS 16.0.2

### Browser

Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
I cannot reproduce this on the same version of iOS. Try killing the app (swipe up on the app switcher) and see if the problem persists.

**Comment by ankarhem** [comment]
I got this issue today. I killed the app and it started working again.

**Comment by sct** [comment]
Strange! I still haven't been able to reproduce it myself. Likely a bug with safari, but we aren't doing anything special with our dropdowns. It's a standard HTML select element. So this isn't an issue with Overseerr, I believe? If you continue to have issues please let me know in Discord!

**Comment by krrishsgk** [comment]
No problem, thanks! Has happened a couple more times since first report, killing it and re-opening works like a charm every time.
