### ISSUE TITLE
Error checking user access: This user does not exist on the main Plex account's shared list

### ISSUE THREAD

**Issue by jonathan-bloodworth** [sct/overseerr#3057]
### Description

Hi,

Ran into this issue today when trying to login to overseerr using my plex account (fyi I am the overseerr admin and plex admin).

[error]: Error checking user access: This user does not exist on the main Plex account's shared list 
[warn][API]: Failed sign-in attempt by Plex user without access to the media server {"ip":"::ffff:192.168.32.1","email":"xxx@gmail.com","plexId":xxx,"plexUsername":"xxx"}

Luckily my phone was still logged into the site so I've been able to create a local admin user so I can still gain access however I appear to be locked out of my actual plex user's account. This account was able to login within the last week or so and I'm not aware of any major changes to plex or overseerr settings wise which may have caused this.

Any help will be much appreciated.

Thanks

### Version

1.30.0

### Steps to Reproduce

1. On the login page click "Sign In" (using a plex account)
2. Sign into plex on the popup
3. When the popup closes a red error message appears on the login page saying "Access denied."

### Screenshots

![image](https://user-images.githubusercontent.com/7051884/193236278-d2129934-c381-41c0-8ae8-43500c69fd3e.png)

### Logs

```shell
[error]: Error checking user access: This user does not exist on the main Plex account's shared list 
[warn][API]: Failed sign-in attempt by Plex user without access to the media server {"ip":"::ffff:192.168.32.1","email":"xxx@gmail.com","plexId":xxx,"plexUsername":"xxx"}
```

### Platform

desktop

### Device

All devices

### Operating System

All operating systems

### Browser

All browsers

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Some other users in discord reported this issue and seemingly resolved it by refetching their Plex server info and re-saving it in their settings.
