### ISSUE TITLE
Ratings on poster hover over.

### ISSUE THREAD

**Issue by porkie02** [sct/overseerr#306]
Would it be possible to have the rating show on hover over of a poster so I dont have to click through and back again? You probably have better things to do but t would be nice.

![example](https://user-images.githubusercontent.com/22452625/102217134-0acb0c00-3ed4-11eb-97fe-2b8e8e587833.jpg)

**Comment by sct** [comment]
We can maybe show TMDB ratings, but not any others.

**Comment by FSCorrupt** [comment]
Omdb could pull imdb as well!

Example:

![Screenshot_20210110_181304.jpg](https://user-images.githubusercontent.com/45659314/104130615-03334180-5372-11eb-9ce8-701dc6f33ae5.jpg)

**Comment by FSCorrupt** [comment]
Free Users have a 1000 Api hits limit per day...

Imdb itself publish a daily dataset of ratings for download (Free)

Description:
https://www.imdb.com/interfaces/

Datasets:
https://datasets.imdbws.com

It should be possible for you to schedule the download of the imdb rating dataset + Mapping the rating based on IMDB ID on the daily Plex Scan from Overseerr...

**Comment by sct** [comment]
> (Omdb)Free Users have a 1000 Api hits limit per day...
> 
> Imdb itself publish a daily dataset of ratings for download (Free)
> 
> Description:
> https://www.imdb.com/interfaces/
> 
> Datasets:
> https://datasets.imdbws.com
> 
> It should be possible for you to schedule the download of the imdb rating dataset + Mapping the rating based on IMDB ID on the daily Plex Scan from Overseerr...

Yeah it's possible. Just not something that is not on the radar at the moment.

And yes, while omdb provides 1000 free api hits, each user will need to register for an api key on their own. You would burn through those 1000 api keys pretty quickly as well just scrolling through our infinitely scrolling pages.

**Comment by FSCorrupt** [comment]
> Yeah it's possible. Just not something that is not on the radar at the moment.

Just wanted to inform you with the required links and info 👍  -> For maybe Future implementation

> And yes, while omdb provides 1000 free api hits, each user will need to register for an api key on their own. You would burn through those 1000 api keys pretty quickly as well just scrolling through our infinitely scrolling pages. And unless omdb is providing a batch query to get multiple titles at once, thats a separate query for ratings on anything they hover on, which could be a ton of api hits.

Right, that sucks.....

**Comment by sct** [comment]
> Just wanted to inform you with the required links and info 👍 -> Maybe for future implementation

I appreciate it!

**Comment by XYZeb** [comment]
Any chance of reopening this for future consideration please?  It would be great to have ratings on the discovery screen somehow to help with, err, discovery, and on hover would seem to be best option to keep the page looking clean.  Thanks for the awesome tool.

**Comment by r4f4w** [comment]
> Any chance of reopening this for future consideration please? It would be great to have ratings on the discovery screen somehow to help with, err, discovery, and on hover would seem to be best option to keep the page looking clean. Thanks for the awesome tool.

I agree. And for the IMDb ratings, maybe just show those inside the title details, then I think the 1000 request won't be a problem.

**Comment by fscorrupt** [comment]
another option could be, [mdblist](https://docs.mdblist.com/docs/api) :)

**Comment by rrik** [comment]
I'm interested in seeing ratings IMDB/RT on the splash page of trending media. This is a very easy quick pass filter when browsing this page and would be a great addition. Any chance this can be revisited?

**Comment by ericvlog** [comment]
it posible i also hope it have see rating just on poster for most convinent. thanks
