### ISSUE TITLE
Ability to prevent login page background image from loading to prevent login issues

### ISSUE THREAD

**Issue by jimmyhiggs337** [sct/overseerr#3061]
### Description

Overseer doesn't allow me or my users to sign in until the large background photo loads on the login page. I would like to disable this photo, or allow the user to login before this photo loads. Because my connection is slow to cloudflare, this large image loading causes my externally facing instance of overseerr to not load properly. I often have to refresh 3 to 4 times so that everything is cached before the request to load the background image makes everything else time out.

### Desired Behavior

A toggle in admin settings to disable background splash image on logon screen.

### Additional Context

If not a toggle, then maybe change the request order so that the user is allowed to sign into overseer before the large background image loads in.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
I'm not sure why your background image loading affects the ability to sign in. It shouldn't? Do you have image caching enabled? Try turning it off if you do and try again.

Either way, this isn't something we will add a toggle for. You shouldn't be spending much time on this page either way so hopefully, it doesn't trouble you too much.
