### ISSUE TITLE
Setting: Request without the modal

### ISSUE THREAD

**Issue by MikeO7** [sct/overseerr#3062]
### Description

Setting to a skip the second request button 
1. Main screen
2. See media I want to request
3. Press the request button and it adds the content using the default profile (vs opening the modal and pressing request again)

### Desired Behavior

Click request and it auto adds. No need for pressing the request button on the modal. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Unfortunately the design of our request sytem requires the modal to be present in all request situations. No plans to change this.
