### ISSUE TITLE
Sort by feature

### ISSUE THREAD

**Issue by cparello** [sct/overseerr#3063]
### Description

Can we please add a feature to sort by release date when viewing hulu, netflix, hbo max extra shows? When i open hbo i should be able to sort and see all of the most recent shows up top rather than seeing the shows I watched tens years ago at the top.

You already have all of the dates

### Desired Behavior

Add a drop down to sort by release date when lookin at a certain platforms shows like netflix hbo showtime apple

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Duplicate of https://github.com/sct/overseerr/issues/459
