### ISSUE TITLE
Failed sign0in attempt by plex user without access to media server

### ISSUE THREAD

**Issue by boivinx7** [sct/overseerr#3067]
### Description

I get this error when trying to log with my owner account, no issue on 1.28

### Version

1.30

### Steps to Reproduce

1. Sign-in (Use plex account)
2. Access Denied

### Screenshots

![2022-10-08_08h50_16](https://user-images.githubusercontent.com/30272385/194708544-815c9d3c-5334-4337-b900-a26f41b59c1c.png)

### Logs

```shell
Screenshot is a copy of the logs,
Expending the logs would give personnal information that i'm not willing to show.
```

### Platform

desktop

### Device

iPhone 12, Galaxy Tab 4, Windows 10 Computer

### Operating System

Windows 10

### Browser

Chrome. Edge

### Additional Context

Has there is no way to backup/restore i have not tried to reinstall.

My install is on Ubuntu 20.04.5 LTS
with snap install

for now i did a snap revert. and its working.
but i wanted to bring the issue to light,
Seems to be subredits with the issue too.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by kungfoome** [comment]
getting the same error. I can't login

**Comment by Huffman17** [comment]
Yes this is not working for me. The buttons actually arent even links for me over reverse proxy since 1.30.

**Comment by dakotatokad** [comment]
see #3068 - i had to reset the appdata. There may be other ways but I'm not that technical.

**Comment by espensgr** [comment]
Possible manual solution is to update the `plexid` on the user, described in the [discord support thread](https://discord.com/channels/783137440809746482/1021425099921965186)

**Comment by kungfoome** [comment]
@espensgr Thanks, thats exactly what it is. I set that and it works.

**Comment by boivinx7** [comment]
Good workaround,
`sudo sqlitebrowser /root/snap/overseerr/common/db/db.sqlite3`

**Comment by dakotatokad** [comment]
I was able to fix this issue but it appears the problem is back 24 hours later. Once again facing the same issue with a main admin account.

**Comment by espensgr** [comment]
@dakotatokad with the manuell change in db og reset of appdata?

**Comment by dakotatokad** [comment]
@espensgr this was after i reset the app data - i'm not sure I know how to access the database using Unraid's docker system/adminer

**Comment by dakotatokad** [comment]
Ok, I fixed the issue by modifying the Plex User ID in the database. For Unraid/Docker users I installed SQLiteBrowser from Community Applications. I added a path to the docker to map the container path `/mnt` to the system path `/mnt/user/appdata/overseerr/db`. I could then open the database in the SQLiteBrowser container using the WebUI and modify the Plex User ID in the table and save it back to the database. Sure enough it was NULL. Restarted Overseerr to be safe and I was able to log in with Plex OAuth.

**Comment by espensgr** [comment]
@dakotatokad yeah it seems that has been the solution from the discord.
A bit surprised that this hasn't been added as an answer in github, but just in discord.

**Comment by sgtsquiggs** [comment]
Somewhat easier fix (if you have sqlite3 available on CLI):

```
cd path/to/overseerr/db
sqlite3 db.sqlite3 "update user set plexId = '<plexid>' where id = 1;"
```

should work without having to restart overseerr. I'm making this into a cron job until it's fixed.
