### ISSUE TITLE
Access denied: This user does not exist on the main Plex account's shared list 

### ISSUE THREAD

**Issue by espensgr** [sct/overseerr#3068]
### Description

Running Overseer on docker and the user has been logged out and get Access denied.
The logs get: 
```
[error]: Error checking user access: This user does not exist on the main Plex account's shared list
[warn][API]: Failed sign-in attempt by Plex user without access to the media server {"ip":"::ffff:xxx.xx.x.x","email":"user@email.com","plexId":xx,"plexUsername":"user"}
 ```
This is the second time this has happened, but the last time was after the Plex breach, so i thought it was a one off, apparently not.
Cant login or do anything, tried restarting the containers too, nothing.
Does it exist some renew credentials from the terminal or anything like this?

Edit:
Found this #3057 but how do i "refetching their Plex server info and re-saving it in their settings"?

### Version

1.30.0

### Steps to Reproduce

Try to login with "Use your Plex account"
Get access denied.

### Platform

desktop

### Device

All

### Operating System

Mac os, ios

### Browser

Chrome, PWA safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by espensgr** [comment]
Thanks for the solution @dakotatokad, it also is a manuall solution in the [discord](https://discord.com/channels/783137440809746482/1021425099921965186) channel.
It seems to be that the user gets `null` as the `plexid` on the user, so you can manually update it in the database.
So i'm going to try that first too see if that works.

**Comment by Manfred73** [comment]
What is the best solution to fix this without doing a lot of manual stuff to fix this?
I'm also getting access denied. Logging out of plex and login again doesn't work.

**Comment by sgtsquiggs** [comment]
Is there a way to instead force setup again? I don't want to pick through configurations line-by-line. This happened to me today - was working fine until I restarted the overseerr docker container.

**Comment by dakotatokad** [comment]
The best way to avoid the resetting and editing configs is modifying the database as far as I know. I posted these in the other threat mentioned above but I'll post here too for Unraid/Docker. Other set ups should be similar though - just a question of how you access and what you use to edit the database. 

>> Ok, I fixed the issue by modifying the Plex User ID in the database. For Unraid/Docker users I installed SQLiteBrowser from Community Applications as @boivinx7 pointed to. I added a path to the container to map the container path /mnt to the system path /mnt/user/appdata/overseerr/db. I could then open the database in the SQLiteBrowser container using the WebUI and modify the Plex User ID in the table and save it back to the database. Sure enough it was NULL. Restarted Overseerr to be safe and I was able to log in with Plex OAuth.

**Comment by sgtsquiggs** [comment]
Mentioned this on the other thread (these should be merged) https://github.com/sct/overseerr/issues/3067#issuecomment-1287471347

**Comment by boivinx7** [comment]
issue came back with 1.30.1, would love for this to be fixed

**Comment by augmentedagent** [comment]
It appears to be back in 1.33.0

**Comment by exilewolf** [comment]
Can confirm I am also seeing this issue as well.

**Comment by exilewolf** [comment]
> It appears to be back in 1.33.0

Can also confirm for this version as well, saving the same issue..

**Comment by Laiteux** [comment]
> It appears to be back in 1.33.0

@augmentedagent I believe this fixed it for me: https://www.reddit.com/r/Overseerr/comments/u74hn0/comment/ijifw8v/

**Comment by adamk33n3r** [comment]
> > It appears to be back in 1.33.0
> 
> @augmentedagent I believe this fixed it for me: https://www.reddit.com/r/Overseerr/comments/u74hn0/comment/ijifw8v/

Deleting users isn't something I'd like to do. Is that part necessary?

**Comment by Laiteux** [comment]
I don't remember deleting no users (and wouldn't have wanted to either), so
I would assume not. Try until step 5 and see I guess

Le sam. 30 sept. 2023 à 20:35, Adam Keenan ***@***.***> a
écrit :
