### ISSUE TITLE
Unable to Sync Plex Watchlist

### ISSUE THREAD

**Issue by AndreAga** [sct/overseerr#3071]
### Description

Every time I try to sync the watchlist with Plex I got a **Plex.TV Metadata API** ERROR.

### Version

1.30.0

### Steps to Reproduce

1. Go to Settings
2. Click on "Process & Cache"
3. Run Now "Plex Watchlist Sync"
4. Go to "Registry" to find the error

### Screenshots

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/1497308/194933502-49aa35ef-fa30-4946-9304-cd78427db1f5.png">

### Logs

```shell
{
 "errorMessage": "Cannot read properties of undefined (reading 'find')"
}
```

### Platform

desktop

### Device

Browser

### Operating System

Windows 11

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by pvojar** [comment]
Same issue appeared recently:
**Setup:**

- Overseerr: 1.33.2
- Plex: 1.32.8.7639

**Reproduction:** Run Plex watchlist sync for Owner account throw following exception, other Plex imported users works as expected. 

**Exception:** `2024-01-17T08:25:18.498Z [error][Plex.TV Metadata API]: Failed to retrieve watchlist items{"errorMessage":"Cannot read properties of undefined (reading 'find')"}`

**Comment by panaris** [comment]
same error here
