### ISSUE TITLE
Hide available media is buggy

### ISSUE THREAD

**Issue by saschabrockel** [sct/overseerr#3082]
### Description

When hide available media is activated the media that is available is still shown on the actor view, only the green hook is missing. I'm referencing my bug https://github.com/sct/overseerr/issues/3025.

### Version

1.30.1

### Steps to Reproduce

1. Activate Hide available media
2. Go to the page of an actor (e.g. Jason Statham)
3. You see the missing green hooks even if the media is available (instead the movies should not appear there)

### Screenshots

With hide available media enabled:
![image](https://user-images.githubusercontent.com/33376463/196069590-ab2fd9f9-187b-4595-b868-ea972953c66a.png)

If I click on the respective movie:
![image](https://user-images.githubusercontent.com/33376463/196069656-d7145327-5bc9-481a-9b2f-603d501db6b6.png)

With hide available media disabled:
![image](https://user-images.githubusercontent.com/33376463/196070002-fcfe9f47-c48b-4397-b41f-fa0d5f42f95d.png)

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Ah sorry, we never updated the original issue after discussing this internally.

This is by design, since it is not desirable to hide media on people pages if you're trying to get information about the actor/actress intead of looking for requestable media.
