### ISSUE TITLE
Most Overseerr users watchlist not showing up and is unaccessable in Overseerr and returns an error 401

### ISSUE THREAD

**Issue by ascheel319** [sct/overseerr#3083]
### Description

When Overseerr runs the Plex.TV Metadata API job, most of the job comes back with a code 401 and says it is unable to retrieve watchlist items. This happens for 13 out of 18 of my users, so 5 work and the rest don't. This happens every time the job runs. As far as I can tell this has been happening for at least since 10-08-2022 as that's as far as I was able to find in the logs. This happens both when it runs automatically and also when I manually run it. 

1-2 users that it works for have a Plex pass and the other 3 do not have a Plex pass. I have tried to restart Overseerr, restart Plex, update Overseerr, and update Plex. None have helped. My Plex server is on Unraid docker version 1.29.0.6244 and I am on the official Overseerr Unraid docker version 1.30.1

### Version

1.30.1

### Steps to Reproduce

1. Let Plex.TV Metadata API run.

### Screenshots

![unknown](https://user-images.githubusercontent.com/41492233/196101718-f115fbac-1d62-4d49-9c3e-2b49ab703d83.png)

### Logs

```shell
2022-10-17T05:20:01.051Z [error][Plex.TV Metadata API]: Failed to retrieve watchlist items{"errorMessage":"Request failed with status code 401"}
```

### Platform

desktop

### Device

All devices

### Operating System

UnRaid

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Have these users logged back in since the breach? If their plex tokens are invalid, the request for their watchlist items will fail.

**Comment by ascheel319** [comment]
That does seem to have solved the issue. I totally forgot about that. Thank you

**Comment by Healzangels** [comment]
Sorry to post on a closed thread and if better to open a new post certain can!

I'm having the same issue as described above. Only certain users watchlists will connect and the rest 401 error. 

I've had a user who has content on their watchlist both log in and out of Overseerr as well as Plex and confirm the Watchlist settings are enabled but when I run a sync logs still don't show any change in which users have a 401 error. 
Unsure if I missed something. Thanks!
