### ISSUE TITLE
The retry button does nothing if request failed at some point

### ISSUE THREAD

**Issue by frodeknutsen** [sct/overseerr#3090]
### Description

Users file requests, but sometimes Radarr fails to add movies for some reason. After a while these requests ends up in a failed state with a "retry" button. When clicking Retry nothing happens. It loads for a few milliseconds but instantly goes back to Retry.

### Version

1.30.1

### Steps to Reproduce

1. Make sure a request has failed (not sure how to reproduce this)
2. Click the retry button

### Platform

desktop

### Device

Macbook Pro

### Operating System

MacOs 12.6

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by frodeknutsen** [comment]
The retry request responds with a 200 HTTP status. There is nothing happening in the error log.

**Comment by Moflows** [comment]
Having the same issues with requests being failed but the requested movie is actually requested on Radarr/Sonarr then some outright failed and not on Radarr/Sonarr. 

Some with: Failed to add movie to Radarr/Sonarr. This might happen if the movie already exists, in which case you can safely ignore this error.

And some with: Could not find any entity of type "Media" matching: { "where": { "id": 10258 } }.

Requesting/retrying some of the movies/shows again makes the cache side have some of these "missing" hits: 

The Movie Database API | Hits: 44 | Misses: 16 | Total keys: 16

Them being marked as failed and saying that it already exists on Radarr/Sonarr on FIRST ever request of said movie/show is happening, then i have to delete request like Frodeknutsen and do it again. Which will "successfully" add it as requested and/or add it to Radarr/Sonarr.

**Comment by screamjojo** [comment]
I've the same issues ...
no debug item in the logs
Version : 1.30.1 Develop

**Comment by maraouf** [comment]
Same issue
Version 1.30.1 Stable on Snap

Nothing appears in logs or in browser console

**Comment by johnistheman** [comment]
Same issue. Nothing in the logs. Tested in Chrome and Safari. Requests work if I delete them and re-create them.

**Comment by flvinny521** [comment]
Just commenting that I also experience this same issue. My user made four requests while I have taken Sonarr and Radarr offline temporarily. As a result, the request could not be passed to those applications. Upon bringing them back online, I clicked the Retry button for each of these four requests, and there is no response at all. I agree that an auto-retry after a configurable time period would be nice, or even if Overseerr could monitor the status of the services and automatically resubmit the requests upon a healthy test check.
