### ISSUE TITLE
migrate `LGTM analysis` to `CodeQL analysis`

### ISSUE THREAD

**Issue by xuatz** [sct/overseerr#3094]
### Description

I noticed that `LGTM analysis` is shutting down in Dec 2022 (pretty soon)!

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

Overseerr only needs to switch to use `CodeQL analysis`, seems like LGTM team joined GitHub and `CodeQL analysis` is the successor to it.

### Desired Behavior

Remove `LGTM analysis` and replace with `CodeQL analysis`

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Will get to this before too long. Thanks for reminding us!
