### ISSUE TITLE
[API] /request/{requestId}/available endpoint not working

### ISSUE THREAD

**Issue by ceptonit** [sct/overseerr#3097]
### Description

A post request to the `/request/{requestId}/available` endpoint doesn't seem to change the status of a request from approved to available.
The other 3 endpoints: `/request/{requestId}/pending`, `/request/{requestId}/approve` and `/request/{requestId}/decline` all work fine on the other hand.
I suspect it's because the request tries to change the wrong key:value.

At present, an approved request has the following JSON (I've only kept the relevant key/values to make this shorter):
```
{
    "id": 1,
    "status": 2,
    "type": "movie",
    "media": {
        "id": 1852,
        "mediaType": "movie",
        "status": 3
    }
}
```
While the 'pending', 'approve' and 'decline' endpoints change the first 'status' value, the 'available' endpoint actually has to change the 'status' value that's under 'media'.
The api documentation doesn't specify what the status numbers mean under the 'media' key, but after making the request available via the frontend, that value changed from '3' to '5'.
Safe to assume that '5' means 'available'.
```
{
    "id": 1,
    "status": 2,
    "type": "movie",
    "media": {
        "id": 1852,
        "mediaType": "movie",
        "status": 5
    }
}
```
From the api docu, the first 'status' key can only have 3 values: 1, 2 or 3 (pending, approved, declined).
The 'available' endpoint is probably trying to set that value to a value beyond '3', which would also explain why the first 'status' key:value is not shown in the response of the 'available' post request unlike the other 3 endpoints.

In the process, it would also be nice to document the meaning of the status values under the 'media' key in the swagger schema.

### Version

1.30.1

### Steps to Reproduce

1. Create a request
2. Approve it if auto-approve is not enabled
3. Via the API, `/request` to get the list of all the request IDs
4. Locate the request ID
5. Change the status of the request from Approved to Available: `/request/{requestId}/available`
6. Notice the 'status' key:value is not present in the response
7. Check the frontend, the request is still marked as 'Requested' instead of 'Available'

### Platform

desktop

### Device

PC

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
There is no "available" status for a request. Requests can be pending, approved, or declined only.

Media, however, can be marked available. Requests derive their availability status from the associated media.

**Comment by ceptonit** [comment]
> There is no "available" status for a request. Requests can be pending, approved, or declined only.
> 
> Media, however, can be marked available. Requests derive their availability status from the associated media.

That is not what the API doc documents:
https://api-docs.overseerr.dev/#/request/post_request__requestId___status_

You will see that it shows 4 possible status: pending, approve, decline and available

**Comment by TheCatLady** [comment]
> That is not what the API doc documents: https://api-docs.overseerr.dev/#/request/post_request__requestId___status_
> 
> You will see that it shows 4 possible status: pending, approve, decline and available

Ah, that is outdated/inaccurate. There are likely other inconsistencies as, being human, we sometimes miss or forget things. Feel free to submit a PR!

**Comment by ceptonit** [comment]
Yes I will asap.
Good thing you mentioned the `/media/{mediaId}/available` endpoint as I completely missed it in the docs and is what I was looking for :)
