### ISSUE TITLE
Allow request for all servers

### ISSUE THREAD

**Issue by quazzie** [sct/overseerr#3109]
### Description

I have two instances of radarr configured, english and swedish.
I can only request something once to one of them, then the movie is flagged and not requestable again, even though one of my radarr instances does not have that movie requested.

### Desired Behavior

I would like to be able to request something if it isn't in all radarr instances.

### Additional Context

Even if the movie is already in plex but not in all radarr instances it should be requestable to the instance that does not have it.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Overseerr doesn't keep track of where a media item is located or media languages, so this is not possible.

However, you can accomplish this with multiple Overseerr instances if you only add one Radarr instance to each and only sync the Plex library containing media for the corresponding language.

Another option is to only fetch multi-language releases or to supply subtitles when users report issues with the media.

You can see a previous discussion on this topic in our Discord server: https://discord.com/channels/783137440809746482/789002037529804833/811561591949754390
