### ISSUE TITLE
Option to default login using request account instead of plex

### ISSUE THREAD

**Issue by C8opmBM** [sct/overseerr#3110]
### Description

Due to having most of my family and friends very anti tech, I ended up giving them the plex account credentials and setting up home users for them (with pin). I've tried to teach them to create their own plex account, but failed miserably.

Now, with overseerr, the default landing login page is a big SIGN IN with your plex account.
This is fine for the first time, cause I teach them to press down on login with Request Account.
Then they forget and ask me every time why it doesnt work, or ending login with the admin.

### Desired Behavior

Can we have an option in settings to revert the actual login behaviour and have the landing login page swapped - "Use your requests account" instead of Plex account?

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
The login page will be updated in #3015 to hopefully be more straightforward for your users.
