### ISSUE TITLE
Colors of icons on top of the cards

### ISSUE THREAD

**Issue by ztjuh** [sct/overseerr#3117]
### Description

I would like to have a change in the icon of the cards when a movie/serie is requested it should be more noticeable, it has a purple icon right now, I would like to change this to orange if the movie has been requested but not downloaded, green if downloaded and no icon when not requested.

### Desired Behavior

A orange icon for a requested movie.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Pending requests are orange, while approved requests are purple.

**Comment by ztjuh** [comment]
Ahh yes, my mistake, what I meant is, the purple ones are not really
noticable so I would suggest a other color! Hope this makes more sense 😅

Op vr 11 nov. 2022 19:57 schreef TheCatLady ***@***.***>:

**Comment by ztjuh** [comment]
This is the image I meant.

![image](https://user-images.githubusercontent.com/8126179/201464525-79ae5d46-e842-4d15-a0a9-30c5960da2b3.png)

**Comment by TheCatLady** [comment]
Overseerr has purple theming throughout, so I don't know if we would change the color of this badge. It also matches the `Requested` badges elsewhere in the UI.

**Comment by ztjuh** [comment]
Alright!
