### ISSUE TITLE
Proxy Support for external addresses

### ISSUE THREAD

**Issue by aperfilyev** [sct/overseerr#3126]
### Description

Since TMDB [suspended](https://blog.themoviedb.org/the-movie-database-suspends-access-from-russia-and-belarus-b6a1a96fb35b) all Russian ip addresses, I'm unable to use overseerr without a global proxy.

### Desired Behavior

Please add an option to specify http/s proxy like sonarr/radarr do
![Screenshot 2022-11-21 at 13 38 03](https://user-images.githubusercontent.com/14963604/203029852-c3eec9d9-472c-4634-93f6-8c8414597864.png)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Closing in favour of #1907
