### ISSUE TITLE
Thr known Nginx issue in 1.31

### ISSUE THREAD

**Issue by Fhd-pro** [sct/overseerr#3127]
### Description

I'm not sure if this is need to be described as it's very known issue
The discord is full of requests regarding the issue

which has no answers or permanent solution for those who can't fix it by them self

overseerr is broken if you are using reverse proxy
The login page is unresponsive and if you already logged in nothing is responsive.

Either you have to use insecure link or do some editing to overseerr files which is not possible in my case.

Appreciate your response on this issue.

### Version

1.31

### Steps to Reproduce

Use reverse proxy with 1.31

### Screenshots

N/A

### Logs

```shell
N/A
```

### Platform

desktop

### Device

All

### Operating System

All

### Browser

All

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
I'm sorry but this doesn't tell me anything. Sounds like you need support with your reverse proxy setup. You can ask for help in our discords tech chat. 

I and many others are using Nginx reverse proxies with the latest version without any issue.
