### ISSUE TITLE
Allow user to customize quality profile 

### ISSUE THREAD

**Issue by jwmoss** [sct/overseerr#3129]
### Description

This would solve for certain users desiring a higher quality copy vs default at 720p.

### Desired Behavior

There’s a toggle that drops down with a quality profile selector. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by stephenmoore33** [comment]
Hi @jwmoss,

This is a feature that is already in existence. If you set Quality Profiles in Sonarr/Radarr and connect the services (via Settings > Services in Overseerr), you will have the options to request content is a specific quality profile. 

(see attached)

<img width="588" alt="1" src="https://user-images.githubusercontent.com/77762551/204415491-c60119cf-d829-49eb-85ef-bc7d45f5bf55.png">
<img width="900" alt="2" src="https://user-images.githubusercontent.com/77762551/204415494-49cfcdbd-8532-4b47-a365-34dcea81d912.png">

**Comment by jwmoss** [comment]
> Hi @jwmoss,
> 
> This is a feature that is already in existence. If you set Quality Profiles in Sonarr/Radarr and connect the services (via Settings > Services in Overseerr), you will have the options to request content is a specific quality profile.
> 
> (see attached)
> 
> <img alt="1" width="588" src="https://user-images.githubusercontent.com/77762551/204415491-c60119cf-d829-49eb-85ef-bc7d45f5bf55.png">
> 
> <img alt="2" width="900" src="https://user-images.githubusercontent.com/77762551/204415494-49cfcdbd-8532-4b47-a365-34dcea81d912.png">

Oh wow! Thanks for this. If the request is not available (there is no such copy of 4K) notify the user? Or should I just adjust the profile in sonarr/radarr to include lower qualities?

**Comment by stephenmoore33** [comment]
> > Hi @jwmoss,
> > This is a feature that is already in existence. If you set Quality Profiles in Sonarr/Radarr and connect the services (via Settings > Services in Overseerr), you will have the options to request content is a specific quality profile.
> > (see attached)
> > <img alt="1" width="588" src="https://user-images.githubusercontent.com/77762551/204415491-c60119cf-d829-49eb-85ef-bc7d45f5bf55.png">
> > <img alt="2" width="900" src="https://user-images.githubusercontent.com/77762551/204415494-49cfcdbd-8532-4b47-a365-34dcea81d912.png">
> 
> Oh wow! Thanks for this. If the request is not available (there is no such copy of 4K) notify the user? Or should I just adjust the profile in sonarr/radarr to include lower qualities?

Yes, that's what I do. In Radarr/Sonarr, in each quality profile you can select multiple Qualities and organize it based on most preferred to least. So if you have 4K as a top preferred option and that is not available, it will go down to the next selected choice.
