### ISSUE TITLE
Add Pushover as a notification agent

### ISSUE THREAD

**Issue by JakeShirley** [sct/overseerr#313]
Right now email notifications are sent to all admins via their Plex email.  I'd like to send them instead to my [Pushover](https://pushover.net/) email agent so they get turned into push notifications for my devices.

There is no way to currently do this unless I make a Plex account with an email address that points to my Pushover server.

**Comment by sct** [comment]
What about just having Pushover as a notification agent directly?

**Comment by JakeShirley** [comment]
> What about just having Pushover as a notification agent directly?

That'd be amazing :)

**Comment by sct** [comment]
I will rescope this Issue for that then 😁

**Comment by ankarhem** [comment]
I want this assigned to me
