### ISSUE TITLE
Parental controls / age rating restrictions

### ISSUE THREAD

**Issue by bverkron** [sct/overseerr#3130]
### Description

As a parent I like to give my kids access to discover new content and request it. However there are some movies / tv shows that have inappropriate covers. Here is an example that came up when my child was browsing the Discover section on the iPad.

![image](https://user-images.githubusercontent.com/19174503/203686621-8d1ff3fd-de67-43d0-9e77-c7cc8ab2e133.png)

### Desired Behavior

It would be helpful if, like Plex and other apps, I could limit what they can see based on rating. Plex handles it by allowing only specific age ratings / labels or excluding specific age ratings / labels. I find this system works pretty well but there are a number of other ways it could be implemented too. Ideally the restrictions would apply to all content including Discover and search results, etc.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/19174503/203686418-c6476552-f754-4ce1-a447-c0c10a53af16.png">

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by bverkron** [comment]
Still valid

**Comment by deers** [comment]
I would love to have this also...

**Comment by Andy4Shurr** [comment]
Has there been any development on this request? It is a feature I would also love to see implemented and having filters that can be persistently set in the user pane of an admin account would be a great fix for any controlled accounts.
