### ISSUE TITLE
Android TV Navigation Functionality

### ISSUE THREAD

**Issue by kaywhy1** [sct/overseerr#3133]
### Description

when attempting to view Overseerr on a browser on a Firestick, it is very cumbersome to maneuver through the page with the remote. 

### Desired Behavior

enhance the page to better handle browsing via a remote control. for example, tapping the navigational buttons up and down would move directly from 1 category to the next, rather than just scrolling the page. right and left would move from poster to poster, rather than doing nothing.

### Additional Context

 (browser tested:Brave) 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
See https://github.com/sct/overseerr/issues/2287#issuecomment-1008313891
