### ISSUE TITLE
When an item is already Available on Plex, the actor view (person) view does not report as such

### ISSUE THREAD

**Issue by stephenmoore33** [sct/overseerr#3137]
### Description

Actor view is not reflecting if the item (movie/series) is currently available on PMS. 

NOTE: I have only tested this issue with movies, and not TV series'.

### Version

1.30.1

### Steps to Reproduce

-Search the name of an actor on an item that you know is on your PMS. 
-You will find there is an option to request the item, in spite of it being already available, and errors out with 'Something went wrong while submitting the request." Additionally, does not display the green 'Available' check

### Screenshots

<img width="1918" alt="1" src="https://user-images.githubusercontent.com/77762551/204414525-ed0fdc39-53eb-4a07-b7b9-7351b6063847.png">
<img width="1918" alt="2" src="https://user-images.githubusercontent.com/77762551/204414531-7ff05d1c-924c-45d5-99b4-9e58356843f9.png">

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This is already fixed in the develop branch. It will be in the next release.
