### ISSUE TITLE
accessing web ui

### ISSUE THREAD

**Issue by brandonh2003** [sct/overseerr#314]
after setting up the docker image i went to the logs and it said it was ready on port 3000 so i did http://localhost:3000 and was hit with the unable to connect screen on firefox. i then tried http://localhost:5055 and was hit with the same screen. this screen is usually shown when i havn't started the image by accident with other apps such as sonarr or radarr. any idea why this is happening and how to fix?

I am on Windows 10 
Docker Engine v19.03.12

**Comment by samwiseg0** [comment]
You will need to use discord for support. Issues is not for support. https://discord.gg/PkCWJSeCk7

**Comment by brandonh2003** [comment]
sorry
