### ISSUE TITLE
Notification Agents - Matrix

### ISSUE THREAD

**Issue by Spider-One** [sct/overseerr#3159]
### Description

Would love to see Matrix supported.

Keep up the good work! Overseerr see's a ton of use in my house and has been working flawlessly! Currently using the Telegram notifications which work perfectly but would like to have these match with my other services on Matrix. Minor issue.

### Desired Behavior

Matrix support for notifications

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by louisgrasset** [comment]
Hey, quick question: do you prefer a single overseer matrix user to handle that job or a matrix user you create specifically for that?

**Comment by dannymate** [comment]
> Hey, quick question: do you prefer a single overseer matrix user to handle that job or a matrix user you create specifically for that?

Not sure if you still need an aswer for this. 

By the first option I'm guessing you mean a global bot that serves everyone across instances.

The second option you're saying to create a bot that either the user would input the details for or overseerr would register with a specific instance.

For me personally I'd want the second option as I host my own server and in theory others may not be running a federated instance. 

On the flip side, those people using somebody elses instance of Matrix may require a universal bot.
