### ISSUE TITLE
Movies added in non synced catogorie show up as recently added

### ISSUE THREAD

**Issue by BionicAlice** [sct/overseerr#316]
**Describe the bug**
I have my 4k content separate from my regular movies. I do not wish my users to have access to the 4k at this time. When I synced and scanned Overseerr I only selected regular Movies. 
I recently added a movie to my 4k  content. This movie is not in my regular Movies. It shows up on overseerr as recently added and that It is on plex (Technically true but I do not have overseerr syncing my 4k content)

**What version of Overseerr are you running?**
    develop-33f8831e880dc7fd3f69d951246cada5c6c0ffe7

**To Reproduce**

If you have 4k content seperated on plex. and have overseerr only looking at movie folder and not 4k.
Add a movie to 4k folder
It will show up on overseerr

**Expected behavior**
Overseerr should not be able to see the added movie from folders it does not monitor/sync

**Desktop (please complete the following information):**

- OS: Windows
- Browser Firefox
- Version [e.g. 22] 84

**Comment by sct** [comment]
This is solved in the `1.6.0` release.
