### ISSUE TITLE
Does not support capital letters in /etc/hosts host names

### ISSUE THREAD

**Issue by ShanaryS** [sct/overseerr#3160]
### Description

You can add extra hosts names to the docker container in compose by:
extra_hosts:
  - "qServer:10.10.10.100"

This gets added to the /etc/hosts in the container. But when I set the ip for radarr/sonarr/plex/etc... to qServer, it fails. If I change it to all lower case it works. However, when using the host name for the server set by my router, it does works with capital letters.

### Version

1.30.1

### Steps to Reproduce

Add extra host with capital letter in host name.

### Platform

desktop

### Device

Windows

### Operating System

Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by saltydk** [comment]
Aren't hostnames case insensitive? At least I believe that is the case on Linux.

**Comment by didyouexpectthat** [comment]
> Aren't hostnames case insensitive? At least I believe that is the case on Linux.
> 
> ```
> ~ # ping -c 1 radarr
> PING radarr (172.19.0.8) 56(84) bytes of data.
> 64 bytes from radarr (172.19.0.8): icmp_seq=1 ttl=64 time=0.045 ms
> 
> --- radarr ping statistics ---
> 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> rtt min/avg/max/mdev = 0.045/0.045/0.045/0.000 ms
> 
> ~ # ping -c 1 radarR
> PING radarr (172.19.0.8) 56(84) bytes of data.
> 64 bytes from radarr (172.19.0.8): icmp_seq=1 ttl=64 time=0.043 ms
> 
> --- radarr ping statistics ---
> 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> rtt min/avg/max/mdev = 0.043/0.043/0.043/0.000 ms
> 
> ~ # ping -c 1 rAdarr
> PING radarr (172.19.0.8) 56(84) bytes of data.
> 64 bytes from radarr (172.19.0.8): icmp_seq=1 ttl=64 time=0.029 ms
> 
> --- radarr ping statistics ---
> 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> rtt min/avg/max/mdev = 0.029/0.029/0.029/0.000 ms
> 
> ~ # ping -c 1 Radarr
> PING radarr (172.19.0.8) 56(84) bytes of data.
> 64 bytes from radarr (172.19.0.8): icmp_seq=1 ttl=64 time=0.030 ms
> 
> --- radarr ping statistics ---
> 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> rtt min/avg/max/mdev = 0.030/0.030/0.030/0.000 ms
> ```

Normally, I agree with you that hostnames are case insensitive, but the container running overseerr does not care.

```
    extra_hosts:
      - "testServer:10.10.10.10"
```
I added this to my docker-compose file.  Then I exec'd `sh` into overseerr. See below. 
```
/app # cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.10.10.10     testServer
172.16.3.2      86a6e8056cf6
/app # ping testServer
PING testServer (10.10.10.10): 56 data bytes
^C
--- testServer ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
/app # ping testserver
ping: bad address 'testserver'
/app #
```

**Comment by danshilm** [comment]
This is an issue with how Docker handles the extra hosts, and unfortunately Overseerr isn't the only application that is going to be affected by this.
