### ISSUE TITLE
Indicate that a request was made on behalf of when notification is made

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#3165]
### Description

I like that you can request on behalf of one of your users.  But I still think the notification to the user should include that fact - so that it's less of a surprise when the notification is received.

### Desired Behavior

Indicate an additional piece of text in the notification indicating that the administrator (or autofill in the username) has made this title available on your behalf.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by winbatch** [comment]
Also an optional text field to write a custom message.

**Comment by hirenshah** [comment]
Unstale

**Comment by hirenshah** [comment]
Was this completed?
