### ISSUE TITLE
I am seeing a lot of Asian titles in my recommendation feed.

### ISSUE THREAD

**Issue by gezuka77** [sct/overseerr#3166]
### Description

I am seeing a lot of Asian titles in my recommendation feed. This is a fresh install. It was not an issue earlier.

### Version

1.30.1

### Steps to Reproduce

Happens all the time.

### Platform

desktop

### Device

docker

### Operating System

linux

### Browser

all

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Recommendations come straight from TMDb. You can adjust which regions/languages to filter your discover sections in the Settings; the default is all regions & languages
