### ISSUE TITLE
Add a Discord Request Bot

### ISSUE THREAD

**Issue by FSCorrupt** [sct/overseerr#317]
For Ombi there is 'Requestrr' this is a discord bot that can request shows/movies from discord and send it to ombi, ombi then can handle those requests and forward it to sonarr/radarr.

Would be really nice to have such a feature for 'overseerr' because all my users use only discord for requesting and notifications and and and..

**Comment by samwiseg0** [comment]
There is an API for overseerr. This should be requested over at Requestrr and have them intefgrate with Overseerr.

**Comment by samwiseg0** [comment]
This request should be made at https://github.com/darkalfx/requestrr.
