### ISSUE TITLE
Plex oauth fails when using masked URL 

### ISSUE THREAD

**Issue by vertabatt** [sct/overseerr#3171]
### Description

Using masked URL with Overseerr causes login to hang after entering Plex credentials. Changing to an unmasked URL solves the issue, but does not allow a custom URL to be displayed. 

### Version

1.31.0

### Steps to Reproduce

1. Set custom domain to use masked URL when accessing Overseerr. This essentially creates a frame that displays Overseerr to display custom domain instead of IP address. 
2. Open overseer using custom domain 
3. choose login using Plex credentials 
4. Pop up allows user to enter credentials and returns to login screen
5. Overseer will not login and hangs. 

### Platform

desktop

### Device

iPhone 13 Pro, 2017 MacBook Pro

### Operating System

iOS 16.2, MacOS 13.2

### Browser

Safari, Firefox, Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
You should set up a reverse proxy if you want to use a custom URL. We likely won't support whatever you are using to mask your URLs.
