### ISSUE TITLE
Twilio Integration

### ISSUE THREAD

**Issue by FreeManFreeThinker** [sct/overseerr#3172]
### Description

Delivering notifications to non-tech-savvy users has always been almost impossible for me. I don't want my users to download another app to receive notifications or anything. Ideally, an SMS message would be perfect

### Desired Behavior

Having a way to integrate Twilio into Overseer in Settings > Notifications and users' phone numbers under User>Settings>Notifications would be an awesome way to notify users when their requests are available. A simple SMS message for notification delivery would be painless for them.

### Additional Context

Potentially adding options for notifications on the confirmation page when requesting would be a good idea as well.

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by FreeManFreeThinker** [comment]
> I'm using email. The email used for their plex accounts receives a notification when their request is fulfilled. Is this not sufficient?

Email would work but I honestly feel an sms message would be the ultimate form of notification. Twilio has a powerful api too so this would be easily implemented, I'd imagine.

**Comment by SnippetSpace** [comment]
More options is of course always better. My point was just to say we already have a global easy to implement notification system that requires no specific app.

**Comment by M91** [comment]
you could push an email as a text you could do 1234567890@txt.att.net, every carrier has there own email address for texting.

**Comment by FreeManFreeThinker** [comment]
> More options is of course always better. My point was just to say we already have a “painless” global notification system that requires no specific app.
> 
> 
> 
> 

Yeah you're totally right 👍🏻. I'm just weird 😂

**Comment by FreeManFreeThinker** [comment]
> you could push an email as a text you could do 1234567890@txt.att.net, every carrier has there own email address for texting.
> 
> 
> 
> 
> 
> T-Mobile – number@tmomail.net 
> 
> Virgin Mobile – number@vmobl.com 
> 
> AT&T – number@txt.att.net 
> 
> Sprint – number@messaging.sprintpcs.com 
> 
> Verizon – number@vtext.com 
> 
> Tracfone – number@mmst5.tracfone.com 
> 
> Ting – number@message.ting.com 
> 
> Boost Mobile – number@myboostmobile.com 
> 
> U.S. Cellular – number@email.uscc.net 
> 
> Metro PCS – number@mymetropcs.com

Good idea! I'll try that and see how it goes.

**Comment by mderubertis** [comment]
Can I suggest HTML5 notifications? If I'm not mistaken, the web app already has a service worker registered on the client.
