### ISSUE TITLE
[Feature Request] Add support for external database connections

### ISSUE THREAD

**Issue by aleksasiriski** [sct/overseerr#3176]
### Description

I'd love to be able to connect Overseerr to an external MySQL or Postgres-compatible database to allow for sharding, replication, and HA deployments. Currently Overseerr uses an internal SQLite database for request storage.

### Desired Behavior

Ideally, I'd like for there to be a set of environment variables that can be set in order to configure and use an external database connection. That way, the default (with no variables set) would be SQLite and no functionality is broken or removed for simple deployments like this. If the user so desires, they would be able to enable and configure the database, significantly expanding deployment options.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by aleksasiriski** [comment]
I guess Jellyseerr will take up the slack

**Comment by warlordattack** [comment]
very neeeded :)

**Comment by elliotcourant** [comment]
@sct glancing at the code, would this be as easy as making the config here: https://github.com/sct/overseerr/blob/0c39057ca58743697e9dcc3b678440ac3688c65a/server/datasource.ts#L5-L31

more configurable? Like allowing `postgres` to be thrown in via an env variable and allowing the other appropriate values to be propagated as well?

I see there are migrations as well, I'd be curious if those might just work with another DB. But are you aware of other places one might want to look for making this a feature?

**Comment by akgoode** [comment]
It was only slightly more complicated than that, because postgres has some different column types than sqlite or mysql.  I'm fairly certain I have this working locally but don't know this app well enough to know if everything is working yet.  I'll do some more testing and make a pr.  Hopefully later this week or next.

**Comment by aleksasiriski** [comment]
Jellyseerr already has this, Overseerr seems to be abandonware: https://github.com/Fallenbagel/jellyseerr/pull/628

**Comment by ericflix** [comment]
The issue is closed, but are the docs on how to enable postgres in overseerr? Is this in a specific branch that should used for docker?

**Comment by jahanson** [comment]
This is still a valid request despite the requesters feelings on Overseerr.

**Comment by akgoode** [comment]
> This is still a valid request despite the requesters feelings on Overseerr.

This is true, but I abandoned my dev efforts because it worked perfectly in Jellyseerr.  I just followed the instructions and I've had my jellyseerr up and running flawlessly in pgsql ever since.

**Comment by jahanson** [comment]
Am I missing something or does Jellyseerr work with Plex?

**Comment by akgoode** [comment]
> Am I missing something or does Jellyseerr work with Plex?

Jellyseerr is a fork of Overseerr and yes it works with Plex.  It also works with Jellyfin.  Also the postgres implementation was very similar to the one I was writing, but better fleshed out.  Just pull the fallenbagel/jellyseerr:preview-postgres image.

**Comment by jahanson** [comment]
Well that was my misunderstanding. I thought Plex was a either removed from Jellyseerr or treated like a third wheel. I'll have to check this out for sure. Thank you for the quick reply!

**Comment by Lebowski89** [comment]
> > Am I missing something or does Jellyseerr work with Plex?
> 
> Jellyseerr is a fork of Overseerr and yes it works with Plex. It also works with Jellyfin. Also the postgres implementation was very similar to the one I was writing, but better fleshed out. Just pull the fallenbagel/jellyseerr:preview-postgres image.

TIL Jellyseerr also covers Plex. Postgres Jellyseerr here I come.
