### ISSUE TITLE
save for later?

### ISSUE THREAD

**Issue by M91** [sct/overseerr#3178]
### Description

save for later, or don't auto approve? maybe?

### Desired Behavior

any chance we can get a save for later button? incase we don't want to download it right now but we want to come back to it another time. Guess even a request with out downloading option would work. With me being an admin all my requests are approved automatically.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Duplicate of #3173
