### ISSUE TITLE
After snap refresh to 1.31.0, overseerr won't start

### ISSUE THREAD

**Issue by jalewis** [sct/overseerr#3189]
### Description

After snap refresh to 1.31.0, overseerr fails to start. Logs attached.    This can be fixed with the following command:  apparmor_parser --add /var/lib/snapd/apparmor/profiles/snap-update-ns.overseerr

Maybe there is missing step during the upgrade?   Hope this helps someone else.

### Version

1.31.0

### Steps to Reproduce

1. update snap
2. fails with apparmor error
3. add overseer profile

### Logs

```shell
Dec 29 20:05:29 seedbox systemd[1]: Started Service for snap application overseerr.daemon.
Dec 29 20:05:29 seedbox overseerr.daemon[7038]: missing profile snap-update-ns.overseerr.
Dec 29 20:05:29 seedbox overseerr.daemon[7038]: Please make sure that the snapd.apparmor service is enabled and started
Dec 29 20:05:29 seedbox overseerr.daemon[7020]: snap-update-ns failed with code 1
Dec 29 20:05:29 seedbox systemd[1]: snap.overseerr.daemon.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 20:05:29 seedbox systemd[1]: snap.overseerr.daemon.service: Failed with result 'exit-code'.
```

### Platform

desktop

### Device

Server

### Operating System

snap

### Browser

Any

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
I am not sure why this happened to you, but I don't think this is anything we can change or fix on our end.
