### ISSUE TITLE
[Feature Request] Replacing media

### ISSUE THREAD

**Issue by buroa** [sct/overseerr#3192]
### Description

Sometimes media files have issues (bad encoding, can't play, audio out of sync, etc) and I have to manually go in Sonarr/Radarr to replace the media. I would love this to be some sort of action my users. can even do themselves in Overseerr with permissions.

### Desired Behavior

Create a new permission and flow to replace media automatically in Sonarr/Radarr.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #2682

Overseerr will never _automatically_ blacklist or redownload media. However, we may offer options in Overseerr to manually perform these tasks in the future.
