### ISSUE TITLE
Support for Prowl

### ISSUE THREAD

**Issue by PhilRumi** [sct/overseerr#3193]
### Description

please enable support for Prowl for easy integration of IOS notifications once a user requests a movie

### Desired Behavior

please enable support for Prowl for easy integration of IOS notifications once a user requests a movie

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Is there any reason pushbullet or pushover doesn't do what you need here?
