### ISSUE TITLE
"Test" function for email settings

### ISSUE THREAD

**Issue by Hobbabobba** [sct/overseerr#320]
Please add a "test" button for the email settings in notifications.

**Comment by modem7** [comment]
@Hobbabobba - how come this was closed?

I was looking at this exact functionality myself, but may have missed if it's already been implemented?

**Comment by samwiseg0** [comment]
It's already been implemented. https://github.com/sct/overseerr/commit/44a305426f3e9829c167a4a73095d0d248641f47

**Comment by modem7** [comment]
@samwiseg0 Ahhah! Thank you!
