### ISSUE TITLE
Unshared user stuck logging in

### ISSUE THREAD

**Issue by pmcnano** [sct/overseerr#322]
**Describe the bug**
If a user, which is not currently in your shared users in the plex server, tries to login to Overseerr the login screen is stuck with "Logging in..." instead of showing a friendly message.

**What version of Overseerr are you running?**
1.50

**To Reproduce**

1. Create a new plex account
2. Never invite that account to your plex server
3. Login with that account to Overseerr

**Expected behavior**
Receive a friendly error message. Something along the lines of "You do not have access to this Plex server".

**Screenshots**
![Image 2020-12-15 at 2 21 42 PM](https://user-images.githubusercontent.com/12994799/102268389-e0cc1680-3ee0-11eb-8390-b86b2317174c.png)

**Comment by JohnnyGrey86** [comment]
I encountered this as well using a dummy account yesterday. I agree with pmcnano's expected behavior.
