### ISSUE TITLE
Make MPAA rating visible on discover summary card

### ISSUE THREAD

**Issue by i-am-at0m** [sct/overseerr#3230]
### Description

I would like to be able to see the MPAA rating (or whatever rating is available) in the summary card alongside budget etc when adding or viewing an item

### Desired Behavior

I would like to be able to see the MPAA rating (or whatever rating is available) in the summary card alongside budget etc when adding or viewing an item

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This is already viewable under the title of the movie/series.

**Comment by i-am-at0m** [comment]
So it is. Then I'm blind, feel free to delete this then.
