### ISSUE TITLE
Allow 1 instance of radarr/sonarr to handle both regular and 4k requests

### ISSUE THREAD

**Issue by Brandoskey** [sct/overseerr#3231]
### Description

This may actually be a bug, but I assume it's not.

It would be nice to be able to properly use a single instance of radarr or sonarr for both regular and 4k requests. I am able to add the same instance twice and add NEW 4k requests, however any existing media does not get updated to my 4k profile nor does it cause radarr to begin a search.

I know people are of the belief that the only proper way to do this is with multiple instances of radarr, however I don't quite understand the need for that limitation. That's what profiles are for.

### Desired Behavior

I see this working in a couple ways:

1. Either as is where you add a second radarr instance to overseerr but this time using your 4k profile as the default

2. and/or allow once radarr instance in the overseer interface to handle both 4k and regular by adding a 4k profile option under settings

### Additional Context

I know people are of the belief that the only proper way to do this is with multiple instances of radarr, however I don't quite understand the need for that limitation. That's what profiles are for and I've never felt limited by using profiles alone

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
This is not possible, as each instance of the *arrs can only manage one copy of media.

If you only maintain one copy of media, then you should modify the profiles at request time rather than using Overseerr's 4K support. See: https://docs.overseerr.dev/using-overseerr/settings#services

**Comment by Brandoskey** [comment]
Understandable for those who want multiple copies, however I would assume others beside myself only care to have a single copy. I'm fine with a few people transcoding from time to time.

I guess, the feature I'm looking for is to allow users to request a movie be upgraded to 4k. Adding a new movie in 4k already works in the current version as I reported above.

Maybe a check box under the radarr/sonarr settings for "Allow request to upgrade to 4k" with a drop down for your desired 4k profile would be useful?

I suppose its entirely possible I'm the only person in the world that wants this so it's not worth worrying about

**Comment by Brandoskey** [comment]
I'd like to have this request re-opened and considered for a future release

Radarr v5 will support multiple files per movie which will hopefully eliminate the need to run multiple instances just for 4k/HD

It would be nice if overseerr supported this as an option
