### ISSUE TITLE
Feature Request - Switch Default Sign-In Method / Link to Overseer Login

### ISSUE THREAD

**Issue by some-guy-23** [sct/overseerr#3236]
### Description

This is kind of a two-part feature, for less tech-savvy users who might get confused by multiple sign-in methods (Plex vs Overseer).

First problem would be, when you have most of your users sign-in with Overseer instead of Plex, would be good to have the option to default to opening the "sign in with Overseer" portion of the login UI.

Same could be done for cases where you create a local user, and the invite email is sent, Would be nice to have it where the link they click would by default open the "sign in with Overseer" portion of login.

### Desired Behavior

Both could be solved by having a new route / URL on the Login page. When "login with Overseer" is clicked, URL could be updated to "/login/overseer" or something similar.

At this point, you could use the link to send to users manually who should login with a local user, and it could also be used for the automatic user invite emails.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
We will change the login in #3015 to show the local/plex login form alongside each other without an extra click. It should be clearer for your users.

**Comment by some-guy-23** [comment]
@sct that sounds perfect, thank you!
