### ISSUE TITLE
Discover search with spaces returns no results

### ISSUE THREAD

**Issue by EmptyVisual** [sct/overseerr#3237]
### Description

Using discover and searching with a space included in the name returns no results. Issue commit #3232 

### Version

c2a1a20a3bb20039a1936c7fe0ecb9e8311a0aea

### Steps to Reproduce

1. Select Discover
2. Search 'Harry'
3. Observe Harry Potter results as an example
4. Search 'Harry Potter'
5. Observe no results returned.

### Screenshots

No space
![image](https://user-images.githubusercontent.com/4710051/212367312-68555ee5-ce3a-4b9a-9024-a0afec5df2d3.png)

With space
![image](https://user-images.githubusercontent.com/4710051/212367365-4082f1b3-f416-4e9d-9bf2-861be10a0a46.png)

### Platform

desktop

### Device

Desktop PC

### Operating System

Host: Docker / Client: Linux

### Browser

Brave, Chromium, Firefox

### Additional Context

Currently running docker container image: sctx/overseerr:develop

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by phutur1st** [comment]
Looks like it is is using %2520 instead of %20 for the space in search string. %20 returns the results.
