### ISSUE TITLE
Ability to fetch new token for Plex.tv auth in Plex settings

### ISSUE THREAD

**Issue by samip5** [sct/overseerr#3245]
### Description

I'm really annoyed when I cannot update the Plex Auth token Overseerr uses.

### Desired Behavior

I would like the possibility to click a button like on Tautulli, that would fetch a new token from Plex.tv as it might not always be valid and there doesn't seem to be a way to change it.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
At the moment, you can log in and out to refresh your token. In #3015 you will be able to click a button to refresh your token similar to Tautulli.
