### ISSUE TITLE
Ability to add notes to users and / or splash page

### ISSUE THREAD

**Issue by shushry** [sct/overseerr#3246]
### Description

Similar applications to this one (ombi?) often had the ability to customize some content on the login page and/or the main dashboard.   This was useful when you wanted to have a little FAQ or custom instructions / notes to your users.  

### Desired Behavior

Settings page where I can add html content to appear either on the login page or the top of the dashboard.  Possibly even just a menu section?

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Minituff** [comment]
I like this idea. It seems similar to the request I just submitted: https://github.com/sct/overseerr/issues/3262

**Comment by danshilm** [comment]
Closing as a duplicate of #3138
