### ISSUE TITLE
Not explicitly clear that it's OK to "Continue" after initiating a Manual Scan during setup

### ISSUE THREAD

**Issue by chazlarson** [sct/overseerr#325]
**Describe the bug**
When going through initial setup, it's suggested that a manual scan be initiated.  However, it is not explicitly stated that it's safe to continue the setup.

**What version of Overseerr are you running?**
1.5.0

**To Reproduce**

Go through Plex Server setup.
Initiate manual scan.
Wonder if clicking the active "Continue" cutton will cancel that scan or leave it in an indeterminate state.

**Expected behavior**
I'd expect an explicit not that continuing is fine, rather than letting the user blindly assume that an enabled button is safe to press.

**Desktop (please complete the following information):**

OS X, MS Edge

**Comment by sct** [comment]
Good point. I will add a message to make this clear.

**Comment by sct** [comment]
![image](https://user-images.githubusercontent.com/234213/102296809-7c1cc480-3f91-11eb-8c6e-203e753b1106.png)

How's this look?

**Comment by chazlarson** [comment]
Perfect.

**Comment by sct** [comment]
Great. I will get this committed then!
