### ISSUE TITLE
Localization not indexed

### ISSUE THREAD

**Issue by IshanJ25** [sct/overseerr#3252]
### Description

Hindi language is not indexed in the translation status list here (at the time of creating this issue):

<a href="https://hosted.weblate.org/engage/overseerr/"><img src="https://hosted.weblate.org/widgets/overseerr/-/overseerr-frontend/multi-auto.svg" alt="Translation status" /></a>

However, the language is visible in the linked dashboard:

![image](https://user-images.githubusercontent.com/86649457/212892672-9be153fc-4451-4ec3-ba11-f6600b11b0c6.png)

### Desired Behavior

I would like to contribute to Overseerr by adding translations for this language, and am looking for procedure. How can I contribute?

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by gaurang7goel** [comment]
Hi, I would like to contribute to Overseerr by adding translations for this language, and am looking for procedure. 
How can I contribute? Also I am kinda beginner so could you help if I need.

**Comment by gaurang7goel** [comment]
As I understand in weblate there are 1222 words for which I have to provide Hindi translation. Am I correct?

**Comment by IshanJ25** [comment]
Alright I figured it out.

I also added translations for about 60 words, more coming up.

@sct Could you please acknowledge if this is the correct method?
