### ISSUE TITLE
Ability to change default 5055 port in docker

### ISSUE THREAD

**Issue by capsel22** [sct/overseerr#3253]
### Description

If there is one thing missing for me is the ability to select your own web ui port. The docker container only listens on 5055 and there is no way to change it.

### Desired Behavior

ability to pass environment command e.g. WEB_PORT or HTTP_PORT using docker cli or compose with custom port for web gui to listen on.

  Overseer:
    image: overseer
    ports:
      - (customport):(customport)
    environment:
     - HTTP_PORT=(customport)

   

### Additional Context

This would be most useful in environments where using nginx-proxy where it relies on native listening port of a container to hand-over traffic.
Or when using VPN port forwarding with VPN container such as Gluetun, where all traffic is directed via vpn container using network_mode: service:gluetun. With this network mode you cannot expose or map host port, it relies on native port that the container is listening on which the WEB_GUI or HTTP_PORT would solve.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Already possible by using the `PORT` environment variable, it's just not in the documentation. Will submit a PR shortly.

**Comment by capsel22** [comment]
> Already possible by using the `PORT` environment variable, it's just not in the documentation. Will submit a PR shortly.

oh wow! Apologies, I am yet to get used to how to use Github, is this change already in production of :latest release?

I'm guessing it will be like this in compose?
Overseer:
image: overseer
ports:
- (customport):(customport)
environment:
- PORT=(customport)

**Comment by danshilm** [comment]
Yep, it's just that it wasn't mentioned in the documentation.

if you are using a `docker-compose.yml` file, here's an example
```yaml
service:
  overseerr:
    image: ghcr.io/sct/overseerr
    environment:
      - PORT=(CUSTOM_PORT)
    ports:
      - 6000:(CUSTOM_PORT)
```

Also, you can have text be formatted as code by putting it between 3 backticks `
Like so:

> \```
>   \# code here
> \```
>

**Comment by capsel22** [comment]
> Yep, it's just that it wasn't mentioned in the documentation.
> 
> if you are using a `docker-compose.yml` file, here's an example
> 
> ```yaml
> service:
>   overseerr:
>     image: ghcr.io/sct/overseerr
>     environment:
>       - PORT=(CUSTOM_PORT)
>     ports:
>       - 6000:(CUSTOM_PORT)
> ```
> 
> Also, you can have text be formatted as code by putting it between 3 backticks ` Like so:
> 
> > ```
> > # code here
> > ```

Most helpful. Thank you.
