### ISSUE TITLE
Feature for addiontal Radarr/Sonarr like 4K but for English requests

### ISSUE THREAD

**Issue by Joshua1337** [sct/overseerr#3256]
### Description

Hello, 

currently i have the problem, that i only can have my german radarr/sonarr setup and my 4K german radarr/sonarr setup for requests in overseerr. It would be perfect to have a option to set an additional radarr/sonarr for EN content requests. Like the 4K requests. I know you can override an Request to the EN Sonarr but its not possible to have 3 Requests on all 3 Sonarrs. 

### Desired Behavior

Requests for English Content like 4K with addiontal Radarr/Sonarr in place. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #2281
