### ISSUE TITLE
Rotten Tomatoes API 404 error

### ISSUE THREAD

**Issue by pingcheunglai** [sct/overseerr#3261]
### Description

Overseerr stopped showing Rotten Tomatoes ratings when I click into a movie. The logs show an API error with the description "Something went wrong retrieving movie ratings":

`{
 "errorMessage": "[RT API] Failed to retrieve movie ratings: Request failed with status code 404",
 "movieId": "913820"
}`

This is an issue that appears to be isolated to Overseerr on my system. Other Docker containers are able to pull Rotten Tomatoes ratings with no issue.

### Version

1.31.0

### Steps to Reproduce

N/A - appears to be an API issue

### Logs

```shell
{
 "errorMessage": "[RT API] Failed to retrieve movie ratings: Request failed with status code 404",
 "movieId": "913820"
}
```

### Platform

desktop

### Device

Intel NUC

### Operating System

Docker

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Fixed in latest develop #3179. Will be added to next release.
