### ISSUE TITLE
Users not getting tagged on Discord for issue responses/closure

### ISSUE THREAD

**Issue by BigJazzz** [sct/overseerr#3266]
### Description

When replying to or closing an issue, the Discord post isn't tagging the user who raised the issue.

### Version

1.31.0

### Steps to Reproduce

1. Set up Discord bot
2. Have user open issue
3. Reply/close as admin
4. Check post to Discord, note no tag

### Screenshots

<img width="401" alt="image" src="https://user-images.githubusercontent.com/2503113/214017902-faa15d0f-6e42-450d-9964-abe1ae81b9ea.png">

### Platform

desktop

### Device

MacBook Pro

### Operating System

macOS Ventura 13.2

### Browser

Edge, Opera

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by BigJazzz** [comment]
@TheCatLady so I've just noticed that there's no tags at all now. O.o I've upgraded to 1.32.5 just now, and the screenshot is from before (first Available post) and after upgrading and deleting the data for the show (Request and second Available post). I re-requested as the user, then scanned my Plex library to generate the second ping.

I've disabled and reenabled Mentions in the Discord settings, as well as confirmed the Discord ID is available in the User's settings.

Additionally, should there be tags on any post, or just Available? Because it's never tagged for Requested or Approved requests either. (Happy to open another bug report for this).

![image](https://user-images.githubusercontent.com/2503113/216014310-6466cd93-6648-4f09-82b8-fb59be066a1b.png)

**Comment by sct** [comment]
The latest release didn't touch any of the code related to notifying users besides issues. Are you sure each user also has each notification type enabled under their discord ID?

**Comment by BigJazzz** [comment]
@sct Thanks for the reminder. They were working as late as 21 hours ago, then suddenly nothing. I just checked the last user to get tagged, and their permissions have been turned off. I'm not sure how or why, but there we have it. I'm going through now and reconfiguring all of this. I'm going to chalk this up to a glitch in the Matrix.
