### ISSUE TITLE
Latest Version is not available on snapcraft.

### ISSUE THREAD

**Issue by ShadowThePatriot** [sct/overseerr#3281]
### Description

Currently, the latest version of Overseerr available is not up to date. The latest version available on the stable snap branch is v1.31.0

### Version

v1.32.1

### Steps to Reproduce

1. Go to https://snapcraft.io/overseerr
2. Check the latest available version for amd64 under the latest/stable branch.

### Screenshots

![Screenshot 2023-01-26 150623](https://user-images.githubusercontent.com/33302451/214950499-719a8cc7-d13b-4a10-8eac-3dd7f5ad8fb4.png)

### Platform

desktop

### Device

N/A

### Operating System

N/A

### Browser

Mozilla Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by D3ezy** [comment]
I'm seeing the same thing. When I run `snap refresh` it says "All snaps up to date." and the last update for overseerr was 2022-12-17. How soon after a release does snap get updated?

**Comment by danshilm** [comment]
The builds for the latest snap failed to publish because of a change upstream (the snaps successfully built, they just weren't published to snapcraft). I made a pull request to fix it already, just gotta wait for someone to review it.
