### ISSUE TITLE
Show full release name in Manage Movie

### ISSUE THREAD

**Issue by costaht** [sct/overseerr#3286]
### Description

Would it be possible to show the full release name when hovering the mouse over the release name like shown bellow?

![Screenshot from 2023-01-26 22-00-59](https://user-images.githubusercontent.com/50637431/215001007-d7a17b00-a983-466c-babe-29566caed11e.png)

My suggestion is a floating text like the one shown here:
![Screenshot from 2023-01-26 21-59-52](https://user-images.githubusercontent.com/50637431/215000863-f95aa5e9-078c-4a71-8e5f-7a2802140799.png)

Thank you

### Desired Behavior

When hovering the mouse over the release name Overseerr will show the full release name.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Definitely something that can be added.
