### ISSUE TITLE
Air date

### ISSUE THREAD

**Issue by mrwestside12** [sct/overseerr#3289]
### Description

I notice that every TV show shows air date the day before they come out? 

### Version

1.32.2

### Steps to Reproduce

Look at the air date of a tv show

### Platform

desktop

### Device

Docker

### Operating System

Docker

### Browser

Any

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
You are going to have to give us more info than this. What exactly is wrong?

**Comment by mrwestside12** [comment]
<img width="1440" alt="Screenshot 2023-01-27 at 10 48 23 AM" src="https://user-images.githubusercontent.com/97942502/215128611-5dbb5915-7a99-4bc8-b213-8a75c6974765.png">

The date shows tomorrow but it don't come out till Sunday?

**Comment by sct** [comment]
This data is sourced directly from TMDB. We also display the time relevant to your local timezone on your machine. If the data is wrong, then TMDB needs to be fixed. Not a problem with Overseerr.

**Comment by mrwestside12** [comment]
Idk I have my timezone correct on my Overseerr America/New_York. TMBD shows the date on the website correct.

**Comment by mrwestside12** [comment]
![Uploading Screenshot 2023-01-27 at 11.13.20 AM.png…]()
![Uploading Screenshot 2023-01-27 at 11.13.20 AM.png…]()
![Uploading Screenshot 2023-01-27 at 11.13.20 AM.png…]()
![Uploading Screenshot 2023-01-27 at 11.13.20 AM.png…]()

**Comment by mrwestside12** [comment]
Can't post screenshot for some reason

**Comment by ionyx0** [comment]
I am noticing this as well.

The Last of Us - Ep. 3 on my Overseerr:
![image](https://user-images.githubusercontent.com/17012367/215291056-f4a20028-35f3-4886-98ab-419c21d2331c.png)

The Last of Us - Ep. 3 on TMDB:
![image](https://user-images.githubusercontent.com/17012367/215291112-dc67d483-2c8d-4890-957c-45b99c279aaf.png)

Can pull logs, if needed.
