### ISSUE TITLE
Add Multiple Plex/Emby/Jellyfin

### ISSUE THREAD

**Issue by chazlarson** [sct/overseerr#330]
I have more than one Plex server.  One is content I manage myself via Sonarr/Radarr, the other is basically read-only from a group of colleagues.  I'd like to be able to use Overseerr to provide unified search across the two servers, as Overseerr is addressing my one issue with Requestrr, which is that it doesn't search Plex to find this sort of thing.

I'd like the ability to add multiple Plex servers the way we can currently add multiple Radarr/Sonarr.  This would allow users to search for Movie X and find it in either Plex A or Plex B, or request it if not on either.

There isn't really a direct alternative aside from the Plex built-in search, which doesn't tie into requests.  I suppose if I assume that Plex B is a superset of Plex A, I could link **Plex B** to Overseerr.  Requests would go to Radarr, which would add it to Plex A, so eventually that user would see Movie X.

**Comment by RobinMol** [comment]
First off all thanks for this nice piece of software!

I have 2 Plex server setup at the moment.

One for 1080p content, video transcoding allowed.
The second for 4k content, video transcoding not allowed.

With above enchantment, will it be possible to manage this setup with 1 overseerr instance?

**Comment by sct** [comment]
> First off all thanks for this nice piece of software!
> 
> I have 2 Plex server setup at the moment.
> 
> One for 1080p content, video transcoding allowed.
> The second for 4k content, video transcoding not allowed.
> 
> With above enhancement, will it be possible to manage this setup with 1 overseerr instance?

It's not possible and there are no plans to support more than one Plex server. Have you considered using a single Plex server and a Tautulli script to prevent transcodes on 4k content? see: https://dailysysadmin.com/KB/Article/2894/stop-or-disable-plex-from-transcoding-4k-content-using-tautulli-scripts/

A few people on the discord are doing that. Seems to work for them!

**Comment by RobinMol** [comment]
hey sct, thank you for your quick reply, this seems like a good idea, thanks for this tip!!

**Comment by TheCatLady** [comment]
There are no plans for supporting more than one Plex server.  Please see @sct's response here: https://github.com/sct/overseerr/issues/1094#issuecomment-791154047
