### ISSUE TITLE
Movie/Series not found (Error 500)

### ISSUE THREAD

**Issue by dominikheiss** [sct/overseerr#3312]
### Description

Hey guys,

I'm using the "latest" docker version and never had a problem.
Today I saw this problem:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/70059992/216443335-61a552f7-cefc-438f-8627-4fe6b6e5e591.png">
<img width="899" alt="image" src="https://user-images.githubusercontent.com/70059992/216443395-7d6d0662-9ffc-4d1d-b71c-53252ea123c4.png">

Do you know what I can do or is my DB dead?

Regards
Dominik

### Version

1.32.5 Stable

### Steps to Reproduce

Dashboard

### Logs

Warning: data for page "/" is 195 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.

### Platform

desktop

### Device

Laptop

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Korni22** [comment]
@dominikheiss I am running into the same issue, how did you solve the problem?

**Comment by gnogeek** [comment]
Running same issue also, @dominikheiss can you help us?
