### ISSUE TITLE
Please add LDAP and SSO

### ISSUE THREAD

**Issue by jeryd** [sct/overseerr#332]
**Is your feature request related to a problem? Please describe.**
My users use LDAP and SSO to log into web services. I cant do this with overseerr

**Describe the solution you'd like**
I would like the option to use LDAP and SSO to log in.

**Describe alternatives you've considered**
OMBI

**Comment by ibracorp** [comment]
Would also love this feature. Came to request it and found this one here. We would like not be at Plex's whim with our accounts.

**Comment by shocker2** [comment]
Since now there is support for local users, LDAP integration will make sense. By this also Emby will be supported and this might be a quick win :)

**Comment by ankarhem** [comment]
How is this supposed to work? Validate the login and then create the user if it doesn't exist with default permissions?
