### ISSUE TITLE
Allow OR filter in Genres

### ISSUE THREAD

**Issue by VorlonCD** [sct/overseerr#3321]
### Description

When I pick multiple genres in filters, it does an AND search.   I would like the ability do to an OR search.    I'm on version 1.32.5

### Desired Behavior

Currently if you search on Comedy and Western it only shows items that are tagged with both.

If you could say "Comedy OR Western" or "Comedy | Western" it would be great! 

Just say no to Romance and Music :)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by unlucio** [comment]
Indeed, how was it `AND` in the 1st place? What's the rational behind it?
it just empties the search results:

https://user-images.githubusercontent.com/778799/218332942-85e4c248-b06c-40fd-accc-f7ab6c35a144.mp4

Let the user decide what they want to do, always the best choice.
