### ISSUE TITLE
Deleted titles are STILL stuck on “Available”; doesn’t detect deletions

### ISSUE THREAD

**Issue by DanAykroyd256** [sct/overseerr#3324]
### Description

Is there any update on [Deleted titles are stuck on "Available" #377](https://github.com/sct/overseerr/issues/377)? Still as of now, shows deleted on Radarr / Sonarr, and completely removed all their traces from everywhere; keep showing as “Available”; with that green tick, on Overseer. Not even manual scans fix this.

### Version

1.32.2

### Steps to Reproduce

Full Library Sync should detect missing media and unmark it in Overseerr.

### Platform

desktop

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Already an open PR #3219 for this and, please don't open duplicate issues.
