### ISSUE TITLE
Open a Bulgarian language track on Weblate

### ISSUE THREAD

**Issue by Roobyx** [sct/overseerr#3330]
### Description

Hey, I am enjoying Overseer a huge deal!
My use-case is strictly tied to language (letting older relatives make requests). I am willing to help translate and will be happy to spend some time on that, but I can't see a track for **Bulgarian** in Weblate.use case

### Desired Behavior

The Weblate page to have **Bulgarian** as a possible translation language for Overseer

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by jordanjones98** [comment]
https://github.com/sct/overseerr/pull/3597 and https://github.com/sct/overseerr/pull/3597 once these are merged this will be completed.
