### ISSUE TITLE
Removal of movie/serie after watched

### ISSUE THREAD

**Issue by mduijm** [sct/overseerr#3343]
### Description

Would like to request to see if it is possible to remove a download after a user watched a movie or series. 

### Desired Behavior

Plex knows when and who played a file, or finished I think, so would that be a good source to use?

Perhaps to start with a message to admin > user X who requested Y has watched this movie, would you like the movie deleted? 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #1924

**Comment by mduijm** [comment]
Sorry for the duplicate.
