### ISSUE TITLE
Bug? It’s possible sending multiple API requests for the same movie

### ISSUE THREAD

**Issue by arjanterheegde** [sct/overseerr#3344]
### Description

Hello, I don’t know if this is a bug or a feature but when you do a request for a movie in the API it’s possible to add multiple requests for the same movie. 
Is this as designed?

### Version

1.32.5

### Steps to Reproduce

Send a api request for a movie with an tmdbId. After sending send another one and you will see the movie will be double listed as request.

### Platform

desktop

### Device

All

### Operating System

All

### Browser

All

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Can't reproduce this at all. Can you get us some logs so we can investigate?
