### ISSUE TITLE
Partially available movies need a higher contrast icon in thumbnail

### ISSUE THREAD

**Issue by pistachiomatt** [sct/overseerr#3345]
### Description

When a 4K and non-4K servers are provided, and a movie is available on just the 4K one, this icon appears:

<img width="183" alt="Screenshot 2023-02-19 at 2 19 51 pm" src="https://user-images.githubusercontent.com/170421/219978604-5460fa04-49d6-4faf-8846-c8fdc1e51439.png">

This is very hard to see (and when this issue was first posted I didn't even notice it!)

It should instead be this icon: 
 
<img width="195" alt="Screenshot 2023-02-19 at 2 21 31 pm" src="https://user-images.githubusercontent.com/170421/219978639-390613ff-714a-4334-95e6-baba53b4a2fd.png">

Additionally, I would request an option to "show a check if movie is available on any default server". In my situation if a 4K movie is available on the 4K server, and not on the non-4K server, that's "available" enough that I'd want it to appear as a check to contrast when browsing/discovering other movies.

### Version

1.32.5

### Steps to Reproduce

1. Add a 4K and non-4K server both as "default"
2. Request a movie in 4K and wait for it to download
3. In the movie detail view, the status changes to "4K available". This is correct.
4. Search for the same movie in the search bar. The icon is not noticeable.

### Platform

desktop

### Device

All

### Operating System

Any

### Browser

Any

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
That's not supposed to be there actually. I'll make a fix shortly.

The reason we haven't added a badge like the regular one to indicate 4K availability is because we didn't like any of the ideas we had for how it should look.
