### ISSUE TITLE
Unable to import managed plex users

### ISSUE THREAD

**Issue by FatHarryWhite** [sct/overseerr#3352]
### Description

Hi,

I only seem to be able to set up Managed Plex users by creating local users for them, rather than importing them. The users don't have email addresses associated with them (and there doesn't appear to be a means of doing this within Plex). Is this feature supposed to work for Managed users, or only for other Plex Accounts with library access?

If it isn't supposed to exist at the moment, please could this feature be added? I imagine we would have to associate the email address to the user inside Overseerr.

Thanks!

### Version

1.32.5

### Steps to Reproduce

Go to users. Click Import Plex Users. Popup says there are no Plex users to import

### Platform

desktop

### Device

PC, Samsung Galaxy S21

### Operating System

W10, Android

### Browser

Chrome, Firefox, Samsung internet

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Managed Plex users don't have their own Plex credentials, so it is not possible to import them. Our recommendation is to create Plex accounts for your users and invite them to your Plex Home.
