### ISSUE TITLE
Requests made by local users don't display download progress

### ISSUE THREAD

**Issue by musshorn** [sct/overseerr#3355]
### Description

Making requests to Radarr as a local user generates the following in the log file and the progress for the download progress is never displayed. 
```
2023-02-24T09:33:45.612Z [debug][API]: Failed to retrieve request.{"errorMessage":"Could not find any entity of type \"MediaRequest\" matching: {\n    \"where\": {\n        \"id\": 14\n    },\n    \"relations\": {\n        \"requestedBy\": true,\n        \"modifiedBy\": true\n    }\n}"}
```

When the download completes, it does not appear as avaliable

### Version

1.32.5

### Steps to Reproduce

1. Create a local user
2. Request content that is downloaded via Radarr
3. Observe the logs and download status.

### Platform

desktop

### Device

PC

### Operating System

Windows 10, server on Ubuntu 22.10

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Unable to reproduce. We do not have permissions blocking local users from seeing download status. Are you able to see the status with Plex users?

**Comment by musshorn** [comment]
Just tested. I can't see the download status for Radarr requests for Plex users either. The Download Sync job seems to run without issue though(?)
![image](https://user-images.githubusercontent.com/874740/221341367-8133517b-3d26-40cd-9aa6-94a308ed1a99.png)

Content however just sits on requested.

**Comment by OwsleyJr** [comment]
Do you have scan enabled for your Radarr/Sonarr services?

**Comment by musshorn** [comment]
Ah yep that appears to be the issue. Enabling that now shows progress for all users. Thanks
