### ISSUE TITLE
Requesting additional seasons of a partially available series doesn't count against a user's request limit

### ISSUE THREAD

**Issue by omginbd** [sct/overseerr#3360]
### Description

Hi there, I limit users on my server to 2 movie requests and 2 series request per month, and I noticed that if a user requests additional seasons of a partially available series it doesn't count against their limit.

This seems like it's maybe a feature change? I'm not sure what the expected behavior is, but I know that I expected that they wouldn't be able to make any more requests.

### Version

1.32.5

### Steps to Reproduce

1. Set a request limit on a user
2. Have that user request a new season of a show which is already partially downloaded
3. See that it hasn't counted against their request limit

### Screenshots

User's recent requests (2 new movies, one new series, and more seasons of a partially available series):
![image](https://user-images.githubusercontent.com/2192241/221325127-90cf320d-2b7d-420b-8926-67e9ffbd4479.png)

They have a request limit of 2 movies and 2 series per month, see that they only have one of their two requests counting against their limit:
![image](https://user-images.githubusercontent.com/2192241/221325216-a5caee2f-3a9b-4e02-b4aa-99d775b59fa1.png)

### Platform

desktop

### Device

Any

### Operating System

Any

### Browser

Any

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
I can't reproduce this; neither when trying to request on another user's behalf on my admin account, or when trying to request from the restricted account.

One thing I'm noticing though, is that it shows the amount of requests for the past 7 days. If that user was limited to 2 series requests per month, it'd would say "past 31 days" there instead (or 30 days, whichever you chose).
