### ISSUE TITLE
AvailabilitySync job fails to delete requests for deleted/unmonitored movies if they still have radarr DB entries.

### ISSUE THREAD

**Issue by andrew-kennedy** [sct/overseerr#3363]
### Description

The code here: https://github.com/sct/overseerr/pull/3219/files#diff-a28b2c65a45f7ef7d693cb24a8daf6ee6dce66df8d07ecf4fb37f74312a244f7R309-R324 causes a bug where if a movie is within the radarr UI but totally unmonitored, it will not have it's requests deleted. This makes automated pipelines rather hard to set up. An option to consider movies "nonexistent" in radar if they are unmonitored AND have no media files present would be best. 

I have an automated pipeline set up where when a set number of days has elapsed since the requester has watched a movie, the movie file is deleted. Radarr has a feature to automatically unmonitor any movies that have their files deleted. Having overseerr delete the requests in that case would be ideal.

### Version

2520d8f739abfde608f3ef66a9fbe6b7b5c6647a

### Steps to Reproduce

Request a movie in overseerr.
Delete the movie file via plex or some other method. 
Set the movie to unmonitored in Radarr, or set the setting that automatically unmonitors deleted movies.
Run the AvailabilitySync job, notice the request for the movie isn't deleted.

### Platform

desktop

### Device

Macbook Pro M1

### Operating System

Linux server, macos client

### Browser

Chrome

### Additional Context

If there are no active files for a movie and it's unmonitored, users should be able to request it again, even if it exists in radarr.

This would also set us up for success where movies that already exist in radarr but are unmonitored and have no files can be requested, solving the bug where movies added by import lists don't have their requests fulfilled (a request is created but the movie is not montitored and labeled if it was already in radar and unmonitored)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
I can make a PR for this. So you're saying only if the movie in Radarr has no media file and is unmonitored. What if the movie has no media file but is monitored, should we avoid deletion in Overseerr?

**Comment by ShanaryS** [comment]
@OwsleyJr I think the monitor status should be irrelevant, it should only check if the file exists or not. A monitored item with no current file means they only care about any future releases. But I think a request in that situation should start a search (if enabled) as a user likely wants it now.

**Comment by OwsleyJr** [comment]
> @OwsleyJr I think the monitor status should be irrelevant, it should only check if the file exists or not. A monitored item with no current file means they only care about any future releases. But I think a request in that situation should start a search (if enabled) as a user likely wants it now.

Makes sense I think. Since I've now added a check for the file count, verifying that is monitored or not is probably unnecessary.

**Comment by ShanaryS** [comment]
@OwsleyJr I'm testing the latest develop branch and this feature does not seem to be working. Movies and series that are both deleted and unmonitored still show up in overseerr and can't be re-requested.
