### ISSUE TITLE
Feature Request: Multiple Discord Webhooks for Different Notifications

### ISSUE THREAD

**Issue by adamjsturge** [sct/overseerr#3368]
### Description

I want to be able to separate my notifications to different discord channels. Doesn't have to be exclusive to Discord is just the main use case I have

### Desired Behavior

So Request Automatically Approved goes to Webhook 1 and then Webhook 2 gets Request Processing Failed etc

### Additional Context

I can code this if people are okay with this being a feature. I know NextJS, I would just like this so I can have a user facing discord channel and an "admin" one for separate notification groups. I know I can use webhook but it seems better to have it be an official thing so I don't have to mess any JSON stuff

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #1664
