### ISSUE TITLE
Recently Added still displayed deleted items

### ISSUE THREAD

**Issue by nokternol** [sct/overseerr#3370]
### Description

Even a full manual library scan does not remove an item in recently added if it was subsequently deleted.
I used radarr to delete an item that was added by a list, added to exclusion list but overseerr can picked it up in the meantime.

Attempted to use Full Manual Library Scan in the hopes that would pick it up.

It appears the scans only look for data that has not been picked up yet and does not do the extra work of pruning.

### Version

1.32.5

### Steps to Reproduce

1. Add a List to radarr which auto-adds
2. Add a film to the list (I used trakt but I doubt it matters)
3. Let radarr get and import the item
4. Let overseerr update and pick up the recently added item
5. use radarr to delete and block the item
6. try to get overseerr to remove the recently added item

It is likely the list steps are not required (if I am right about the cause) but I add them for completeness.
If I am right, the bug is simply recently added is not pruned on refresh

### Screenshots

![image](https://user-images.githubusercontent.com/16777127/222494011-1206b0e8-5927-4c09-ace4-7a3e45ea4cee.png)
![image](https://user-images.githubusercontent.com/16777127/222494092-5e728044-f5b6-4bea-b6cf-f3ed9ed873e2.png)

### Logs

```shell
2023-03-02T16:40:00.100Z [info][Plex Scan]: Recently Added Scan Complete

Many different scans have happened since the incident occurred
```

### Platform

desktop

### Device

pixel 4a and Windows Laptop

### Operating System

Win10, Android13

### Browser

Chrome

### Additional Context

running in a docker container, accessed via web ui both on desktop chrome and installed on mobile as PWA

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
#2890 was already merged into develop and will be in the next release.

**Comment by nokternol** [comment]
apologies for not finding it in my search, thank you
