### ISSUE TITLE
Filters: 1) Ability to Save different ones so that you can reapply them and 2) Filter out movies/shows I already have

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#3372]
### Description

On Movies/Shows, it'd be nice:
- To be able to save filters.  Let's say I have one for '80's comedies' and then I want to remove the filter.  I'd then like to bring it back/select it from my list of saved filters
- To not see movies/shows in the filters if I already have them.  So a toggle for this would be helpful.

### Desired Behavior

As above.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
We will most likely add the ability to create a new slider with saved filters. For the already available movies/series, we currently have a global toggle, but we are also exploring the possibility of adding a quick filter toggle specifically for the movies/series filter.

**Comment by Percy2Live** [comment]
May I asked where I can find that global toggle? In my case I would like to see the exact opposite: Only the shows I already have, in order to find out for which ones new content is available

**Comment by OwsleyJr** [comment]
Toggle can be found in general settings.

**Comment by Percy2Live** [comment]
Ah ok, found it - unfortunately this does not help for the mentioned use-case where I would like to filter for shows I already have (partially). Is there any trick to be able to do that?

**Comment by OwsleyJr** [comment]
Not at this moment. But like I said, we plan on adding a toggle of some sort directly to the filter.

**Comment by Percy2Live** [comment]
please reopen
