### ISSUE TITLE
Add monitor fields collections (reopening after closing bot)

### ISSUE THREAD

**Issue by skillix** [sct/overseerr#3375]
### Description

Currently it is not possible to manage the new "monitor" option recently added to radarr

### Desired Behavior

Is it possible to add the new radarr field "monitor" at the time of the request for addition and/or in the default parameters of the application

### Additional Context

![image](https://user-images.githubusercontent.com/68369861/196029077-65609b2d-ceea-4676-beca-f98e9710ee67.png)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by skillix** [comment]
original post : https://github.com/sct/overseerr/issues/3078

**Comment by OwsleyJr** [comment]
I'll reopen the previous closed issue.

**Comment by skillix** [comment]
thx
