### ISSUE TITLE
Tags in Sonarr / Radarr based on usernames

### ISSUE THREAD

**Issue by nicholaskoerfer** [sct/overseerr#3377]
### Description

Please add a setting that allows the username of a user to be automatically inserted into sonarr & radarr for the film or series they have requested. 

### Desired Behavior

User requests Media -> Overseerr adds the username as a tag to the media in Sonarr / Radarr

### Additional Context

Of course, you can also look in Overseerr itself to see who has requested something, but I still often miss the function to look into Sonarr or Radarr to see the Username in the Tag of the Media.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Duplicate of #1964
