### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by nrgbistro** [sct/overseerr#3378]
### Description

When I try to search for certain words, for example "cocaine", I get 500 - Internal Server Error instead of search results. Is this some kind of language filtering? If so, is it possible to disable in Overseerr?

### Version

1.32.5

### Steps to Reproduce

1. Login to Overseerr
2. Type in "cocaine" in the search bar.
3. See that you get "500 - Internal Server Error" instead of search results

### Screenshots

![image](https://user-images.githubusercontent.com/35301702/222987189-411e443e-1ca9-4693-8e54-524e33f7af54.png)
![image](https://user-images.githubusercontent.com/35301702/222987200-c20e4e5b-94db-404a-ba7b-dc4571f1fab1.png)
reloading the page with "cocaine" in the search bar as the search query:
![image](https://user-images.githubusercontent.com/35301702/222987313-7813cd67-5a04-4954-9fcf-431bfef9667d.png)

### Platform

desktop

### Device

Desktop

### Operating System

Windows 11

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by kevin-wynn** [comment]
This started happening to me as well. Was happening on v1.32.4 so I upgraded to v1.32.5 and still getting the error. This is the error I get in logs ```2023-04-05T18:56:38.864Z [debug][API]: Something went wrong retrieving search results{"errorMessage":"Cannot read properties of undefined (reading 'map')","query":"rocky"}```

**Comment by nrgbistro** [comment]
Can confirm that "rocky" causes the issue on my end as well.

**Comment by kevin-wynn** [comment]
This seems to have been resolved for me with no action on my end /shrug

**Comment by RantMaster** [comment]
I am seeing this when searching for Metalocalypse. It seems to be when you get 5 or more characters in some words it gives the error

**Comment by Alexays** [comment]
My PR (https://github.com/sct/overseerr/pull/3393) should fix this issue.

**Comment by teuchezh** [comment]
same issue with this log
`[debug][API]: Something went wrong retrieving trending items {"errorMessage":"[TMDB] Failed to fetch all trending: connect ECONNREFUSED 127.0.0.1:443"}`
![image](https://user-images.githubusercontent.com/40827089/233155480-af7d3b04-20c3-4802-b25b-02e2078972ef.png)
![image](https://user-images.githubusercontent.com/40827089/233155568-99017843-e0d4-442b-a81f-79d98a3b139e.png)

**Comment by TheCatLady** [comment]
Fixed in #3393
