### ISSUE TITLE
UnhandledPromiseRejectionWarning when starting up Overseerr for the first time

### ISSUE THREAD

**Issue by royrico** [sct/overseerr#338]
**Describe the bug**
UnhandledPromiseRejectionWarning when starting up, with this specific error:

        at new EntityNotFoundError (/app/node_modules/typeorm/error/EntityNotFoundError.js:11:28)

For additional context:
I have 1 Plex account, which has 3-4 plex "local" accounts under it, which is probably why you may be seeing a plex user with a null email.    I don't know plex schema well enough to answer this for you, but you may want to see if you can discern actual plex users with local users, and only require email address on real plex accounts. 

I added docker logs below.

    yarn run v1.22.4
    $ NODE_ENV=production node dist/index.js
    2020-12-16T02:36:57.642Z [info][Notifications]: Registered Notification Agents 
    2020-12-16T02:36:57.652Z [info][Jobs]: Scheduled jobs loaded 
    $ref: keywords ignored in schema at path "#/properties/requestedBy"
    2020-12-16T02:36:58.125Z [info][SERVER]: Server ready on port 3000 
    2020-12-16T02:38:02.452Z [error][Auth]: SQLITE_CONSTRAINT: NOT NULL constraint failed: user.email 
    2020-12-16T02:40:00.050Z [info][Jobs]: Starting scheduled job: Plex Recently Added Sync 
    (node:27) UnhandledPromiseRejectionWarning: EntityNotFound: Could not find any entity of type "User" matching: {
        "select": [
            "id",
            "plexToken"
        ],
        "order": {
            "id": "ASC"
        }
    }
        at new EntityNotFoundError (/app/node_modules/typeorm/error/EntityNotFoundError.js:11:28)
        at /app/node_modules/typeorm/entity-manager/EntityManager.js:555:51
        at async JobPlexSync.run (/app/dist/job/plexsync/index.js:233:27)
    (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see    https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
    (node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**What version of Overseerr are you running?**
I don't know the version, probably should include version in log output, or on the UI.
Docker image id is : 6e9a3f67f1ecfcd3f563de143ad86a7dd0e37204fef4defd0e1acfa6229d91ab

You can find it under: Settings -> About -> Version
I can't start the app

**To Reproduce**
1) included overseerr in my docker-compose.yml file with the rest of my media-center apps.
2) started up m`docker-compose up -d`
3) go to 'http://myip:5055/`
4) Asks for plex sign in, signed in
5) Stuck on step #2 "Logging you in" for some time.
6) Patience not great, check docker logs, see error posted below

**Expected behavior**
Not to error, and if it did error, at least an error message in the UI

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux Mint 19.3
- Browser: Chrome

**Additional context**

`

**Comment by royrico** [comment]
P.S. excited to get this working, and try it out.  Thanks for creating and sharing!

**Comment by sct** [comment]
Version is included in the UI already, as mentioned in the PR template. If you don't see it, please upgrade to the latest version and then try again. If you are still having trouble we can re-open this ticket.

**Comment by royrico** [comment]
HI, i was only mentioning the version number thing to fill our your issue template.   The actual issue is further down in the ticket: sorry for any confusion

**Comment by royrico** [comment]
> Version is included in the UI already, as mentioned in the PR template. If you don't see it, please upgrade to the latest version and then try again. If you are still having trouble we can re-open this ticket.

I have updated the original ticket to clear up the confusion

**Comment by sct** [comment]
Ah yeah. Bit hard to see the version if you can't start the app, huh? I will also add the version to the startup logs.

Do you use Plex 2FA by any chance?

**Comment by royrico** [comment]
No, i currently do not. I think the logging into plex went fine.  This is a shot in a dark, but I have one "real" plex account and several local accounts which are for my family inside the house.   I am thinking Overseerr may be trying to import all plex users, but since i have local plex accounts, which do not have email addresses defined for these local users.

**Comment by sct** [comment]
We don't import any users yet, so that shouldn't be the reason. As long as the account your are logging in with has an email registered to Plex, it should work.

**Comment by royrico** [comment]
i have log level set to 'info', if there is a higher one (debug/silly?) i can enable and retry to get more info

**Comment by royrico** [comment]
Oh ok.  interesting.

My email is set properly on my account.

**Comment by sct** [comment]
> i have log level set to 'info', if there is a higher one (debug/silly?) i can enable and retry to get more info

You can set logging to debug. I am not sure how much it will help in this case though.

**Comment by sct** [comment]
Can you delete your database file (`/app/config/db/db.sqlite3`) and try again from the start? See if we run into the same problem?

**Comment by royrico** [comment]
changed LOG_LEVEL to debug, no additional info as you stated.

deleted the db file, still same error.

**Comment by royrico** [comment]
URL: /api/v1/auth/login
HTTP Status: 500
Request Body: `{authToken: "__REDACTED__"}`
Response Body: `{"error":"Something went wrong. Is your auth token valid?"}`

URL: /api/v1/auth/me
HTTP Status: 401
Response Body `{"message":"cookie 'connect.sid' required","errors":[{"path":"/api/v1/auth/me","message":"cookie 'connect.sid' required"}]}`

**Comment by royrico** [comment]
I peeked into the DB file to see if it helps.

      $ sqlite3 db.sqlite3
    SQLite version 3.31.1 2020-01-27 19:55:54
    Enter ".help" for usage hints.
    sqlite> .tables
    media           migrations      season_request  user  media_request   season          session
    sqlite> select * from user;
    sqlite> select count(1) from user;
    0
    sqlite>

**Comment by PotatoQuality** [comment]
Hi @royrico ,

I had something similar. To resolve this. It was required to logout on the plex.tv website and relogin.
That dit solve my problem. Maybe it helps for you too?

**Comment by sct** [comment]
Closing this as there is currently no support (or planned support) for local plex accounts.
