### ISSUE TITLE
Mark as available a little awkward when only a single season requested

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#3380]
### Description

Let's say there's a series I don't have, and it has multiple seasons.  Someone requests the last season (only) and I approve.  When the content comes in its entirety for that season, I have to remember to go back and 'Mark All Seasons as available' so that they get a notification.  But that's not really the case here.  In this case, they made a request for a single season, it's available, and I think they should be automatically notified based on that.  Or make that a configuration settings, etc.

### Version

1.32.5

### Steps to Reproduce

As described above.

### Platform

desktop

### Device

All

### Operating System

All

### Browser

All

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Same concept as #342.
