### ISSUE TITLE
Movie marked as available when deleted from server (not on plex anymore)

### ISSUE THREAD

**Issue by LucaDeslot** [sct/overseerr#3382]
### Description

I deleted a movie from my server so it's not showing nor on radarr or plex anymore, but overseerr still marks the film as available so I can't request it anymore.

### Version

1.32.5

### Steps to Reproduce

1. Remove movie and files from radarr
2. Remove movie and files from RuTorrent (or other client)
3. Remove completely other trace of the movie on the server
4. Overseer does not sync

### Platform

desktop

### Device

All

### Operating System

All

### Browser

All

### Additional Context

Plex and Radarr are both connected to Overseerr.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Rustymage** [comment]
I too have this issue. The work around is to go into Overseerr and delete it manually.

**Comment by nokternol** [comment]
FYI: The fix is already through dev and should be in the next release.. I raised this same bug a few days ago.
