### ISSUE TITLE
Use discord Bot insted of webhook...

### ISSUE THREAD

**Issue by Blazzycrafter** [sct/overseerr#3388]
### Description

in our server we have the channel "overseer" hidden...
no one can get a ping in that channel....
so my idea is an alterenate notify for discord via bot and dm´s

### Desired Behavior

if a request has changed... send it in the overseer log channel...

if MY request got changed...
send ME a DM Via Discord
AND send it to overseer log channel...

### Additional Context

of course only with our own bots....

i'm building a workaround via python and API....
but nah....
let that be a really working and polished feature :D

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
There are no plans to add Discord bot functionality to Overseerr, but there are a couple of third-party bots listed in our docs: https://docs.overseerr.dev/extending-overseerr/third-party
