### ISSUE TITLE
Forward Proxy Support

### ISSUE THREAD

**Issue by hcuk94** [sct/overseerr#3390]
### Description

Please support configuration of a forward proxy for connecting to external APIs.
This has been requested previously in #1907 and #2319, and a PR was submitted as #2481 

In the case of others, this was down to living in countries with limited internet access. In my case, it is due to purposefully restricting server web access to a list of allowed sites through a forward proxy. Either way, it is common functionality supported in the software Overseerr interacts with.

I have set HTTP_PROXY and HTTPS_PROXY environment variables and I do see some requests use the proxy as a result, but clearly some elements of the application are ignoring these environment variables as it doesn't fix all the issues. A configuration item in the web UI would be ideal.

Perhaps the previous PR could be reviewed & merged?

Thanks in advance.

### Desired Behavior

Overseerr should be able to load external resources through a forward web proxy.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by aniqueta** [comment]
+1 

In the interim, it may be possible to use:
https://github.com/rofl0r/proxychains-ng 
https://proxifier.com

**Comment by danshilm** [comment]
For some context, the PR at the time couldn't proxy images. But now it is possible to implement that since there's already an image proxy.
Closing in favour of the old issue #1907
