### ISSUE TITLE
Notifications / Responses via Whatsapp

### ISSUE THREAD

**Issue by Matt2k34** [sct/overseerr#3392]
### Description

Ontop of the agents that are already availlable, WhatsApp is the most used mobile messaging platform globally with approx. 2bn users.

### Desired Behavior

It would be nice if you could send notifications to users via WhatsApp, There's a free tier (1k messages per month) which would cover most installs.

Ontop of notifications, if you could reply to the templated message via WhatsApp (e.g. "Search <moviename>" and it then list the first 5 results, you reply with a number and it adds the request) - that would also be pretty sweet :)

Upon setup you'd probably want a templated message confirming sign up though, to avoid typo's sending repeated messages to the wrong number for example.

### Additional Context

Notifications only get used by me and not by the users of overseerr in my instance, I  think that would lower the barrier for usage (which is pretty much the use case for Overseerr?)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by clemone210** [comment]
Can you share some information about that free tier?

**Comment by Matt2k34** [comment]
Unfortunate change of policy. As it was free 1k either way previously.

Sound's like it'd still be doable just the user would have to message first, then the responses would be templated, no?
