### ISSUE TITLE
Request History

### ISSUE THREAD

**Issue by syaoran68** [sct/overseerr#3397]
### Description

Might be potentially worth it to add a feature where we can track a person's requesting history or have tracking on an entry side of who is requesting that show.

### Desired Behavior

Click on a user and see not only their current total requests, but also their requests history. basically what they have requested in the past and if it was approved, denied, modified, etc.

Second option would be to be able to search via a entry (either a TV show or movie), have a section or a tab to allow for a list of who requested this entry and the details regarding their request. 

### Additional Context

The reason why I would like this requested is among all my friends and family i get quite a few requests.. eventually when i'm looking through sonarr as to what is being downloaded and pulled i can potentially forget who originally requested the show and if they are watching said show. If they are not, i'd like to be able to remove said entry from being tracked and downloaded.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
I am not sure what you mean. You can already see a user's request history when visiting their profile?

**Comment by TheCatLady** [comment]
Additionally, you can already view the requests associated with any media item in the management slideover...
