### ISSUE TITLE
Links to discord community broken/expired

### ISSUE THREAD

**Issue by davidgibbons** [sct/overseerr#3405]
### Description

Within overseer and on the website the community links to discord are broken, 
https://discord.gg/overseerr returns an expired/no permissions error. 

### Version

v1.32.5

### Steps to Reproduce

1.) Goto https://discord.gg/overseerr
2.) Fail to get an invite to the discord community.

### Logs

```shell
Invite Invalid
This invite may be expired, or you might not have permission to join.
```

### Platform

desktop

### Device

Any

### Operating System

Any

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Just tested this and the link works fine.

**Comment by davidgibbons** [comment]
Appears to be a browser issue, tried again directly in the discord client and it's working fine, sorry about that.
