### ISSUE TITLE
Overseerr generating 403 13882 when making use of SWAG reverse proxy.

### ISSUE THREAD

**Issue by Quafley** [sct/overseerr#3413]
### Description

Hi,

As of recently I've started using Crowdsec, which is connected to my SWAG reverse proxy. When visiting the overseerr webpage, when already logged in, users will get banned within 2 seconds. This is due to Overseerr generating numerous 403 errors. When looking at the access-logs within nginx (SWAG), I see the numerous 403 errors generated when simply being on the home page of overseerr.

Please note that it is currently impossible to visit overseerr when actively scanning for 404/403/400 (http-probing). I would have to turn this off in order for overseerr to correctly operate again.

### Version

a4d07f5afab613317d96c9c6e9b47157a5a28986, also happens on latest.

### Steps to Reproduce

1. Be logged in and simply visit Overseerr like you normally would. But you need to have Crowdsec configured and run http-probing (https://hub.crowdsec.net/author/crowdsecurity/configurations/http-probing).
2. get banned within 2 seconds since the 403 get genered within a very short time.

### Screenshots

![AQS7AXp](https://user-images.githubusercontent.com/44779473/230741816-331b36b6-86aa-4cf2-b477-266c43f88e1f.png)

### Logs

```shell
no logs
```

### Platform

desktop

### Device

Computer

### Operating System

Windows 11

### Browser

Firefox

### Additional Context

This happens with everyone that visits the website.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by XRaTiX** [comment]
I have SWAG as well and this happens and if you don't set the fail2ban rule exception of overseerr.
https://docs.overseerr.dev/extending-overseerr/fail2ban

Basically,I have in filter.d a file called overseerr-deny.local with

```
[Definition]
failregex = .*\[warn\]\[API\]\: Failed sign-in attempt.*"ip":"<HOST>"
```

and in the jail.local

```
[overseerr-deny]
enabled  = true
port     = https
filter   = overseerr-deny
logpath  = /config/log/overseerr/overseerr.log
```
You need to mount the directory where overseerr has the log to the SWAG container,and then point that to the logpath.

**Comment by Quafley** [comment]
Hi,

Thanks for your reply, but I'm not using fail2ban, but Crowdsec. I'm thinking about whitelisting specific GET / POST requests.

**Comment by DeftlyMoving** [comment]
Chiming in here, running into exactly the same issue with Crowdsec instantly banning genuine Overseerr logins. Surely this is not intended behavior for Overseerr? I realize this might not be top priority but running Overseerr externally without Crowdsec/Fail2Ban in front is an unnecessary security risk.

**Comment by ToXinE** [comment]
nothing's done in overseer for the bad 403 return ?

**Comment by Hermitter** [comment]
Can this issue be reopened?

**Comment by alxgarci** [comment]
it is still happening...
