### ISSUE TITLE
Search is finding titles in unmonitored PLEX libraries. 

### ISSUE THREAD

**Issue by habskilla** [sct/overseerr#3424]
### Description

I have a 4K PLEX library that I have not enabled/selected in overseerr Plex settings.  

The issue is that search is finding titles in the 4K library.  Users are seeing the title in overseerr and getting an error when they try to play the title because they do not have access to the library in Plex.

### Version

1.32.5

### Steps to Reproduce

Deselect a library in overseerr settings
As a user that does not have access to the deselected library, search for a movie that is only in the deselected library.
Try to play the movie

### Screenshots

![image](https://user-images.githubusercontent.com/13573871/233703505-f1205b75-4b06-48f8-83d7-f85ab194f6e7.png)

### Platform

desktop

### Device

Windows 11

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
This is due to the fact you initially scanned the 4K media and Overseerr still thinks the media is available. The new availability scan currently in develop will take care of this.
