### ISSUE TITLE
Ability to append header to services

### ISSUE THREAD

**Issue by JaydenMaalouf** [sct/overseerr#3425]
### Description

I have recently setup CloudFlare Zero Trust and realised that, now that my services are behind Google Authentication, I have no way to connect Overseerr to them unless I whitelist the api path - which is not ideal.

My Overseerr and my services are on two different networks, so external access is how they communicate.

CloudFlare has a function called Service Tokens which can be added to the HTTP headers to bypass the authentication (as long as your CloudFlare Application config is setup to do so)
https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/

I have tested this using LunaSea and it works as expected.
There is currently no way to append headers to the services - I was wondering if this functionality would be possible to add?

### Desired Behavior

Ability to add custom headers to services

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by milindpatel63** [comment]
Came here to ask this exact same thing, and saw that another issue was already here.
I would love to see this as well.

**Comment by M-Pepper** [comment]
Any update on this?
