### ISSUE TITLE
Overseer wont load anymore on LGTV browser.

### ISSUE THREAD

**Issue by mrmuiz** [sct/overseerr#3426]
### Description

When i go to Overseerr on the tv, Overseerr won't load anymore.

### Version

develop

### Screenshots

![341715576_771313054710675_5651054916823193417_n](https://user-images.githubusercontent.com/118138382/234620324-d6962a63-95c0-4c72-b6e9-f03a9e645837.jpg)

### Platform

Docker/Synology

### Device

LGTV 2021

### Operating System

WebOS 6x

### Browser

Chromium 79

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by mrmuiz** [comment]
I narrowed it down to the version where it goes wrong.
This version is where the discover tab spinning begins :Version "sctx/overseerr:f5191aded680357522a65bbdcc40d162b8fbf594"
All versions BEFORE that version, are showing covers on the discover tab perfectly.

And after version : "sctx/overseerr:dd00e48f59054b44bef6b32a2c169e59f6175051" Overseerr has 2 new options "Movies" "Series" Those 2 options never worked on the TV. They keep flashing the placeholders for the covers.
All versions and options work fine on PC and Mobile.
![342459211_184694054470287_6813366281855917333_n](https://user-images.githubusercontent.com/118138382/236294351-5aa8117f-e508-4ddc-a819-25d4c95242ff.jpg)
![342530402_677875707684347_4768243068688697457_n](https://user-images.githubusercontent.com/118138382/236294358-abcf6b10-e7ee-49da-82d6-bd15b7ecf20c.jpg)

**Comment by danshilm** [comment]
As discussed on [Discord](https://canary.discord.com/channels/783137440809746482/1101619561972903948), this is unfortunately not something we support.
