### ISSUE TITLE
request backup mechanism

### ISSUE THREAD

**Issue by 2fst4u** [sct/overseerr#3429]
### Description

Occasionally my overseerr completely loses all settings which is a problem for another day. Sometimes it's my fault because I break my kubernetes cluster.

When it happens, overseerr needs to be completely reconfigured from scratch. If there was a backup mechanism, similar to the arr suite of apps, this would be much easier.

### Desired Behavior

Provide a backup mechanism to save regular config backups too, and restore from.

### Additional Context

Automatic backups would be good but manual would be fine.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #521
