### ISSUE TITLE
Allow multiple instances of the same notification agent

### ISSUE THREAD

**Issue by yegle** [sct/overseerr#3433]
### Description

It would be great if I can send myself Telegram notifications of all events, and at the same time only send requests available events to a group chat that I share with my friends.

Currently I can only send Telegram notifications to one chat id.

### Desired Behavior

I should be able to add two Telegram notification agents, each with different token/chat id/notification types.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Duplicate of #3060
