### ISSUE TITLE
No pushover notifications on user-level

### ISSUE THREAD

**Issue by nmbrg** [sct/overseerr#3450]
### Description

If using pushover for notifications and settings it up under settings/notifications, I get notifications for all added media (even those I did not request) and all other notification types I’ve checked.

But if I instead set up the notifications on my user, I get no notifications at all, not even added media for what I’ve requested.

### Version

1.32.5

### Steps to Reproduce

the settings are identical on both places when trying this. (Tho I disable one place when trying the other)
Same token and key.
Same types checked.

### Platform

desktop

### Device

Synology nas 

### Operating System

Docker

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Please read the notification descriptions on the user notifications settings pages, they are not exactly the same as the system notification types.

**Comment by nmbrg** [comment]
I know they’re not the same. And I’ve read that page before creating this issues.

but enabling the user notification and checking the “request available” should send a notification to the user when the item that the user requested is available, no?

if not, the wording, and description, is horrible.
![IMG_1115](https://github.com/sct/overseerr/assets/31845361/8345051e-d0ab-4ffe-820c-e26f521e3e58)


And since I’m not getting any notification, of any kind, when using the “user notification”, I do not agree with what you said. And do not understand why you closed the issue.

**Comment by TheCatLady** [comment]
Hi @nmbrg, apologies if you did read it -- it's a common issue that users don't, so I made a wrong assumption :)

Please repro and provide logs if this is a bug: https://docs.overseerr.dev/support/need-help#how-can-i-share-my-logs
