### ISSUE TITLE
Error when requesting TV show "Andor"

### ISSUE THREAD

**Issue by samwiseg0** [sct/overseerr#347]
**Describe the bug**
A user requested [Andor](https://www.themoviedb.org/tv/83867-andor?language=en-US). When clicking on the poster of the request, you receive `Oops - Something went wrong`. This maybe because there is no season or episode information yet?

**What version of Overseerr are you running?**
develop-6cd20491d2a0ceb995c4744eeb92a6e2f57a4893

**To Reproduce**

1. Request Andor
2. Click on the poster to see the show details

**Expected behavior**
The page should load the TV show info

**Screenshots**
![Screen Shot 2020-12-16 at 2 08 52 PM](https://user-images.githubusercontent.com/2241731/102394830-4cc58200-3fa8-11eb-8a01-9ff87f24feda.png)

**Desktop (please complete the following information):**

- OS: macOS
- Chrome
- Version 87.0.4280.88 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Console Log Error:
[overseerr-1608145355016.log](https://github.com/sct/overseerr/files/5704973/overseerr-1608145355016.log)

**Comment by sct** [comment]
I think this is because there is no year/firstAirDate set in TMDB yet. I'm trying to slice on undefined 😱 Will get it fixed.

**Comment by samwiseg0** [comment]
Confirmed fixed! Thanks!

**Comment by douglasparker** [comment]
@sct I am running Overseerr version `develop-67146c33ef7f28d520ba2c50b32673d43f4525c8` and this is still an issue for me. I have tested with "Andor" specifically and there is nothing added to the logs when the request is made.

**Comment by douglasparker** [comment]
Just an update: I upgraded to the latest version and it's working as intended now... It's strange because I was already using a release from after the fix, and the few commits that I was missing seem irrelevant to this issue.

Anyways, I can confirm as well that this is fixed. Thanks for your awesome work. :)
