### ISSUE TITLE
'Backfill' user tags into sonarr/radarr

### ISSUE THREAD

**Issue by HStep20** [sct/overseerr#3475]
### Description

With the recent addition of #3338 to finally close out #1964 ~2 years later, it would be amazing to 'categorize' all of the historic requests with tags in the respective applications. (Thank you devs who added this - Its been my one pain point this entire time)

### Desired Behavior

Ideally, once 'user tagging' is turned on, Overseer would just retroactively apply the User Tags to all historic requests ever made (as some users have hundreds), but another option could just be a user 'setting' to "Apply User Tag" which would kick off a job 'tagging' all of that users media in Sonarr/Radarr

### Additional Context

While it works great right now for tagging future additions (did test, worked great!), it doesn't tag historical requests. Literally anything to facilitate tagging those historical requests would make it at top feature for data management. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
> to finally close out https://github.com/sct/overseerr/issues/1964 ~2 years later

This wasn't necessary.

**Comment by sct** [comment]
I completely understand that having this feature would be super helpful for you and other users. However, our team is currently focused on other features for the moment due to limited time. Have you considered writing a small script using the sonarr/radarr APIs to backfill this information yourself?

**Comment by HStep20** [comment]
Apologies if it came off as dismissive - I meant it in an excited manner in that Im happy its finally here.

As for anyone else who may have a desire for this feature, I put together a quick python script you can use to backfill user tags into your Sonarr/Radarr instances that are connected to Overseerr. The API is amazing in that it provides Sonarr/Radarr API keys, so you only need to provide your Overseerr Address + API key, and it will apply tags to all of your servers listed.

It can be found [here](https://gist.github.com/HStep20/d6c5350bbcc12e40b1c9cdf7d9178c16)

**Comment by ftc2** [comment]
someone should take a stab at this :)

i probably will when this makes its way downstream into jellyseerr

**Comment by Brandoskey** [comment]
> Apologies if it came off as dismissive - I meant it in an excited manner in that Im happy its finally here.
> 
> As for anyone else who may have a desire for this feature, I put together a quick python script you can use to backfill user tags into your Sonarr/Radarr instances that are connected to Overseerr. The API is amazing in that it provides Sonarr/Radarr API keys, so you only need to provide your Overseerr Address + API key, and it will apply tags to all of your servers listed.
> 
> It can be found [here](https://gist.github.com/HStep20/d6c5350bbcc12e40b1c9cdf7d9178c16)

Can confirm, the script worked for me
