### ISSUE TITLE
Plex Watchlists disappearing

### ISSUE THREAD

**Issue by bootsofglory** [sct/overseerr#3477]
### Description

Every few weeks my users' Plex Watchlists disappear from Overseerr. Having them re-login back to Overseerr using their Plex account fixes the issue temporarily but they always end up disappearing again eventually. The logs state a 401 error so it seems the stored credentials are expiring. 

### Version

1.32.5

### Steps to Reproduce

1. Log into Overseerr using Plex to allow it to view watchlists
2. After not logging into Overseerr for about 3 - 4 weeks, Overseerr no longer seems to have access to the watchlists
3. Re-logging into Overseerr with Plex allows watchlists to be viewed again

### Logs

```shell
2023-05-31T01:35:05.098Z [error][Plex.TV Metadata API]: Failed to retrieve watchlist items{"errorMessage":"Request failed with status code 401"}
```

### Platform

desktop

### Device

PC

### Operating System

Unraid

### Browser

Edge

### Additional Context

I am running the Linuxserver Overseerr docker container on my Unraid server. I use Nginx Proxy Manager as a reverse proxy to allow my users WAN access to Overseerr.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by tubbo** [comment]
I'm also having this issue, it's been going on for a few weeks. Plex Watchlist items aren't being retrieved anymore at all.

**Comment by wznazir** [comment]
Experiencing the same issue

**Comment by bweezy21** [comment]
same here

**Comment by AlFontal** [comment]
This seems to be happening for me too now?

**Comment by fabiengagne** [comment]
It's happening to my installation too. I'm using docker image `sctx/overseer` with a persistent volume for it's configuration.
I'm currently using version 1.33.2 but I was using earlier versions before (I don't know exactly when the loss of sync occurred).

**Comment by Mark7563** [comment]
Happening here now too. Plex and Overseerr up to date.
Been a few days.
401 Error.

**Comment by danshilm** [comment]
There's nothing we can do here unfortunately afaik. Fetching the watchlists for users requires their token, and that token has an expiry date. Nor can we request a more long-lived token. Afaik the lifespan of that token is 2-3 months. That's also why even the admin has to sign in with Plex from time to time.

**Comment by bweezy21** [comment]
I know this is old but saw this commit on the sonarr GitHub. Could be a solution here as well?

https://github.com/Sonarr/Sonarr/commit/93bd8543b158c952b50e56d4339e4a3c699770b0

**Comment by fabiengagne** [comment]
@danshilm could you have a look at @bweezy21 code suggestion?
