### ISSUE TITLE
Delete User button broken

### ISSUE THREAD

**Issue by JohnnyGrey86** [sct/overseerr#348]
**Describe the bug**
The delete button on users is broken. It shows as clickable, but nothing happens.

**What version of Overseerr are you running?**
1.6.0

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Go to 'Users'
2. Click on 'Delete'

**Expected behavior**
User deletion should proceed. Perhaps a confirmation?

**Screenshots**
None needed. No error.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: iPhone XS
- OS: 14.2
- Browser Chrome
- Version 87.0.4280.77

**Additional context**
Related: I don't think the 'Delete' button should be visible on the same user that is currently logged in.

**Comment by sct** [comment]
Not broken, but not implemented. Will get it added! Thanks for making the issue!

**Comment by JohnnyGrey86** [comment]
Thank you for the response! And anytime! I'm loving this project!
