### ISSUE TITLE
New per-user tagging feature mutates other non-user radarr/sonarr tags

### ISSUE THREAD

**Issue by andrew-kennedy** [sct/overseerr#3480]
### Description

This PR https://github.com/sct/overseerr/pull/3338 introduced the ability to tag media in radarr/sonarr with the username of the user that requested it. This works, but then due to the line below:
https://github.com/sct/overseerr/commit/24f268b6cb67d9a8d8675cd6e09dd83a7f499add#diff-3bf110abedeb6845e01a08462eabf4136ccb90fb3f19711e066606b04521731cR1076

The other "tags" field in the radarr/sonarr settings has that user added to it, so that as more and more users request content, you end up tagging them with all users who have ever made requests.

### Version

df332cec84f31e7a5152d9ad80f3f7839c0f3329

### Steps to Reproduce

1. Configure radarr and sonarr settings to enable the per user request tag.
2. Have multiple users request content
3. Each subsequent piece of content will be tagged with all the users who have made requests before.

### Platform

desktop

### Device

Linux machine

### Operating System

Fedora 38

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Harrdy** [comment]
I can confirm that, I've noticed that too.

Also, if you open the Sonarr or Radarr settings after a request, you will see that there are all tags from all users who have already requested after the feature was activated.

**Comment by OwsleyJr** [comment]
Hey thanks for creating the issue! I see that you have found the line that is causing the problem. Would you be interested in contributing by creating a PR? I would be more than happy to review it. Alternatively, I can take care of it myself.

**Comment by andrew-kennedy** [comment]
I will take a look! If I think I can do it in under an hour I'll submit a PR tonight.
