### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by lidorkalfa** [sct/overseerr#3481]
### Description

Can you translate the UI to Hebrew?
I’d love to help with that, since there’s already Arabic translation (RTL) it should be easy :)

### Desired Behavior

Hebrew language for UI

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
We already have Hebrew in Weblate. Feel free to contribute to it!

https://hosted.weblate.org/languages/he/overseerr/
