### ISSUE TITLE
Plex auth stopped working in v1.33

### ISSUE THREAD

**Issue by josh-gaby** [sct/overseerr#3507]
### Description

Sign in using Plex results in a 500 error from the `https://{redacted}/api/v1/auth/plex` endpoint.

Reverting to v1.32.5 fixes it so I'm fairly certain that this is not a Plex related issue.

### Version

1.33.0

### Steps to Reproduce

1. Sign In with Plex
2. See "Unable to authenticate." message.

### Logs

```shell
2023-06-18T01:39:24.585Z [error][Plex.tv API]: Something went wrong while getting the account from plex.tv: Socket connection timeout 

2023-06-18T01:39:24.586Z [error][API]: Something went wrong authenticating with Plex account {"errorMessage":"Invalid auth token","ip":"{redacted}"}
```

### Platform

desktop

### Device

iPhone, Macbook, Desktop

### Operating System

MacOS, iOS, Ubuntu 22.04

### Browser

Chrome, Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Try in a private window please

**Comment by josh-gaby** [comment]
Same 500 response with the following JSON `{"message":"Unable to authenticate."}` from the `/api/v1/auth/plex` endpoint 

There is also a 401 error from the `/api/v1/auth/me` endpoint with the following when the page loads

```
{
    "message": "cookie 'connect.sid' required",
    "errors": [
        {
            "path": "/api/v1/auth/me",
            "message": "cookie 'connect.sid' required"
        }
    ]
}
```

**Comment by ItsJamesMurray** [comment]
Any update here?  I started getting this error recently too.

**Comment by rafcio82** [comment]
Same issue here.

**Comment by Basicallyapenguin** [comment]
Same here

**Comment by sct** [comment]
This is an issue with the binhex container. Reach out to them for support.
