### ISSUE TITLE
Plex watchlist not showing for owner

### ISSUE THREAD

**Issue by MarkFace91** [sct/overseerr#3509]
### Description

Plex wachtlist is not showing for me (owner account), it does work for my other users however (plex users)

### Version

1.33.0

### Steps to Reproduce

Not sure

### Screenshots

![Screenshot_20230618_154632_Chrome](https://github.com/sct/overseerr/assets/66941849/f74edaf8-6838-4d81-bcf1-67e3415b2033)

![Screenshot_20230618_191159_Chrome](https://github.com/sct/overseerr/assets/66941849/27d9ef69-0839-46a0-b36e-08ff2fffc7c5)

### Logs

```shell
2023-06-18T08:33:18.369Z [error][Plex.TV Metadata API]: Failed to retrieve watchlist items{"errorMessage":"Cannot read properties of undefined (reading 'find')"}
```

### Platform

desktop

### Device

Synology NAS

### Operating System

DSM 7.2

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
This seems due to one or more of the media in your watchlist having incomplete metadata. Please do a "Refresh Metadata" on the items in your watchlist, prioritising recent media.
For more help, reach out to us on Discord
