### ISSUE TITLE
Unable to change Discover Region back to All Regions in General Settings

### ISSUE THREAD

**Issue by Xiticks** [sct/overseerr#3511]
### Description

After changing the default Discover Region of the General Settings, I tried to change it back to All Regions, but it does not work, it keeps the region that is already set. I'm able to change it to any other regions.

### Version

1.33.0

### Steps to Reproduce

1. Go to your Overseer General Settings (Admin privileges)
2. Change the Discover Regions to any region (In my case it was France)
3. Save the changes
4. Try to change it back to All Regions
5. Saves the changes
6. Reload the page, you will see the previously selected region

### Platform

desktop

### Device

Linux device

### Operating System

Docker on Ubuntu 22.04.2 LTS

### Browser

Brave (Chromium Based)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Jopinder** [comment]
Just ran into this issue myself exploring the interface.

**Comment by Jopinder** [comment]
Still have the same issue. Solution provided [here](https://github.com/sct/overseerr/issues/3512#issuecomment-1714513023) works as a temporary fix.

**Comment by danshilm** [comment]
Closing as a duplicate of #3512. The fix has been implemented and is out on the `develop` tag. Please switch to that tag since it will be a while before a new release.
