### ISSUE TITLE
Unable to change Discover Region back to Default in Profile Settings

### ISSUE THREAD

**Issue by Xiticks** [sct/overseerr#3512]
### Description

After my previous issue (#3511), I tried to change my profile default regions. I can set it to any region, save changes and it will set to this new region. However I can't set it to the default (which is All Regions), even though I can use the All Regions settings  

### Version

1.33.0

### Steps to Reproduce

1. Go to your Profile Settings
2. Change the Discover regions to any region
3. Save the changes
4. Try to change it back to Default
5. Saves the changes
6. Reload the page, you will see the previously selected region

### Platform

desktop

### Device

Linux device

### Operating System

Docker on Ubuntu 22.04.2 LTS

### Browser

Brave (Chromium Based)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by gjobin** [comment]
There is a workaround for this issue.

1. Stop application
2. Edit `settings.json`
3. Set value to `null` for attribute on path `main.region` (Don't forget the coma to keep it a valid Json file)
5. Save
6. Start application

**Comment by gjobin** [comment]
Same issue occurs when trying to revert an override of this same setting on a specific user.

**Comment by DragoPrime** [comment]
> 3\. main.region

Now the attribute is just "region" and the value needs to be empty.
![Code_72BluJRzJm](https://github.com/sct/overseerr/assets/99618256/174dd820-e4a6-4c03-b5c0-d2b2a53dd41d)
