### ISSUE TITLE
Server 500 error when retrieving movie/series info

### ISSUE THREAD

**Issue by firephreek** [sct/overseerr#3513]
### Description

Upgraded from 1.32 to 1.33 and numerous series and movies now shown as 'unavailable' despite having been previously added/requested and verified present on the associated Plex server. 

Per the logs, the source the failure seems to be related to failed parsing of a JSON response and seems to happen in a variety of ways:

examples: 
- `2023-06-20T20:32:34.620Z [debug][API]: Something went wrong retrieving series{"errorMessage":"Cannot read properties of undefined (reading 'crew')","tvId":"202099"}`
- `2023-06-20T20:36:04.355Z [debug][API]: Something went wrong retrieving combined credits{"errorMessage":"[TMDB] Failed to fetch person combined credits: Request failed with status code 500","personId":"93396"}`
- `2023-06-20T20:37:19.972Z [debug][API]: Something went wrong retrieving combined credits{"errorMessage":"[TMDB] Failed to fetch person combined credits: Request failed with status code 500","personId":"1958355"}`
- `2023-06-20T20:33:02.490Z [debug][API]: Something went wrong retrieving movie{"errorMessage":"Cannot read properties of undefined (reading 'facebook_id')","movieId":"793"}`

### Version

1.33.0

### Steps to Reproduce

1. Go to `https://[myoverseer]/tv/82728`
2. Get redirected to home page.

### Logs

```shell
- `2023-06-20T20:32:34.620Z [debug][API]: Something went wrong retrieving series{"errorMessage":"Cannot read properties of undefined (reading 'crew')","tvId":"202099"}`
- `2023-06-20T20:36:04.355Z [debug][API]: Something went wrong retrieving combined credits{"errorMessage":"[TMDB] Failed to fetch person combined credits: Request failed with status code 500","personId":"93396"}`
- `2023-06-20T20:37:19.972Z [debug][API]: Something went wrong retrieving combined credits{"errorMessage":"[TMDB] Failed to fetch person combined credits: Request failed with status code 500","personId":"1958355"}`
- `2023-06-20T20:33:02.490Z [debug][API]: Something went wrong retrieving movie{"errorMessage":"Cannot read properties of undefined (reading 'facebook_id')","movieId":"793"}`
```

### Platform

desktop

### Device

Browser

### Operating System

Linux, Android, Mac

### Browser

Firefox, Safari, Chromium

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by jzulkeski** [comment]
Have the same issue. [Reported on overseerr discord](https://discord.com/channels/783137440809746482/1019783950413082687/threads/1120815729294446736). It's also affecting covers of recently added as well. I do not use cache.

**Comment by Skyl3lazer** [comment]
Same here

**Comment by xandervanerven** [comment]
same issue, i tried deleting a request and readding, but just getting a 500 error when entering the series page

**Comment by JiggsNephron** [comment]
This seems to be an issue with TMDB's API: 
https://www.themoviedb.org/talk/6491f7572f8d0900c6679013

**Comment by PH1L900D** [comment]
Same here

**Comment by firephreek** [comment]
> This seems to be an issue with TMDB's API: https://www.themoviedb.org/talk/6491f7572f8d0900c6679013

That there may be an issue with TMDB's API doesn't mean there isn't an issue here. The logs seem to suggest a failure in the response parsing of whatever TMDB is coming back with. More investigation is needed than what the logs currently provide.  Anyone know the easiest way to find the associated call with these error messages?

**Comment by firephreek** [comment]
At least one of the problems is here in [this line](https://github.com/sct/overseerr/blob/f32a9c20ef54b92c0ecf7c6ee9f6a3f710c9cfb4/server/models/Tv.ts#L216)  
```
...
 cast: show.aggregate_credits.cast.map(mapAggregateCast)
 crew: show.credits.crew.map(mapCrew),
...
 ```
 
 There's no null check for child properties, so if the TMDB JSON result drops something like 'credits' or 'cast' here, map will be called on undefined, throwing errors and the models used don't have defaults built.

**Comment by Percy2Live** [comment]
Same problem here, even a downgrade to an earlier version of overseerr does not solve this issue

**Comment by dhaos21** [comment]
This is a weird one as series it was happening to ever single time yesterday are no longer doing it today, So maybe like the above user said its a TMDB API issue.

**Comment by TheDeadestCow** [comment]
This is also resolved for me today, but it would be great to hear fromt he devs on root cause. Was an API limit reached for the app or was this a problem at IMDB/TVDB? If ti's a limit, seems likely to happen again.

**Comment by Drol** [comment]
I have had this problem multiple times for a few weeks. Sometimes it goes away and then it comes back.

**Comment by ystryuchkov** [comment]
Bumping up - getting same exceptions while trying to open a movie entry:

Request:
`https://<overseerr>/movie/11687`

Response:
`2025-04-21T11:30:25.646Z [debug][API]: Something went wrong retrieving movie{"errorMessage":"Cannot read properties of undefined (reading 'facebook_id')","movieId":"11687"}`

Version: `1.34.0`
