### ISSUE TITLE
Add support for Lidarr 

### ISSUE THREAD

**Issue by lborruto** [sct/overseerr#352]
Add support for Lidarr for requesting music!

**Describe alternatives you've considered**
Currently using Spotify playlist sync with Lidarr, but not convenient for my users.

Thanks!

**Comment by HamilcarH** [comment]
I would love to see this too !

especially the ability to add all albums and following lidarr’s metadata profiles.

**Comment by robinfinney42** [comment]
I would really like this too! pls & thx

**Comment by Adrian-at-CrimsonAuzre** [comment]
Throwing in my vote for this feature as well. IMO Ombi's implementation is kinda clunky.

**Comment by dkedinger** [comment]
+1 to this. My kids are getting to the age were I would like them to be able to request music to add to Plex.

**Comment by Dabu-dot** [comment]
Don't close this issue please. Lidarr support still would be appreciate at one point.

**Comment by iamwoz** [comment]
Overseer is amazing - I even use it myself for requests instead of opening sonarr or radarr. Lidarr support would be fantastic. Happy to help with funding if that would help to get this across the line.

**Comment by Pheggas** [comment]
So this feature is pretty much off scope? That's really sad for user like me which have plex literally only for medium size library and remote users.

**Comment by aalencia** [comment]
This is a natural feature that should have already been added I humbly submit :D  Do you need help with the implementation?  It seems a straight copy from sonarr/radarr with slight tweaks right? it would be nice to give overseer only to my family members instead of teaching them about lidarr too.  Thanks!

**Comment by samwiseg0** [comment]
> This is a natural feature that should have already been added I humbly submit :D Do you need help with the implementation? It seems a straight copy from sonarr/radarr with slight tweaks right? it would be nice to give overseer only to my family members instead of teaching them about lidarr too. Thanks!

This is an open source project and we welcome PRs. If you care to implement it yourself since you believe it is a simple copy of the current code but slightly modified for lidarr then we look forward to your PR. 

Also given that this is a project that we work on in the Devs spare time no ETA or deadlines are to be expected.

**Comment by rascal2018** [comment]
+1

**Comment by TheCatLady** [comment]
Sorry folks, this was discussed internally and there are no plans to implement music support at this time.

Music support isn't something we feel we can deliver with the stellar user experience we provide for movies/TV. If this changes in the future, we will re-evaluate/reopen this feature request.

**Comment by d-j-a** [comment]
> Sorry folks, this was discussed internally and there are no plans to implement music support at this time.
> 
> Music support isn't something we feel we can deliver with the stellar user experience we provide for movies/TV. If this changes in the future, we will re-evaluate/reopen this feature request.

Super disappointing. I get the explanation- but I would personally be willing to pay for something like this...donate or whatever.

**Comment by jackmeat** [comment]
I was only recently asked by one of my users if music was possible in Overseer, so thought I would take a look and see it is NOT going to happen. I reacted accordingly above but thought I would just say I know of at least one person who wants it. I can see it being useful as well. Anyways, love the product and just wanted to voice something that was reported to me.

**Comment by deanrbennett** [comment]
+1.  Would be great if someone put the effort into building this as whoever is spending the time to report critical comments on this thread...

**Comment by samwiseg0** [comment]
> +1.  Would be great if someone put the effort into building this as whoever is spending the time to report critical comments on this thread...

Comments like these are not constructive nor helpful. In fact it is offensive that you think you are entitled to this feature. No one is entitled to a feature or ask from the devs. 

This project is worked on in peoples spare time for free. If you want the feature you are more than welcome to learn how to write it yourself. This project is open to PRs.
