### ISSUE TITLE
500 error with specific search

### ISSUE THREAD

**Issue by SnowDrifterr** [sct/overseerr#3520]
### Description

When searching for Metalocalypse, the search results display a 500 error when "Metalo" is typed in

### Version

    1.32.5

### Steps to Reproduce

1. Log in
2. Search bar at the top
3. Type Metalo or Metalocalypse
4. 500 error displayed in search results

### Platform

desktop

### Device

Docker

### Operating System

Synology

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Update to 1.33.
