### ISSUE TITLE
Preserve requests history

### ISSUE THREAD

**Issue by RaunoT** [sct/overseerr#3523]
### Description

After implementation of the much awaited availability sync (thank you 🙌 ), the request (history) itself is no longer preserved once an item is deemed un-available. I'm building a Spotify Wrapped style app for Plex using mostly Tautulli to fetch user stats and I've also implemented Overseerr request counts for individual users via the `user/${user}/requests` endpoint.

### Desired Behavior

Would be great if we could still preserve the full request history irregardless of availability, or at the very least add an API endpoint for it. From a UX perspective, it would be pretty simple also to keep a separate card for previous requests under the _manage_ tab:

<img width="419" alt="image" src="https://github.com/sct/overseerr/assets/22045687/41136b87-3b31-44f3-9be9-df6a32a6287c">

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
#3460 will keep request history once its merged.

**Comment by RaunoT** [comment]
> #3460 will keep request history once its merged.

Thanks for the response! Sorry, didn't notice that PR, my issue can be closed.
