### ISSUE TITLE
Allow automatic approval of *current* season only

### ISSUE THREAD

**Issue by sgtsquiggs** [sct/overseerr#3527]
### Description

Sonarr does not support automatically searching for season packs instead of single episodes. If someone has requested an old show I want to manually intervene so I can tell sonarr to grab the season packs. Or maybe Overseerr can do this?

For long running shows, auto approving the current season is fine because there is no season pack yet. For earlier seasons however, I would much prefer to grab season packs because on private trackers they are more likely to be freeleech.

### Desired Behavior

* Option to auto approve a season if the season has episodes that aired within the past two months
* Instruct Sonarr to search for season packs instead of individual episodes in a completed season (if possible).

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by BagMan9** [comment]
From my knowledge of sonar, I don't think it's possible in v3 at all, as beyond the initial configuration for a series, (seen from the UI [here](https://cln.sh/cVwMTWjK+)), you cannot change the specific sorting mechanism for a specific series in Sonarr.

Now, with v4, it is technically possible, but I think it is infeasible. v4 has added custom formats a la Radarr. Theoretically, Overseer could:

1. Create a new custom format that ranks season packs at +10000
2. Apply that custom format to the quality profile in use.
3. Request the season(s)
4. Wait for all the seasons to finish downloading
5. Revert steps 1 and 2

However, I think this is infeasible. If you have any other searches start while that custom format is still active, they would likely be affected by the season pack weight and download that instead, which is likely undesirable behavior. On top of that, it just in general requires a lot of extra monitoring by overseer which introduces even more potential bugs and unintended behavior.

My recommendation would be to make a quality profile that ranks season packs really high and make that you default for requesting in overseer. That way, users can request and have it approved automatically, but if the series is old & has a season pack, it will prefer it over individual files.

**Comment by sgtsquiggs** [comment]
Thanks for the tip! Was hoping there was an API option since you can filter season packs in the results list in sonarr.

This works though 🤘
