### ISSUE TITLE
Instruct Sonarr to search for season packs for completed seasons

### ISSUE THREAD

**Issue by sgtsquiggs** [sct/overseerr#3528]
### Description

When a completed season is requested, Sonarr ends up searching for each episode individually instead of searching for a season pack. This is detrimental to people using private trackers because we're losing out on all that delicious freeleech.

### Desired Behavior

Instruct Sonarr to search for season packs of completed seasons instead of individual episodes.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by 2fst4u** [comment]
This comes down to your sonarr setup. Overseerr is just telling sonarr to search for the season and sonarr will search for a season pack first if one is available.

I added a show just yesterday and sonarr picked the season pack rather than individual episodes.
