### ISSUE TITLE
Request Status Goes Back To “Requested” Again

### ISSUE THREAD

**Issue by mshereef03** [sct/overseerr#3542]
### Description

When requesting a movie, the request status will go from **requested** -> **processing** -> **requested** again instead of **available** until either a Plex scan or a Radarr scan happens. The Plex recently added scan has a 5 minute window and so it could be confusing for some people when this happens.

### Version

1.33.0

### Steps to Reproduce

1. Request a movie.
2. Wait for download to finish.
3. If Plex or Radarr Scan still hasn’t been done, the status of the request will go back to “Requested”.

### Platform

smartphone

### Device

iPhone 11

### Operating System

iOS 16.0

### Browser

Safari

### Additional Context

I believe this could be solved by calling the plex recently added task when the download sync command detects that a movie has completed downloading.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
Processing isn't an actual database value status. We can only determine the processing status by seeing it in Radarr/Sonarr. So sometimes, yes, it shows as requested again but after at most a few minutes it should become available.

**Comment by mshereef03** [comment]
@sct I see. May I ask why it isn't a database value? would it cause any issues ?

**Comment by sct** [comment]
The state of "requested" already means that it's in Radarr/Sonarr. It doesn't really make sense to add another status for what essentially hasn't changed.

**Comment by mshereef03** [comment]
@sct I would say that a more complete state system is : 

1. Not Requested.
2. Requested ( Not approved yet )
3. Processing ( Now in Sonarr/Radarr but not downloaded )
4. Available (Done Downloading)

Would this cause issues when implementing?

**Comment by sct** [comment]
> @sct I would say that a more complete state system is :
> 
> 1. Not Requested.
> 2. Requested ( Not approved yet )
> 3. Processing ( Now in Sonarr/Radarr but not downloaded )
> 4. Available (Done Downloading)
> 
> Would this cause issues when implementing?

This is already the flow. You forget about the pending status.

1. Not Requested.
2. Pending
3. Requested (or Processing, if activity detected in Sonarr/Radarr)
4. Available

**Comment by mshereef03** [comment]
@sct Okay that's perfect, you're right I totally forgot about the pending state.

**Comment by smshome** [comment]
Hey all. Mine does this as well. I go to Plex and it's ready but Overseerr says requested
P.S. the starr bunch is awesome stuff!
