### ISSUE TITLE
Images Being Cached when Caching Disabled

### ISSUE THREAD

**Issue by hirenshah** [sct/overseerr#3544]
### Description

Caching is disabled, but it still appears to cache images.

### Version

01de972a8fe2ea3c18d5b2f426d01b5b14d142d4

### Steps to Reproduce

1) Disable Caching
2) View Jobs and Cache page to see stats

### Screenshots

![image](https://github.com/sct/overseerr/assets/418112/945b1c55-f259-4f36-b3f3-e167a450fd44)

![image](https://github.com/sct/overseerr/assets/418112/a95207e2-3fe9-41e4-ab59-8809c3d4119f)

![image](https://github.com/sct/overseerr/assets/418112/d31f55bd-6526-4c80-8655-0888ff5b9530)

### Platform

desktop

### Device

n/a

### Operating System

Synology Docker

### Browser

n/a

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
When you disable it we don't delete the cache. Just delete the cached images in your config folder.

**Comment by hirenshah** [comment]
I've deleted them quite a few times, as well as the entire folder. They keep coming back.

**Comment by sct** [comment]
That seems odd. Its possible you have something cached in your browser that's causing your frontend to still hit the image proxy endpoint instead of tmdb directly?
