### ISSUE TITLE
Error checking user access: This user does not exist on the main Plex account's shared list

### ISSUE THREAD

**Issue by xabileiro** [sct/overseerr#3550]
### Description

I had a Plex server set up with user access. I changed the server and set up a new server.
I gave access to this new server to users who already had access to the old server and to new users who only had access to this new server.

Overseerr I set it up with only the new server and when I import users from Plex (or when they try to log in) I only get the users that had access to the old server, the new users do not appear in the list and I get the following error:

`Error checking user access: This user does not exist on the main Plex account's shared list`

I tried the answers in issue #3068 but it doesn't work. 

### Version

1.33.0

### Steps to Reproduce

1. I click on Users.
2. I click on "import Plex Users".
3. Only the users that had access to the old server that no longer exists are listed.
4. The logs show the above error, one for each user.

### Logs

```shell
[error]: Error checking user access: This user does not exist on the main Plex account's shared list 
[error]: Error checking user access: This user does not exist on the main Plex account's shared list
```

### Platform

desktop

### Device

Desktop

### Operating System

Docker

### Browser

Vivaldi

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by scorp200** [comment]
Can confirm this happens for any new plex user, on old server too.

**Comment by TheMonDon** [comment]
I think this is related to plex friends being an optional thing now, with being able to invite users without adding them as friends. No one I invite whether friend or not will show up in Overseerr.

**Comment by jdloaner** [comment]
I came here to open the same report although I think my problem was triggered by upgrading to Plex Pass on same server.  Anyone added to plex post-upgrade is not being recognized on Overseer import and this error shows in the log.  Any ideas on how to correct?

**Comment by DCarlson12** [comment]
Haven’t changed anything to my server besides adding a new user 10 minutes ago. Trying “Import Plex Users” prompts a “No Plex users to import” along with a log error message mentioned. Very frustrating. Occasionally booting the new user from the server then re-adding them works. Can we get some info on why this is happening. Makes my users very apprehensive to use Overseerr when I have to tell them I can’t even add them so they say “nevermind”.

**Comment by staugaard** [comment]
I'm running in to the same issue here

**Comment by scorp200** [comment]
I might have found the issue, I haven't tested anything though.
https://github.com/sct/overseerr/blob/01de972a8fe2ea3c18d5b2f426d01b5b14d142d4/server/api/plextv.ts#L260C21-L260C48

This line overseer gets the users with `friends.MediaContainer.User`,
But the data plex returns is structured:
`{
  "MediaContainer": {
    "size":  0,
    "identifier": "",
    "Account": []
  }
}`

**Comment by scorp200** [comment]
> I might have found the issue, I haven't tested anything though. https://github.com/sct/overseerr/blob/01de972a8fe2ea3c18d5b2f426d01b5b14d142d4/server/api/plextv.ts#L260C21-L260C48
> 
> This line overseer gets the users with `friends.MediaContainer.User`, But the data plex returns is structured: `{ "MediaContainer": { "size": 0, "identifier": "", "Account": [] } }`

ok after some more digging, this is not the issue.
calling `https://plex.tv/pms/friends/all` does not return full friend list.

**Comment by JonnyWong16** [comment]
FYI, I'm pretty sure `https://plex.tv/pms/friends/all` was deprecated by Plex quite a while ago.

You should be using `https://plex.tv/api/users`, which is [already implemented in Overseerr](https://github.com/sct/overseerr/blob/01de972a8fe2ea3c18d5b2f426d01b5b14d142d4/server/api/plextv.ts#L280). It looks like the only thing that needs to change is changing `getFriends()` to `getUsers()`.

https://github.com/sct/overseerr/blob/01de972a8fe2ea3c18d5b2f426d01b5b14d142d4/server/api/plextv.ts#L258C38-L258C38

**Comment by scorp200** [comment]
> FYI, I'm pretty sure `https://plex.tv/pms/friends/all` was deprecated by Plex quite a while ago.
> 
> You should be using `https://plex.tv/api/users`, which is [already implemented in Overseerr](https://github.com/sct/overseerr/blob/01de972a8fe2ea3c18d5b2f426d01b5b14d142d4/server/api/plextv.ts#L280). It looks like the only thing that needs to change is changing `getFriends()` to `getUsers()`.
> 
> https://github.com/sct/overseerr/blob/01de972a8fe2ea3c18d5b2f426d01b5b14d142d4/server/api/plextv.ts#L258C38-L258C38

just tested that out, and it works.

**Comment by scorp200** [comment]
created a PR: #3551

**Comment by shiftoptk** [comment]
Same issue, looking forward to the fix update.

**Comment by Flameeeeee** [comment]
Kinda having the same issue. On a brand new Overseerr setup without any user yet, I am getting the "There are no Plex users to import" when trying to import from Plex (2 users with access to librairies inside my server). Hope the fix can solve my issue as well :) 

Thanks for digging into it @scorp200

**Comment by jvenuto80** [comment]
Same issue here.  just added a new user to my plex and it wont sync to overseer.  no existing users have issues

**Comment by Its-Bootz** [comment]
I've just pulled this today via Docker-Desktop as per documentation install instructions and it seems that latest image I pulled doesn't have this fixed yet? Image pulled was sctx/overseerr. New to this sorry, appreciate the help.

**Comment by AlgorithmArcher** [comment]
Same issue, I am not able to see any other users

**Comment by DCarlson12** [comment]
> Kinda having the same issue. On a brand new Overseerr setup without any user yet, I am getting the "There are no Plex users to import" when trying to import from Plex (2 users with access to librairies inside my server). Hope the fix can solve my issue as well :)
> 
> Thanks for digging into it @scorp200 @JonnyWong16

You need to use the develop tag. Working on the develop build here

**Comment by Jordinthecloud** [comment]
Issue is still there. Please fix

**Comment by 333robbie333** [comment]
U can confirm the issue is still present on my server as well

**Comment by masonlieu** [comment]
Confirming that it's still an issue in 1.33.2

**Comment by 0ut1awStar** [comment]
I am also experiencing this issue in 1.33.2.

**Comment by Araisite** [comment]
still an issue in 1.33.2 for me

**Comment by 0ut1awStar** [comment]
I ran into this issue after doing a plex migration to a new host. I forgot to go back into overseer settings->Plex and updated my server details there to resolve the issue.

**Comment by mthievin** [comment]
Same thing happened to me. Wasn't working when i migrated to a new host. Needed to go to setting -> Plex -> sync again with my server and it found my friends.

**Comment by squedwards** [comment]
I can only assume, most of the time it's a specific issue with the configurations of both the local Plex and Overseerr servers. It also did not work for me until I enabled Web App URL on Overseerr (Settings -> Plex). For me this was "https://app.plex.tv/desktop/" .

**Comment by williamhw3** [comment]
Changing the plex server from local/direct worked for me 7/24/25
