### ISSUE TITLE
Auto page width on Requests page misbehaving

### ISSUE THREAD

**Issue by JohnnyGrey86** [sct/overseerr#356]
**Describe the bug**
The overall transition into and out of the mobile view is extremely graceful, however, the requests list within the requests page seems to be misbehaving. If I condense the browser window width down, it condenses with it, but if I force it to transition into a mobile view, the width of the actual list will "snap" back to an extreme width, requiring the user to then use a scroll bar. After this issue is encountered, the desktop view will no longer condense down to the same point before switching to a scroll bar.

Behavior also happens on iOS. After a few seconds of viewing the requests page, the list snaps to a much larger width than is initially seen.

**What version of Overseerr are you running?**
1.6.0

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Go to 'Requests'
2. Start playing with the browser window width.
3. Change browser width small enough to force the mobile view
4. Wait for a second or two
5. See the list snap back to an extreme width, moving the previously seen statuses to outside the window.

**Expected behavior**
More so a _wanted_ behavior: Continue condensing the requests list so all information remains visible. I'd be ok with the height of each entry increasing to accommodate the data. We shouldn't have to scroll right or left on the mobile view 

**Screenshots**
Unlisted YouTube video: https://youtu.be/r3HHdWe3AhM
First few seconds show main screen, after is the behavior of the requests page.

**Desktop (please complete the following information):**

- OS: Chrome
- Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: iPhone XS
- OS: 14.2
- Browser Chrome
- Version 87.0.4280.77

**Additional context**
n/a

**Comment by modem7** [comment]
Yup, I'm getting this on an ultrawide monitor as well.

![image](https://user-images.githubusercontent.com/4349962/102724058-9c87ae80-4304-11eb-8c55-8b78d157baa3.png)


![image](https://user-images.githubusercontent.com/4349962/102724062-a1e4f900-4304-11eb-9c88-ff6d6172bc3c.png)

**Comment by sct** [comment]
> Yup, I'm getting this on an ultrawide monitor as well.


I blieve this is a different issue? How are you causing this layout shift to happen? I cant reproduce this.

**Comment by sct** [comment]
As for the original issue @JohnnyGrey86 this is actually intended behavior. I have yet to come up with how to really render these tables in a friendly mobile view so right now they snap to a scrollable form. I will rework the display of this content in the future so that it all renders nicely on the screen in mobile form.

**Comment by modem7** [comment]
@sct I'll raise a new issue number so things don't get muddled with OP's issue.
