### ISSUE TITLE
Unable to communicate with Sonarr/Radarr. Nothing in logs or console display.

### ISSUE THREAD

**Issue by DeusMaximus** [sct/overseerr#3568]
### Description

Since updating the docker image and Overseerr to 1.33.2, I've been unable to communicate with Sonarr or Radarr, and requests immediately fail.

When testing the connection, the error message states "Failed to connect to Sonarr/Radarr".

When attempting to request anything, the error message is "Something went wrong when submitting this request".

No error messages of any kind appear in any log or the console output.

Config for Sonarr and Radarr were untouched from previous working version 7 hours ago. I have re-added the API key for Sonarr again as a test, but it still fails and doesn't state why in the logs.

It appears that Overseerr can still talk to the Plex server.

All instances of Plex, Overseerr, Radarr and Sonarr are running on the same machine.

### Version

1.33.2

### Steps to Reproduce

All functionality requiring Sonarr or Radarr fails. No logs or errors recorded and no console output occurs. "Failed to connect to Sonarr/Radarr" appears when attempting to test or re-create a Sonarr or Radarr service.

### Platform

desktop

### Device

Desktop PC (client), ls.io docker on Unraid (server)

### Operating System

Windows 11 (client), ls.io docker image running on Unraid (server)

### Browser

Opera

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by DeusMaximus** [comment]
Managed to resolve this one. "Enable CSRF Protection" was enabled at some point. Overseerr worked with this setting before 1.33.2, but since breaks after the update.

I was unable to change this setting directly, so I had to change the following to false in the settings.json file for Overseerr:

`"csrfProtection": false`

**Comment by giorgosn** [comment]
I have the same problem with "csrfProtection": false 
i am using docker
