### ISSUE TITLE
Something went wrong getting unimported Plex users

### ISSUE THREAD

**Issue by FrackerZ** [sct/overseerr#3569]
### Description

I can't import the list of users from plex, I don't know why but I can't display it when I click on import. 

### Version

1.33.2

### Steps to Reproduce

1. I click on Users.
2. I click on "import Plex Users".

### Screenshots

![error](https://github.com/sct/overseerr/assets/140951125/11e62789-15bf-4b4a-914e-973a19e57b64)

### Logs

```shell
{
 "errorMessage": "Request failed with status code 401"
}
```

### Platform

desktop

### Device

Desktop

### Operating System

Docker

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by grenius** [comment]
I am also having this issue.

**Comment by FrackerZ** [comment]
I don't encounter the problem when I log on to my ipad via safari...strange.

**Comment by rplushh** [comment]
from a closed ticket #3550, the only thing that needs to change is changing `getFriends()` to `getUsers()`.

This has been implemented in the develop branch but has not been pushed out to the main release
