### ISSUE TITLE
Users should be not be allowed to have "http" or "https" in the hostname field

### ISSUE THREAD

**Issue by samwiseg0** [sct/overseerr#357]
**Is your feature request related to a problem? Please describe.**
In the hostname field when setting up server connections, users should receive an error if they include `http` or `https` in the hostname field 

**Describe the solution you'd like**
A field validation to verify that users are not putting a URL into the hostname field.

**Describe alternatives you've considered**
Repeating to users over and over not to put a URL in the hostname field till I pass away of old age.

**Additional context**
![Screen Shot 2020-12-16 at 6 13 48 PM](https://user-images.githubusercontent.com/2241731/102418465-cd49aa00-3fcb-11eb-83d9-6866f281d4e1.png)

**Comment by sct** [comment]
What do you think about doing something like this to infer they should not include `http/https`?

![image](https://user-images.githubusercontent.com/234213/102426575-eb0e2200-4052-11eb-9d34-a02bf4356bd3.png)

If SSL is checked it changes to https

![image](https://user-images.githubusercontent.com/234213/102426603-f82b1100-4052-11eb-888d-be6c9cbacf34.png)

**Comment by samwiseg0** [comment]
I like it.

**Comment by sct** [comment]
I can do the same thing for the Radarr/Sonarr modals as well.
