### ISSUE TITLE
Correction in the web page translation

### ISSUE THREAD

**Issue by nfribeiro** [sct/overseerr#3587]
### Description

In the Portuguese version we have in the left side "Movies" instead of "Filmes, the portuguese word for movies or films.
Please update.

### Version

1.33.2

### Steps to Reproduce

In all pages

### Screenshots

![image](https://github.com/sct/overseerr/assets/5471534/cd33b5f2-9e43-40c0-8e99-2333d20d6517)

### Platform

desktop

### Device

Proxmox - LXC container

### Operating System

Debian

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Any language changes should be made with [Weblate](https://hosted.weblate.org/projects/overseerr/#languages).
