### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by quenthal** [sct/overseerr#3604]
### Description

I'm looking for Finnish (Suomi) translation of Overseerr and opening the project for Finnish on weblate. I'm willing to help as much as I can.

### Desired Behavior

Finnish translation for Overseerr

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by megasyntax** [comment]
https://github.com/sct/overseerr/blob/develop/CONTRIBUTING.md

**Comment by OwsleyJr** [comment]
Added!
