### ISSUE TITLE
Impossible to revert `Discover Region` to `All Regions`

### ISSUE THREAD

**Issue by gjobin** [sct/overseerr#3610]
### Description

General settings for `Discover Region` cannot seccessfully saved as "All Region" once a region has been saved with something else. The previously saved value always comes back.

### Version

 1.33.2

### Steps to Reproduce

1. Go to `Settings`
2. Under General Tab
3. Change `Discover Region` from `All regions` to any value.
4. Save
5. Change `Discover Region` from previously selected value to `All Regions`
6. Save
7. Refresh

### Platform

desktop

### Device

Desktop

### Operating System

MAc Ventura 13.4.2

### Browser

Chrome

### Additional Context

Same happens from phone

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Closed as this has been resolved by #3652.
