### ISSUE TITLE
Add multiple servers plex

### ISSUE THREAD

**Issue by iPleyGit** [sct/overseerr#3612]
### Description

It would be nice if you could add multiple plex servers in the configuration, and access both users and content from both.

### Desired Behavior

In the configuration, the same as we put the IP address of Plex to detect the info of the same, that several servers can be added and that the info takes it from both

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by dohlin** [comment]
Yes yes yes yes yes.  This would be absolutely awesome!

I am currently using Ombi, and I REALLY want to switch to Overseerr...but unfortunately I have two Plex servers and it would be really nice not to have to set up two completely separate instances of Overseerr just to accommodate all my users.

**Comment by danshilm** [comment]
This has been requested before but is unfortunately not something that's in the plans, would require a significant rework of how Overseerr works and therefore is not something we can consider for now.
We've also yet had time to work removing Plex as being a requirement and something like this would only be able to happen if the former happens.
We may revisit this in the future if it comes up, but I will close this issue until then and refer to it if needed.

**Comment by Drewster727** [comment]
Unfortunately, this is a deal-breaker for me. I'll have to stick to Ombi then... :(

**Comment by raindropworks** [comment]
Ironically, Ombi doesn't work for me because of multiple sonarr instances. I'm not even entirely certain why there's a need for plex/emby connection since availability seems to be more a function of the *arr connections
