### ISSUE TITLE
add Ukrainian translation

### ISSUE THREAD

**Issue by yaremko96** [sct/overseerr#3616]
### Description

Hello, I want to help add the Ukrainian language to Overseerr)

### Desired Behavior

.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Added!

**Comment by lewkoo** [comment]
Apologies for re-opening @OwsleyJr, but it is not in the list of display languages as of v1.33.2. Am I missing something?
