### ISSUE TITLE
Newly Added Media isn't detected via Recently added if not using default Plex Agents

### ISSUE THREAD

**Issue by mfields05** [sct/overseerr#363]
**Describe the bug**
Newly Added Media isn't detected via Recently added if not using default Plex Agents

**What version of Overseerr are you running?**
develop-ae2ede89529342048c47310a72d7b1653504693e

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Change Media Agent to anything but Plex (Movies)
2. Add New Movie from Overseerr
3. Wait for Movie to finish downloading
4. Verify movie is showing in recently Added section in Plex
5. Check Log and see no mention of Movie
6. Also check overseerr and see request is still shown as unavailable

**Expected behavior**
Request should change to available in Overseerr

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 0
- Browser: Chrome
- Version: 87.0.4280.88

**Smartphone (please complete the following information):**

**Additional context**
Troubleshooting via Discord Channel
![RecentlyAdded](https://user-images.githubusercontent.com/48490517/102438665-bc5c6100-3fea-11eb-997f-1f3932779beb.png)
[request.txt](https://github.com/sct/overseerr/files/5706718/request.txt)

**Comment by sct** [comment]
As of 764db94f1bd7866309684d5bd56033b21cbc2e0c we should be able to process the tmdb agent now for movies. Other agents will not be supported as there is no way to cover all the possible formats and databases out there.

I will consider adding Title/Year lookup as a fallback option at some point for agents we don't support.
