### ISSUE TITLE
Set quality profiles per user

### ISSUE THREAD

**Issue by gravelfreeman** [sct/overseerr#3634]
### Description

I want my movies as remux and I want my users' movies as web-dl.

### Desired Behavior

I want the ability to setup a different quality profile for each user.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ionred** [comment]
I believe this will be rolled into the issue #609

**Comment by OwsleyJr** [comment]
Duplicate of #609.
