### ISSUE TITLE
Age Rating Filtering and User Age Restrictions

### ISSUE THREAD

**Issue by ItzMxrcxl** [sct/overseerr#3646]
### Description

I've noticed that in Overseerr, there's no way to filter by age rating (or age restrictions).

### Desired Behavior

I want to be able to filter content based on age rating. Additionally, it would be nice to set a User Age restriction, therefore users can only see and request based on this "max age" setting.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ccartano** [comment]
#3533 Sounds like what youre asking

**Comment by OwsleyJr** [comment]
Closed in favor of #3533.
