### ISSUE TITLE
"Discover Region" doesn't want to change back to "All Regions"

### ISSUE THREAD

**Issue by DragoPrime** [sct/overseerr#3651]
### Description

I've wanted to make a test to see if it shows me only the movies and series from Japan, so I've changed "Discover Region" to Japan and "Discover Language" to Japanese. Now I want to change them back but "Discover Region" is stuck on Japan, doesn't want to change even after I save settings. After a refresh it goes back to Japan an my discover page is stuck only to movies and series from Japan.

### Version

1.33.2

### Steps to Reproduce

1. Go to Settings -> General
2. Change Discover Region to Japan -> Save
3. Refresh
4. Change back to All Regions
5. Refresh
6. Still on Japan

### Screenshots

![chrome_mVf25Ptqlx](https://github.com/sct/overseerr/assets/99618256/e4e4f2cb-4ae5-4867-addd-954cd005365b)

### Platform

desktop

### Device

ASUS TUF Gaming F17

### Operating System

Windows 10

### Browser

Chrome, Edge, Firefox

### Additional Context

Overseer is hosted on Docker in Unraid from linuxserver image.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by DragoPrime** [comment]
Well, I'm dumb. Forgot to search and this was reported before.

**Comment by OwsleyJr** [comment]
Closed in favor of #3512.
