### ISSUE TITLE
Searching for Actors / Directors

### ISSUE THREAD

**Issue by nickichi84** [sct/overseerr#3655]
### Description

Pretty sure when searching for actors / directors, it would list the movies/tv shows they where in to make it quicker to discover new content.  Just noticed recently all it displays is a synopsis of the person and no further information.

I get the same thing if I use search or click on their name from another movie

### Version

1.33.2

### Steps to Reproduce

search any actor or director from the search bar at the top of discovery / movies or series.
or search from within another show and click that actor.

### Screenshots

![image](https://github.com/sct/overseerr/assets/141187977/23184ad1-9830-4d91-b6ca-057742a84e3d)

### Platform

desktop

### Device

Docker

### Operating System

Ubuntu

### Browser

Chrome 118

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
Seems to be a bug with the TMDB API. Will have to wait for a fix from their side.

**Comment by b01000100** [comment]
Same thing happening for me.  I thought I was going crazy before I checked the logs for an error.

```json

{
 "errorMessage": "[TMDB] Failed to fetch person combined credits: Request failed with status code 404",
 "personId": "64"
}
```

**Comment by ramalnirad** [comment]
Same here

**Comment by OwsleyJr** [comment]
API is working again.
