### ISSUE TITLE
Emails to include links to issues/requests

### ISSUE THREAD

**Issue by cranky-coder** [sct/overseerr#3656]
### Description

I would like to see a link in the emails that will take you directly to parts in overseer.

Im already looking at the email at that point, a link would just make it quicker and easier (especially if im seeing the requests while walking around ect)

### Desired Behavior

Examples:

New Issue email.  Would link you straight to the issue in the webui.  
New Request.  Takes you right to the request to approve, or even have an approve/reject button right in the email that will open to the approve/reject page.
Request Fulfilled.  Give the option to go to the show/movie in overseer (in case they forgot exactly what they requested) or have the "open in plex" link 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
We already have links in our emails. Make sure you set your overseerr URL in the settings.
