### ISSUE TITLE
Sonarr Season Folders do not work

### ISSUE THREAD

**Issue by Panzer1119** [sct/overseerr#367]
**Describe the bug**

When activating "Season Folders" for a Sonarr Instance and requesting a Series, the "Season Folders" Option is not activated on the Sonarr Instance for that Series.

**What version of Overseerr are you running?**

1.6.0

**To Reproduce**

1. Go to 'Discover'
2. Click on a Series and then on 'Request'
3. Request all Seasons
4. Sonarr has not selected "Season Folders" for that Series

**Expected behavior**

Sonarr should use "Season Folders" for a Series if that's activated in the Overseerr Settings.

**Screenshots**

n/a

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Opera

**Additional context**

n/a

**Comment by sct** [comment]
#358 This is fixed in develop already. Will be pushed to the latest tag soon.
