### ISSUE TITLE
[Feature Request] Add a pass-through tag for requestor 

### ISSUE THREAD

**Issue by Terebi42** [sct/overseerr#3680]
### Description

Add tags to each item in sonarr/radarr indicating the person that requested the content. This would allow for easier content cleanup to do bulk deletes

### Desired Behavior

Add tags to each item in sonarr/radarr indicating the person that requested the content. This would allow for easier content cleanup to do bulk deletes

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
We already support this.

**Comment by bkylngaucho** [comment]
FYI:  This is in the Settings...Services...Radarr/Sonarr Settings.
