### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by davidfrench0** [sct/overseerr#3685]
### Description

This isn't a issue, just a feature request. I have a few friends who I allow to request media using Overseer, and would love to be able to be able to integrate SSO services with this so that I'm able to protect the app, and have a unified log in page for all of my services. It's frustrating having to either leave Overseer exposed with just a plain login, or require users to do a double login through my SSO provider and Overseer itself just to be able to protect it. I currently use Authentik as my auth provider so would love to be able to use OAuth2/OpenID to be able to authenticate. 

Having this feature would be amazing, and I'm sure many users would benefit from it/use it. I understand that it's probably not an easy thing for you guys to integrate into the app, but if you guys have the time it would be fantastic! If it's easy to do perhaps even just enable an option to sign in with basic http header auth, as then this can be passed through from an auth provider? 

### Desired Behavior

Go to Overseer login page > Option to either log in internally/with plex, or choose SSO provider e.g. using OIDC.> User selects SSO provider and logs in to their user. 

Having the ability to be able to hide the internal login page and just automatically redirect to the SSO provider would be great, much like how apps like Portainer do. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by h3mmy** [comment]
I believe this is a duplicate of #1638

**Comment by danshilm** [comment]
Like already mentioned, this is a duplicate issue and I would like to keep all the people of the original one notified whenever there is some movement for this feature. Please subscribe to the original issue for updates whenever we have any. Closing this issue as a duplicate of #1638.
