### ISSUE TITLE
Add download progress provided by radarr/sonarr

### ISSUE THREAD

**Issue by itschasa** [sct/overseerr#3688]
### Description

I think that a key feature of Overseerr is that everything is in one place. The fact you can request both Movies and Shows in the same place makes it very convenient. However, it's currently missing a certain feature I think would be beneficial for everyone:

Displaying the download progress of requests.

This allows both the admin and users to see how long it is estimated until the request is fulfilled.

Here is how it could be displayed in the Recent Requests tab:

![image](https://github.com/sct/overseerr/assets/79016507/76d9b4d8-1966-48df-9145-3a4021efdbac)

It is a very possible feature to add, as the info is given to you by the Radarr/Sonarr API:

`/api/v3/queue/details` returns a list of movie objects, containing `estimatedCompletionTime`, `size`, and `sizeleft`:
![image](https://github.com/sct/overseerr/assets/79016507/1ced0f4c-338a-4652-912c-571766cc8137)
![image](https://github.com/sct/overseerr/assets/79016507/f1ac8935-9a22-484d-a5c7-960c74aab03b)

### Desired Behavior

For a series download, you can total the entire series size together, and the total downloaded for each torrent that's being downloaded, and for the ETA, you can just take the highest ETA from all of the downloads.

For a movie download, you only need to fetch data from one item queued, grab the data and do a little bit of maths and time conversions.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
We already support this.

**Comment by itschasa** [comment]
> We already support this.

Where can I enable this?

**Comment by OwsleyJr** [comment]
> > We already support this.
> 
> Where can I enable this?

Enable scan in your radarr/sonarr settings in Overseerr

**Comment by itschasa** [comment]
> > > We already support this.
> > 
> > Where can I enable this?
> 
> Enable scan in your radarr/sonarr settings in Overseerr 

Brilliant, thank you for quick response!
