### ISSUE TITLE
Add "Network" under details for TV Shows "Studio" under details for movies

### ISSUE THREAD

**Issue by djbobbyrhodes** [sct/overseerr#370]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
It would be helpful to be able to see the Networks / Studios in the movie/show overview page. Add a line for Network on the TV show details page under "Original Language". Add a line for Studio on the Movie details page under "Original Language." Using the tmdb API this information should be very simple to implement.

**Describe alternatives you've considered**
N/A

**Additional context**
Example: 

<img width="260" alt="Screen Shot 2020-12-17 at 10 42 32 AM" src="https://user-images.githubusercontent.com/67330126/102511142-6c1ae880-4056-11eb-8b64-ae4a74d06af9.png">

https://github.com/sct/overseerr/issues/369#issue-770154742 was locked, so I'm creating a new one with the appropriate template. Probably should be merged.

**Comment by sct** [comment]
Will get this added!
