### ISSUE TITLE
Deleted media are stuck on "requested" status

### ISSUE THREAD

**Issue by snack32** [sct/overseerr#3709]
### Description

***note:** I have only tested it with radarr, but I guess that it also happens with sonarr.

If radarr scan is enabled, monitored media that are added directly to radarr without overseerr intervention (i.e as request), correctly appears as "requested" in overseerr searches in case a movie file does not yet exist.

However, if these movies (still in "requested" status) are removed from radarr, subsequent radarr scans and media availability sync not detect that they no longer exist and remain in "requested" status.

Apart from showing inaccurate information, this means that requests for these media can no longer be made. In any case, I don't know if this behavior is expected/desired.

### Version

1.33.2

### Steps to Reproduce

1. Make sure that movie not exists in plex/radarr/overseerr (the latter in the request form). In this example, I will use the Goldeneye movie (with tmdbId 710).

2. Add the movie to radarr as monitored but without movie file (screenshot 1).

3. Run radarr scan and media availability sync. Overseerr detects the movie and marks it as "requested". (screenshot 2, log section 1 and additional context 1).

4. Remove the movie from radarr and run again the radarr scan and media availability sync.

5. Overseer not detect that Goldeneye movie has been deleted and still shows the "requested" status. (log section 2 and additional context 2).

### Screenshots

![1](https://github.com/sct/overseerr/assets/23261891/13d1d3d1-1b04-4af8-9bff-8b222acf86f1)
![2](https://github.com/sct/overseerr/assets/23261891/56b1af11-e4b4-4610-bb0d-6c9e1a811b6a)

### Logs

```shell
1# Added movie to radarr
grep -i 'goldeneye\|TMDB ID 710'
2023-12-05T11:10:07.713Z [debug][Radarr Scan]: Saved new media: GoldenEye
------
2# Deleted movie from radarr
grep -i 'goldeneye\|TMDB ID 710'
2023-12-05T11:10:07.713Z [debug][Radarr Scan]: Saved new media: GoldenEye
```

### Platform

desktop

### Device

Home server

### Operating System

Debian 11.8 "bullseye"

### Browser

Not applicable. But using Chrome

### Additional Context

1# Overseeer json media for Goldeneye with the movie in radarr.
```
curl -s http://localhost:5055/api/v1/media -H  X-Api-Key:*redacted* \
-H 'Content-Type: application/json' | jq '.results|.[]|select (.tmdbId==710)'
{
  "downloadStatus": [],
  "downloadStatus4k": [],
  "id": 134,
  "mediaType": "movie",
  "tmdbId": 710,
  "tvdbId": null,
  "imdbId": null,
  "status": 3,
  "status4k": 1,
  "createdAt": "2023-12-05T11:10:07.000Z",
  "updatedAt": "2023-12-05T11:10:07.000Z",
  "lastSeasonChange": "2023-12-05T11:10:07.000Z",
  "mediaAddedAt": null,
  "serviceId": 0,
  "serviceId4k": null,
  "externalServiceId": 903,
  "externalServiceId4k": null,
  "externalServiceSlug": "710",
  "externalServiceSlug4k": null,
  "ratingKey": null,
  "ratingKey4k": null,
  "seasons": [],
  "serviceUrl": "http://*redacted*/movie/710"
}
```

2# Overseeer json media for Goldeneye after being deleted from radarr.
```
curl -s http://localhost:5055/api/v1/media -H  X-Api-Key:*redacted* \
-H 'Content-Type: application/json' | jq '.results|.[]|select (.tmdbId==710)'
{
  "downloadStatus": [],
  "downloadStatus4k": [],
  "id": 134,
  "mediaType": "movie",
  "tmdbId": 710,
  "tvdbId": null,
  "imdbId": null,
  "status": 3,
  "status4k": 1,
  "createdAt": "2023-12-05T11:10:07.000Z",
  "updatedAt": "2023-12-05T11:10:07.000Z",
  "lastSeasonChange": "2023-12-05T11:10:07.000Z",
  "mediaAddedAt": null,
  "serviceId": 0,
  "serviceId4k": null,
  "externalServiceId": 903,
  "externalServiceId4k": null,
  "externalServiceSlug": "710",
  "externalServiceSlug4k": null,
  "ratingKey": null,
  "ratingKey4k": null,
  "seasons": [],
  "serviceUrl": "http://*redacted*:7878/movie/710"
}
```

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment]
This is the intended behavior. There are some instances where we do not want to remove a requested item.
