### ISSUE TITLE
Turkish Display Language Support

### ISSUE THREAD

**Issue by yigitgungor** [sct/overseerr#3723]
### Description

I would like to contribute to the translation of the UI to Turkish. Currently Turkish is not listed on the Weblate page.

### Desired Behavior

Display Language being able to set to Turkish

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by jordanjones98** [comment]
@sct has to add this to weblate I believe. If he does I can make the PR to add it to the language dropdown in the app.

**Comment by thurstonmills** [comment]
Indonesian, Turkish, Slovak and Maori need to be added to weblate.
