### ISSUE TITLE
Add a "Bollywood" Movie / Series Genre

### ISSUE THREAD

**Issue by AhmedNSidd** [sct/overseerr#3728]
### Description

It'd be nice to have a "Bollywood" section to the Movies & Series genre in Overseerr.

### Desired Behavior

Similar to how there are "Action" & "Animation" movies & TV Shows section in Overseerr, I'd imagine there'd be a "Bollywood" genre that'd display Bollywood movies & TV Shows.

### Additional Context

I manually edited the HTML of Overseerr to present an idea of how I image the execution would look like, note the "Bollywood" genre:

https://share.cleanshot.com/9r0H5Jvc

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Unfortunately, the genres are not something we can modify since those come straight from TMDB.
The genre would have to be added to TMDB. Doing a quick google search, I don't really see relevant results neither.
I unfortunately don't see how this would be possible.
