### ISSUE TITLE
Cannot add TV Shows when partially available.

### ISSUE THREAD

**Issue by JohnnyGrey86** [sct/overseerr#373]
**Describe the bug**
This is a copy of Issue #323, but with proper template.

Requesting additional seasons of a show already partially available fails to send to Sonarr. Tried with two shows. Adding a _new_ show works fine.

**What version of Overseerr are you running?**
develop-727fa06c18febb2a97ca219cc6bf0277ff462acd

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Search for a show already partially available.
2. Click on 'request more'
3. Select some seasons
4. Select 'Request # Season(s)'

**Expected behavior**
Seasons requested should be added to Sonarr. They never make it to Sonarr

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 87.0.4280.88 (Official Build) (64-bit)

Attached Log of everything involving the failed request.
[Sonarr Error.log](https://github.com/sct/overseerr/files/5711522/Sonarr.Error.log)

**Sonarr Version**
2.0.0.5344

**Comment by samwiseg0** [comment]
Sonarr v2 is unsupported at the moment. Please the the wiki [FAQ](https://github.com/sct/overseerr/wiki/Frequently-Asked-Questions#general-q4). 

An issue was already raised for sonarr v2 here. https://github.com/sct/overseerr/issues/282

**Comment by BodingClockchian** [comment]
Im also seeing this 'issue' with Sonarr version 3.0.4.1055.
Overseerr version: develop-67f2b57f00216ded3b34965629d6fdd2f16bc25f

**Comment by hirenshah** [comment]
I don't use Sonarr, but still have the issue where Partially Available seasons cannot be requested. 

![Screenshot_20210110-220705_Chrome Beta](https://user-images.githubusercontent.com/418112/104136862-cdea1c00-5390-11eb-82af-5fc50f7123ab.png)

**Comment by Polartch** [comment]
Same issue. I have several shows where I had previously downloaded a season or two, and when a user requests additional seasons, after I approve the request it will fail. I've tested it on 5+ shows and it fails every time when trying to request additional seasons on pre-existing shows. If I delete the show from Sonarr then request the desired season(s), it will add it just fine.


Sonarr version 1.16.0
MacOS Google Chrome desktop Version 87.0.4280.88

[error.log](https://github.com/sct/overseerr/files/5797976/error.log)
<img width="1435" alt="Screen Shot 2021-01-11 at 12 10 08 PM" src="https://user-images.githubusercontent.com/77297330/104229669-cdda3280-5409-11eb-9b36-ca675b4f07ea.png">
<img width="1426" alt="Screen Shot 2021-01-11 at 12 10 21 PM" src="https://user-images.githubusercontent.com/77297330/104229691-d2065000-5409-11eb-93cd-3ca6ae2b0afb.png">
<img width="1430" alt="Screen Shot 2021-01-11 at 12 10 34 PM" src="https://user-images.githubusercontent.com/77297330/104229693-d3377d00-5409-11eb-9c69-204c939e9a9d.png">

**Comment by hirenshah** [comment]
@Polartch Do you have the same issue as me as well? It doesn't seem to be possible to request a season (not series) which is partially available... the request slider is enabled and greyed out (see my screenshot above).

**Comment by samwiseg0** [comment]
@Polartch This is not related to your issue. Your sonarr version is not supported. https://docs.overseerr.dev/support/faq#i-receive-409-or-400-errors-when-requesting-a-movie-or-tv-show

In the future please use support as issues is not the place for support. 
https://docs.overseerr.dev/support/asking-for-support

**Comment by TheCatLady** [comment]
This issue was opened over 2.5 months ago and I am not able to repro this issue on latest/develop, so closing this.  Please open a new issue with updated logs if you encounter this issue again!

**Comment by hirenshah** [comment]
@TheCatLady This issue hasn't been resolved... if some episodes of a season are available, it is marked as Partially Available and users cannot request any episodes from that season.

![image](https://user-images.githubusercontent.com/418112/110236857-199fe880-7f30-11eb-8102-bc5ded839ad2.png)

**Comment by TheCatLady** [comment]
> @TheCatLady This issue hasn't been resolved... if some episodes of a season are available, it is marked as Partially Available and users cannot request any episodes from that season.

That is not what this bug/issue is about.  There is an open feature request for adding the ability to request partially-available seasons (#349).

**Comment by hirenshah** [comment]
Apologies, my mistake 🤦🏻‍♂️
