### ISSUE TITLE
Change wording of unavailable to something more clear like requested

### ISSUE THREAD

**Issue by Fiala06** [sct/overseerr#374]
**Is your feature request related to a problem? Please describe.**
Few of my users and fb users have thought it was broken when they request something and says "unavailable" not realizing that means unavailable in plex. 

**Describe the solution you'd like**
Maybe change "unavailable" to "requested" or something similar

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/5183146/102531733-aa64d780-4057-11eb-8fd9-4ee04334fb57.png)

**Comment by douglasparker** [comment]
I agree and think `Requested` sounds better than `Unavailable`

However, I also think that it should change from `Requested` to either `Approved`, `Processing` or some other identifier so that user knows that their request is being handled.

I'm not sure if denials should be marked as `Denied` or if they should go back to the state they were in before being requested. Depending on how denials are handled, it might be worth leaving a denial reason associated with the media as well, especially if it'll carry a visual `Denied` indicator.

**Comment by shark2k** [comment]
I'd like to add my support to this request as I was thinking of something similar.

`Unavailable` is definitely a poor way to show that a request has been approved but has not yet been added to the server.
Along the line of what @douglasparker suggested, I think it would be great to have additional statuses so our users know the progress.
For myself personally, I'll be using this without Radarr/Sonarr, so being able to set the status to something like `In Progress` or even `Adding Soon` would be nice.  This way the users have a better idea of what is going on/status of the request.

One thing I was thinking was for statuses, there could be some default ones (`Requested`, `Approved`, `Processing`) but also make it a field where the admin (or whoever the admin also gives access to) can enter status that would then be available in the "drop down" box.  It would be like one of those combo text field/drop down boxes where when you start typing it will pre-populate the list with values that are matching what you type but if it doesn't exist, once you finish typing what you want then save or whatever, it becomes a new value in the list.  This would be similar to how Plex handles the Tag field for collections.
Not sure how that would work for the Radarr/Sonarr integegration, but hopefully it would be compatible.

This might not fall under this exactly but I think the ability to change the request from `Approved` to `Denied` (and maybe be able to put a reason) would be nice in case you aren't able to fulfill the request for whatever.  Right now if you approved something but it is unavailable the only option you have is to delete the request but it would be nice to be able to switch it to `Denied` or even something else (`Not Obtainable`, so kind of goes along with what I said earlier about being able to add custom values for status).  That way if you manage to get it in the future it could always be changed back or if you changed your mind and approved something then decided for whatever reason you don't want to add that, you can just deny it and not have the request deleted and then need to deny it if it gets added again.

Just my $0.02 added to this enhancement.

-Shark2k

**Comment by loheiman** [comment]
I agree that Unavailable is confusing. Requested or Not Yet Available would be more clear.

**Comment by doob187** [comment]
For the German Users I made a request  to change age the wording now also for the English members 

From Unavailable  to Requested in English 
From 'Nicht Verfügbar' to 'Angefordert' 

You all  can help ..when you open the weblate Page and made PR on the correct part

**Comment by PotatoQuality** [comment]
I'd like to contribute as well on this.

I like the idea from @shark2k with status like " adding soon"
In addition on this, i added a request to get live the data from sonarr and radarr:  https://github.com/sct/overseerr/issues/417

**Comment by sct** [comment]
Next release will have this renamed to `Requested` for now until we get better status updates from syncing with Radarr/Sonarr.
