### ISSUE TITLE
Include Audience Score on Rotten Tomatoes Tomatometer

### ISSUE THREAD

**Issue by HarshaKota** [sct/overseerr#3747]
### Description

Most of the times Tomatometer is biased based on critics. I'd be great to also see the Audience Score beside it, so I can make a good guess to add the movie to my watchlist or not.

### Desired Behavior

 Audience Score alongside the Rotten Tomatoes Tomatometer

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
We already show this if we have it available.
