### ISSUE TITLE
Ability to filter "Discover" by original language

### ISSUE THREAD

**Issue by kingfenix** [sct/overseerr#375]
Would it be possible to allow filtering of content seen in discover page? by original language shown on the item detail page, among other items that would be useful please and thanks!

**Comment by sct** [comment]
@kingfenix Can we get this template fixed please?

**Comment by samwiseg0** [comment]
@kingfenix Can you fill out the template please?

**Comment by sct** [comment]
Closing this issue in favor of #732 as the template is correct there.
