### ISSUE TITLE
Email notification Timestamp locale

### ISSUE THREAD

**Issue by suggymoto** [sct/overseerr#3770]
### Description

When I receive email notifications the time stamp is Japan locale despite all my settings being English and UK

### Version

1.33.2

### Steps to Reproduce

Email notification timestamp showing Japan timezone

logs show correct local time to my location

### Logs

```shell
2024-02-07T16:50:00.138Z [info][Notifications]: Sending notification(s) for MEDIA_AVAILABLE{"subject":"Southland (2009)"}
```

### Platform

smartphone

### Device

iPhone 15 Pro

### Operating System

iOS 17.3

### Browser

Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
You need to set the `TZ` environment variable for the container, there's an example of setting this on the docs [here](https://docs.overseerr.dev/getting-started/installation#docker).
Here are the possible values: [link](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) - use the value in the "TZ identifier" column.
