### ISSUE TITLE
Build out compatibility with upcoming Plex Native TV Agent

### ISSUE THREAD

**Issue by rg9400** [sct/overseerr#378]
**Is your feature request related to a problem? Please describe.**
Plex is introducing a new native TV agent in line with their movie agent. It's in preview stages but will make its way to Plex Pass Beta and public releases in the future. It may be wise to be able to support it prior to larger rollouts

**Describe the solution you'd like**
The GUIDs are exactly the same as the new movie agent. For example:

```xml
guid="plex://episode/5d9c15fe2df347001e43f279" parentGuid="plex://season/5d9c0a1d6c3e37001ecdfb06" grandparentGuid="plex://show/5ea8a313629ea20040c83f83"
```
and
```xml
<Guid id="imdb://tt7553404"/>
<Guid id="tmdb://1693543"/>
<Guid id="tvdb://4880756"/>
```

Note that the way episode orders will work is not exactly clear. Seems it follows TMDB ordering, but maybe with the flexibility to use alternate orders in the future. As long as you peg things to ratingKeys, it should be okay I think...but just FYI

**Describe alternatives you've considered**
Don't upgrade I guess?

**Comment by sct** [comment]
Thanks for the heads up! Assuming that the tmdb id will come back reliably this should be easier to implement than having to lookup based on the tvdb id.

**Comment by TheCatLady** [comment]
New Plex TV Series Scanner now available for beta / Plex Pass users: https://forums.plex.tv/t/beta-new-plex-tv-series-scanner/696242
