### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by mazzetta86** [sct/overseerr#379]
**Is your feature request related to a problem? Please describe.**
It's not a problem

**Describe the solution you'd like**
I would like to contribute by translating Overseerr in Italian. Could you please include this so I can use Weblate to translate it? Thank you in advance.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sct** [comment]
I set up Italian in Weblate for you.

https://hosted.weblate.org/projects/overseerr/overseerr-frontend/it/

Thank you for the help!
