### ISSUE TITLE
Optimize Project Performance: Transition from Synchronous to Asynchronous File Operations

### ISSUE THREAD

**Issue by sangimed** [sct/overseerr#3795]
### Description

Throughout the project, various synchronous file operations such as `fs.readFileSync()`, `fs.copyFileSync()`, `fs.existsSync()`, and similar methods are utilized for tasks related to data reading, copying, and existence checking. However, the widespread use of synchronous methods raises concerns regarding application performance and scalability.

### Desired Behavior

To address these concerns, it is recommended to transition from synchronous to asynchronous file operations across the project. By adopting asynchronous methods like `fs.readFile()`, `fs.copyFile()`, `fs.access()`, and others, the application can achieve improved responsiveness and scalability, especially under heavy load conditions.

### Additional Context

![image](https://github.com/sct/overseerr/assets/857405/c0a97e72-c3fd-4bda-acb1-86f6f545c4c0)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
It has its use. Please look at where and how it's used before opening up project issues over this.
