### ISSUE TITLE
auth/reset-password/{guid} API Call

### ISSUE THREAD

**Issue by ajalewis** [sct/overseerr#3813]
### Description

I'm following the API docs to to use the `auth/reset-password/{guid}` API call where it mentions to supply the GUID however, I cannot find this value anywhere.

I have extracted the sqlite DB and can see the `resetPasswordGuid` key under the users table but its NULL for every user? Is this something you have to manually add or am I missing something?

### Version

1.33.2

### Steps to Reproduce

n/a

### Platform

desktop

### Device

n/a

### Operating System

n/a

### Browser

n/a

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
When a POST request is made to the `/reset-password` endpoint, that property will be set to a random uuid and used in the reset password link that's sent in an email. Then, when the user clicks on the link in the email, we check if that's the same uuid that was generated (and a few more conditions). If yes, we proceed with resetting the password.

If you need more info, hop on Discord and tag me in the #development channel.
