### ISSUE TITLE
A filter button to either search movies or series only.

### ISSUE THREAD

**Issue by XenosTechLabs** [sct/overseerr#386]
**Is your feature request related to a problem? Please describe.**
- No

**Describe the solution you'd like** 
- By default, it will search for both movies and series. A checkbox near the "Search Results" for the user to select if they want only series or movies to populate the search results.

**Describe alternatives you've considered**
- There is none. However in Ombi, separate searching movies and series into different pages. 

**Additional context**
- none at the moment

**Comment by sct** [comment]
Lets merge this in with #459 as it will cover this feature as well.
