### ISSUE TITLE
Add API ping to refresh Plex authentication token

### ISSUE THREAD

**Issue by stonedemoman** [sct/overseerr#3861]
### Description

Overseerr users currently have to log in periodically to refresh the authentication token for plex that allows watchlist sync. I've been alerted to the existence of a [ping function in the MyPlex module](https://python-plexapi.readthedocs.io/en/latest/modules/myplex.html#plexapi.myplex.MyPlexAccount.ping) that will refresh this token to prevent it from expiring.

### Desired Behavior

Implementation of the MyPlex module's ping function for automatic refresh of Plex authorization token so that users do not have to periodically sign in for their Plex watchlist to sync with Overseerr.

### Additional Context

![image](https://github.com/sct/overseerr/assets/78284421/6e271435-9867-4201-959a-3bcc389589dc)

![image](https://github.com/sct/overseerr/assets/78284421/e0789f69-ae90-43b7-97ec-5125ac1bdb04)

![image](https://github.com/sct/overseerr/assets/78284421/c41dfc99-4bb9-4810-ab81-f47d52a46b8a)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Was just notified of this being a thing too!
I'll implement this whenever I get some time.
