### ISSUE TITLE
[Feature Request] Add A24 to Discover Studios Section

### ISSUE THREAD

**Issue by demrich** [sct/overseerr#3890]
### Description

 It would be really nice to have A24 displayed in the Discover Studios selection

### Desired Behavior

When browsing studios in discover, have a selection for studio A24 titles

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by MilanJa** [comment]
add
```js
  {
    name: 'A24',
    image:
      'https://image.tmdb.org/t/p/w780_filter(duotone,ffffff,bababa)/1ZXsGaFPgrgS6ZZGS37AqD5uU12.png',
    url: '/discover/movies/studio/41077',
  },
 ```
to https://github.com/sct/overseerr/blob/14cf43de26e44d5ef082806c2b97a88ce4bd6c84/src/components/Discover/StudioSlider/index.tsx#L16

and make a PR

**Comment by demrich** [comment]
@MilanJa Okay, I've created the PR
