### ISSUE TITLE
Link in notification email don't pickup the Application URL config

### ISSUE THREAD

**Issue by jbrody17** [sct/overseerr#392]
**Describe the bug**
The link in the notification email don't pickup the Application URL config

**What version of Overseerr are you running?**
develop- (12/18 - Docker c9eff15b4b66)

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Click on "Overseerr" link at the top of the notification email

**Expected behavior**
Link opens the url provided in Application URL

**Additional context**
Currently opens:
https://example.com/

**Comment by Fiala06** [comment]
A link that takes you to the item in plex would also be great!

**Comment by sct** [comment]
Whoops. Forgot to update the template for the header link. Thanks!
