### ISSUE TITLE
Tautulli integration error

### ISSUE THREAD

**Issue by vicvavan** [sct/overseerr#3922]
### Description

Overseerr is failing to integrate with Tautulli. Tautulli is successfully integrated to Plex. 

Tautulli is running on the same host as Radarr/Sonarr which are both also successfully integrated with Overseer (with SSL), so I don't see how this is a certificate issue. 

### Version

1.33.2

### Steps to Reproduce

I have the following settings configured:

Hostname or IP Address: https://hostname.domain
Port: 8181
Use SSL: Checked
API Key: Obtained from Tautulli>Settings>Web Interface> Api Key

Clicking save yields: **Something went wrong while saving Tautulli settings.**

### Logs

```shell
**Something went wrong testing Tautulli connection:**
 "errorMessage": "[Tautulli] Failed to fetch Tautulli server info: read ECONNRESET"

**Something went wrong fetching Tautulli server info:**
[error][API]: Something went wrong testing Tautulli connection{"errorMessage":"[Tautulli] Failed to fetch Tautulli server info: unable to verify the first certificate"}
```

### Platform

desktop

### Device

N/A

### Operating System

Ubuntu 22.04

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by RussellLeVasseur** [comment]
Having the same issue

**Comment by Glynnryan** [comment]
Works just fine for me, except I don’t have SSL enabled. 
Have you tried without SSL enabled?

**Comment by vicvavan** [comment]
Unfortunately, it yields the same result even without SSL enabled.
