### ISSUE TITLE
Netflix recommendations

### ISSUE THREAD

**Issue by codeuriii** [sct/overseerr#3923]
### Description

I would like link a netflix account with a overseerr user and get a personalized slider with movies and tv recommendations with thumbs up and down of netflix, but all movies in slider not in netflix.

### Desired Behavior

I would like link a netflix account with a overseerr user and get a personalized slider with movies and tv recommendations with thumbs up and down of netflix, but all movies in slider not in netflix.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
I don't think we will ever have support for doing something like this. Sorry.
