### ISSUE TITLE
Plex Users can still login in while option is disabled

### ISSUE THREAD

**Issue by LazeX7** [sct/overseerr#3925]
### Description

Hello,

First I was using Jellyfin with Jellyseerr, there you had an option to only enable login for local or Jellyfin users.
I disabled local and enabled Jellyfin users and that worked fine.

Now i'm using Plex with Overseerr and there you have the option to turn off "New Plex Sign-In" I did this and only allow "Local Sign-In" But the option to login with Plex is still visible....and users can still use the plex sign in to login although the option is disabled.

![image](https://github.com/user-attachments/assets/4414e629-5363-471e-a5c3-d53bf5bccc54)
![image](https://github.com/user-attachments/assets/59a250d4-1536-4a50-ab79-0be32765a571)

### Version

v1.33.2

### Steps to Reproduce

1. Turn off the option
2. sign off
3. Go to login page and see login still there 

### Platform

desktop

### Device

Chrome

### Operating System

Debian 11 Proxmox VM

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This doesn't disable plex login, it just disables automatic plex account importing (when they have access to your server)

What you want is #3015 which will hopefully be completed sometime this year 😄

**Comment by LazeX7** [comment]
> This doesn't disable plex login, it just disables automatic plex account importing (when they have access to your server)
> 
> What you want is #3015 which will hopefully be completed sometime this year 😄

Thank you! I hope so too!! I will donate for sure
