### ISSUE TITLE
PUID/PGID and TZ ENV var support in Dockerfile

### ISSUE THREAD

**Issue by chazlarson** [sct/overseerr#394]
**Describe the bug**
Specifying the TZ ENV does not change the timezone in the container.
Container does not support PUID/PGID ENV vars to control file and folder permissions.

**What version of Overseerr are you running?**
1.9.1

**To Reproduce**

1. create a docker container specifying PUID/PGID and TZ ENV vars.
    In my case:
    ```
            "Env": [
                "PGID=1001",
                "PUID=1000",
                "TZ=America/Chicago",
                ...
    ```
    Those ids are my user: `seed`.
2. Note that all files created by the app are owned by `root`, not `seed`:
    ````
    ➜  ls -haltr /opt/overseerr
    total 4.0K
    drwxr-xr-x 1 root root   26 Dec 15 16:28 logs
    drwxrwxr-x 1 seed seed   38 Dec 15 16:28 .
    drwxrwxr-x 1 seed seed 2.2K Dec 17 11:31 ..
    -rw-r--r-- 1 root root 2.7K Dec 18 16:24 settings.json
    drwxr-xr-x 1 root root   20 Dec 18 16:25 db
    ````
3. Note date does not match the timezone specified in the ENVs.
    ```
    ➜ date
    Fri Dec 18 16:31:55 CST 2020
    ➜ docker exec overseerr date
    Fri Dec 18 22:32:00 UTC 2020
    ```

**Expected behavior**
I expected the time to match the 'TZ' and files to be owned by the `PUID/PGID`.

**Additional context**
Background information available here:

https://docs.linuxserver.io/general/understanding-puid-and-pgid

**Comment by sct** [comment]
TZ will be fixed in the next release.

As for PUID and GUID I believe that is a setup specific to the LSIO containers. I wonder if `--user` would work for our case? I think I need to set a default user for that to work but it provides the same functionality.

**Comment by chazlarson** [comment]
I'm pretty sure I've seen the PUID/PGID in non-lsio images, but any means of accomplishing the goal would be fine.

**Comment by sct** [comment]
I'm not sure if I actually have to do anything in particular to get it to work. Can you try using the `--user` flag and see if it works for you?

Should be able to do `--user uid:gid`

**Comment by samwiseg0** [comment]
`--user uid:gid` appears to work

Container Command:
```
/bin/sh -c yarn start --user 1017:1017
```

Linux Host:
```
# ls -lh /opt/overseerr/
total 4.0K
drwxr-xr-x. 2 overseerr overseerr   24 Dec 18 22:35 db
drwxr-xr-x. 2 overseerr overseerr   27 Dec 13 23:47 logs
-rw-r--r--. 1 overseerr overseerr 3.3K Dec 18 22:52 settings.json
```
Inside the container (Config Dir):
```
/app/config # ls -lh
total 4K
drwxr-xr-x    2 1017     1017          24 Dec 18 22:54 db
drwxr-xr-x    2 1017     1017          27 Dec 13 23:47 logs
-rw-r--r--    1 1017     1017        3.3K Dec 18 22:52 settings.json
```

**Comment by sct** [comment]
Maybe we can add that to the documentation and just go this route. This is the official method from Docker to pass in uid/gid.

**Comment by chazlarson** [comment]
:thumbsup:
