### ISSUE TITLE
Discover / Trending - Showing a lot of foreign language content.

### ISSUE THREAD

**Issue by jamiewgrant** [sct/overseerr#3963]
### Description

On Discovery page, Trending is showing a lot of Asian content and other foreign language content. I have filters for language and location (English, UK), but they don't appear to help. This has only been an issue for a day or so. Prior, suggestions in trending were language appropriate and in keeping with previous experiences. 

### Version

1.33.2

### Steps to Reproduce

1. Go to Discovery Tab
2. Look at Trending
3. Notice all of the wrong language and poor quality suggestions.

### Screenshots

![image](https://github.com/user-attachments/assets/7ee05771-2e77-4b94-aed1-0ec41f7b12c2)

### Platform

desktop

### Device

Windows PC

### Operating System

Windows 10

### Browser

Chrome

### Additional Context

I run Overseerr in a Docker container on an Unraid server. Been a very happy user for a long time. Hope this helps find a fix.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Optekah** [comment]
I'm also experiencing this issue with Docker and Unraid.

**Comment by joshuapeterson** [comment]
Just came here after googling the same issue.  I have my Discover Language set to "English" but the majority of the Trending content is not English language.

**Comment by JonnyWong16** [comment]
Trending comes directly from the TMDB homepage.

https://themoviedb.org

**Comment by dh91779** [comment]
Hi I am also experiencing this same issue I thought it was my language settings but have ran with English and USA for at least a week and no change. I hope this gettings fixed soon

**Comment by gslance** [comment]
Yep, same here. Very annoying, I wish we could change the source to something else or have more options to filter for Discovery...

**Comment by AlliAlliAlli** [comment]
Not sure if this is the same issue or a different one but my trending section isn't even filled with movies or shows, it's just actors and actresses.

**Comment by JonnyWong16** [comment]
https://www.themoviedb.org/talk/6711c96f097c3d7760f87c6a#6713eced99f22f326aad25e7

**Comment by AlliAlliAlli** [comment]
@JonnyWong16 thanks for the link! Glad to know it's the same problem and that a fix is on it's way. Much appreciated :)

**Comment by sct** [comment]
Looks like this is fixed on TMDBs side so I will close this issue now.
