### ISSUE TITLE
Issue when updating past version 1.8.0

### ISSUE THREAD

**Issue by shark2k** [sct/overseerr#397]
**Describe the bug**
Whenever I update my Docker instance to a version above 1.8.0 I am no longer able to access the server at hostip:5055.
It's very possible I am doing something wrong in my docker-compose yml but going back to 1.8.0 I am able to access again.

**What version of Overseerr are you running?**
1.8.0 when it works
I have tried to upgrade to 1.9.1 and 1.10.0 with the result of losing access

**To Reproduce**
Not really sure if this will be reproduceable on your end.
All I do to reproduce is remove the :1.8.0 tag that I had added to go back to that version and run the `up -d` command for docker-compose (the 1.9.1 and 1.10.0 have already been pulled).
Once the container is recreated I am no longer able to access the web page.

**Expected behavior**
After upgrading still be able to access the webpage for my Overseerr instance.

**Screenshots**
Not really applicable but I'll post the what I see from the `docker ps` command output as I think that might be a little helpful

`docker ps` command output for 1.8.0:
![image](https://user-images.githubusercontent.com/37518107/102681960-9c1bd600-4193-11eb-9541-bc23365b3f3f.png)

`docker ps` command output for 1.10.0:
![image](https://user-images.githubusercontent.com/37518107/102681988-dab19080-4193-11eb-971a-3f6a01c22d60.png)

You can see that with 1.8.0 it shows just the port mapping of 5055 -> 3000 whereas with 1.10.0 it shows port 5055 and 5055 -> 3000, which I believe is what's causing the issue

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: Chrome
- Version: 87.0.4280.88

**Smartphone (please complete the following information):**

N/A

**Additional context**
I will also upload my log which might be helpful (I know there are some other errors in there about "failing to process plex item" so maybe that is helpful for other troubleshooting).
If you look at the log and check out the entries when the server is loaded you will see only 1.8.0 says "Server ready on port 3000" for 1.9.1 and 1.10.0 it says "Server ready on port 5055".
[overseerr.log](https://github.com/sct/overseerr/files/5718960/overseerr.log)

And what is in my docker-compose yml:

>overseerr:
>    image: sctx/overseerr
>    container_name: overseerr
>    restart: unless-stopped
>    environment:
>      - PUID=${PUID}
>      - PGID=${PGID}
>      - TZ=America/New_York
>      - LOG_LEVEL=info
>    ports:
>      - 5055:3000
>    volumes:
>      - /opt/appdata/overseerr:/app/config

Again, I might have something not set correctly in Docker as I'm not intimately familiar but good enough to normally get stuff up and running.
I do have a similar issue to this with another container I am trying to get setup (where the port mapping is not working how I am expecting but also issues with the IP address) but that was from the creation of that container.
With Overseerr it worked fine when initially setup with 1.8.0 (the latest version available when I initially set this up) but once I tried to upgrade I ran into the issue.

Hopefully that is enough info to start, but let me know if anything else is needed.

-Shark2k

**Comment by sct** [comment]
Check top of the wiki https://github.com/sct/overseerr/wiki#-version-191-breaking-change-

**Comment by shark2k** [comment]
Again, thanks for the quick response and sorry for opening an unnecessary bug (and hopefully this won't re-open this thread).

-Shark2k
