### ISSUE TITLE
Custom agent for anime is not marked as available in Overseerr

### ISSUE THREAD

**Issue by PrincessLuna2253** [sct/overseerr#398]
**Describe the bug**
A lot (possibly all) of my Plex anime library is not being detected by Overseerr, even after running a manual library scan . This would allow my users to request a show that already exists on the server. This bug seems specific to anime, I spot checked my Movies and TV Shows libraries and everything seems to be detected fine.

**What version of Overseerr are you running?**
1.9.1

**To Reproduce**

1. Add anime to plex
2. Run manual library scan in Overseer
3. Check to see if the show is marked as available

**Expected behavior**
Show appears as available when searched in Overseer

**Screenshots**
Example 1: [https://i.imgur.com/LZEZROb.jpg](https://i.imgur.com/LZEZROb.jpg)
Example 2: [https://i.imgur.com/UmHLeC9.jpeg](https://i.imgur.com/UmHLeC9.jpeg)
[Proof I have Overseer set to scan my Anime library](https://i.imgur.com/0Rmd4NU.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge (Chromium)
- Version: 87.0.664.60

**Additional context**
None

**Comment by PrincessLuna2253** [comment]
Oops, it seems like this may be a duplicate of #363, [my anime library is not using one of the default Plex agents.](https://i.imgur.com/BTCQZQr.png)

**Comment by sct** [comment]
Lets continue discussion for this in #453
