### ISSUE TITLE
Add Serbian language to weblate

### ISSUE THREAD

**Issue by Shagon94** [sct/overseerr#399]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To have Serbian added to weblate

**Describe alternatives you've considered**
/shrug

**Additional context**
There are 4 "versions" of Serbian on weblate, but for 99% of the things on the internet [this](https://hosted.weblate.org/languages/sr/) one is the way to go.

**Comment by sct** [comment]
Added to Weblate: https://hosted.weblate.org/projects/overseerr/overseerr-frontend/sr/

Thanks!
