### ISSUE TITLE
Weblate doesn't recognize ellipsis

### ISSUE THREAD

**Issue by costaht** [sct/overseerr#409]
**Describe the bug**
I was translating the app with no trouble until yesterday 12/18, but today when I decided to pick it up where I left off, I got some errors like the one below

![image](https://user-images.githubusercontent.com/50637431/102698944-26ede680-420f-11eb-8493-a0b950a6cc5d.png)

If you look closely, you'll see that the source ellipsis is different from mine. Yesterday that wasn't a problem, but something has changed overnight.

**Additional context**
If I ignore the error and save the translation, it moves forward, but I'm afraid the translations will be rejected later on.

**Comment by sct** [comment]
This isn't a bug with Overseerr.

You can click the ellipsis in the button menu above the translation to get the unicode ellipsis:
![image](https://user-images.githubusercontent.com/234213/102702887-1f7c1b00-42ab-11eb-822f-97e312fef38c.png)
