### ISSUE TITLE
Docker healthcheck

### ISSUE THREAD

**Issue by modem7** [sct/overseerr#411]
**Is your feature request related to a problem? Please describe.**
Would like a docker healthcheck to be implemented if possible, especially in alpha if something gives a hard fault and needs restarting automatically via something like autoheal.

**Comment by doob187** [comment]
```
HEALTHCHECK --timeout=5s --start-period=30s --interval=15s CMD curl --silent --fail localhost:5055
```

Something like this

**Comment by modem7** [comment]
> 
> 
> ```
> HEALTHCHECK --timeout=5s --start-period=30s --interval=15s CMD curl --silent --fail localhost:5055
> ```
> 
> Something like this

Aye, I tried:

healthcheck:
  test: curl --fail -s 127.0.0.1:5055 || exit 1
  interval: 5s
  retries: 3

But it keeps failing unfortunately.

**Comment by sct** [comment]
Would a public status endpoint on the api suffice for the check?

**Comment by modem7** [comment]
> 
> 
> Would a public status endpoint on the api suffice for the check?

That's be perfect!

**Comment by doob187** [comment]
So when  you install curl 
And take this command 

```

docker exec overseerr /bin/sh -c "apk update -y"
docker exec overseerr /bin/sh -c "apk add curl -y"
docker exec overseerr /bin/sh -c "curl --fail http://127.0.01:5055"

```
It works 

So next test.. 

Different  port 

```
docker exec overseerr /bin/sh -c "curl --fail http://127.0.01:5005"
curl: (7) Failed to connect to 127.0.01 port 5005: Connection refused
```
Wrong port and it's print the fail

**Comment by samwiseg0** [comment]
Maybe this to future proof when/if TLS is supported? Also after the public status endpoint is added. 

```
HEALTHCHECK --start-period=90s CMD curl -ILfSs http://localhost:5055/api/v1/status > /dev/null || curl -ILfkSs https://localhost:5055/api/v1/status > /dev/null || exit 1
```

**Comment by doob187** [comment]
For HEALTHCHECK  you don't need a TLS Option,
It's  internal  check only.
The curl command is enough.
It's just for the user the runs autoheal or portainer to monitor the dockers

**Comment by modem7** [comment]
In the interim until an endpoint is created, adding curl to the image should be enough to get a "curl --fail -s 127.0.0.1:5055 || exit 1" check done

**Comment by sct** [comment]
We do have a public status endpoint now at `/api/v1/status` which returns the current commitTag. (Used for the update notification)

Could try using that?

**Comment by modem7** [comment]
Ahhah! I must have missed that update!

Endpoint works, but curl needs to be added to the image for the HC to work

**Comment by ericzinnikas** [comment]
@modem7 this is working for me, though the included version of wget is very limited so there might be edge cases where it fails, but I believe it will exit non-zero on any non-200 HTTP response:
```
    healthcheck:
      test: wget http://localhost:5055/api/v1/status -o /dev/null || exit 1
      ...
```

**Comment by modem7** [comment]
Works beautifully! Thanks!

**Comment by modem7** [comment]
Raised this as a pull request to add to dockerfile.

https://github.com/sct/overseerr/pull/2051
