### ISSUE TITLE
Docker email and discord env variables

### ISSUE THREAD

**Issue by modem7** [sct/overseerr#412]
**Is your feature request related to a problem? Please describe.**
Please implement (if it hasn't already, couldn't find it) email variables for docker for the email and discord variables.

**Describe the solution you'd like**
This would allow for easier management of variables in an env file

**Comment by sct** [comment]
It would require a bit of work to rewrite the settings system to support this. I'm curious what's the use case for this?

**Comment by modem7** [comment]
So in this case, it would make it easier to manage new installs, or recreating installs from scratch, especially with Google app passwords (due to 2fa) etc.

I typically keep my passwords/variables such as discord Webhooks in an env file (secrets usually in the case of passwords).

It mostly makes it easier to centrally manage things rather than rely on going to the app(s) and changing settings.

**Comment by samwiseg0** [comment]
Why would you need to change it that often? Also once you redeploy and you use the previous backup you don't have to change anything?

**Comment by sct** [comment]
Either way it's definitely possible but something I'll tackle in the long term.

**Comment by modem7** [comment]
> 
> 
> Why would you need to change it that often? Also once you redeploy and you use the previous data backup you don't have to change anything?

For me, it's more of a centrally managed convenience rather than anything else. But absolutely agreed, the values shouldn't need to change much at all.

@sct Aye, it's definitely not an immediate request, more something that I thought I'd raise to keep on the radar for as and when. There's undoubtedly far more important priorities.

**Comment by modem7** [comment]
Bumping so this doesn't get closed automatically.
