### ISSUE TITLE
Requesting media already in Radarr/Sonarr allows it to be repeatedly requested

### ISSUE THREAD

**Issue by SlothstronautX** [sct/overseerr#415]
**Describe the bug**
When requesting any media, and it already exists in Radarr but is not available, Overseerr will throw an error that the media could not be sent to Radarr (correct behavior) but still adds the media to the Overseerr requests queue.

Logging out and back in or reloading the page will allow the same media to be requested again with the same result, generating multiple entries in the Requested section and generating an alert for every instance it was requested when its finally downloaded.

**What version of Overseerr are you running?**
1.11.0

You can find it under: Settings -> About -> Version

**To Reproduce**
This was outlined in the description

**Expected behavior**
A failure to add the media to Radarr should be an error that is expected to happen from time to time. Either the request needs to be aborted completely and no entry is made, or the error from Radarr is parsed and a decision made based on the error. (e.g. if Radarr cant be reached, fatal error and the request is aborted. If Radarr throws error that media is already requested, process the request in Overseerr and instruct Radarr to scan for a release)

**Screenshots**
No screenshots available, just envision a requests page with 5 entries all for the same crappy movie :), all showing unavailable.

**Desktop (please complete the following information):**

- OS: Windows 20H2
- Browser Firefox
- Version 83

**Additional context**
This might be related to another ticket for handling Radarr/Sonarr requests that already exist. I only mentioned Radarr above but the exact same behaviour is evident with Sonarr as well.

**Comment by sct** [comment]
This shouldn't be possible. We send to Radarr/Sonarr asynchronously. Even if something fails, it will still write the media data in Overseerr, so a second request shouldn't be possible. Refreshing/logging out should have no affect on this either.

Is there maybe a file permission issue with your config directory?

**Comment by SlothstronautX** [comment]
A follow-up to this. The first request was made on one of the very early versions, I want to say 1.30. I was able to request it 4 more times and when it was fulfilled by Radarr it sent 5 total emails in a row, which tells me that it was recorded each time i submitted. 

Now, I am unable to reproduce it with a brand new request in 1.11. So either this was a bug that was fixed between 1.3.0 and 1.11 or I am losing my mind. You can probably close this bug as I can't reproduce it, and I'll reopen or make a new one later if I can break it again.

**Comment by samwiseg0** [comment]
Thanks for verifying!

**Comment by sct** [comment]
There was a bug in older versions where we sent multiple emails for the same request becoming available. Maybe it was that.
