### ISSUE TITLE
Cast Photos Cut Off

### ISSUE THREAD

**Issue by ramsaytc** [sct/overseerr#416]
**Describe the bug**
Cast photos are cut off vertically when they are credited for multiple roles in the movie/series.  A perfect example is "A Christmas Carol (2009); Jim Carrey's photo is nearly cut off, as he is credited for eight roles in the movie.

**What version of Overseerr are you running?**
develop-c9fe6cb0b7ea984d8e4e1cb3f284935c9da7cc2b

**To Reproduce**

1. Search for 'A Christmas Carol' and select the 2009 version of the film.
2. Scroll down to cast photos
3. Cast photos are shifted vertically, Jim Carrey's photo is the worst offender.

**Expected behavior**
It would be more pleasing to the eyes if all cast photos are aligned horizontally across the page, rather than some being higher/lower than others.

**Screenshot**
<img width="802" alt="Screen Shot 2020-12-19 at 10 31 45 PM" src="https://user-images.githubusercontent.com/16809662/102704627-e95b7e80-424b-11eb-898f-3f417b394197.png">

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.05
- Browser: Safari, Chrome/Brave

**Comment by sct** [comment]
The context here is hilarious.

I will get it fixed. Thanks for the report!

**Comment by ramsaytc** [comment]
> The context here is hilarious.
> 
> I will get it fixed. Thanks for the report!

I agree, it's an extreme example.  Thanks!
