### ISSUE TITLE
Add live request status after request is approved 

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#417]
**Is your feature request related to a problem? Please describe.**

In Overseerr, there is at this time only the status "Unavailable" and "available" for a request.
is it possible to ad more statuss for a request like in progress and/or downloading?

**Describe the solution you'd like**

From a other projected called "Petio" they fetching live the download status from Sonarr and Radarr.
![image](https://user-images.githubusercontent.com/2944704/102718794-66d5cc00-42ea-11eb-8495-27963d3a7c7d.png)

Maybe  something to consider for overseerr aswell. It is really nice for a end-user to see what the current status is of the request.

**Describe alternatives you've considered**

Instead of live status, you can consider to introduce the status in progress and wait until the internal job see the file as available on plex

**Additional context**

**Comment by sct** [comment]
First step will be syncing requests from Sonarr/Radarr into Overseerr. But I would love to also show the accurate status as well. This is planned but will come later :)

**Comment by shark2k** [comment]
This request seems like it is basically the same as this one requested earlier: https://github.com/sct/overseerr/issues/374

-Shark2k

**Comment by samwiseg0** [comment]
They are different as this one is asking for part of that request. We can leave them separate for now.

**Comment by shark2k** [comment]
> They are different as this one is asking for part of that request. We can leave them separate for now.

Sounds good.  Didn't realize that @PotatoQuality had also posted in that other request as well and mentioned they opened this request.

-Shark2k
