### ISSUE TITLE
Add support for movie collection request

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#418]
**Is your feature request related to a problem? Please describe.**

From a user perspective, it will be nice if you can request a whole movie collection.

**Describe the solution you'd like**

Give end users the ability to request a movie collection for exemple: James bond, lord of the rings

**Describe alternatives you've considered**

**Additional context**

**Comment by Fiala06** [comment]
I really like this idea!

**Comment by Magikarplvl4** [comment]
Thanks @sct for making this possible <3
