### ISSUE TITLE
Plex Recently Added Sync Job not Picking Up Recents

### ISSUE THREAD

**Issue by samclam23** [sct/overseerr#419]
**Describe the bug**
The Recently Added Sync Job is not picking up recently added media, I was able to run a full library sync and pick up the media.

**What version of Overseerr are you running?**
1.11.0

**Expected behavior**
I expected the Recently Added Sync Job to pick up the recently added movie

**Desktop (please complete the following information):**

- OS: 11.1
- Browser Chrome
- Version 87.0.4280.88 (Official Build) (x86_64)

**Terminal output showing the problem**
<img width="791" alt="Screen Shot 2020-12-20 at 10 43 02 AM" src="https://user-images.githubusercontent.com/4596461/102721628-c911db00-42b0-11eb-929e-51e157c0072f.png">

**Comment by samclam23** [comment]
Not sure why this was closed, is there some easy fix I missed for this @samwiseg0 ?

**Comment by samwiseg0** [comment]
Can you stop by support? Unfortunately, this could a few things and some debug will be needed before an issue can be opened.

**Comment by samclam23** [comment]
@samwiseg0 understood! Thank you for the quick response :)
