### ISSUE TITLE
Allow login by username only

### ISSUE THREAD

**Issue by devros42** [sct/overseerr#422]
**Is your feature request related to a problem? Please describe.**

I'm looking to possibly looking to switch from Ombi to Overseerr, but unlike Ombi, Overseerr required both a username and password to log in

**Describe the solution you'd like**

A feature similar to Omni where a non admin user only needs to input their plex username(with no password) and will be logged in after Ombi checks that user is on your friendliest 

**Describe alternatives you've considered**
I could make my users always remember their passwords, but your should meet some of my users...  It's a small group of users and nothing get approved automatically, so I'm fine taking on some risk

**Additional context**

**Comment by Nomar383** [comment]
This is the first thing I was looking for as well. No one on my plex server remembers their plex password. Sad

**Comment by samwiseg0** [comment]
From a security perspective this is a very bad idea. This would increase the risk to overseerr. This would increase the attack vectors someone could use to gain access to overseerr. 

The problem is not a technical one it is a people problem. What do your users do with their bank and other services logins? Should someone decrease security because your users cannot remember their passwords?

**Comment by Nomar383** [comment]
I don't think it hurts to offer it as an option. People have had it setup this way for years with Ombi. I'm just not that worried about it as an "attack vector". Don't make it the default obviously

**Comment by samwiseg0** [comment]
> I don't think it hurts to offer it as an option. People have had it setup this way for years with Ombi. I'm just not that worried about it as an "attack vector". Don't make it the default obviously

Of course it does. You no longer need to know someone username and password just to get in. Just their username which is far easier to obtain than someone’s password. 

Just because Ombi had bad security practices does not justify this “feature”.

**Comment by Nomar383** [comment]
But this is software for just your own personal server. If I don't care if it's less secure, what does it matter? You can ignore the checkbox that enables this feature

**Comment by doob187** [comment]
> This is the first thing I was looking for as well. No one on my plex server remembers their plex password. Sad

There is an option  on plex server.. 

Passwort reset .. 

It's a security  risk . 
When they user don't know his password . 
Simple reset the password and made a new one.

**Comment by sct** [comment]
The closest thing we will get to this is #335. If you want, you can make the username and password the same for them. Then they only need to remember the username like you said. (I don't recommend this but its your server!)
