### ISSUE TITLE
Add an (X) button to clear search on mobile devices.

### ISSUE THREAD

**Issue by 14wkinnersley** [sct/overseerr#423]
**Is your feature request related to a problem? Please describe.**

When searching for a movie or tv show on a phone(iPhone/Android), there is no option to easily clear your search, so you have to backspace the entire search.

**Describe the solution you'd like**

An (X) Button or a [Cancel] Button to easily clear your search. 

**Describe alternatives you've considered**

Backspacing all the characters.

**Additional context**

https://imgur.com/a/FwMg6kr
![IMG_0458](https://user-images.githubusercontent.com/1341459/102723582-2cf2ce80-42c6-11eb-9751-7be43447fe97.jpg)

**Comment by kieron** [comment]
Worth mentioning on this, some browsers do add it already, I do have an 'x' to clear on my Android phone using Chrome, and Chrome desktop. 

So if a custom one is to be added, native ones may need to be overridden so not to overlap them etc.

**Comment by samwiseg0** [comment]
Adding image for context
![0C77F8CA-2F57-4DE6-851B-226D6667BD55](https://user-images.githubusercontent.com/2241731/102726766-4b20f480-42ef-11eb-87bd-9a02db9f445e.jpeg)
