### ISSUE TITLE
Sort Movies /Tv Show by IMDB / RottentTomatoes / TheMovieDB score ?

### ISSUE THREAD

**Issue by Zazou89** [sct/overseerr#427]
Hello,

**Is your feature request related to a problem? Please describe.**
Sometimes it's hard to find a good movie. There should be external indicators.

**Describe the solution you'd like**
I'd like to sort movies / Tv Show by their IMDB / RottentTomatoes / TheMovieDB score in Discover tab. for example in the Popular movies :
![image](https://user-images.githubusercontent.com/206181/102728660-4aa74e80-432d-11eb-9323-eb3bc6672812.png)

**Describe alternatives you've considered**
Check every film page to check the score.

![image](https://user-images.githubusercontent.com/206181/102728620-1c297380-432d-11eb-8e32-6aa11ef1476b.png)

**Additional context**
No.

Thank you !!!

**Comment by Zazou89** [comment]
Edited :)

**Comment by sct** [comment]
There is no way to sort by RT/IMDB scores but we could sort by TMDB scores in search results (and offer other sorting methods)

**Comment by sct** [comment]
Let's merge this in with #459 as it will handle both sorting and filtering.
