### ISSUE TITLE
Add filtering/sorting to Request list

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#431]
**Is your feature request related to a problem? Please describe.**
After some time, the request overview page can be really long with available requests

**Describe the solution you'd like**
It would be nice if there is a setting in the admin page to purge available request after x days.

**Describe alternatives you've considered**

**Additional context**

**Comment by sct** [comment]
Do you mean the requests on the home page? It will not show more than 10 items.

**Comment by PotatoQuality** [comment]
Hi @sct , i mean the /requests page.

For exemple, i have now 11 items on the list with 10 request that are available.

**Comment by sct** [comment]
I plan to add better filtering and sorting to that table so you can show only pending requests. Would that suffice?

**Comment by PotatoQuality** [comment]
> I plan to add better filtering and sorting to that table so you can show only pending requests. Would that suffice?

(Y)

**Comment by sct** [comment]
This is now merged into `develop`. It will default to only showing pending requests. I will improve the available filters in the future. (There is no declined, yet)

**Comment by Magikarplvl4** [comment]
Whoop whoop!!! 👯

**Comment by Panzer1119** [comment]
But are "pending" Requests only not-approved ones?
Because i'm missing the filter option to only show Requests that are "requested" but not yet available, the filter option "pending" shows no Requests for me even though there are approved Requests, but not available yet (i'm on v1.16.0).
