### ISSUE TITLE
Notifications issue

### ISSUE THREAD

**Issue by modem7** [sct/overseerr#436]
**Describe the bug**
Email notifications aren't being sent. 
Discord works as expected.

Nothing in gmail with an attempted send.

```
today at 3:41 PM  2020-12-21T15:41:16.032Z [info][Notifications]: Sending notification for MEDIA_PENDING 
today at 3:41 PM  (node:27) UnhandledPromiseRejectionWarning: Error: 140159839280456:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
today at 3:41 PM  
today at 3:41 PM  (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 49890)
```

**What version of Overseerr are you running?**
1.11.0

You can find it under: Settings -> About -> Version

**To Reproduce**
![image](https://user-images.githubusercontent.com/4349962/102794444-4cabf480-43a3-11eb-8743-f6111bdaa8e9.png)

**Expected behavior**
Email notifications to send

**Desktop (please complete the following information):**

- OS: Docker
- Browser Waterfox
- Version 3.0.2

**Comment by sct** [comment]
Several other people reported a similar issue and resolved it by using a different port.

**Comment by modem7** [comment]
Confirmed that changing from 587 to 465 works. Thanks for the workaround!

Do we know why this is occurring at all?

**Comment by sct** [comment]
587 is TLS and 465 is SSL. It looks like nodemailer is very picky about making connections to either/or. In the case of SSL we want to enable the secure setting but... not in the case of TLS... where the docs seem to say it will handle it for us? I will need to do a little more research.

**Comment by Fiala06** [comment]
Incase this might help others I use mailgun and some reason in Tautulli I use port 587 but overseerr I had to use 465 to get working.

**Comment by samwiseg0** [comment]
Going to close this issue and put in a wiki article to help others.
