### ISSUE TITLE
Add overseer link to discord notification

### ISSUE THREAD

**Issue by modem7** [sct/overseerr#437]
**Is your feature request related to a problem? Please describe.**
Additional functionality.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/4349962/102796011-8120b000-43a5-11eb-8338-803eca3cd9b9.png)

Requesting a hyperlink to open overseer (make "pending approval" into hyperlink to https://overseer.mydomain.com/requests maybe?) to authorise requests much like in email notifications.

**Comment by goldenpipes** [comment]
Can the same thing be added for issue notifications?  Also add what the issue text is? I'll look into doing a PR but I'm a noob.
