### ISSUE TITLE
Webserver down while docker running

### ISSUE THREAD

**Issue by sean-sullivan1** [sct/overseerr#439]
**Describe the bug**
With the container started the webui/webserver is not available.

**What version of Overseerr are you running?**
sctx/overseerr:develop
You can find it under: Settings -> About -> Version
Cannot find exact version as webui is unavailable. Latest as of 12/21/2020 @ 12:00pm EST
**To Reproduce**

1. Start container

**Expected behavior**
Webserver should be running and or the log should show why the webserver has failed to start.

**Desktop (please complete the following information):**

- OS: Windows 10 x64
- Browser firefox, chrome
- Version FF83.0, C87.0.4280.88

**Additional context**
The container was working correctly before latest update.
If anyone can tell me how to manually start the webui while consoled in maybe I can find an error message.

**Comment by samwiseg0** [comment]
There has been an announcement in the wiki. Please update your container settings. 

https://github.com/sct/overseerr/wiki

**Comment by sean-sullivan1** [comment]
@samwiseg0 Thanks for your help.
