### ISSUE TITLE
Unmatched Media View

### ISSUE THREAD

**Issue by dirtycajunrice** [sct/overseerr#447]
**Is your feature request related to a problem? Please describe.**
Items that do not match just show as unavailable. There is no way currently for the admin to establish which items fall under this bucket or why without reading the logs

**Describe the solution you'd like**
Page view of a list of items that currently do not match. Possibly with the assumed reason? e.g. No tmdb id, wrong metadata agent, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by samwiseg0** [comment]
Don't do it stale-bot!

**Comment by samwiseg0** [comment]
Bump bump...

**Comment by samwiseg0** [comment]
No! Stalebot!
