### ISSUE TITLE
Partial Approval Permission Level

### ISSUE THREAD

**Issue by dirtycajunrice** [sct/overseerr#449]
**Is your feature request related to a problem? Please describe.**
Ability to assign a role that gives someone the ability to "provisionally" approve a request, 

**Describe the solution you'd like**
This is a user you trust to weed through large amounts of requests, but would still require final approval from an "approval" admin to send the request to the upstream client.  This would allow approval admins to have a requests view that was only the things already processed by the initial reviewers.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dirtycajunrice** [comment]
@samwiseg0  Wait nooo reopenn

**Comment by TheCatLady** [comment]
Sorry, but the team discussed this feature request and there are no plans to implement this.
