### ISSUE TITLE
Disable certificate checking for smtp notification

### ISSUE THREAD

**Issue by TadMSTR** [sct/overseerr#451]
**Is your feature request related to a problem? Please describe.**

I'm using the Protonmail Bridge to send smtp notifications. That requires the use of SSL/TLS but uses self-signed certificates.

**Describe the solution you'd like**

Would it be possible to allow for SSL but have an option to disable the certificate check?

**Describe alternatives you've considered**

Limited on options due to how the Protonmail Bridge works.

**Comment by sct** [comment]
Closed by 6898357b13a6aa53a55709ea95819c2b3df6784c
