### ISSUE TITLE
Request on behalf of another user

### ISSUE THREAD

**Issue by Reddax** [sct/overseerr#457]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I get users messaging me for requests, without using the site. I'd like to be able to request a movie/tv series on behalf of another user, so they'll get a notification once it's available.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hirenshah** [comment]
This would definitely be an excellent feature because I'm sure most Plex server owners have the same issue with their users :)
