### ISSUE TITLE
Release Year when Searching

### ISSUE THREAD

**Issue by 1activegeek** [sct/overseerr#462]
**Is your feature request related to a problem? Please describe.**
When searching for a title, the year of release or of series start is not shown, but it is shown when looking in other views. 

<img width="395" alt="image" src="https://user-images.githubusercontent.com/6810720/102907794-88e36180-4444-11eb-8d19-49929516f69f.png">

**Describe the solution you'd like**
Year to be shown in () next to names of series or movies, to help isolate between remakes and reboots.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/6810720/102907841-9862aa80-4444-11eb-9f9c-7d4cae550917.png">

**Describe alternatives you've considered**
Leaving it as is.

**Additional context**
None to provide.

**Comment by sct** [comment]
This is actually a bug. It should be showing the dates there.
