### ISSUE TITLE
Release Date info in Detail View

### ISSUE THREAD

**Issue by 1activegeek** [sct/overseerr#463]
**Is your feature request related to a problem? Please describe.**
There isn't any release date information for Shows/Movies in the details view. When looking at the media, can't tell when it was released. 

**Describe the solution you'd like**
Very helpful when browsing through items in the request queue or others, to see the date of release in the right bar along with ratings and such. Years are good to get the right era versions, but dates are useful for helping identify if maybe you have an indexer or download problem to investigate when its December, but the media was released in January.

**Comment by sct** [comment]
Movies already have this
![image](https://user-images.githubusercontent.com/234213/102950833-c6acbc80-450e-11eb-87e6-35fdc824875e.png)

However, shows do not. So that will be fixed.
