### ISSUE TITLE
Detection of existing requests

### ISSUE THREAD

**Issue by 1activegeek** [sct/overseerr#464]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a linkage between Sonarr/Radarr existing items, to the Requested items for the first time. Something already in Sonarr/Radarr, is not being shown as already "requested" or existing. 

**Describe the solution you'd like**
Would be great to see the ability to identify items already in Radarr/Sonarr and indicate they're already requested. This could also be a good point to introduce the ability of users to be added to be notified, when that title becomes available. I saw indications of voting coming in the future - but even being able to have multiple users request and get notified of a single entry would be fantastic.

**Comment by PotatoQuality** [comment]
Duplicate: https://github.com/sct/overseerr/issues/298

**Comment by 1activegeek** [comment]
Yup sorry about that. Will close this one.
