### ISSUE TITLE
Invalid dom-nesting in TitleCard

### ISSUE THREAD

**Issue by ankarhem** [sct/overseerr#476]
**Describe the bug**
There are descendants of an a tag which are themselves also interactive (a-tag / button).

**What version of Overseerr are you running?**
v1.13.0

[Spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element):

> The a element can be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g., buttons or other links).

**Comment by sct** [comment]
This happened when I refactored the titlecard to turn the whole thing into a link after its hovered (or clicked on mobile): https://github.com/sct/overseerr/commit/e8776fd3361c6a579fba554b3b9ae8015f726f26

I am aware of the dom nesting issue. Just need to refactor it a bit further and move the buttons outside of the `a` element and position them absolutely above the link. Will get to this eventually.
