### ISSUE TITLE
Clicking on a certain movie returns a 404 "Movie does not exist"

### ISSUE THREAD

**Issue by jbrody17** [sct/overseerr#477]
**Describe the bug**
When searching for a specific movie, the response is that the movie does not exist which returns an error page.

**What version of Overseerr are you running?**
1.12.1

**To Reproduce**

1. Search for "Euphoria"
2. Click on the 2020 movie "Euphoria: Trouble Don't Always Last"
3. See error

**Expected behavior**
Either the movie is not available to search or clicking on it does not return the error

**Screenshots**
Standard 404 page:
404 - Something went wrong
Return Home

**Additional context**
Request:
/api/v1/movie/775762?language=en
Response:
{"message":"Movie does not exist"}

Error in logs:
(node:28) UnhandledPromiseRejectionWarning: Error: [TMDB] Failed to fetch discover movies: Request failed with status code 404

at TheMovieDb.getMovieRecommendations (/app/dist/api/themoviedb.js:196:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 116)

**Comment by samwiseg0** [comment]
Seems to be an error on the TMDb side?
https://www.themoviedb.org/movie/775762-euphoria-trouble-don-t-last-always?language=en-US

**Comment by samwiseg0** [comment]
Going to close this as it is not an overseerr issue.

**Comment by jbrody17** [comment]
Yeah, turns out TMDB has the "movie" in question listed as a special...
https://www.themoviedb.org/tv/85552-euphoria/season/0/episode/1?language=en-US

Why they also have it listed as a movie, I do not know...

**Comment by samwiseg0** [comment]
> Why they also have it listed as a movie, I do not know...

More than likely its just mis-tagged. It would be easy to edit fi the page loaded lol

You could always post the issue in their forums. They are good about fixing things.
