### ISSUE TITLE
Flashing scrollbar

### ISSUE THREAD

**Issue by mrhotio** [sct/overseerr#488]
**Describe the bug**
When there's no scrollable content (content fits on screen) the scrollbar flashing when hovering different posters.

**What version of Overseerr are you running?**
develop-dd22d158ff77f730b184b6ba9d76c73df18866a2

**To Reproduce**

1. Go to a 'Actors' page with low amount of movies under their name
2. Hover the posters

**Expected behavior**
No flashing scrollbar as on most pages

**Screenshots**
https://user-images.githubusercontent.com/26902309/103089893-b7517000-45ef-11eb-873c-9f880ebdedbb.mp4

**Desktop (please complete the following information):**

- OS: mac os
- Browser chrome
- Version 87

**Comment by sct** [comment]
Can you try pulling the latest develop tag and see if this is still happening?

**Comment by mrhotio** [comment]
on `develop-d7b1c2840690c144ebf29a360defcbd6fdb21354` it's still the same and the text on the poster is only showing half width now....


https://user-images.githubusercontent.com/26902309/103090440-49a64380-45f1-11eb-9526-81d78b75b25b.mov

**Comment by sct** [comment]
Latest tag is bd947409e6e8ff313011b77adc76ccd5f9112c78

**Comment by mrhotio** [comment]
will test latest too

**Comment by mrhotio** [comment]
text is fixed again, scrollbar is the same

**Comment by sct** [comment]
Very odd. I am unable to reproduce on chrome 87 on mac osx on the same page...

https://user-images.githubusercontent.com/234213/103091107-6b75e980-4636-11eb-8173-daa6055befbc.mov

Could it be some extension interfering?

**Comment by mrhotio** [comment]
incognito same thing, using mac book pro m1 big sur

**Comment by mrhotio** [comment]
your screen height looks to be a bit more

**Comment by sct** [comment]
Okay was able to reproduce it. Looks like the content reflow's just enough that if your screen is within a few pixels of showing the scrollbar, it will jump around like this.

**Comment by sct** [comment]
Will need to investigate why the content is reflowing from just showing the absolutely positioned div but should be fixable.

**Comment by mrhotio** [comment]
I'm no longer seeing this behaviour, so closing it
