### ISSUE TITLE
Make Studio and Genre clickable and searchable

### ISSUE THREAD

**Issue by frakkingtoaster** [sct/overseerr#493]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem, but a request for usability consistency.

**Describe the solution you'd like**
It's currently possible to click on actors and other cast members of items. It would be awesome to be able to also click on 2 other tags that are listed in the item detail page: each individual genre, as well as the network/studio. Clicking on each genre would load top items for that genre, and clicking the studio would give all media that network/studio has produced. 

**Describe alternatives you've considered**
Perhaps, instead of making the genres and studios hyperlinks, there can be a row in addition to Recommendations and Similar titles for other movies/series the studios or networks have produced and maybe a row for other movies/series in those genres (inclusive).

**Additional context**
Understandably, Genre is pretty broad, so it would return many results. So that one may be already covered by Similar titles and Recommendations. 
For the networks and studios, if using hyperlinks, it would follow the same UI as clicking on the names of Director, Producer, Screenplay, etc.

**Comment by sct** [comment]
Genre might not be too awful combined with filters. Seeing the top films/series in a certain genre sorted by popularity could be fun!

**Comment by Zazou89** [comment]
Good request ! 
I'd like to view all recent "Comedy" films or something like this :)
