### ISSUE TITLE
The Rotten Tomatoes page for Soul links to the wrong movie

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [sct/overseerr#494]
**Describe the bug**
Incorrect Rotten Tomatoes page is linked in the Soul movie.

**What version of Overseerr are you running?**
Develop, but I last upgraded when 1.13 was released 

**To Reproduce**
Open the "Soul" movie page and click on the Rotten Tomatoes link. 

**Expected behavior**
The "Soul" Rotten Tomatoes page. 

**Smartphone (please complete the following information):**

- Device: Pixel 4XL
- OS: Android 11
- Browser: Chrome
- Version: 87.0.4280.101

**Additional context**
Links to https://www.rottentomatoes.com/m/mr_soul

**Comment by danshilm** [comment]
This seems to be a limitation of the Rotten Tomatoes API used
https://github.com/sct/overseerr/blob/c8c74b0ae54fcc524aa8b2edf5a5c5e5db6c1638/server/api/rottentomatoes.ts#L48-L57

**Comment by sct** [comment]
> This seems to be a limitation of the Rotten Tomatoes API used
> 
> https://github.com/sct/overseerr/blob/c8c74b0ae54fcc524aa8b2edf5a5c5e5db6c1638/server/api/rottentomatoes.ts#L48-L57
> 
> 

Correct. The matching is best effort. Two movies with the same release year and nearly same name. We can do some refinements to the matching in the RT search results to try and avoid this. But I will need to think about how.
