### ISSUE TITLE
Telegram - Notification to Requester only

### ISSUE THREAD

**Issue by costaht** [sct/overseerr#499]
**Is your feature request related to a problem? Please describe.**
The issue #365 led to a PR that will enable notifications using Telegram. According to the developer, the notification will work the same way it works on Ombi, sending all the messages to a single chatid.

**Describe the solution you'd like**
My proposal is to add telegram chatid or username (for convenience, Overseerr would get the id in background) to userprofiles. (I don't know if the last is possible). With that information in the database, Overseerr would send the notifications to the chatid on the user profile (if it exists) that the request originated from.

This way only the people involved in the request (requester and users with "Manage Requests" profile) would be notified.

**Comment by ankarhem** [comment]
I think the individual notifications should be _in addition_ to the normal one.

It is also impossible to do it via username as bots can't start conversations. So the chat id(s) has to be gathered manually.

Also before I can start on this I think it should be ironed out how this should be managed.

On the admin side we can add a field to the editable user page, just over the request permission settings. However, if this should be editable by the users themselves, where should this "profile-page" navigation be located? Top right dropdown next to sign out? Settings tab?

@sct maybe?

**Comment by sct** [comment]
Yeah this would be blocked until I have user settings pages done.

**Comment by costaht** [comment]
I think giving the user the ability to manage their own chat Id is a "plus" that could be added later on. Since the user don't sign up for Overseerr, they are actually chosen by the admin, I think, at least initially, editing the chatid could be an exclusive admin feature, considering that 90% or more of the users aren't tech savvy and wont be able to manage it them selves.

**Comment by ankarhem** [comment]
> ... considering that 90% or more of the users aren't tech savvy and wont be able to manage it them selves.

They are still going to need to be the ones who create their own chat with your bot and adding the get_id_bot to that chat to get the chat id. So if they want personalized notifications you've got to help them or they are going to be somewhat savvy.

**Comment by costaht** [comment]
> you've got to help them

I'm aware of that, and it's totally fine. In my case it's just a family thing. I just can't wait for this feature and the local users 🎉

**Comment by Mikrz** [comment]
In terms of users adding themselves to the Telegram notifier, you can have the user send the bot a message with a generated code as an identifier, and then just get the chat id from that message. This obviously could be overridden or bypassed by the admin if they wanted, but I would hope people using Telegram would at least know how to start a new conversation in the app.

"To receive notifications about your requests from Overseerr on Telegram, send a message to @botName with [short temp id code] in it!"

**Comment by costaht** [comment]
> In terms of users adding themselves to the Telegram notifier, you can have the user send the bot a message with a generated code as an identifier, and then just get the chat id from that message. This obviously could be overridden or bypassed by the admin if they wanted, but I would hope people using Telegram would at least know how to start a new conversation in the app.
> 
> "To receive notifications about your requests from Overseerr on Telegram, send a message to @botName with [short temp id code] in it!"

I definitely can see people who go beyond a "family Plex" using something like that. It's very cool but too advanced for my need and I don't know how to give life to a bot since I'm not a developer. I just want the simple. People request a movie and 30 minutes later they get a message "hey, that movie is available".
