### ISSUE TITLE
Request Modal text should be centered on mobile

### ISSUE THREAD

**Issue by kieron** [sct/overseerr#507]
**Description**
When the request modal is displayed on the desktop view and the user is admin, the left-aligned text works fine, because the title is left aligned.
However on mobile view, everything goes centred, but the text remains left-aligned, looks a bit janky- I don't think it was always like this though.

**What version of Overseerr are you running?**
1.14

**To Reproduce**
Request media, notice the text on the modal looks a bit funky, being left-aligned when everything else is centred.

**Screenshots**
![image](https://user-images.githubusercontent.com/8655212/103154516-ab9caf80-478f-11eb-8922-642430a514f9.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 87.0.4280.88

**Additional context**
Something like `text-center sm:text-left` will resolve this.

**Comment by kieron** [comment]
I'm also happy to resolve this, if it is indeed an agreed issue.

**Comment by sct** [comment]
Centering this would be fine.

**Comment by kieron** [comment]
currently not working on this anymore. up for grabs.
