### ISSUE TITLE
Remove Request Modal and immediately Request

### ISSUE THREAD

**Issue by loheiman** [sct/overseerr#511]
**Is your feature request related to a problem? Please describe.**
When i click Request, a modal is displayed and I have to click Request again. 

**Describe the solution you'd like**
Don't show a modal. Immediately request the title after clicking Request once. 

**Describe alternatives you've considered**
None available

**Additional context**
![Screen Shot 2020-12-26 at 5 27 48 PM](https://user-images.githubusercontent.com/956613/103162079-11913300-47a0-11eb-9b21-3af36883e433.png)

**Comment by sct** [comment]
This won't change for two reasons.

1. Users with auto approve could easily misclick and request something by mistake. With no confirmation, that request will end up immediately in Radarr or Sonarr.

2. The request modals will do more than just request in the future. Admins or users with permissions will have options for server or profile overrides directly in the modal before submitting the request. 

The modals are designed to operate independently of where they are called from. Your proposal would move the burden of handling requests into the pages themselves, which doesn't fit the current design plans.
