### ISSUE TITLE
Choose Which Notifications Get Sent Per Agent

### ISSUE THREAD

**Issue by gstacks13** [sct/overseerr#513]
**Is your feature request related to a problem? Please describe.**
In my current Ombi setup I have two notification agents enabled: email for my users, and Pushbullet for me.  For emails I have it set to only send notifications related to requests that user has made.  Alternatively, the Pushbullet agent sends more admin-y type notifications: new requests (and from whom), issues, etc.  This is really the only functionality I'm missing from Ombi right now, since I'm completely in the dark of when a new request is made.

**Describe the solution you'd like**
Customization of which notifications are sent on a per-agent level.

**Describe alternatives you've considered**
I could set up these notifications via Sonarr and Radarr, but those won't show up if a request is still awaiting approval, nor will they show me which of my users made the request.  It would be much better if they were integrated here.

**Comment by sct** [comment]
This is already in the works.

**Comment by gstacks13** [comment]
Wonderful! And great work thus far; even in its early stages, this is already a _huge_ improvement over Ombi!
