### ISSUE TITLE
SMTP Notifications

### ISSUE THREAD

**Issue by OzBarge** [sct/overseerr#518]
**Describe the bug**
SMTP notifications to Office365 are not working it seems. 

**What version of Overseerr are you running?**
develop-8af6a1f566769c583af7dd9e18d162717835b7cc

You can find it under: Settings -> About -> Version

**To Reproduce**
I've setup Office 365 App password, configured with:

SMTP Host: smtp.office365.com
SMTP Port: 587
Enable SSL: No (tried Yes, same result)
Auth User: my office365 username@domain.com
Auth Pass: app password setup from https://account.activedirectory.windowsazure.com/AppPasswords.aspx

**Expected behavior**
Test notification does not send. When requesting media notifications are not sent. 

**Desktop (please complete the following information):**

- OS: Win10
- Browser Edge
- Version  87.0.664.66

**Comment by sct** [comment]
What do your logs say?

**Comment by OzBarge** [comment]
Logs aren’t saving, I’m actually not sure where the config is saving. I’m using Docker on a Synology NAS device.

I’ve mapped docker/Overseerr to /config but there’s nothing at all in the docker/Overseerr folder on the Synology.

I set the container to run with higher privledge in Synology and the notification just worked. I’ve stopped/started the container and my config is saved, but I have no idea to where?...



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by samwiseg0** [comment]
That is incorrect. It’s /app/config

Please provide logs after fixing the mapping. 

You can upload logs to https://gist.github.com

**Comment by OzBarge** [comment]
That’ll do it. Thanks! Working on it now

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by samwiseg0** [comment]
Just tested with my O365 account and it works. It must be your settings/username password. If you have 2FA then you may need an app password.

**Comment by OzBarge** [comment]
It’s working now with higher permissions setup on Synology’s Docker instance and the /app/config mapping.

Thanks! Sorry for the false alarm.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by OzBarge** [comment]
Actually - no longer working. 

2020-12-28T05:01:13.259Z [debug][Notifications]: Sending email notification 
2020-12-28T05:02:05.247Z [error][Notifications]: Connection timeout

**Comment by samwiseg0** [comment]
That would be an issue where the container cannot communicate to the smtp server. Since it is as working and now it is nort. It’s not an overseerr issue.
