### ISSUE TITLE
TV shows with same tmdbId number as a movie in URL incorrectly show as available. (& Vice Versa)

### ISSUE THREAD

**Issue by JohnnyGrey86** [sct/overseerr#526]
**Describe the bug**
TV shows with the same "ID number" as a movie show as available, when they don't exist in Plex. The same is true going the reverse way. For example, http://localip:5055/movie/9350 refers to Cliffhanger. If I navigate directly to http://localip:5055/tv/9350, that refers to the show called Soldier's Girl, which does not exist in Plex, however, Overseerr shows it as available. The same thing occurs when searching for that show manually, although it may be very far down in search results.

This is confirmed by drpeppershaker, xFlawless11x, and Fiala06 on discord, roughly [here](https://discord.com/channels/783137440809746482/789002037529804833/793217559923130368)

**What version of Overseerr are you running?**
develop-8af6a1f566769c583af7dd9e18d162717835b7cc

**To Reproduce**

1. Click on an item actually existing in Plex
2. Change "tv" in URL to "movie." (or vice versa)
3. If an entry under than number exists, it will show as available, regardless of Plex availability.

**Expected behavior**
Should show as not available.

**Desktop (please complete the following information):**

- OS: Win10 Pro
- Browser Chrome
- Version Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
![image](https://user-images.githubusercontent.com/14120301/103243063-2562a380-491e-11eb-8cee-7c3502366991.png)
![image](https://user-images.githubusercontent.com/14120301/103243223-cd786c80-491e-11eb-8169-f2e1ba89e7a6.png)

**Comment by JohnnyGrey86** [comment]
Deleting the request from "Soldier's Girl" also removed it from "Cliffhanger," allowing that to be requested again. I'm guessing they will both become available again on the next scan.

**Comment by drpeppershaker** [comment]
> Deleting the request from "Soldier's Girl" also removed it from "Cliffhanger," allowing that to be requested again. I'm guessing they will both become available again on the next scan.

Confirmed as well. Both items with the same tmdb ID appear to be the same item. 

Using "Clear All Media Data" on the eroneous item will also clear the media data of the correct item.

i.e. clearing media data on Das Boot (1981)--which _is not_ in Plex also clears the media data on Spongebob Squarepants tv series--which _is_ in plex. Manually scanning plex library adds both items back.

**Comment by JohnnyGrey86** [comment]
> ...Manually scanning plex library adds both items back.

Mine automatically went back to "available" a few minutes later. It just so happens that "Cliffhanger" is one of my recently-added items, so it was automatic. If it's an older entry, it probably would still be automatic, but picked up on the next full scan instead.

**Comment by sct** [comment]
This is a mistake on my part. Completely didn't think about the fact that TMDB movies and shows can share the same id. Will need to do a little refactoring to get this fixed.

**Comment by sct** [comment]
Fixed on develop now.
