### ISSUE TITLE
[Feature request]: Auto Update

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [sct/overseerr#528]
**Is your feature request related to a problem? Please describe.**
Auto update that will update for you when there is a new version available.

**Describe the solution you'd like**
Auto update that will update for you when there is a new version available. Just like Sonarr and Raddar. Usefull when installed on a headless Linux server.

**Describe alternatives you've considered**
Manually updating.

**Additional context**

**Comment by samwiseg0** [comment]
https://docs.overseerr.dev/support/faq#how-do-i-keep-overseerr-up-to-date

**Comment by Cookie-Monster-Coder** [comment]
Watchtower is only for docker and the other one is one is not even in development... if one is manually building it on Linux you can't use watchtower...

**Comment by sct** [comment]
> Watchtower is only for docker and the other one is one is not even in development... if one is manually building it on Linux you can't use watchtower...

We are not offering support at the time for those who go the route of manually building the app. You can see the latest version on the `settings -> about` page and you can manually update if there is a change.
