### ISSUE TITLE
Security - api-docs should require authorization

### ISSUE THREAD

**Issue by freender** [sct/overseerr#529]
TC:

1. Install overseerr in docker
2. Configure reverse proxy access e.g. https://nginxproxymanager.com
3. Go to https://[your.domain]/api-docs

**Expected behavior**
Page should be available for authorized users only

**Actual Result**
Page available for non authorized user

**Comment by samwiseg0** [comment]
You can configure nginx to disallow access. That is just documentation and there would not be any security risk to your instance.

**Comment by freender** [comment]
This page allows executing remote API calls without authorization
![image](https://user-images.githubusercontent.com/40869255/103252878-a173e000-494c-11eb-8bdb-52e5a492cb9d.png)

**Comment by samwiseg0** [comment]
That is not the case. You need to provide the API key/be logged in. Try to hit execute without being logged it. You will see an unauthorized error.

<img width="1761" alt="Screen Shot 2020-12-28 at 8 47 44 PM" src="https://user-images.githubusercontent.com/2241731/103253169-024fe800-494e-11eb-8e22-19bcbb177a4e.png">

**Comment by sct** [comment]
Not a security issue. As @samwiseg0 pointed out you are logged in via cookie.

**Comment by freender** [comment]
Yep, doesn't sound as bad I I thought. Just checked on another device over internet - API is available but require cookies.

Suggestion: Add an option to disable external API. This is client facing service - end users rely on Plex account for authorization. In this case it's not feasible to isolate whole service by nginx authorization.

I am not really comfortable to expose API which I am not gonna use to whole internet

**Comment by sct** [comment]
Are you asking to disable the api documentation or the entire API?

There is absolutely 0 security concern here. The entire app requires the api to be able to function. We can't turn it off.

**Comment by freender** [comment]
Oh got it so it's same API used by frontend. In this case we can close this ticket - API documentation without authorization seems reasonable.

Thanks for detailed response!
