### ISSUE TITLE
Movies are not being added to the database

### ISSUE THREAD

**Issue by pedrofmp** [sct/overseerr#532]
tried to sync with plex and most of the movies are returning:
[debug][Plex Sync]: No Guid metadata for this title. Skipping {"ratingKey":"80724"}
only 280 out of 3000 are showing on the db.

**Comment by Magikarplvl4** [comment]
https://docs.overseerr.dev/support/faq#some-media-is-missing-from-overseerr-that-i-know-is-in-plex
