### ISSUE TITLE
Discord notification with "Application URL"

### ISSUE THREAD

**Issue by tomas-lejdung** [sct/overseerr#533]
**Describe the bug**
Discord notification does not work when "Application URL" is set to a value.

**What version of Overseerr are you running?**
1.14.0

**To Reproduce**

1. Set "Application URL" to any value
2. Test send discord notification
3. See error

**Expected behavior**
A notification on discord

**Comment by sct** [comment]
Are you using a full URL? Like https://example.com?

**Comment by Magikarplvl4** [comment]
I can't reproduce the issue, what is your full applicatio nurl?

**Comment by tomas-lejdung** [comment]
My bad, I did not use https:// part. Though it worked with the email agent and testing the discord agent did not throw any errors.

Though it does not make sense for the discord agent to fail due to missing the https://.

**Comment by sct** [comment]
Discord's api is rejecting the payload. If you don't pass a valid URL it will fail.
