### ISSUE TITLE
Rate limited auto-approval

### ISSUE THREAD

**Issue by Bothari** [sct/overseerr#536]
**Is your feature request related to a problem? Please describe.**
I am loathe to give users auto-approval in case they go and totally spam my server with requests.

**Describe the solution you'd like**
Allow us to rate limit auto-approval permissions. For example, "auto approve no more than [X] [movies|TV seasons] per [day|week|month]".

**Comment by samwiseg0** [comment]
This is a dupe of this request. https://github.com/sct/overseerr/issues/263
