### ISSUE TITLE
Internal Server Error - RangeError: 'de_DE' is not a structurally valid language tag

### ISSUE THREAD

**Issue by soonic6** [sct/overseerr#539]
**Describe the bug**
Access without deleting cooking causes: "Interal Server Error". Logging in from an Inkognito tab works.

**What version of Overseerr are you running?**
1.14.0
Docker: hub.docker.com/r/sctx/overseerr

**To Reproduce**
Try opening Overseerr with LAN IP, in an IFrame. All the same.
Access with Revere Proxy works.

**Screenshots**
https://pasteboard.co/JHs84fJ.png
Logfile: https://pastebin.com/RmpeE46P

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Chrome 
- Version Version 87.0.4280.88 (Offizieller Build) (64-Bit)

**Comment by sct** [comment]
Are you running the app in Docker? I don't see this error on the latest image?

**Comment by soonic6** [comment]
oh, i forgot about that.

yes, i am running the docker version from hub.docker.com/r/sctx/overseerr

need more informations?

**Comment by sct** [comment]
I am not sure how you are getting this error? We don't even have `de_DE` as a specific language? (Our language file for german is only `de`)

Can you show me your current cookies? (Don't show up the `connect.sid` one, but anything else)

**Comment by soonic6** [comment]
i restarted my plex server, now the error is gone. maybe my plex server was not reachable? 
https://pasteboard.co/JHu150p.png

**Comment by sct** [comment]
Well, im happy it resolved itself. I don't think it's an overseerr issue though? Let us know if it happens again I suppose!

**Comment by soonic6** [comment]
got it again:

https://pastebin.com/sBMDfENF

access about Reverse Proxy is possible, direct over LAN IP: 
![image](https://user-images.githubusercontent.com/73687921/104105701-39a88800-52b0-11eb-8db6-bfda8e85144e.png)

**Comment by sct** [comment]
For some reason your `locale` cookie is getting set to `de_DE` instead of just `de` which is causing the issue. I am not sure how that's possible as we don't every reference `de_DE` in the code...

**Comment by samwiseg0** [comment]
@soonic6 We cannot reproduce. Please use Discord for support so we can try and troubleshoot the issue. 
https://discord.gg/sZNaxsb6tc

**Comment by soonic6** [comment]
@samwiseg0 i will join discord, when the problem apears the next time. Maybe that has something to do with iFrames or Organizr.
