### ISSUE TITLE
Plex Invite System

### ISSUE THREAD

**Issue by Cyb3rGh05t** [sct/overseerr#543]
**Is your feature request related to a problem? Please describe.**

Not an issue but a request. Will it be possible to add an Plex invite system for new users like in Organizr?
Plex Invite System to have the ability to invite new users to your own plex sever over an invite code.
In Overseer you could then create an invite for your Plex server and send it through Overseerr to the user.
With this code he can then log into Overseerr with that invite code or if already a user then he uses the Plex login over Overseerr.

**Describe the solution you'd like**

Some sort of adding a plugin like in Organizr or maybe fully implemented
Having the ability to add new users to Plex over an invite system in Overseerr will be a good addition i think.

**Describe alternatives you've considered**

**Additional context**

https://organizr.app/setup-plex-invite/

**Comment by sct** [comment]
Can you be more descriptive of what a "plex invite system" is?

**Comment by Cyb3rGh05t** [comment]
> Can you be more descriptive of what a "plex invite system" is?

thanks for the reply, i edited the template provided.

**Comment by sct** [comment]
I think for now we will leave this up to Organizr. Maybe look at it again in the distant future.
