### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by RobertGleaden** [sct/overseerr#553]
**Describe the bug**
Getting a Error: Request failed with status code 400

**What version of Overseerr are you running?**
1.14.0

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Search for the "The Serpent" click in
2. Select all the Series and then hit request

**Expected behavior**
The show to be added to the requested list

**Screenshots**
![image](https://user-images.githubusercontent.com/3193292/103446030-ee202980-4c72-11eb-8023-66565f401191.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS]  Windows 10
- Browser [e.g. chrome, safari] Microsoft Edge 
- Version [e.g. 22] 87.0.664.66 (Official build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by RobertGleaden** [comment]
Seen on the FAQ that this can be caused by not using Sonnarr V3 but I am using version 3.0.4.1042

**Comment by sct** [comment]
This is because this title doesn't have a tbdbid set on TMDB yet. Add that and it should start to work once their API cache clears.

I will add better error handling for this case though, so its less confusing whats going wrong.
