### ISSUE TITLE
Specify admin email address for notifications

### ISSUE THREAD

**Issue by KyleMcKnz** [sct/overseerr#557]
**Is your feature request related to a problem? Please describe.**
I have a separate admin email than the account that the Plex server is owned by so any emails are being sent to the Plex server email rather than my management email. 

**Describe the solution you'd like**
It would be great if we could specify the Admin email address within Overseerr rather than it just pulling the email from Plex account.

**Describe alternatives you've considered**
I have thought about changing the email tied to the Plex account but I would prefer to keep that as more of a personal account rather than making it uses the more admin email.

**Additional context**
I am thinking it could be implemented similarly to Ombi

![image](https://user-images.githubusercontent.com/75816931/103449921-e95f8200-4d13-11eb-9a43-242575a17309.png)

**Comment by sct** [comment]
We send notifications to any accounts with admin or manage requests permissions. One workaround you could do in the meantime is set up a Plex account on your other email and sign into Overseerr with it. Then give that account the manage requests permission and you will get emails there as well. Or you could wait for the local accounts feature and add a local account with that email for the sole purpose of getting notifications.

**Comment by JohnnyGrey86** [comment]
Another option as a workaround: forward the mail from this specific address from the Plex owner's email to your admin email.
