### ISSUE TITLE
Hookable keywords sliders for Discover Tab

### ISSUE THREAD

**Issue by Dabu-dot** [sct/overseerr#561]
**Is your feature request related to a problem? Please describe.**
Not a problem but rather an enhancement over an existing solution. 

The " Happy Holidays" tab got a response overwhelmingly positive either from the community of Overseerr but also from my local users. As this functionality was put to an end in version 1.14.1, the next step could be to allow admins to create their own sections within the Discover Tab to pull keywords for movies and TV shows into categorized sliders.

Basically, reintroduce the "Happy Holidays" Tab but custom ones.

**Describe the solution you'd like**
Create a modal to add a specific keyword pulled from TMDB (Action, Adventure, Horror, Holidays, etc..) and a text field to add in a title linked to this custom slider. After validation, this slider would be added at the bottom of the Discovery page after all already existing sliders (N+1).

Extensively, simply allow to delete an existing custom tab.

**Additional context**
It doesn't need to be fully developped with options and allowing to re-order custom tabs. The point is to re-use the work done on the "Happy Holidays" tab and upgrade it even to the most basic point. It is also another step to custom Discovery Tab.

**Comment by sct** [comment]
This is absolutely something I want to do! I want to say the priority is medium for this but I think it needs to take a back seat to some other pressing features.

However, adding the Holiday slider means I already built out the keyword api. Basically only need a way to manage which keywords/sliders you want to show. This will be added!

**Comment by GhostPyxel** [comment]
Roger that and thanks @sct, you rock.

**Comment by costaht** [comment]
Ohh man, my girlfriend will love a Horror section just for her hahaha
