### ISSUE TITLE
No frontend handling of requests where tvdbId is null

### ISSUE THREAD

**Issue by ankarhem** [sct/overseerr#562]
**Describe the bug**
Sending a payload with tvdbId as null when requesting tvseries is unsupported and will result in a `400 Bad Request` but nothing is shown to the user in the frontend.

**What version of Overseerr are you running?**
v1.14.0

**Expected behavior**
Should handle this and show something relevant in the frontend, so that the user knows what's up. Maybe we add a section in the docs that we can link to on how they can resolve it by adding the correct id to tmdb. This way we would encourage improving the resources as well.

**Comment by samwiseg0** [comment]
We had another user with this issue today. Another idea would be if the ID is unavailable, fall back to a name search and add the series/movie that way? Is that possible?

**Comment by Magikarplvl4** [comment]
> We had another user with this issue today. Another idea would be if the ID is unavailable, fall back to a name search and add the series/movie that way? Is that possible?

If it isnt possible, maybe considering to push it to a retry/failed queue that tries to fetch the ID on a daily basis. You can mark the request with a status like something as "delayed"

**Comment by sct** [comment]
> We had another user with this issue today. Another idea would be if the ID is unavailable, fall back to a name search and add the series/movie that way? Is that possible?

Not sure if this is a great idea, since the request would happen in the background it could match the wrong series?

> If it isnt possible, maybe considering to push it to a retry/failed queue that tries to fetch the ID on a daily basis. You can mark the request with a status like something as "delayed"

Depending on the show this might end up trying over and over again for weeks or months.

**Comment by ankarhem** [comment]
We had some further discussion about this [here](https://discord.com/channels/783137440809746482/789002037529804833/795407610056278027), on how we can (optionally) send the correct tvdbId to tmdb when we have matched it correctly.

This is how to search by name in sonarr:
`/sonarr/api/v3/series/lookup?term=`

**Comment by sct** [comment]
I see. If the user must confirm the match I think it might be fine. I worry it might be a little advanced for the end-user to bother with though.

**Comment by samwiseg0** [comment]
> I see. If the user must confirm the match I think it might be fine. I worry it might be a little advanced for the end-user to bother with though.

Allow the end user to make the request and only when the admin approves it present the "fix match". Auto approvers will have to deal with matching in this case?

**Comment by sct** [comment]
> > I see. If the user must confirm the match I think it might be fine. I worry it might be a little advanced for the end-user to bother with though.
> 
> Allow the end user to make the request and only when the admin approves it present the "fix match". Auto approvers will have to deal with matching in this case?

Hm. Still not really feeling it. What if, in the case there is no tvdbid, the modal will have some extra text like "We had trouble finding the title [or something], is this data correct?" and it shows some little preview of the data fetched from the sonnar response?

**Comment by samwiseg0** [comment]
I think that would work just fine. If we can show the year and a bit of the overview I think that would work nicely.
