### ISSUE TITLE
Upcoming + Trending for TV shows

### ISSUE THREAD

**Issue by TRaSH-** [sct/overseerr#564]
**Describe the solution you'd like**

We got for movies Upcoming, Trending, Popular
And for TV shows only Popular .
I would like to see this also for TV Shows

**Describe alternatives you've considered**

Ombi v4 

**Additional context**

![image](https://user-images.githubusercontent.com/6155095/103474662-7ce19300-4da6-11eb-9f9b-ba927ea1a492.png)

**Comment by sct** [comment]
Trending is both movies and series combined. We just don't have upcoming for series.

**Comment by sct** [comment]
I am not sure what type of data you would want returned from TV upcoming? What is an upcoming tv show? Is it just a show that has an episode airing soon? Or a new show? How long until the new show is released do we show it? TV releases are not the same as movies in this way.

TMDB exposes some endpoints that I could maybe use to get something like shows on air currently, or shows that have an episode airing within the next week. Would those be of interest?

**Comment by Ynd21** [comment]
+1 to showing “TV Shows currently on air”

**Comment by TRaSH-** [comment]
Upcoming shows would be shows that are new.
S01E01 stuff.
This way you can take a look which new tv shows are too be expected

**Comment by sct** [comment]
Looks like I can use the TMDB discover api to get shows which first air date is after the current date for this. Seems to give pretty decent results.

**Comment by TRaSH-** [comment]
Sounds good

**Comment by TRaSH-** [comment]
i think ombi uses tvmaze, 
don't know if they got a API
