### ISSUE TITLE
Auto Delete Available Requests

### ISSUE THREAD

**Issue by TRaSH-** [sct/overseerr#565]
**Is your feature request related to a problem? Please describe.**

After some time, the request overview page can be really cluttered with available requests

**Describe the solution you'd like**

The option that request that have been downloaded will be removed after x days.

**Describe alternatives you've considered**

Ombi v4

**Additional context**

![image](https://user-images.githubusercontent.com/6155095/103474749-288ae300-4da7-11eb-86b9-ec5cf67154ab.png)

**Comment by nameproof** [comment]
I'd prefer the ability to hide them instead of deleting them. (Or both obviously). 

Reasoning being, just as Trash explains UI quickly gets cluttered but at the same time I'd like to in a future be able to dig down and look at stats who has requested what.

**Comment by sct** [comment]
This isn't planned but we will be adding filtering to the requests page: https://github.com/sct/overseerr/issues/431

**Comment by mariomarijananic** [comment]
I would like to see an option like delete availabe request after certain time, because I have scripts to delete movies and shows from the disk after like 30 days, and 60 days.

**Comment by TRaSH-** [comment]
Maintainer should be able to handle all of this

**Comment by mariomarijananic** [comment]
Yes, but... Users are using Watchlists, how to manage those? I delete requests manually, but they appear again... Telegram spamming starts again, endless loop and messy drives. I'm not sure how to manage users, requests and files the best way possible with as much automation possible. As said, I use local scripts to delete movies after 30 days and TV shows after 60 days.

After having 15 users, telegram notifications set, bunch of requests situation starts to become messy and hard to track.
