### ISSUE TITLE
Page width on firefox broken

### ISSUE THREAD

**Issue by savoiringfaire** [sct/overseerr#566]
**Describe the bug**
This was first described in https://github.com/sct/overseerr/issues/356#issuecomment-748668853 related to a different issue, and although modem7 said they were going to open an issue, I don't see one so I'm opening this 😄 It appears that on Firefox the 'built-in' horizontal scrolling for the items on the request page doesn't work and so the width of those items make the page very wide pushing all the request buttons off to the far right hand side.

The same issue happens on individual movie/tv pages where all the info on the top right is pushed way off to the side.

**What version of Overseerr are you running?**
develop-ce0687922a94588b3492e8ddf2e84f54dd1a0d4e

**To Reproduce**
Open the root overseer page in firefox and see the browser horizontal scroll bar being used. 

**Expected behavior**
Opening the root page you should be able to scroll each horizontal line of movies/tv's using the built-in scrolling functionality. On the tv/movie details pages the info cluster should be in the top right without scrolling and you should be able to scroll the cast without using the browser scroll bar.

**Screenshots**

(both shamelessly stolen from @modem7! 😁)

![102724062-a1e4f900-4304-11eb-9c88-ff6d6172bc3c](https://user-images.githubusercontent.com/45015065/103479785-f2aa2680-4dc7-11eb-8f87-7e107509c314.png)
![102724058-9c87ae80-4304-11eb-8c55-8b78d157baa3](https://user-images.githubusercontent.com/45015065/103479787-f3db5380-4dc7-11eb-950d-66f0dc528d9f.png)

**Desktop (please complete the following information):**

- OS: MacOS (though it appears modem7 was on windows 10)
- Browser Firefox
- Version 78.6.0esr (64-bit)

**Smartphone (please complete the following information):**

N/A

**Additional context**
N/A

**Comment by sct** [comment]
Wow yeah.. had no idea this was happening. Woops!

**Comment by sct** [comment]
Fixed in `develop` and will be in the next release

**Comment by modem7** [comment]
Huh! I honestly thought it was my jank setup here as it worked on every other browser!

Good catch Savoiringfaire!
