### ISSUE TITLE
integrate a DVR backend/service

### ISSUE THREAD

**Issue by mtonnie** [sct/overseerr#587]
At the Moment it's just possible to use radarr and sonarr to get new media. It's not possible to take into account the media which broadcasted e.g. cable or satellite.

I like to integrate a DVR back-end e.g.. tvheadend in the same way sonarr and radarr are integrated and to automatically schedule recordings from overseerr.

**Comment by mtonnie** [comment]
That's clear but overseerr will place a search request for radarr and sonarr, I guess it would be possible to create an recording request for tvheadend as well. 

And if the media has been recorded and maybe postprocessed, e.g. something like skip commercials it would be added to plex and overseerr should recognize its and close the request.

**Comment by sct** [comment]
This is out of scope for this project.
