### ISSUE TITLE
Not searching after requesting additional season to a show already existing in sonarr

### ISSUE THREAD

**Issue by bobokun** [sct/overseerr#588]
**Describe the bug**
When creating a TV series request for a show that is already existing in sonarr it will add the season requested as "monitored" but it will not execute a search for the season that was requested.

**What version of Overseerr are you running?**
develop-e2c2172ac641de58ba6bbd5efd31c7a6e8287924

**To Reproduce**
1. Have a show that is already existing in your sonarr installation. In my situation I had Modern Family show with season 10 and 11 available. All other seasons are unmonitored and missing.
2. Request for season 9 for the show above.
3. Request auto approved and season 9 now shows up as monitored 
4. Stays monitored but does not search for the season

**Expected behavior**
After step 3 Sonarr should be searching for the existing season

**Screenshots**
After step 3:
![image](https://user-images.githubusercontent.com/12660469/103696721-d72c5080-4f6c-11eb-8640-a15b3e670974.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
I've enabled debug tracing in my sonarr logs and have attached them.
[sonarr.debug.txt](https://github.com/sct/overseerr/files/5772593/sonarr.debug.txt)
Running Sonarr Version 3.0.4.1058

**Comment by Magikarplvl4** [comment]
I saw this behaviour to if a movie is already on Radarr but unmonitored.
A request from overseerr will be accepted but it doesn't triggered a monitoring and searching state in Radarr

**Comment by BodingClockchian** [comment]
Jep same for me.
Overseerr develop-1aa0005b4298fc1af9c1d0bf1f357738c0fa2673
Radarr 3.0.1.4259
Sonarr 3.0.4.1060

**Comment by Xwaler** [comment]
Experienced it too with season 3 of Westworld, would be neat to have it fixed.
Overseerr stable 1.16.0
Sonarr 3.0.4.1062

**Comment by TheCatLady** [comment]
> I saw this behaviour too if a movie is already on Radarr with a unmonitored.
> A request from overseerr will be accepted but it doesn't triggered a monitoring and searching state in Radarr

I believe the Radarr bug was fixed by @ankarhem in #760.

I'm looking into the Sonarr now.
