### ISSUE TITLE
Available Items Should Show Which Library They Are In

### ISSUE THREAD

**Issue by sysmoon14** [sct/overseerr#603]
**Is your feature request related to a problem? Please describe.**
When a user comes to Overseerr to request something that is actually already available, they currently aren't told where it is.

**Describe the solution you'd like**
The green "Available" icon could append the library name i.e. "Available in Library: TV - Documentary"

**Comment by sct** [comment]
We don't really store which plex library an item is found in. Plex libraries are also not set in stone. They can be renamed, files can be moved, etc. There could be a desync between what it shown in Overseerr and where the item actually is in Plex. Items can also be found in multiple libraries. There is a lot of stuff that can happen here and it invites a whole new UX challenge.

No plans for this. Sorry :(
