### ISSUE TITLE
eBook support

### ISSUE THREAD

**Issue by henningBunk** [sct/overseerr#605]
**Is your feature request related to a problem? Please describe.**
My users don't have a way to whish for eBooks right now so they text me directly and I forget it. A central place for these requests would be great.

**Describe the solution you'd like**
It would be sufficient to have a possibility to request books. No further automation needed.  
In the future lazylibrarian, readarr, mylar etc. support would be nice but I don't think it's necessary to bring additional value.

**Describe alternatives you've considered**
Having some kind of shared goodreads list? I don't know if this is even possible and it's not a great experience for the users.

**Additional context**
This feature request does also exist for Ombi and is the third most popular request right now: https://features.ombi.io/suggestions/120488/implement-ebook-requests

**Comment by flying-sausages** [comment]
As the author of the feature request you linked I absolutely support this hahaha.

One of the issues I can see with this is that there seems to be no good single and well maintained metadata provider for ebooks, as GoodReads lacks anywhere other than English.

**Comment by JeramieG-IDG** [comment]
This would be AMAZING and very well used by my users.

**Comment by flying-sausages** [comment]
.

**Comment by flying-sausages** [comment]
unstale

**Comment by DovahDoVolom** [comment]
This could also include audio books with Plex as I use plex's ability to play back audio as a kind of manager for audio books. I.e. Artist = Author , Album = Book , and multiple chapters being each "song".

**Comment by henningBunk** [comment]
still useful

**Comment by rascal2018** [comment]
+1

**Comment by 97WaterPolo** [comment]
+1 would absolutely love this feature

**Comment by darkcloud784** [comment]
Would love to see this implemented with Readarr.

**Comment by TheCatLady** [comment]
Sorry folks, this was discussed internally and isn't going to be implemented.

**Comment by 97WaterPolo** [comment]
Hi TheCatLady, 

Do you mind disclosing the reasons why its not feasible to implement/maintain? Just curious!

**Comment by TheCatLady** [comment]
> Do you mind disclosing the reasons why its not feasible to implement/maintain? Just curious!

We simply aren't going to add new media types unless we could provide the same great UX we currently do for movies/TV. :)  While we understand it can be disappointing when feature requests are closed/declined, we try to maintain high standards (which is what has drawn many people to Overseerr in the first place) and that sometimes means saying "no" or reducing scope.

**Comment by 97WaterPolo** [comment]
No worries thanks for the explanation :) hopefully in the future there will be a way to implement it with a great UX experience as it is right now. Thanks again for all the work towards this great project! ❤️

**Comment by Wdavery** [comment]
> > Do you mind disclosing the reasons why its not feasible to implement/maintain? Just curious!
> 
> We simply aren't going to add new media types unless we could provide the same great UX we currently do for movies/TV. :) While we understand it can be disappointing when feature requests are closed/declined, we try to maintain high standards (which is what has drawn many people to Overseerr in the first place) and that sometimes means saying "no" or reducing scope.

Thanks for the explanation, totally understandable!
Just for future reference, would you say that the reasons you couldn't provide the same UX as movies/TV are lack of a suitable backend to connect to and lack of consistent database à la TVDB/TMDB?

**Comment by ctrought** [comment]
Anyone know if any request tool supports readarr yet? I'm using ombi now for everything else, will be switching to the first one to support it.

**Comment by raiseacidic** [comment]
@TheCatLady I see you closed mine and linked it to this. Can you expand on the lack of ability to provide similar UX - I was considering taking on the feature I submitted as a contribution I made, but if there's been a lot of investigation and consideration made to this, it might save me a lot of time.. especially if a merge request isn't accepted after I spend a lot of effort on it..

**Comment by nebb00** [comment]
I would love this!

**Comment by tckelly38** [comment]
@raiseacidic did you have a chance to work on this?

**Comment by ScousePete** [comment]
I know this request is a non-starter for ebooks, but I think it is worth reconsidering for audiobooks. Plex handles audiobooks extremely well and combined with Prologue and Readarr, it is (almost) the perfect set up. All that is missing is a request system.

**Comment by flamerged** [comment]
Yeah I feel like adding e-books, audiobooks and music to overseer would make a shit ton of sense. 
@TheCatLady Would it be possible to add some requirements that would make this work somewhere like the readme file?
What from an ux, ui, api, code and what not would be needed for this to happen? Knowing the requirements might get the right people to contribute :)

**Comment by eriksneff** [comment]
Came here to find out the same - I've got Readarr / Audiobookshelf working great now, and I've got a lot of people asking me to add stuff. Overseer has been great for removing the burden of adding friends and family's tv and movie requests, but now that they're using audiobookshelf, the requests are coming non-stop. I sincerely hope the overseerr team reconsiders audiobooks.

**Comment by ctml91** [comment]
1.2k upvotes on ombi feature request site.
https://features.ombi.io/suggestions/120488/implement-ebook-requests

Whichever of the popular request applications (ombi, overseer, petio, etc) implements the book requests through readarr will get my pick and I'm sure many others too.
