### ISSUE TITLE
Let users decide which root path is used

### ISSUE THREAD

**Issue by henningBunk** [sct/overseerr#606]
**Is your feature request related to a problem? Please describe.**
I am having multiple root paths for radarr (movies, documentaris, concerts) and sonarr (series, documentary series). Right now, when a user would wish for a documentary, documentary series or a concert, that content would be added to the wrong path.

**Describe the solution you'd like**
The option not to choose a fix root path in the radarr/sonarr settings. The user can decide a root path before the request is send.  
It would be great to give the root paths friendly names which are displayed to the user:
`/array/media/video/movies` -> `Movies`

**Describe alternatives you've considered**
Some kind of programmable logic to automatically choose the root path for each item. In my case something like "genre contains 'documentary'" would help, but I don't know how other people use their root paths and maybe this is to rigid.

**Additional context**
None.

**Comment by danshilm** [comment]
Looks like #351
