### ISSUE TITLE
Cannot start initial setup

### ISSUE THREAD

**Issue by tmurphy605** [sct/overseerr#611]
**Describe the bug**
**overseerr.log:**
[error][Plex.tv API]: Something went wrong getting the account from plex.tv: getaddrinfo EAI_AGAIN plex.tv
[error][Auth]: Invalid auth token

**What version of Overseerr are you running?**
Latest Version. Just installed it.

**To Reproduce**

1. Navigate to web page
2. Attempt to log in with plex.
3. Box goes away and I am still at the same screen.

**Additional context**
I have tried signing out of plex.tv and signing out of my local plex server connection. I have rebooted the VM that overseerr is on and nothing works. Please advise. Thank you!

**Comment by unapox** [comment]
Closed with "answered on discord". What was the solution?
