### ISSUE TITLE
Show IMDB ratings beneath poster.

### ISSUE THREAD

**Issue by frakman1** [sct/overseerr#612]
Related to this [issue](https://github.com/sct/overseerr/issues/306)

It would be ideal if an IMDB rating would appear beneath each poster so I know if it's worth my time clicking on and investigating.

It would look something like this (maybe with a toggle switch)

![image](https://user-images.githubusercontent.com/5826484/104107089-e4588080-5287-11eb-8b08-f21e5249a4cd.png)

This would be similar to a [chrome extension](https://chrome.google.com/webstore/detail/imdb-ratings-viewer/daaoegihbflfijkdhalidlmochdbobgb?hl=en) that displays the ratings next to a movie title like this:

![image](https://user-images.githubusercontent.com/5826484/104107025-86c43400-5287-11eb-8f2f-1540f3187ce7.png)

**Comment by sct** [comment]
We don't even have IMDB ratings on the details page. Find me an open API to pull these from and I can make ratings more visible, until then, there is nothing I can do.

**Comment by frakman1** [comment]
Then why don't you add IMDB ratings to the details page? It's the only rating that mattes.

I included the link to the chromecast extension for ratings. Just copy the code/method used there.

**Comment by FSCorrupt** [comment]
Omdb is capable of doing this!

Example:

![Screenshot_20210110_181304.jpg](https://user-images.githubusercontent.com/45659314/104130175-9c148d80-536f-11eb-9af9-686369263754.jpg)

**Comment by sct** [comment]
> Omdb is capable of doing this!
> 
> Example:
> 
> ![Screenshot_20210110_181304.jpg](https://user-images.githubusercontent.com/45659314/104130175-9c148d80-536f-11eb-9af9-686369263754.jpg)

OMDB is limited to 1000 requests per day unless you become a patreon.

**Comment by r4f4w** [comment]
> > Omdb is capable of doing this!
> > Example:
> > ![Screenshot_20210110_181304.jpg](https://user-images.githubusercontent.com/45659314/104130175-9c148d80-536f-11eb-9af9-686369263754.jpg)
> 
> OMDB is limited to 1000 requests per day unless you become a patreon.

I guess 1000 is better than 0? 

Maybe create this function anyway and then, when it reaches 1000, it stops showing. But I highly doubt that most Overseerr users will click on more than 1000 titles per day.
