### ISSUE TITLE
Discord Notification Spam

### ISSUE THREAD

**Issue by tigervol** [sct/overseerr#614]
**Describe the bug**
User requested TV series (kids show). I approved the request and the entire series downloaded into my main TV shows folder. I then manually changed in Sonarr where it was looking for the files to be to my Kid-Friendly TV Shows folder and manually moved the content to that folder. Afterwards, the Overseerr bot sent 15 "Available" notifications until I restarted Overseerr.

**What version of Overseerr are you running?**
1.16.0

You can find it under: Settings -> About -> Version

**To Reproduce**

I have not attempted to recreate this issue, but I would assume download something to one folder, then manually move it to another one.

**Expected behavior**
Multiples of the same notification stating content availability.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Unraid
- Browser N/A
- Version N/A

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by tigervol** [comment]
![image](https://user-images.githubusercontent.com/76700138/104108634-533bd680-5294-11eb-97e6-69c345604851.png)

The second notification in the image at 4:01 PM below the line break was after container restart. I have now used the "Clear All Media Data" option and don't expect to receive additional notifications from this point forward, but I thought it was worth noting that this persisted through the restart.

**Comment by sct** [comment]
This should be resolved as of https://github.com/sct/overseerr/commit/f17fa2a2db8144bac89936f588627e8dd37bf54a in `develop`. Will be in the next release. Let me know if it happens again.
