### ISSUE TITLE
Recently added should be the same as what is in Plex

### ISSUE THREAD

**Issue by shark2k** [sct/overseerr#615]
**Describe the bug**
Recently added includes media that was not just recently added.
For example I have Fear the Walking dead showing but the last episode I added was almost 2 months ago on November 23, 2020.

**What version of Overseerr are you running?**
1.16.0 (this has been an issue for a while I've just been lazy)

**To Reproduce**

Look at the recently added compared to what has been recently added to your libraries

**Expected behavior**
Recently added should show the latest media that was added just like Plex does (with the exception of the libraries being combined, i.e., Plex has recently added for each library but Overseerr should work just like Tautulli does as an example).

**Screenshots**

![image](https://user-images.githubusercontent.com/37518107/104113861-e5ab9c80-52cb-11eb-86d3-4103745bfd2c.png)

In this image, Fear the Walking Dead was added on November 23rd, 2020 and Bull was added on January 5th of this year.  Fear the Walking Dead shouldn't be showing this far up the recently added list.

![image](https://user-images.githubusercontent.com/37518107/104113890-4a66f700-52cc-11eb-98ad-cabd194b3b50.png)

All Rise added on January 5, 2021
True Blood added on November 9, 2020
Terminator: The Sarah Conner Chronicles added at June 27, 2020
Teen Titans added at July 1, 2019
Star Trek added at September 30, 2018
Spider-Man added at February 20, 2016
Rocko's Modern Life added at August 11, 2019
Rome added at September 28, 2020
Saved by the Bell added at September 13, 2020

![image](https://user-images.githubusercontent.com/37518107/104114009-76cf4300-52cd-11eb-8728-5431af130247.png)

Just for comparison, this is how recently added shows in Plex.

![image](https://user-images.githubusercontent.com/37518107/104114015-94041180-52cd-11eb-99d7-b2fd394dc14f.png)

This is how recently added shows in Tautulli (and what makes the most sense as it combines libraries into one list).

**Desktop (please complete the following information):**
(Not really relevant but will add it)
- OS: Windows 10
- Browser: Chrome
- Version: 87.0.4280.141

**Smartphone (please complete the following information):**
N/A (I only use a browser from my laptop)

**Additional context**
Not really applicable, just to look at Tautulli as a good example of how I believe it should work)

-Shark2k

**Comment by samwiseg0** [comment]
This is not a bug. Recently added is based of when it was added to overseerr.

**Comment by shark2k** [comment]
> This is not a bug. Recently added is based of when it was added to overseerr.

That seems like an odd decision.
Why would you want to see when it was added to Overseerr?  It makes more sense for recently added to be when it was added to the server.

-Shark2k

**Comment by samwiseg0** [comment]
I don't disagree but that is how it works today. I think this should be an enhancement request. I will convert it over to one.

**Comment by shark2k** [comment]
> I don't disagree but that is how it works today. I think this should be an enhancement request. I will convert it over to one.

Thanks.  I was going to suggest maybe changing it to an enhancement.

-Shark2k

**Comment by sct** [comment]
After your initial scan, it should more closely reflect the plex recently added as new items become available.

**Comment by shark2k** [comment]
> After your initial scan, it should more closely reflect the plex recently added as new items become available.

Thanks for the response sct.

I still think using the added at from Plex makes the most sense as that will ensure that it matches what is shown in Plex, but if for some reason you want the recently added to still reflect when items were added to Overseerr, would you be willing to make it an admin optional setting to choose the sort order for recently added?

I realize it's not a big deal, but just seeing items that were added to my Plex server from a couple of years ago as recently added in Overseerr is weird and misleading.  Just today I see a show that I added back in August that just got picked up by Overseerr sometime between when I opened this ticket and my reply now and it is the first item now in my recently added for Overseer.

I realize that last bit shouldn't be common, though it does look like I might have around 43 shows/movies that are not in Overseerr (I'm not 100% as I'm looking at my library totals in Tautulli and I know I have some "duplicates" because of how I have decided to handle different cuts of movies), so it could potentially happen again.

Again though, there is a chance for items to get added to Overseerr out of order and I will sometimes go on "binge" adds (on New Years Day for instance I added 133 new movies) and I would personally prefer those adds to be in the same order as they appear on Plex, as I believe from a user stand point that consistency is a better experience.

Appreciate you taking the time to comment and ultimately the decision is up to you and whoever approves pull requests (as somebody could potentially make one to address this) but just wanted to give you my thoughts/reasoning on this.

Thanks,
-Shark2k

**Comment by flying-sausages** [comment]
Unless there are new commits in master that address this, my Recently added is sorted by date added to overseerr (therefore the last library that was scanned which is just anime), rather than sorted by the date added to Plex. It would be nice of OS imported the date added on these items and used those for the sort instead.

**Comment by sct** [comment]
Okay one thing we can do here is look at the `addedAt` value returned from the plex api and just use that to sort the media that's added. I will need to store it alongside the media info on Overseerr's end, but that should get you the exactly the same order from plex's recently added.

**Comment by sct** [comment]
I went ahead and quickly took care of this in https://github.com/sct/overseerr/commit/d688a967596afcba9799b8133089bebb5add27cf. Your next recently added sync should reorganize your recently added list in Overseerr to better reflect plex.
