### ISSUE TITLE
Choose default value for requests filter/sorting

### ISSUE THREAD

**Issue by leepeuker** [sct/overseerr#616]
**Is your feature request related to a problem? Please describe.**
On every new load of the request page, the default value for the filter option is `Pending` and for sort order `Request Date`. I don't have pending requests, so I always have to manually change the the filter to `All` or `Approved`.

**Describe the solution you'd like**
I would like an option in the settings to choose the default value for these options.

**Describe alternatives you've considered**
Instead of a default option maybe Overseerr could remember the last selected value and set it again on a new page load.

**Comment by sct** [comment]
Maybe storing the last used settings in local storage? And we prefer those each time? 🤔

**Comment by leepeuker** [comment]
> 
> 
> Maybe storing the last used settings in local storage? And we prefer those each time? 🤔

That would be better than nothing atm, but I would still prefer to have the ability to set a permanent default value, persisting over all my devices/browsers. I know I would never want to use the `Pending` filter, so what if I am using Overseer on another device or different browsers for the first time? I would always have to initially set my preferred option.

**Comment by hbooo** [comment]
Hi, 

It could be great if we were also allowed to filter on requests that are not available yet

**Comment by qazero** [comment]
+1 Would love to see this feature implemented!
