### ISSUE TITLE
TV shows which are deleted / removed from Plex cannt be re-requested

### ISSUE THREAD

**Issue by doma2345** [sct/overseerr#617]
**Describe the bug**
When a program or tv show is deleted from plex, overserr still shows it as available so it cant be re-requested

**What version of Overseerr are you running?**
1.16.0

**To Reproduce**

1. Go to plex
2. Delete TV show
3. wait for overseer to do full scan
4. search for that show in overserr

Overserr still shows it as available and and as you are unable to request

**Expected behavior**
You should be able to request it

**Additional context**

**Comment by sct** [comment]
Click the cog (manage series) button on the right and hit "Clear All Media Data" to reset the state of the media. This will let you request it again.

This is a duplicate of https://github.com/sct/overseerr/issues/377

**Comment by ManiMatter** [comment]
hi,

I agree with the original poster and see this as a bug.

After the user has deleted a movie from plex, behaviour of overseer is as follows:
Currently: Shows as Available, you can't request (unless you manually clear all media data)
Expected: Does not show anymore, and you can request (as if this was a new-to-the-world movie that you haven't had in the past)

I do not understand why the full sync does not simply take all movies / tvshows that are currently present in plex, and shows them as available, and everything that might have been there at some point just "deletes" them.

**Comment by lajoshanostra** [comment]
I recently lost two drives storing my media and in the process of re-downloading. 

@sct to clear all media data on each individual series + movie manually would take forever.

I believe @ManiMatter  earlier mentioned expectations are logically sound, and, similar to how Plex itself works.

> I do not understand why the full sync does not simply take all movies / tvshows that are currently present in plex, and shows them as available, and everything that might have been there at some point just "deletes" them.

**Comment by doma2345** [comment]
> Click the cog (manage series) button on the right and hit "Clear All Media Data" to reset the state of the media. This will let you request it again.
> 
> This is a duplicate of #377

This is being worked on here according to the thread

**Comment by cdemi** [comment]
I see that #377 has been closed. I have switched to the dev version, but it looks like the issue is still there. Is it a configuration that we need to turn on? I have checked the settings but I didn't find any related options I could turn on (unless I missed it)

**Comment by namaneko** [comment]
Want to confirm that this is still a thing on 1.32.5 stable.

Had a major drive crash and lost my libraries ... I can't get Overseerr to actually reflect that Plex has different libraries. I've removed the libraries and re-added them but Overseerr continues to list old data.

I've forced scans but the scans don't make a change.

At this point, a full re-install of Overseer seems to be required as nothing is allowing a proper reflection of the Plex libraries in Overseerr.

When clicking "Start Scan" after removing and re-adding the server, nothing happens.

**Comment by phptanker** [comment]
Can confirm, I remove shows that I have watched and I still see them as available in Overseerr.

**Comment by Royalflamejlh** [comment]
Best way I have found to remove a large amount of content is to just remove the db folder in the overseerr config and then resync everything. You will lose the previous requests but its much simpler than manually deleting them all.

**Comment by ColonelBuendia** [comment]
After being scared of doing this for months because of laziness, I just deleted the sqlite DB and was pleasently surprised to learn it didn't affect my settings at all.  The delete DB adivce was **much** more reasonable than I had assumed.  

\* For context, my setup is docker-compose, and my compose file is the default/recommended one from the [docs page](https://docs.overseerr.dev/getting-started/installation).  I took down the container, removed the sqlite file, and started it up again.

**Comment by kotyy** [comment]
> After being scared of doing this for months because of laziness, I just deleted the sqlite DB and was pleasently surprised to learn it didn't affect my settings at all. The delete DB adivce was **much** more reasonable than I had assumed.
> 
> * For context, my setup is docker-compose, and my compose file is the default/recommended one from the [docs page](https://docs.overseerr.dev/getting-started/installation). I took down the container, removed the sqlite file, and started it up again.

Just a note… Deleting the database will remove any users you’ve permitted to access Overseerr, so save those from the previous DB and add them after the new one is created.

**Comment by kotyy** [comment]
> Is this still not fixed? Was hoping to be able to clean up requests, I don't understand how this obvious edgecase wasn't considered and it's been 2 years. From my understanding, there is no way to remove request data on Overseerr without manually doing each request or deleting the entire DB

I know this is a community supported project and I’m certainly underestimating the difficulty of a proper solution, but can we get a task to manually clear approved tasks in the UI as a stopgap?

**Comment by vincenzogianfelice** [comment]
This problem is still present

**Comment by silvercolt** [comment]
Is there a solution for this that is more user-friendly than what's been proposed already? Seems the Overseer Plex Sync job should consider this.

**Comment by kanadiou** [comment]
still the issue

**Comment by ericnotthered** [comment]
Still an issue.  How can we re-open this?

**Comment by Asghardhyl1991** [comment]
Still an issue, can someone re-open this please ? :)

**Comment by Sdhb1** [comment]
Still an issue.
