### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by reaxi0n** [sct/overseerr#619]
**Is your feature request related to a problem? Please describe.**
As an admin user I like to keep to my regular users informed of backend news about the server & media. Such as increased storage, network issues, and any scheduled downtime & maintenance which saves me receiving messages from users telling me the media server is down which I already know about. :|

**Describe the solution you'd like**
Id like to see a landing & news page where I keep my users informed of any and all media server information. I rather have the landing/news page within overseerr because my users are visiting my requests page more than any other page or site I may redirect them too.

**Describe alternatives you've considered**
On my domain I setup a separate site with a button at the bottom to redirect my users to overseer. While this worked for awhile, the problem is editing the page on mobile where I find myself mobile rather than on a PC. The other problem is that users have bookmarked the url to overseer bypassing the page I setup. >:|

**Additional context**
I'd like to see a landing page that has a user editable wysiwyg editor or something similar allowing me to make news posts informing my users of any downtime and could grow into the possibility of supporting widgets listing current plex (media server) status (up/down).

**Comment by Magikarplvl4** [comment]
Please no, let's Overseerr focus to be a great request app instead of adding other nonrelevant features.
There are plenty of other apps out there to create something like a portal for users.

**Comment by flying-sausages** [comment]
A space for a custom HTML element on the dashboard at the top? I don't see a huge issue with that. I'd enforce a max-height and a wrap to enforce scrolling inside this element so as not to break the entire visual identity.

**Comment by stroodle96** [comment]
I agree this would be a welcomed feature.  I also like @evilhyde idea of just a simple message banner.  If the homepage is included there should be an easy way to disable it with a checkbox in settings.  
In addition or alternatively to this idea, it would be nice to have the option to send users custom emails with Overseer branding that we could use to notify users via email.

**Comment by evilhyde** [comment]
Bump

**Comment by FSCorrupt** [comment]
Bump
