### ISSUE TITLE
Telegram notifications with no sound

### ISSUE THREAD

**Issue by costaht** [sct/overseerr#623]
**Describe the solution you'd like**
When a notification is sent using Telegram, the recipient will get a pop-up and a notification sound. Depending on the volume of messages people will just silent messages coming from the bot.
Because I don't want my users being annoyed by my bot, I would like to request the implementation of a flag that allows us to send a message that will show the notification pop-up but **no sound**.

The parameter is "disable_notification (boolean)"
**Documentation:** https://core.telegram.org/bots/api#sendmessage

**Additional context**
Radarr implementation
![image](https://user-images.githubusercontent.com/50637431/104144339-d17da300-5390-11eb-801a-dd0fbcf8ddd6.png)

**Comment by TheCatLady** [comment]
Please assign this to me 🐱
