### ISSUE TITLE
Load posters from Plex server

### ISSUE THREAD

**Issue by TheCatLady** [sct/overseerr#626]
**Is your feature request related to a problem? Please describe.**
The poster images in Overseer for existing media do not match the custom ones I've set in my Plex server.

**Describe the solution you'd like**
Would be great if Overseer could display the posters set in Plex.  (Tautulli does this!)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by samwiseg0** [comment]
This is by design. Posters are only loaded from the TMDB.

**Comment by sct** [comment]
As @samwiseg0 said this is just how it works. We pull posters from TMDB.
