### ISSUE TITLE
Jobs - Run Now

### ISSUE THREAD

**Issue by hirenshah** [sct/overseerr#634]
**Describe the bug**
The Run Now buttons on the Jobs screen are always greyed out and clicking on them does nothing.

**What version of Overseerr are you running?**
develop-1aa0005b4298fc1af9c1d0bf1f357738c0fa2673

**To Reproduce**

1. Go to 'Settings > Jobs'
2. Click on 'Run Now'

**Expected behavior**
The respective job should run and show some indication of this on the screen 

**Screenshots**
![image](https://user-images.githubusercontent.com/418112/104304085-d5a9dd80-54c2-11eb-8544-e71fb19969f4.png)

**Comment by sct** [comment]
They are not yet implemented. The buttons are disabled for now.

**Comment by hirenshah** [comment]
@sct Ahh, that explains that then lol.

Just to note, after the job runs, the text in the Next Execution field starts counting up rather than showing when it will next run.  You have to refresh the page for it to show when the next execution will be.
