### ISSUE TITLE
Notifications (mail) localisation

### ISSUE THREAD

**Issue by ghost** [sct/overseerr#636]
**Is your feature request related to a problem? Please describe.**
Notifications like mail are in English.

**Describe the solution you'd like**
Able to get notifications in same language as interface. 

**Describe alternatives you've considered**
Use English notifications.

**Comment by costaht** [comment]
That would be nice, specially for movie names.

**Comment by sct** [comment]
Not stale.

**Comment by saschabrockel** [comment]
I would also wish that the mails or notifications, in general, had the same language as the one chosen for a user account because I got old users who do not speak English.
