### ISSUE TITLE
Custom CSS and Logo

### ISSUE THREAD

**Issue by hirenshah** [sct/overseerr#637]
**Is your feature request related to a problem? Please describe.**
I would like to tweak some parts of the UI with CSS and have my own logo.

**Describe the solution you'd like**
A section in the Settings which allows the administrator to enter Custom CSS and define the site logo.

**Describe alternatives you've considered**
Modifying the core files, but that gets quite messy when the application is updated, especially when using Docker.

**Additional context**
Something similar to what Ombi has:
![image](https://user-images.githubusercontent.com/418112/104318432-507cf380-54d7-11eb-8b82-30a39efe68e6.png)

It could also tie into this Landing Page enhancement request:
https://github.com/sct/overseerr/issues/619

**Comment by sct** [comment]
There is already a request for a custom logo here: https://github.com/sct/overseerr/issues/404

As for custom css, I have no plans for it at this time.

**Comment by pir8radio** [comment]
> There is already a request for a custom logo here: [#404](https://github.com/sct/overseerr/issues/404)
> 
> As for custom css, I have no plans for it at this time.

why?   it would be super easy to inject it.  Or do you not want people hiding that they are using Overseerr?     Just have a text box in the settings write to the settings and include those settings.  I don't use react so this is probably wrong, and you would have to secure it up im sure..  :-)  But something like this anyway.



## 1. Migration: Add `customCss` Column

```typescript name=server/migration/XXXXXX-AddCustomCssToUserSettings.ts
import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCustomCssToUserSettingsXXXXXX implements MigrationInterface {
  name = 'AddCustomCssToUserSettingsXXXXXX'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "user_settings" ADD COLUMN "customCss" text`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "user_settings" DROP COLUMN "customCss"`);
  }
}
```

---

## 2. Update UserSettings Entity

```typescript name=server/entity/UserSettings.ts
// existing imports and code...
@Column({ type: 'text', nullable: true })
public customCss?: string;
// rest of the class...
```

---

## 3. Update User Settings API Routes

- **Return `customCss` in responses:**

```typescript
// When returning user settings (inside your GET route)
customCss: user.settings?.customCss,
```

- **Save `customCss` in POST handler:**

```typescript
// When saving user settings (inside your POST route)
user.settings.customCss = req.body.customCss;
```

---

## 4. Frontend: Add Custom CSS Field to User Settings Form

```tsx name=src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
// Inside your Formik form/fields:
<div className="form-group">
  <label htmlFor="customCss">Custom CSS</label>
  <Field as="textarea" id="customCss" name="customCss" className="input" rows={6} />
  <div className="label-tip">Paste any custom CSS code here to customize your app's appearance.</div>
</div>

// Add customCss to initialValues:
<Formik
  initialValues={{
    // other fields...
    customCss: data?.customCss || '',
  }}
  // ...rest of setup...
  onSubmit={async (values) => {
    // other values...
    customCss: values.customCss,
  }}
>
```

---

## 5. Inject Custom CSS Into HTML Head

```tsx name=src/components/Layout/index.tsx
import Head from 'next/head';
// .other imports...

// After fetching user settings:
<Head>
  {/* ...existing meta, links, etc... */}
  {user?.settings?.customCss && (
    <style id="custom-css" dangerouslySetInnerHTML={{ __html: user.settings.customCss }} />
  )}
</Head>
```
