### ISSUE TITLE
Support to request "both" (4k and normal request at the same time)

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#641]
**Is your feature request related to a problem? Please describe.**
Maybe add an option to the dropdown menu to request both versions at the same time instead of clicking 2 times (normal and 4k request)

**Describe the solution you'd like**
Add an option to the request dropdown menu to request both versions at the same time

**Describe alternatives you've considered**

**Additional context**

**Comment by sct** [comment]
I think having to request twice is a small price to pay for the flexibility having two separate popup modals gives us. When I get the profile/path selection and server selection I think that will make more sense. So for now, I don't see this happening.
