### ISSUE TITLE
Weekly newsletter to users listing new content added to server

### ISSUE THREAD

**Issue by grigsby** [sct/overseerr#645]
**Is your feature request related to a problem? Please describe.**
No problems. This is a feature request.

**Describe the solution you'd like**
Ombi has a nice feature that sends out an email newsletter once a week to tell users about any new content that has been added to the server during the past week. I'd love to see this feature in Overseerr, too.

**Describe alternatives you've considered**
None.

**Additional context**
This would also depend on Overseerr having local users (analogous to Plex managed users) with their own email addresses, which is issue #335.

**Comment by sct** [comment]
Tautulli already does a fantastic job with this. I don't currently foresee this being added.

**Comment by grigsby** [comment]
I did not know Tautulli had this capability! I already have Tautulli installed, so I'm configuring the newsletter now. Thank you very much!
