### ISSUE TITLE
Follow up work on local users

### ISSUE THREAD

**Issue by ankarhem** [sct/overseerr#646]
**Describe the solution you'd like**
- Improve create user modal. Hide/show password, move generate password checkbox etc.
- Add correct autocomplete to login page form fields. Maybe `new-password` to the user create modal?
- Add reset password button somewhere to the edit user page
- Somehow lessen the "importance" of local login, so that it has to be a deliberate action to choose it. (look at how tautulli handles it etc.)

LEFT TODO:

- [x] Reset password flow
~~- [ ] Welcome email template~~
~~- [ ] Improve create modal~~

**Comment by sct** [comment]
A few other must-haves for a user system:

- Reset password flow on the login page. (Request new password reset. click link in email. etc)
- Password changes on user settings page, when we finally have a user settings page

Reset password button on the edit page is fine, but we can also just have a password field the admin can edit at any time if they like.

**Comment by TRaSH-** [comment]
Thnx for this option,
but when creating the user where you need to add a username i'm forced to use a email.
after adding the user i can't edit the username (shown).
Would be nice if i could edit the username

**Comment by costaht** [comment]
- Save language preference

**Comment by hirenshah** [comment]
> Thnx for this option,
> but when creating the user where you need to add a username i'm forced to use a email.
> after adding the user i can't edit the username (shown).
> Would be nice if i could edit the username

Maybe have the email address as the username but then have a separate field as the Display Name?

**Comment by costaht** [comment]
> > Thnx for this option,
> > but when creating the user where you need to add a username i'm forced to use a email.
> > after adding the user i can't edit the username (shown).
> > Would be nice if i could edit the username
> 
> Maybe have the email address as the username but then have a separate field as the Display Name?

I like the first option better. Regular username instead of email as username.

**Comment by costaht** [comment]
It seems to be an inconsistency:

![image](https://user-images.githubusercontent.com/50637431/105082698-f1ccf200-5a61-11eb-9d35-a357a2b6b021.png)

**Comment by ankarhem** [comment]
Extracting the last two points as I want this closed and the last two tasks seem less important and could be prioritized by themselves.
