### ISSUE TITLE
Option to hide "Sign in with Overseerr" button

### ISSUE THREAD

**Issue by TheCatLady** [sct/overseerr#647]
**Is your feature request related to a problem? Please describe.**
I have some less-tech-savvy users who always forget they are supposed to sign in with Plex.  Would be great to remove the option to attempt sign-in as a local user, since I won't be setting up any local users anyway.

**Describe the solution you'd like**
An option in the settings to disable local user sign-in and hide the button.
Or, don't show the button if local users don't exist.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ankarhem** [comment]
I feel like this is related to the last point i made here #646.

**Comment by samwiseg0** [comment]
Lets keep this with #646
