### ISSUE TITLE
Add Chinese (Traditional) language for translations on Weblate

### ISSUE THREAD

**Issue by TheCatLady** [sct/overseerr#648]
**Is your feature request related to a problem? Please describe.**
I've been working on translating to Chinese (Traditional) and need the language added on Weblate to share my translations.

**Describe the solution you'd like**
Chinese (Traditional) added to allow translations on Weblate

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sct** [comment]
Added! Thanks!

https://hosted.weblate.org/projects/overseerr/overseerr-frontend/zh_Hant/
