### ISSUE TITLE
Inform admin when connection to Plex instance has been lost

### ISSUE THREAD

**Issue by extrobe** [sct/overseerr#652]
**Is your feature request related to a problem? Please describe.**
In certain situations, Overseerr may lose it's connection to Plex (in my case I changed the Network settings, and it could no longer connect to localhost). There's no clear signal that this connection has been lost. I realised as items added weren't marked as available, and then checked the logs to understand why.

**Describe the solution you'd like**
Inform the user if/when connection to Plex instance fails. The existing sync jobs could be the trigger for this. Notified via web pop-up, banner, or push notification.

**Describe alternatives you've considered**
Completing the Logs tab may make diagnosing this a little easier, but a notification alerting the admin would be nest

**Additional context**
Perhaps similar functionality for Sonarr/Radarr connection failures should be considered.

**Comment by costaht** [comment]
Get out
