### ISSUE TITLE
Sort by Requested only

### ISSUE THREAD

**Issue by Reddax** [sct/overseerr#656]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to filter the requested list by 'Requested' only and not shows that are 'Available' as I manually find some of my TV series/Movies rather than using Radarr/Sonarr,

**Describe alternatives you've considered**
I have to use the 'Approved' filter and ignore the large number of 'Available' shows

**Comment by hirenshah** [comment]
This suggestion makes sense. The Approved filter should show the requests that are approved but not Available.

![image](https://user-images.githubusercontent.com/418112/104817336-86441400-5818-11eb-92c1-d6f29458f06a.png)

**Comment by Reddax** [comment]
Is this something that is being considered please? :)

**Comment by TheCatLady** [comment]
I'm working on this, please assign the issue to me! 🐱
