### ISSUE TITLE
Flag/recommend titles missing from collections

### ISSUE THREAD

**Issue by extrobe** [sct/overseerr#658]
**Is your feature request related to a problem? Please describe.**
It’s not always clear when you’re missing a title from an established collection without going into that collection to see. These are likely to be highly desired, so worth flagging up.

**Describe the solution you'd like**
Given overseerr already understands the notion of collections, and in fact already flags (when you go into that collection) by means of a flair if that collection has missing titles.

Option 1 - Having a ‘complete the collection’ section on discover flagging partial collections
Option 2 - Have a separate section/tab just for collections (Requests, Discover, Collections), which flags which may be incomplete

optional:
- could be permission based (eg only show to admins)
- Could Be grouped by collection (‘complete the Die Hard collection’) or just show items missing from collections ‘Die Hard 4’

**Comment by sct** [comment]
In its current state, this isn't actually possible. We get our collection date from TMDB, and it's only returned when we get the full details of a movie. There isn't really a way to compare your entire collection and see whats missing. There are some tools that can help you do this though, like https://github.com/JasonHHouse/gaps. Would be cool to have something like this built in some day, but just not possible at the moment.
