### ISSUE TITLE
[Feature Request] Add a 'Do Not Search' checkbox to Sonarr and Radarr Settings

### ISSUE THREAD

**Issue by Magic815** [sct/overseerr#662]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have a scenario where I like to manually choose the exact release of a movie or show when someone requests it to my server. Even with my best attempts to set Quality profiles and Cutoffs in Radarr/Sonarr settings, I never seem to 100% agree with what ends up getting grabbed automatically. I use Torrents entirely for my sourcing, and perma-seed, so I want to make sure I have the ability to choose the **exact** file that gets downloaded - so that my ratio doesn't take a hit from a release that wasn't my preferred choice. The way Ombi allowed this was to simply have a "Do Not Search" checkbox in the Radarr/Sonarr settings. That way the request at least brought everything into Sonarr/Radarr, and then all I'd have to do is run a manual search on that item, and choose the release I want. And then Ombi (or in this case Overseerr) would still handle notifying the requester once the file was on the server. I'd love to see this feature added to Overseerr! 

**Describe alternatives you've considered**
None

**Comment by abarber229** [comment]
👍

**Comment by hcourthias** [comment]
I'm also interested in this feature !

**Comment by abarber229** [comment]
The app shows I’m on version 1.18 but I don’t see a setting to where I can check that box. I even tried to create a new sonarr setup to see if it was there and wasn’t. I’m also on the develop instance.

**Comment by samwiseg0** [comment]
:wave: @abarber229, we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our support channels to get help with Overseerr.
- [Discord](https://discord.gg/PkCWJSeCk7) - [GitHub Discussions](https://github.com/sct/overseerr/discussions)
