### ISSUE TITLE
Declined Request Showing as Failed

### ISSUE THREAD

**Issue by hirenshah** [sct/overseerr#664]
**Describe the bug**
When I decline a request, it shows as Failed and gives me the option to Retry. It hasn't Failed, because it has intentionally been Declined, and there is nothing to Retry. 

**What version of Overseerr are you running?**
develop-d9919abb8998d28558ddec35b8e60ab2af75d5b7

**To Reproduce**

1. Decline a Request

**Expected behavior**
Request should show as Declined and not show an unnecessary Retry option.

**Screenshots**
![image](https://user-images.githubusercontent.com/418112/104850672-61b76d00-58e8-11eb-9d50-6db4a489f561.png)

**Additional context**
What does the Retry option even do in this scenario?

**Comment by sct** [comment]
Failed is actually the state that's supposed to show when an item failed to get sent to Radarr/Sonarr. I fixed it so that will only show when the item actually fails. The Declined status should correctly show up now.
