### ISSUE TITLE
Text size not scaling properly on W10

### ISSUE THREAD

**Issue by Glasti1** [sct/overseerr#673]
**Describe the bug**

When using windows scaling and/or the magnifying glas (crtl +) the text on posters from a search result get to big/small and unreadable

Tested on Chrome and Edge, both have the same result

**What version of Overseerr are you running?**

develop-4fe8172eb1d06c118c04b1d2a53adc3362d08b4c

**Screenshots**

100% windows scaling
![Screenshot 2021-01-18 174730](https://user-images.githubusercontent.com/57273176/104944830-12407200-59b8-11eb-834d-86262429a72c.jpg)

125% windows scaling
![Screenshot 2021-01-18 174629](https://user-images.githubusercontent.com/57273176/104944491-96dec080-59b7-11eb-825e-7fb41adf10ae.jpg)

100% windows scaling, 150% magnifying glass
![Screenshot 2021-01-18 175158](https://user-images.githubusercontent.com/57273176/104944843-18cee980-59b8-11eb-9d3e-3815c5c5cb96.jpg)

125% windows scaling, 33% magnifying glass
![Screenshot 2021-01-18 181044](https://user-images.githubusercontent.com/57273176/104945226-aca0b580-59b8-11eb-8d09-7691c72e06cb.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10 19042.746
- Browser: 
Chrome Version 87.0.4280.141 (Official Build) (64-bit)
Edge  Version 87.0.664.75 (Official build) (64-bit)

**Comment by TheCatLady** [comment]
This was fixed with #871.
