### ISSUE TITLE
Adding a film/series into plex before approving bug

### ISSUE THREAD

**Issue by Reddax** [sct/overseerr#688]
**Describe the bug**
With auto-approval disabled, if a movie or series is available in plex before approving, it will show as available and then send the available notification but still shows options to approve or not. If you then approve it, it shows as 'Requested' again. On the next incremental schedule, it will pick the item up again, set it as available, and send another available notification.

**What version of Overseerr are you running?**
1.16.0

**To Reproduce**

1. Request a movie
2. Add the movie manually into plex
3. Let overseerr scan incrementally
4. You will see 'Available', and it will send a notification as expected but also show approve/decline
5. Approve the item.
6. It will show as 'Requested' again
6. Wait for the scan to run
7. It will show as available and send another notifcation

**Expected behavior**
If Overseerr sees the item as added in plex but has not yet been approved, it shouldn't show the approve/decline options as it's already available.

**Screenshots**
![image](https://user-images.githubusercontent.com/1349626/105022161-54fa5c80-5a41-11eb-9522-c9feb5951c07.png)

**Comment by sct** [comment]
Where are you seeing "Approve/Decline" after it already becomes available?

**Comment by Reddax** [comment]
> Where are you seeing "Approve/Decline" after it already becomes available?

It's on the requests page for the admin, I've attached a screenshot to the OP

**Comment by sct** [comment]
Appears to be a desync going on in the rendering there. If you refresh does it not show the buttons anymore?

**Comment by Reddax** [comment]
> Appears to be a desync going on in the rendering there. If you refresh does it not show the buttons anymore?

Refresh doesn't fix it, I've tried clearing cache & using a new browser and the Approve/Decline is still there. I've also updated to 1.17.1 and re-requested another film & added it and getting the same

![image](https://user-images.githubusercontent.com/1349626/105023420-d9011400-5a42-11eb-92ec-9f76452a2225.png)

**Comment by sct** [comment]
Okay got it. Will try to get this fixed asap. Thanks for the report.
