### ISSUE TITLE
Declined series request: seasons are still 'pending'

### ISSUE THREAD

**Issue by kobaubarr191** [sct/overseerr#690]
**Describe the bug**
When a request for a series has been declined, and a user tries to request the same series again, the status of the previously declined seasons is still 'Pending' in the request pop up. Once the declined request is removed from the 'Requests' page, the 'Pending' status is gone.

**What version of Overseerr are you running?**
1.17.1

**To Reproduce**

1. User requests a series (completely or partially)
2. Decline the request
3. User clicks the 'request' button of the same series.
4. User is unable to request the previously declined seasons, because it is still 'Pending'
5. Remove the declined request
6. User can again request the seasons

**Expected behavior**
Declined movies can be requested again. I don't know what the consequence of declining a request should be, but I guess users could request the series again, like with movies. Unless declining is supposed to act as a 'ban' of the requested media. In any case, the 'Pending' status should not be there I think. 

**Screenshots**
_Series partially requested and declined_
<img width="400" alt="partial" src="https://user-images.githubusercontent.com/45538219/105026229-9e9d7400-5a4e-11eb-8a4b-3526d730c5a8.png">

_All seasons requested and declined_
<img width="400" alt="complete" src="https://user-images.githubusercontent.com/45538219/105026255-a4935500-5a4e-11eb-816d-b4a2c7d22180.png">

**Comment by hirenshah** [comment]
I just checked the test requests I had from yesterday and can confirm this behaviour.  

Declined TV Shows still appear as Pending and cannot be re-requested.  Films can be re-requested without any issue though.
