### ISSUE TITLE
Mixed quality seasons arent market as available

### ISSUE THREAD

**Issue by bgktmxg** [sct/overseerr#695]
**Describe the bug**
I have a 10 episode season of a TV show that is made up from 9 episodes in 1080 and 1 episode is 4k (all that was available). I believe the season/request should be marked as available.

**What version of Overseerr are you running?**
v1.17.1

**To Reproduce**
Request a season of a TV show and ensure Sonarr grabs mixed qualities

**Expected behavior**
Mark the season as available once all episodes are available. The "4k partially available" could remain.

**Screenshots**
![image](https://user-images.githubusercontent.com/51685078/105113675-146a1400-5b11-11eb-94eb-8bc3adcdf7ac.png)
![image](https://user-images.githubusercontent.com/51685078/105113701-2481f380-5b11-11eb-94aa-98ac1a03deb1.png)

**Desktop (please complete the following information):**

- OS: Unraid 6.8.3
- Browser - Firefox

**Comment by sct** [comment]
We will add the ability to mark things as available manually. Will that solve this? It's tough to deal with this otherwise. We can't know for sure how you have your plex setup and if you are trying to fill out a 4k season alongside your standard.

**Comment by bgktmxg** [comment]
Hi and thanks for the quick reply. Being able to manually mark it as available manually would solve this, I cant see it happening too often.
Thanks

**Comment by sct** [comment]
I will leave this ticket open for now. We discussed some alternative, future, fixes in the discord. Some options like marking a library as 4K/no 4k only. But adding the manual controls for availability is the best short-term solution.
