### ISSUE TITLE
Ability to use multiple Radarr/Sonarrs and use filtering to route requests/checks.

### ISSUE THREAD

**Issue by saltydk** [sct/overseerr#704]
**Is your feature request related to a problem? Please describe.**
My sonarr/radarr setup is not limited to HD/4K versions but expanded to each unique library that I have (Anime as an example). My case is not as bad as others that, for performance reasons, have their radarrs split into decades (radarr80s, radarr90s) etc. I am missing an option of directing requests to the arr instance of choice without having to educate users on advanced options.

**Describe the solution you'd like**
My suggestion is the ability to have a filtering system where you can redirect requests based on various metadata like genre, year or whatever strikes your fancy. In an ideal world this feature would not be visible at all to the user requesting and just be handled by the logic setup by the admin. My solution would not be a case of needing to check every radarr/sonarr instance for each entry like with the 4K option but rather splitting out the unique movies/shows into filtered options.

**Describe alternatives you've considered**
Running multiple instances of Overseerr which is not ideal as some users won't remember to use the correct instance.

**Additional context**

**Comment by saltydk** [comment]
Please re-open this. Would love for this functionality to be added in order to move back to Overseer from Petio, which by tying everything to the TMDB API has blocked itself off from properly supporting stuff like HAMA.

**Comment by cchiapusio** [comment]
I'd be interested in being able to route a particular users requests to a specific instance of radarr/sonarr as well

**Comment by HikariNoKitsune** [comment]
Need this exact thing... relying on end users to 'know' how to request things specifically is a really bad idea..
