### ISSUE TITLE
Cache and Serve posters locally

### ISSUE THREAD

**Issue by RedSpid3r** [sct/overseerr#710]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is it possible to cache posters so they can be served locally from the Overseerr server rather than directly from TMDB?

**Additional context**
My Overseerr is behind Cloudflare but I can't take advantage of this to cache posters with a long TTL because they are not part of the domain serving overseerr.

**Comment by ankarhem** [comment]
We could add an endpoint and replace the tmdb image urls I think

**Comment by ankarhem** [comment]
I don't know if this is something that we would want/need to do though. What are the benefits of cacheing it with cloudflare cdn instead of fetching from tmdb? I looked at the response headers on the tmdb image, and they are already using a cdn `x-cache: Hit from cloudfront`

**Comment by sct** [comment]
I don't see how there would be any gain to putting this burden on us instead of TMDB. No plans to do this.
