### ISSUE TITLE
TV Show notification via Telegram partially broken 

### ISSUE THREAD

**Issue by costaht** [sct/overseerr#718]
**Describe the bug**
When a user requests a TV show, the notification of Request and Approval are sent to the chat ID in the notification settings, but once the TV show is available, no notification is sent.

**What version of Overseerr are you running?**
develop-a3fe4e6321c3480ac0463ed26e0d9be25d88352f

**To Reproduce**

1. Request a TV show with a user that needs manual approval.
2. You will get the Request notification
3. Approve the request
4. You will get the Approval notification
5. Wait until the movie gets available on Plex/Overseerr
6. No notification is sent.

**Expected behavior**
Because the user in question hasn't auto-approve set into its profile, it's expected that all three messages are sent.

**Additional context**
The notifications for Movies are working fine.
The user used in the test does not have auto-approve set into their profile.

**Comment by sct** [comment]
Does the item show as available in Overseerr? Or only partially available? We only send notifications when the _request_ is fulfilled. If someone asks for seasons 1-4, they will only get a notification once all seasons are fully available.

**Comment by costaht** [comment]
It is partially available because there are still episodes coming up for the last season. They are exhibit once a week.

**Comment by sct** [comment]
We don't send notifications for partially available.

**Comment by costaht** [comment]
But then notification will only work for "old" stuff, not what most people will actually be requesting. Like at this moment Your Honor, Wandavision, etc ...
Any plans on having summarized notifications when many episodes get available at once? Like "S01-S03 is available" considering that season 03 isn't complete yet, the next notifications would be per episode.

**Comment by sct** [comment]
There are so many reasons this will not be a reliable notification. To start, a lot of new series that are currently airing are often not fully filled out on TMDB. It may only show 3 episodes available while it's still airing and new episodes are added only shortly before they become available. How do we know when the show is complete or just in progress?

Overseerr is trying to fill a user's request. So when a user asks for seasons 1-3, and only 1,2 are fully available, well.. the request has not yet been fulfilled.

Maybe an option in the future to send notifications when a single episode from a season becomes available. But will need a lot of thought into how to really handle the implementation.

**Comment by costaht** [comment]
> a lot of new series that are currently airing are often not fully filled out on TMDB. It may only show 3 episodes available while it's still airing and new episodes are added only shortly before they become available. 

I didn't have this background information. I'll see what I can do combining overseer and sonarr notifications
