### ISSUE TITLE
Similar titles not loading when navigating from details page

### ISSUE THREAD

**Issue by Zazou89** [sct/overseerr#719]
**Describe the bug**
When I search a similar movie (with french UI), it returns a maximum of 5 lines of movies fot about 10-15 sec, then hunderds of results are displayed.

If I start a search directly in English, all results are displayed instantly. 

**What version of Overseerr are you running?**
1.17.2

**To Reproduce**

1. Set UI in French
2. Go on a similar movie section, it will display 40 results and some processing results
3. Switch to English, it loads lots of results
4. Revert to French, results still here (excepted behavior)

**Screenshots**

In French :
![image](https://user-images.githubusercontent.com/206181/105431490-0671db80-5c56-11eb-8fd2-ea896d1f66db.png)

**Comment by Zazou89** [comment]
Oh yes you’re right ! Thanks for the explanation

**Comment by hwwilliams** [comment]
This is also happening when you open an item and open more items for recommendations not just similar items.
