### ISSUE TITLE
overseerr.log spelled wrong in Settings/Logs

### ISSUE THREAD

**Issue by HubDuck** [sct/overseerr#721]
**Describe the bug**
Under Settings/Logs the name of the log file has a trailing s. Minor cosmetic issue.

**What version of Overseerr are you running?**
develop-083a74a686d202cce5775bf9752caaa9a626cf45

**To Reproduce**

1. Go to 'Settings/Logs'
2. Current spelling is '/app/config/logs/overseerr.logs'

**Expected behavior**
Spelling to be '/app/config/logs/overseerr.log'

**Desktop (please complete the following information):**
Independent of OS, Browser or Smartphone

**Comment by sct** [comment]
Thanks, fixed it with the other small fix I just pushed!
