### ISSUE TITLE
Support Base URL (Like Radarr, Ombi and Sonarr etc)

### ISSUE THREAD

**Issue by Swiftnesses** [sct/overseerr#725]
Good day,

Thanks for the great tool (currently testing it as an alternative to Ombi).

Is it possible to support a 'base URL' for example '/overseerr' - I use Organizr and have my apps proxied at locations like:

https://dashboard/overseerr

Many thanks in advance.

**Comment by samwiseg0** [comment]
Dupe of https://github.com/sct/overseerr/issues/274
