### ISSUE TITLE
Mismatched Plex items, don't get picked back up when fixed

### ISSUE THREAD

**Issue by 1activegeek** [sct/overseerr#728]
**Describe the bug**
Plex mismatched a TV Show item that was requested. In this scenario, Plex had a show already added, but it was matched as something else. Close/similar in name, but wrong ID. Once going to Plex and fixing the Match, the TV Show was then updated in plex. Went back to Overseerr and did a sync and full scan. After completion, the Requests still show no match even though the Plex library is showing the correct match.

**What version of Overseerr are you running?**
1.17.2

**To Reproduce**
Haven't gone through reproducing, but should be:

1. Add new show to Overseerr
2. Plex mismatches show
3. Fix Match in Plex
4. Back in Overseerr, run sync and full scan
5. Check Requests tab, note still mismatched show

**Expected behavior**
Was expecting that after fixing the match in Plex, that Overseerr would see the change for that show and recognize the updated metadata associated, and presumably a TVDB ID or similar.

**Screenshots**

**Desktop (please complete the following information):**
Not relevant - validated from different browsers, endpoints, etc - it's backend related

**Additional context**
None that I can think of

**Comment by samwiseg0** [comment]
Did it match the wrong show in overseerr? Can you clear the metadata on the wrong show and scan again?

**Comment by 1activegeek** [comment]
Interestingly - I just went to check on it to validate as you said and/or clear the show - it shows them as available now. So I had hit the Full Scan last night before bed. I did it again this AM. It didn't show up initially, but it looks like it's not showing. Is there something running on the backend a specific time that perhaps needed to just cycle through? Or is it possible I was facing a scenario of stale/cache data? Odd, sorry for the bother. Will close this out since it seems to have cleared itself up.
