### ISSUE TITLE
Email Notification Enhancements

### ISSUE THREAD

**Issue by SpecialBus** [sct/overseerr#729]
**Is your feature request related to a problem? Please describe.**
Many of my users will create multiple requests in one sitting and have asked if email notifications can be cut down so they aren't flooded with individual emails for each request.  Depending on how many notification types are setup (request approved, available etc), a single request can generate a bunch of separate emails.  Multiply this over 5-6 requests and it's easy to flood a users inbox. 

**Describe the solution you'd like**
Add a 'Group Email Notifications' checkbox/option.  This will then allow you to configure a 'Time in seconds' to wait before sending email notifications.  Overseer can then send a single notification email after that delay passes containing all notifications that have occurred during that span.

**Comment by samwiseg0** [comment]
Did it match the wrong show in overseerr? Can you clear the metadata on the wrong show and scan again?

**Comment by SpecialBus** [comment]
I think you meant to reply on another thread @samwiseg0 :)
