### ISSUE TITLE
Ability to filter "Discover" results by language or set a default language server side

### ISSUE THREAD

**Issue by Drawmonster** [sct/overseerr#732]
**Is your feature request related to a problem? Please describe.**
Currently "Discover" lists items in all languages by default.

**Describe the solution you'd like**
Would like the ability to filter "Discover" items by the language they are in.

**Describe alternatives you've considered**
Instead of filtering on the "Discover" page, could also just have a server side setting with a drop down where you could pick the language of the moves/shows are populated. Only issue with doing that server side would be if a user wants a movie in a different language. So would still need normal searches to return movies in all languages.

**Additional context**
This would allow "Discover" to deliver all results in the users preferred language so the results are more relevant. If done server side, it would keep users from accidentally adding movies from "Discover" without realizing it's in the wrong language.

**Comment by costaht** [comment]
Since this will be implemented, I just want to ask to keep the ability to search in multiple languages the way it is today.

**Comment by sct** [comment]
> Since this will be implemented, I just want to ask to keep the ability to search in multiple languages the way it is today.

Of course. No plans to take that away :)

**Comment by erwintwr2** [comment]
another vote for a language filter -> clash with requests based on the discovery page and the primary language filter in Sonarr, resulting in requested shows that cannot be completed (Korean requested vs english in this case)

**Comment by dalepmay7** [comment]
Just wondering when this feature is going to be enabled on the backend. I see it on the front end, but it doesn't appear to do anything.
