### ISSUE TITLE
Settings button directly underneath Clear All Media Data button for requested items

### ISSUE THREAD

**Issue by Arcanemagus** [sct/overseerr#750]
**Describe the bug**
On media items that have an existing request the `Clear All Media Data` button covers ~60% of where the settings "gear" button is, so when you click on that if you accidentally double click it will remove all media data... and all requests.

**What version of Overseerr are you running?**
`develop-82ac76b0540ba1133cb5384744d2499c2488a4e8`

**To Reproduce**

1. Go to any media item that has an active request
2. Click on the settings button
3. **Don't** accidentally click the `Clear All Media Data` button

**Expected behavior**
The `Clear All Media Data` button should either be moved out of directly over (most of) the settings button, or should have a confirmation dialog on it.

**Screenshots**
![RQY7aKB2zR](https://user-images.githubusercontent.com/427137/105802898-0709bb00-5f51-11eb-99af-689743c0b386.gif)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 90

**Additional context**

**Comment by sct** [comment]
Uploading Screen Recording 2021-01-26 at 14.11.18.mov…

This will be resolved with #734
