### ISSUE TITLE
Set a default UI language for all users

### ISSUE THREAD

**Issue by hbooo** [sct/overseerr#753]
**Is your feature request related to a problem? Please describe.**
Currently there is only the possibility to edit the language for the current user. 

**Describe the solution you'd like**
Add an option to define default user language and add the possibility to bulk edit users with a default language

**Additional context**
General Settings: 
![image](https://user-images.githubusercontent.com/242125/105861309-de380300-5fee-11eb-9b4c-b9af81e7cd3a.png)

Bulk Edit:
![image](https://user-images.githubusercontent.com/242125/105861605-30792400-5fef-11eb-8d00-0e2a76797aa9.png)

**Comment by kobaubarr191** [comment]
This would be very helpful! A lot of my users are not too skilled and don't know how to change the language themselves. A global default language setting for the whole Overseerr instance could be useful too (so the login page is translated by default too).

But maybe a similar, more hassle free solution could be that Overseerr automatically changes the language to the browser's language.

**Comment by virusperfect** [comment]
I would love to see that as well! At the moment everytime you log in into a new device with the same account the language is set to English.
