### ISSUE TITLE
Manually approve 4K requests but auto approve other requests

### ISSUE THREAD

**Issue by ssiddiqui87** [sct/overseerr#757]
**Is your feature request related to a problem? Please describe.**
I am very particular about what versions of 4K movies/tv shows I want downloaded so I don't want to auto approve those while I want to auto approve normal non 4k movies/tv shows

**Describe the solution you'd like**
Have two additional user settings under "Auto Approve" for "Auto approve 4K movies" and "Auto approve 4K tv shows" 

**Describe alternatives you've considered**
Currently I am running Ombi for 4k requests so I can manually approve and overseer for non 4k requests for auto approvals.

**Comment by makkish** [comment]
I would very much like that feature too.

**Comment by TheCatLady** [comment]
Working on this, please assign the issue to me.
