### ISSUE TITLE
Unable to save changes when accessing locally (403 Forbidden)

### ISSUE THREAD

**Issue by bobokun** [sct/overseerr#758]
**Describe the bug**
When having the option "Enable CSRF Protection" checked. and reloading Overseerr. I'm no longer able to save changes when access Overseerr on it's local IP address to save changes. Using reverse proxy will allow me to save changes.

![image](https://user-images.githubusercontent.com/12660469/106012237-358ab180-6089-11eb-9d94-2cd38826cde0.png)

**What version of Overseerr are you running?**
develop-86efcd82c34ad6490f2899ebf6f84cdd1bffc498

**To Reproduce**

1. Check Enable CSRF Protection
2.  Save changes
3. reload Overseerr
4. Access Overseerr through local IP
5. Make changes and try to save

**Expected behavior**
Allow changes to be saved

**Comment by TheCatLady** [comment]
This is the expected behavior.  Since the CSRF cookies have the Secure attribute set, CSRF protection only works via HTTPS.  There's no need for CSRF protection if Overseerr is only accessible locally.
