### ISSUE TITLE
Requests not being sent to Radarr

### ISSUE THREAD

**Issue by GavinHellyer** [sct/overseerr#759]
**Describe the bug**
When approving a request for a movie, Overseerr is not behaving as expected, it says that it is sending the request correctly, but Radarr does not show the new movie.

**What version of Overseerr are you running?**
v1.17.2

**What version of Radarr are you running?**
v3.0.1.4259

**To Reproduce**

1. Request a movie
2. Approve the movie
3. Navigate to Radarr
4. Search for movie

**Expected behavior**
Overseerr should be adding the movie to Radarr

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: chrome
- Version: 87

**Additional context**
I am running Overseer in Docker. This issue is not happening on the "latest" branch but is happening on the "develop" branch. i.e. it was working 5 minutes ago before I changed over to the develop branch. I have restarted the server. Switched back to the "latest" branch (which fixed the issue) and then switched back to "develop" (which brings the issue back).

The logfile shows the following:
```
2021-01-27T16:12:53.695Z [info][Media Request]: Sent request to Radarr 
2021-01-27T16:12:53.699Z [info][Notifications]: Sending notification for MEDIA_APPROVED 
2021-01-27T16:12:53.700Z [debug][Notifications]: Sending email notification 
2021-01-27T16:12:53.927Z [info][Radarr]: Movie already exists in Radarr. Skipping add and returning success
```

I have tested this with multiple movies on both the "latest" and "develop" branches, and "latest" never has an issue, and yes I have made sure the requests are not already on Radarr.

Once approved Overseerr says it is on Radarr and acts as if everything is fine.

**Comment by costaht** [comment]
I can confirm this problem on version develop-ec5fb836785855eb4846fd33b49faeb94c40506a

**Comment by GavinHellyer** [comment]
That is amazing support, thank you
