### ISSUE TITLE
Sort user list by alias

### ISSUE THREAD

**Issue by M3th0s** [sct/overseerr#767]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, more of a QoL addition.

**Describe the solution you'd like**
A capability to sort the user list by all/some column fields

**Describe alternatives you've considered**
Current UI doesn't allow for other alternatives as there are no UI elements for this specific request.

**Additional context**
N/A

**Comment by M3th0s** [comment]
Apologies, initial request updated:)

**Comment by TheCatLady** [comment]
Working on this, will be submitting a PR shortly.

**Comment by M3th0s** [comment]
Thank you very much!! Look forward to it!
