### ISSUE TITLE
Logging in with a local account email address except without '+overseerr' like what's commonly used with Gmail addresses results in undefined error message

### ISSUE THREAD

**Issue by danshilm** [sct/overseerr#771]
**Describe the bug**
I have a local user account 'email+overseerr@gmail.com' and when logging in as 'email@gmail.com' the logs give out a `[Auth]: undefined` error message.

**What version of Overseerr are you running?**
develop-3812989a1ce1e07d4af09149008043a6e2e94060

**To Reproduce**

1. Make a local user account whose email uses the '+something' trick that's used commonly with Gmail addresses.
2. Attempt logging in with the local user's email address, except without the '+something' part.
3. `[Auth]: undefined` in the logs and `message: "Something went wrong."` from the auth request at `/auth/local`.

**Expected behavior**
A failed login attempt with the attempt details in the logs.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by ankarhem** [comment]
I don't think it's expected that you should be able to login with something else that what it was signed up with though? Haven't used this for many sites. Is it common that you could login without it?

**Comment by danshilm** [comment]
You're right. The expected behaviour is to only be able to login with the email address with the `+overseerr` part. 
It's just the `undefined` error message that's not expected when failing a login attempt.

**Comment by ankarhem** [comment]
When testing this I realized it isn't connected to the +suffix in this case. This happens when you try to authenticate a user that has no password. (i.e. trying to login with an email connected to a plex user).

**Comment by danshilm** [comment]
Yep, that was the case actually. Will try to be more clear/give better debugging info in the future.
