### ISSUE TITLE
Show Next episode/season air date on tv detail page if tv show has a Returning Series status

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#774]
**Is your feature request related to a problem? Please describe.**
Just a small idea:
Some end users asking me when the follow-up episode will be on plex.
It will be really nice if end users can see the next episode/season air date on the tv detail page next to "First Air Date"

**Describe the solution you'd like**
Showing next episode/season air date next to the "First Air Date"

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by danshilm** [comment]
Assign me to this please.

**Comment by Magikarplvl4** [comment]
Thanks @danshilm for your great work on this :)
