### ISSUE TITLE
Empty Cast on tv show detail page

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#775]
**Describe the bug**
Overseerr doesn't show the cast of the tv show "Bonding" on the detail and full crew page.

**What version of Overseerr are you running?**
develop-3812989a1ce1e07d4af09149008043a6e2e94060

**To Reproduce**

1. search for the tv show "Bonding"
2. Click on details
3. You can see an empty cast list

**Expected behavior**
Showing the cast list

**Screenshots**
![image](https://user-images.githubusercontent.com/2944704/106217499-a8a13e80-61d5-11eb-8308-a59c7c5038a6.png)

Full crew page is also empty:
![image](https://user-images.githubusercontent.com/2944704/106217409-77c10980-61d5-11eb-9b1d-731ad3cf309d.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome

**Additional context**
No 403 or 50x errors in the network tab of chrome. just 200

**Comment by danshilm** [comment]
Can you assign this to me please?

**Comment by Magikarplvl4** [comment]
Thanks @danshilm for your great work on this <3
