### ISSUE TITLE
Same notification each time sonarr sync runs

### ISSUE THREAD

**Issue by Fiala06** [sct/overseerr#777]
**Describe the bug**
Each time I run the sonarr sync I receive a notification for a show that hasn't changed or new episodes added.

I've tried "re-matching" in Plex and still get the notification. Dirty Jobs is the only show this happens for. 

**What version of Overseerr are you running?**
Latest Dev: develop-b5fd1d520cd2a7be6e6356a25129e93af1caf542
Has been happening since sonarr sync feature was added

**To Reproduce**
Unsure as it's only happening for 1 show weather I manually run the sonarr sync or it auto runs every 24hrs. 

**Expected behavior**
Shouldn't be getting the same notification over and over.

**Screenshots**

![image](https://user-images.githubusercontent.com/5183146/106294131-a48c1580-6203-11eb-97e2-7033d2e7bcd5.png)

![image](https://user-images.githubusercontent.com/5183146/106294191-b8377c00-6203-11eb-8a3f-3d09d1923370.png)

![image](https://user-images.githubusercontent.com/5183146/106294231-c4bbd480-6203-11eb-8ed7-4796d024b326.png)

**Desktop (please complete the following information):**
Unraid 

**Smartphone (please complete the following information):**
 N/A

**Additional context**
Here are some recent logs https://gist.github.com/Fiala06/a160ba135ff86f5696644cb6ddebb566

**Comment by Magikarplvl4** [comment]
I have the same problem. I use Discord notifcations

**Comment by Fiala06** [comment]
I've started to receive the notification's again for this show even though nothing has been added/changed.
