### ISSUE TITLE
Empty 'Play on Plex' dropdown menu when no trailer is available

### ISSUE THREAD

**Issue by kobaubarr191** [sct/overseerr#787]
**Describe the bug**
Whenever no trailer is available for a certain movie or series that is also available on Plex, the dropdown arrow next to the 'Play on Plex'-button will still be visible, but an empty dropdown menu will open. I encountered this issue while testing the UI in different languages. If an English trailer is available, the 'Watch Trailer' button will show in the dropdown; but if no eg Dutch trailer is available, the dropdown is still there, just empty.

**What version of Overseerr are you running?**
1.18.0

**To Reproduce**

1. Go to a movie or series that is available on your Plex server (e.g. The Mandalorian)
2. Click on the dropdown arrow next to the 'Play on Plex' button
3. There is a button 'Watch Trailer', as expected
4. Change the UI language to another language (e.g. Dutch)
5. Click the dropdown button once again. There is no Dutch trailer for this series, but the dropdown menu still appears, but is empty.

**Expected behavior**
No dropdown button when no trailer is available.

**Screenshots**
_When there is a trailer available:_
<img width="250" alt="englishtrailer" src="https://user-images.githubusercontent.com/45538219/106357686-e30af880-6307-11eb-8909-e912fda59c8a.png">

<img width="250" alt="dutchtrailer" src="https://user-images.githubusercontent.com/45538219/106357715-0cc41f80-6308-11eb-846f-3087b3b8e4eb.png">

Both languages show expected behaviour when there is a trailer available.

_When there is no trailer available:_
<img width="250" alt="dutchnotrailer" src="https://user-images.githubusercontent.com/45538219/106357718-12ba0080-6308-11eb-9bfd-0c5d2741d634.png">

**Comment by Magikarplvl4** [comment]
Thanks @danshilm for your great work on this :)
