### ISSUE TITLE
Do Not Search

### ISSUE THREAD

**Issue by asherman07** [sct/overseerr#794]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the ability to add a movie/tv show but not have it search for it

**Describe alternatives you've considered**
This should be added per service

**Additional context**
None at this time

**Comment by samwiseg0** [comment]
https://github.com/sct/overseerr/issues/662

**Comment by samwiseg0** [comment]
https://github.com/sct/overseerr/issues/662

**Comment by asherman07** [comment]
thank you
