### ISSUE TITLE
Editing Users Bug v1.18.0

### ISSUE THREAD

**Issue by 14wkinnersley** [sct/overseerr#799]
**Describe the bug**

When I am trying to edit users, clicking the yellow edit button next to their profile, And I add permissions, it will not let me save. 

**What version of Overseerr are you running?**
Please fill in the version you are currently running.
V1.18.0

You can find it under: Users>Edit

**To Reproduce**

1. Go to 'Users'
2. Click on 'User Edit’
3. Scroll down to ‘check box for ‘manage requests’ and click save.
4. No errors, just doesnt save. 

**Expected behavior**

expect it to save. 

**Screenshots**
If applicable, add screenshots to help explain your problem. N/A

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 88.0.4324.104

**Smartphone (please complete the following information):**

- Device: iPhone 12
- OS: ios 14
- Browser Safari
- Version 

**Additional context**

If I choose the new Bulk edit feature, it will allow me to edit the user.

**Comment by sct** [comment]
I am unable to reproduce this. Can you perhaps open your browser's developer tools and tell me if the request fails? If it's failing, grab the response and paste it here.

**Comment by 14wkinnersley** [comment]
I have no idea where to look in the developer tools if the request is failing.. Im not a developer. Can you point me on where to look? I might just reinstall and re-setup if no one can re-produce.

**Comment by sct** [comment]
If you hop on Discord maybe we can help you. Reinstalling might solve it but I would rather find the cause and fix that instead :)

**Comment by sct** [comment]
Turned out to be an issue with Display Name not being set or having strange characters. I will push a fix at a later date to correctly show an error in that case.
