### ISSUE TITLE
Unable to request season that is already monitored

### ISSUE THREAD

**Issue by BodingClockchian** [sct/overseerr#816]
**Describe the bug**
Im not really sure how to describe this and if this should be considered a bug. Its maybe an unique example.
I have the TV show "The Walking Dead" monitored in Sonarr (See screenshot).
Earlier episodes were deleted to safe some storage.
In Overseerr it is not possible to request season 10 because its already monitored by Sonarr?

**What version of Overseerr are you running?**
1.18.0

**To Reproduce**
1. Request a tv show that is currently airing
2. Delete the downloaded files (Because of an season break orwhatever)
3. Request the tv show season again

**Expected behavior**
I would expect that the whole season will be searched for again.
Requested and monitored is not the same if the episode air date is in the past.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/28387829/106638577-55880c80-6584-11eb-95f5-25a28b48b4ff.png)
![afbeelding](https://user-images.githubusercontent.com/28387829/106638695-6e90bd80-6584-11eb-92b0-bd92ce6390f1.png)

**Desktop):**
- OS: Ubuntu 18
- Browser Firefox / edge
- Version Latest

**Comment by samwiseg0** [comment]
Hit the gear icon on the show and then clear all metadata. 
![Screen Shot 2021-02-02 at 12 49 10 PM](https://user-images.githubusercontent.com/2241731/106641438-3625bb00-6555-11eb-84f9-2c2f5c2e6843.png)
