### ISSUE TITLE
Media processing throbber visible when other movie version is downloading in Radarr of available movie

### ISSUE THREAD

**Issue by kobaubarr191** [sct/overseerr#818]
**Describe the bug**
When a movie is available in Plex, but Radarr is currently downloading another version of the movie, the status is still 'Available', but the throbber (spinning wheel next to 'Processing...') appears next to the 'Available' status.

**What version of Overseerr are you running?**
1.18.0

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Make Radarr download another version of a movie that is currently available.
2. Wait for Overseerr to sync Radarr
3. See the throbber next to 'Available'

**Expected behavior**
The throbber is not there.

**Screenshots**
<img width="100" alt="Schermafbeelding 2021-02-02 om 22 20 17" src="https://user-images.githubusercontent.com/45538219/106665659-dfe16800-65a6-11eb-8936-8a0c292b8ca5.png">

**Comment by TheCatLady** [comment]
I personally don't see this as a bug, since the item is both "available" and "processing."  I think the indication that a new version is being downloaded is quite valuable.

**Comment by samwiseg0** [comment]
I second @TheCatLady, I don't see this as a bug. The download status is only available to the admin and technically it is correct. The item is available but the item is being upgrade/updated so a download status will be shown. Processing would be less accurate imo as it is technically already available.

**Comment by sct** [comment]
This is the intended behavior.
