### ISSUE TITLE
Selected download directory not respected and cfg file setting overrides the directory in the selection box...

### ISSUE THREAD

**Issue by MrAnanas** [sct/overseerr#857]
Situation: Everything works well. Then I removed the movie root directory from Radarr and created a new on a different drive and moved my movies there in Radarr and physically on the drive.  Again everything looks good, Overseer shows the correct new folder when adding a new movie BUT it actually adds the movie to Radarr using the old folder.
The old folder is indeed mentioned in the cfg file: **** "activeDirectory": "/unRaid/Movies/" **** 
The problem was solved by manually changing this to the new folder share.

I just wanted to let you guys know...

**Comment by costaht** [comment]
Clean overseerr cache then try again

**Comment by sct** [comment]
Since the template was not updated and you haven't tried the above suggestion, I will close this for now.
