### ISSUE TITLE
(small bug) empty table row when rating is unavailable on detail page

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#858]
**Describe the bug**
Don't show the upper table row if there isn't a rating available for a tv show or movie

**What version of Overseerr are you running?**
1.19.0

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Go to Search for tv show _Out on Stage_
2. Click on _tv show_
3. See error

**Expected behavior**
Don't show an empty table row

**Screenshots**
![image](https://user-images.githubusercontent.com/2944704/107101298-2806c180-6817-11eb-8366-401c8352d93d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheCatLady** [comment]
I can investigate and fix this 😺
