### ISSUE TITLE
Header cast text is visible even when there is no cast data available

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#859]
**Describe the bug**
The text "cast" is visible on the detail page even when there is no cast data available

**What version of Overseerr are you running?**
Please fill in the version you are currently running.

You can find it under: Settings -> About -> Version

**To Reproduce**

1. search for Back to Berlin
2. click on it
3. See error

**Expected behavior**
Don't show the cast text and click Arrow when  there isn't any data to show :)

**Screenshots**

![image](https://user-images.githubusercontent.com/2944704/107101580-1245cc00-6818-11eb-9118-f402e1e22284.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheCatLady** [comment]
I can investigate and fix this 😺
