### ISSUE TITLE
Posters in detailed view are way too large on large monitors

### ISSUE THREAD

**Issue by vaparr** [sct/overseerr#869]
**Describe the bug**
On the main page, Overseerr can display 20 items per row, of decently sized posters.
on the "more" page, Overseerr displays huge posters, at 8 per row (at 3440 resolution)

**What version of Overseerr are you running?**

develop-8956cb3915330eecf76b262bcf4b66c537e01dfd

**To Reproduce**
Open overseerr, click on Upcoming Movies to get the full view:
![image](https://user-images.githubusercontent.com/70992682/107130968-96439680-68a0-11eb-9fc9-d8c5ffa5c5c5.png)

**Expected behavior**
Posters should not be giant.. Maybe the same size as the main page (or slightly bigger?)
![image](https://user-images.githubusercontent.com/70992682/107130978-b1160b00-68a0-11eb-98f1-fa8ebc4bc549.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge

**Comment by TheCatLady** [comment]
I'm working on this 🐱
