### ISSUE TITLE
Multiple repeat notifications being sent for media availalbe

### ISSUE THREAD

**Issue by bobokun** [sct/overseerr#872]
**Describe the bug**
Multiple notifications are being sent (duplicate) to the same users when one or more seasons of a TV show is requested, approved and downloaded but not the whole TV Series is requested/available.
I have sonarr sync enabled, and this is tested using the email notification agent.

**What version of Overseerr are you running?**
develop-8956cb3915330eecf76b262bcf4b66c537e01dfd

**To Reproduce**

1. Request 1 or 2 seasons of a particular TV Series.
2. Approve and download the series.
3. Wait for notification to send saying the series is available
4. Wait a couple days and see repeat notifications (once a day)

**Expected behavior**
Only one notification should be sent and not repeated

**Screenshots**
Sonarr Screenshot of the TV Show:
![image](https://user-images.githubusercontent.com/12660469/107148120-89b25300-691f-11eb-86b7-4d495a434250.png)

Repeated notifications to the user requesting the show:
![image](https://user-images.githubusercontent.com/12660469/107148126-99319c00-691f-11eb-8263-6d645c115e70.png)

Overseerr screenshot of the TV Show:
![image](https://user-images.githubusercontent.com/12660469/107148166-d4cc6600-691f-11eb-9282-c65fe55cfad4.png)

**Comment by EvilTactician** [comment]
This also happens in my case when the entire show is already available.

Discord Notifications:
![overseerr](https://user-images.githubusercontent.com/39692252/107225268-7fbc4d00-6a10-11eb-888f-ccf7494f221b.png)

Sonarr:
![2021-02-08 13_21_16-Window](https://user-images.githubusercontent.com/39692252/107225394-a5495680-6a10-11eb-9df0-72cdc0d7226a.png)

Overseerr:
![2021-02-08 13_23_04-Window](https://user-images.githubusercontent.com/39692252/107225528-cf9b1400-6a10-11eb-9241-250e239adc03.png)

**Comment by sct** [comment]
This should be solved with https://github.com/sct/overseerr/commit/9b73423d49e1e799cd82764a9ade8c75d92a28a2

Let me know if you still have issues with the latest develop release.

**Comment by EvilTactician** [comment]
This issue is still happening.

![2021-02-25 12_53_08-#requests - Discord](https://user-images.githubusercontent.com/39692252/109159398-77804380-776c-11eb-8757-c37d47f01918.png)

**Comment by rcohen-unext** [comment]
After the fix, you should receive _one more_ notification for the content, and then no more after that.

**Comment by sct** [comment]
The fix in 1.20.0 will trigger _one more_ notification, but you should receive no more after that.

**Comment by EvilTactician** [comment]
Thanks, that means in theory no further notifications should occur - I will provide an update on this tomorrow. (Technically I didn't get one "today" at 4:30am, so that is somewhat promising in that case.)
