### ISSUE TITLE
Anime movies (and some series) in the same Plex library using the HAMA agent, are not detected and marked as available.

### ISSUE THREAD

**Issue by ToaHartor** [sct/overseerr#898]
**Describe the bug**
I'm using the HAMA agent for my anime library on Plex (marked as a TV shows library), which contains both anime series and movies. When I start a Plex Sync, many items (mostly movies, but also happens for some series) get this error in the logs and aren't marked as available. 
For the movies also entered in Radarr, when it fails to detect the item it is marked as "Requested" though. 
Movie example : 
`[error][Plex Sync]: Failed to process Plex item. ratingKey: 55229 {"errorMessage":"Cannot read property 'some' of undefined","plexitem":{"ratingKey":"55229","key":"/library/metadata/55229/children","skipChildren":true,"guid":"com.plexapp.agents.hama://anidb-10937?lang=fr","studio":"Kyoto Animation","type":"show","title":"Koe no Katachi",....`
![silentvoice](https://user-images.githubusercontent.com/41634031/107366657-b06ab800-6ade-11eb-953f-d0a504807923.png)

For the series also entered in Sonarr, they aren't even marked as "Requested".
Serie example :
`[error][Plex Sync]: Failed to process Plex item. ratingKey: 50579 {"errorMessage":"[TMDB] Failed to get TV show using the external TVDB ID: [TMDB] Failed to find a TV show with the provided TVDB ID: 76885","plexitem":{"ratingKey":"50579","key":"/library/metadata/50579/children","skipChildren":true,"guid":"com.plexapp.agents.hama://tvdb-76885?lang=fr","studio":"Sunrise","type":"show","title":"Cowboy Bebop",.....`
![bebop](https://user-images.githubusercontent.com/41634031/107366680-b52f6c00-6ade-11eb-81cd-69a1ca0ab89a.png)

**What version of Overseerr are you running?**
1.19.1

**To Reproduce**

Use the HAMA agent for a Plex TV Shows library, and put both anime series and movies. Then trigger a Plex sync.

**Expected behavior**
Anime movies and series from this library are correctly detected and marked as available.

**Comment by Winter** [comment]
I have the same issue

**Comment by mmozeiko** [comment]
Submitted pull request that fixes Movie lookup - was broken because of some code changes for 4K checks.

As discussed on Discord - Cowboy Bebop issue is on TMDB side, not much to do in overseerr code. They simply don't return any TV show results. Probably need to contact TMDB support if they have any, and ask what is wrong with tvdbid 76885 lookup.
