### ISSUE TITLE
Modify overlays to be more visible

### ISSUE THREAD

**Issue by jrucker2004** [sct/overseerr#900]
**Is your feature request related to a problem? Please describe.**
The current green checkmark used to indicate that something is available is difficult to see when superimposed over images that are a similar color to the green used in the checkmark.
A similar argument could be made for all items that overlay a movie or tv show poster image.

**Describe the solution you'd like**
Modify the checkmark, "movie" overaly, and "series" overlay to make them more visible.  

**Describe alternatives you've considered**
A black outline is often used when using white text to make it more visible on a variety of different colored backgrounds.
Awful MS Paint example below.

**Additional context**
On the left:  Current checkmark
On the right: Example of how a black border around the checkmark makes it much more visible.
![image](https://user-images.githubusercontent.com/19860871/107445549-87075780-6af1-11eb-8ef5-101b487e1951.png)

Example 2:
On the left:  Current "movie" overlay
On the right: Example of how a black border around the "movie" overlay makes it more visible
![image](https://user-images.githubusercontent.com/19860871/107446171-b79bc100-6af2-11eb-9ab8-a2a2969d7f18.png)

**Comment by sct** [comment]
We tried several versions of the checkbox to deal with it over the same color background, including an outline. None of it looked very good.

In the end, everyone felt it's better to stick with how it looks now because the actual cases where the green checkmark is the same color as the poster art is very rare. We are all just noticing it now because of the Wonder Woman poster.

I don't have any plans to change this at this time.

**Comment by costaht** [comment]
If you use another tone of green, it is almost imperceptible when over a nongreen poster but it is easier to see when over a green one

![image](https://user-images.githubusercontent.com/50637431/107460869-e9c71600-6b26-11eb-9ee8-56b984825b35.png)

**Comment by sct** [comment]
> If you use another tone of green, it is almost imperceptible when over a nongreen poster but it is easier to see when over a green one
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/50637431/107460869-e9c71600-6b26-11eb-9ee8-56b984825b35.png)
> 
> 

And if a poster has that same green? Then we run into the same problem.

**Comment by sct** [comment]
Oh the border. Sorry I misread. We tried it. People hated how it looked.

**Comment by costaht** [comment]
What? It was perfectly done...ok then.

**Comment by sct** [comment]
> What? It was perfectly done...ok then.

The border looks really bad in Firefox I think it was? Super pixelated look. It also makes the icon look slightly smaller.

Either way, I don't think anything is wrong with how it is now. Wonder Woman is an edge-case.
