### ISSUE TITLE
Requestor Notifications

### ISSUE THREAD

**Issue by JamesTeague** [sct/overseerr#903]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to be able to notify the requesting user specifically when their request is approved and/or available. Akin to how it is handled with Ombi. Each user having notification preferences to alert them of content updates sooner.

**Describe alternatives you've considered**
I have a general place in a Discord channel where all newly added content is added when Tautulli picks it up. But not all of my users are on Discord or care about all the content that may have been added. I've also sent out a weekly newsletter via email, again to everyone to notify them of new content added that week.

**Comment by samwiseg0** [comment]
This already possible today. Please stop by support if you need help.
