### ISSUE TITLE
Plex doesn't ask password

### ISSUE THREAD

**Issue by GeorgesOrwell** [sct/overseerr#907]
**Describe the bug**
No need to put the password back

**What version of Overseerr are you running?**
1.19.1

You can find it under: Settings -> About -> Version

**To Reproduce**

Log in on Overseerr with your Plex account
Sign out from Overseerr
Sign in back on Overseerr with your Plex account
Plex doesn't ask your password

**Expected behavior**
When you sign in back, Plex must ask you your password

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Chrome, Firefox, Opera,...
- Version the latest

**Smartphone (please complete the following information):**

**Additional context**
The solution: Delete the cookies.

**Comment by TheCatLady** [comment]
Not a bug.  Signing out from Overseerr does not sign you out of Plex, and the Plex login prompt only displays the password input if you are not logged in.

**Comment by GeorgesOrwell** [comment]
With this behavior, everyone can login on my account after me ?!

**Comment by TheCatLady** [comment]
@GeorgesOrwell If you want to log out from Plex, then you need to log out from Plex and not just Overseerr.  Overseerr has no control over your Plex login status.

**Comment by samwiseg0** [comment]
Then make sure you sign out of your Plex account or only use incognito. Again, this is not an overseerr problem

**Comment by GeorgesOrwell** [comment]
It's what you want but, it's not user-friendly

**Comment by samwiseg0** [comment]
I don't think you understand how logins work with Plex oauth. It has nothing do do with it being user friendly. If you have any other application including Plex web they all behave the same. Once you log in it remembers your login information so you don't have log in every time. 

Try logging out of Plex web and see that the login prompt comes back up with your information already populated and all you have to do is hit sign in.
