### ISSUE TITLE
Movie search "The F**k-It List"

### ISSUE THREAD

**Issue by NanobugGG** [sct/overseerr#915]
When you search for "The F**k-It List" it auto writes a bunch of 2's and 5's.
I tried typing it in manually, when I use * it starts.

**Comment by NanobugGG** [comment]
You can get around it by searching for "The F" and it will find it.

**Comment by danshilm** [comment]
This has been fixed in #893 on the develop branch.

**Comment by NanobugGG** [comment]
I didn't know that.
It's the first issue I've encounted, so I'm happy with it so far.
Thank you for the response though :)
