### ISSUE TITLE
Can't change language and quality of request as not-main-admin

### ISSUE THREAD

**Issue by wemiprog** [sct/overseerr#916]
**Describe the bug**
A user, who isn't the main admin can't change quality and language settings from requests (testet only with his own requests).

**What version of Overseerr are you running?**
1.18.0

**To Reproduce**

With a user, who has the right to manage requests and advanced requests:
1. Go to main page
2. Search a new film, request it (without auto approval)
3. Go to requests
4. Click on edit request just made
5. Click on edit in popup
Now, sometimes an error appears, other times a success message, but it isn't possible to edit the values, they aren't even displayed.

**Expected behavior**
Settings may be changed

**Screenshots**
![image](https://user-images.githubusercontent.com/28563189/107794115-54f72f00-6d57-11eb-8f96-546c44ed970b.png)
![image](https://user-images.githubusercontent.com/28563189/107794140-5d4f6a00-6d57-11eb-9638-220ebeb32059.png)
![image](https://user-images.githubusercontent.com/28563189/107794172-65a7a500-6d57-11eb-8347-8001958e25b6.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser MS Edge (the new one)
- Version: 88.0.705.63

**Comment by samwiseg0** [comment]
They need to have the the advanced user request permission.
<img width="590" alt="Screen Shot 2021-02-13 at 12 58 41 AM" src="https://user-images.githubusercontent.com/2241731/107843159-bdb1cc00-6d96-11eb-8c57-11bf656937b0.png">

**Comment by samwiseg0** [comment]
Reopening> after further testing I see what you mean.

**Comment by TheCatLady** [comment]
So the issue here isn't that the user doesn't have the required permissions, but that since they have the "Manage Requests" permission their requests are automatically approved.  Editing already-approved requests is not yet supported.

**Comment by TheCatLady** [comment]
In #908, I added some clarification to the description of the "Manage Requests" permission.  Also, when the "Manage Requests" permission is selected, the "Auto-Approve" permissions will now automatically be selected and grayed out.

The issue with allowing editing of already-approved requests is a bigger one that needs to be carefully considered.  We do not currently remove items from Sonarr/Radarr/Plex, and adding such behavior could potentially result in accidental/unwanted deletion of content.

**Comment by sct** [comment]
I am not sure how they can edit something approved in the first place? We just shouldn't be letting that happen.

**Comment by sct** [comment]
I am closing this until we see it pop up again.
