### ISSUE TITLE
Not require Plex (or any other media player).

### ISSUE THREAD

**Issue by Akirainblack** [sct/overseerr#917]
**Is your feature request related to a problem?
No

**Describe the solution you'd like**
I'd like to be able to use/test Overseerr without requiring Plex. I don't use it, don't want it.
Does Overseerr really need to integrate with Plex (or any media player) to be used?

**Describe alternatives you've considered**
I hate to say it but Ombi works without Plex or Emby or Jellyfin. It works without needing a media player to interface with.

**Comment by sct** [comment]
There are already feature requests for both Emby (https://github.com/sct/overseerr/issues/295) and Jellyfin (https://github.com/sct/overseerr/issues/288). Follow those for updates.

Until we add more, Plex is the only supported media server.

**Comment by Akirainblack** [comment]
I'm not asking for EMBY OR JELLYFIN support!!
I'm asking for it to be possible to use this without a media server.

**Comment by TheCatLady** [comment]
> I'm not asking for EMBY OR JELLYFIN support!!
> I'm asking for it to be possible to use this without a media server.
> "**without** Plex or Emby or Jellyfin"

Why would you want to use Overseerr without a connected media server?  The beauty of Overseerr and what sets it apart from other request management systems is its integration with Radarr/Sonarr **_AND_** your media server.  Overseerr keeps track of the availability of content from all of these sources, and makes it easy to navigate from the Overseerr media detail pages to the relevant locations in your connected services.

Also, no need to yell or get upset.  I understand from your posts in other servers on Discord that you have a strong aversion to using Plex, but there are other options if Overseerr is not the right fit for your use case.
