### ISSUE TITLE
List View

### ISSUE THREAD

**Issue by zsmbrvr** [sct/overseerr#929]
**Is your feature request related to a problem? Please describe.**
It would be nice if overseerr would have a list view and not just a grid view, simmilar to radarr's "overview"

**Describe the solution you'd like**
List view implemented

**Describe alternatives you've considered**
Ombi

**Additional context**
Something like this.

https://wiki.servarr.com/images/thumb/3/36/Radarr-discover-add-new-movies.png/900px-Radarr-discover-add-new-movies.png

**Comment by sct** [comment]
A list view for what exactly? Can you be more descriptive of what you actually want here? Where would this list view be? What behavior are you expecting? Why a screenshot of Radarr?

**Comment by zsmbrvr** [comment]
List view for the media one can request. 

Grid view is nice, if you know exactly what you want and are happy only seeing the movie/show poster. If you use overseer in a different language, for ex, it a bit difficult to realise what movie X is in your own language. 
Plus having to hover on a poster to see details about it is not as user friendly as having the title and a short description next to it.

The screenshot is just so you have an idea of how it would look.

**Comment by sct** [comment]
After giving this some thought, I don't see us adding this any time soon. It's a ton of work and isn't on the cards at the moment. Maybe sometime in the distant future, we can add options for how to view the lists of content.
