### ISSUE TITLE
Hide ability to request Shows OR Movies

### ISSUE THREAD

**Issue by zsmbrvr** [sct/overseerr#930]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could set a user's ability to see and request movies or tv show **only**. 

**Describe the solution you'd like**
Hide shows  **OR** moveis from the UI.

**Describe alternatives you've considered**
ombi 

**Additional context**
Sometimes you don't want people to request stuff you don't want to get. It's easier just to hide the possibility than to try to explain why.

**Comment by mmaghometech** [comment]
Would love to also see this feature as someone who does not have Sonarr configured to Overseerr.  Other than that great but the only real missing feature for me.  Been testing this app and already had users thinking I added the ability to request and watch TV.

**Comment by PhAzE-Variance** [comment]
+1 on this. 

TV shows in their entirety can very quickly consume your available disk space so having control over who can and can't request them would be largely beneficial.
