### ISSUE TITLE
add option this connect only with a nickname and without password 

### ISSUE THREAD

**Issue by tony77682** [sct/overseerr#939]
**Is your feature request related to a problem? Please describe.**

I am currently using OMBI, only one option is missing so that I definitely switch to OVERSEER.
On OMBI there is the option "allow users to connect without password", my users are currently connecting with their nickname 

**Describe the solution you'd like**

is it possible to add this functionality, and allow users to log in only with the nickname?

**Additional context**
 in OMBI:
![image](https://user-images.githubusercontent.com/45037826/107926913-97e31d80-6f76-11eb-8a41-55d9fb6f9096.png)
![image](https://user-images.githubusercontent.com/45037826/107926996-b34e2880-6f76-11eb-8cfe-1dc6f90e5998.png)

**Comment by sct** [comment]
This is a huge security hole. Why would you want this?

**Comment by tony77682** [comment]
because the requests of my users will not be validated automatically anyway
and
that my users are novice and will constantly be asking me for their password

**Comment by sct** [comment]
Just because requests will not be automatically approved does not make it any less of a security hole. Make their passwords easy for them to remember?

This will not be implemented.

**Comment by tony77682** [comment]
but if an option to activate with a warning pop-up. after that is the problem of the server administrator.
I can tell you that several people are interested in this option on discord!

**Comment by sct** [comment]
We will not compromise security because people are unable to remember their passwords. Even with warnings, we would be encouraging people to open their servers to the internet without proper protection.
