### ISSUE TITLE
Support for many webhooks

### ISSUE THREAD

**Issue by EternalDeiwos** [sct/overseerr#972]
**Is your feature request related to a problem? Please describe.**
The build-your-own-payload webhook feature is amazing; however I have multiple services that I would like to notify.

**Describe the solution you'd like**
Refactor to allow zero or more notification webhooks to be registered.

**Comment by TheCatLady** [comment]
I think that allowing multiple webhooks would add unnecessary complexity.  You can simply have your configured webhook send requests to each service you'd like to notify.

**Comment by EternalDeiwos** [comment]
Yeah I was hoping to avoid writing another service to do that... and to take advantage of the payload configuration already part of Overseerr.

**Comment by TheCatLady** [comment]
> Yeah I was hoping to avoid writing another service to do that... and to take advantage of the payload configuration already part of Overseerr.

I highly recommend adnanh/webhook, I personally use it.  I actually thought I wanted support for multiple webhooks previously as well, but I have since realized that it is actually more ideal to have a single webhook containing all of the processing I want to do.

**Comment by EternalDeiwos** [comment]
Thanks, will take a look.

**Comment by hansenc0705** [comment]
I hope this doesn't trigger the issue to reopen but wanted to share another method for those who need multiple webhooks. You could sign up for an account at integromat.com. They have a free tier that would allow you to bring in a webhook and route or distribute to other webhooks (among other things).

Within your Scenario add a new webhook and in that screen click advanced and select JSON pass-through. From there you need to Re-determine data structure and a Router and multiple HTTP > Make a request modules with settings of body type=raw, content type=json, request content=value from webhook in step #1 to forward the Overseerr JSON payload off to other webhooks.

Here is a facebook post about this method, instructions are in the comments.
https://www.facebook.com/groups/integromat/posts/4351029735007626/

**Comment by davidnewhall** [comment]
> I think that allowing multiple webhooks would add unnecessary complexity.

There's no other web hook-supporting app in this ecosystem that only supports 1, not even Plex. There are a number of users requesting this from projects I work on. Please reconsider lifting this burden from others.
