### ISSUE TITLE
Improvements to the header on Safari for iOS (Progressive Web App)

### ISSUE THREAD

**Issue by tdeverx** [sct/overseerr#991]
#### Description

Currently, when you add Overseerr to your home screen as a Progressive Web App, the header has a black bar at the top to accommodate for the "notch". However, this is easily fixed with a little bit of code.

#### Desired Behavior

Have the background expand to the top of the screen

#### Additional Context

You may refer to this blog post on how to implement the fix
https://medium.com/appscope/changing-the-ios-status-bar-of-your-progressive-web-app-9fc8fbe8e6ab

**Comment by TheCatLady** [comment]
Implemented in 958cdf98fd1cb7c1bdb33aebb6c061750e9ab331

**Comment by exentler** [comment]
![Screenshot_20220123-101833](https://user-images.githubusercontent.com/76279565/150672139-da0e4ed6-e34c-4cf2-a353-e537efae8635.jpg)

It is possible fix similar with  the buttom field at Android? Sceenshot is taken with One plus 9 pro
