### ISSUE TITLE
Add User Permission to see Movie/TvShow Download Status

### ISSUE THREAD

**Issue by mous2890** [sct/overseerr#994]
#### Description

When a user requests a movie/tvshow for the admin to approve and then movie/tvshow is approved and subsequently downloading, the state transitions to "processing". Whilst in processing, only the admin can see the state of the movie/tvshow downloading with an ETA and percentage completion bar.

#### Desired Behavior

Please add a permission e.g. Download Status that will allow the admin to grant users the ability to see the status of movies/tvshows that are downloading.

**Comment by WoisWoi** [comment]
I am in favour of adding such a feature :) 
It would also be a good idea, in my opinion, to add an intermediate status ("downloaded") after downloading the file and before availability, for people who are in my case, that is, who stores his media on a drive (cloud).

**Comment by sct** [comment]
> I am in favour of adding such a feature :)
> It would also be a good idea, in my opinion, to add an intermediate status ("downloaded") after downloading the file and before availability, for people who are in my case, that is, who stores his media on a drive (cloud).

We only track it for as long as Sonarr knows about it. We also can't really be sure if it failed or succeeded. So I am not sure if there is a way to really deal with this.

**Comment by mous2890** [comment]
It's possible my feature request has been misunderstood. 

What I am essentially requesting is the ability for users, who are not admin, to see the download status of a movie whilst it is downloading. 

Once the movie is downloaded, then the movie transitions from processing to the usual available state. 

Please see screenshot below for reference of what I mean by download status. 

![Screenshot_20210225-074957](https://user-images.githubusercontent.com/26714548/109120783-4c7efb00-773e-11eb-9c08-b780814d20c0.png)

**Comment by sct** [comment]
Your feature request hasn't been misunderstood, I was just replying to the other comment.

I have plans for another view for download status. It will act differently than the slideout panel but you will be able to give users access to it.

**Comment by mous2890** [comment]
That would be amazing. Thank you.

**Comment by WoisWoi** [comment]
> 
> 
> > I am in favour of adding such a feature :)
> > It would also be a good idea, in my opinion, to add an intermediate status ("downloaded") after downloading the file and before availability, for people who are in my case, that is, who stores his media on a drive (cloud).
> 
> We only track it for as long as Sonarr knows about it. We also can't really be sure if it failed or succeeded. So I am not sure if there is a way to really deal with this.

Perhaps we can setup a webhook on "import" to inform Overseerr that the file was downloaded and successfully picked up by Sonarr /Radarr.

**Comment by douglasparker** [comment]
I'd really like to see this implemented. :)

**Comment by douglasparker** [comment]
bump

**Comment by sadstan** [comment]
bump

**Comment by prattable** [comment]
To avoid this from being Closed and as I would also like this feature, I am making this comment.

**Comment by mous2890** [comment]
Is there a rough timeline on when this feature might be implemented?

**Comment by douglasparker** [comment]
.

**Comment by asherbig** [comment]
Has development of this feature started? Are contributions welcome?

**Comment by WoisWoi** [comment]
> 

Contribution are always welcome 👍🏼 :) !
Perhaps you could join the discord to talk about it.

**Comment by TheCatLady** [comment]
> Has development of this feature started? Are contributions welcome? I would be interested in working on it but if you have already started implementation, then I don't want to interfere.

I believe @sct had some ideas for how he wanted this to look, but not sure if anything is already in the works.  @sct?

**Comment by AyaanZaveri** [comment]
Any updates?

**Comment by BaldissaraMatheus** [comment]
Guys, do we have any updates on this? I'd also be willing to contribute if needed

**Comment by Andrerm124** [comment]
I'd also be willing to contribute to this feature. Feels like an important feature for users, as an idea of how long they might wait for a download would be really useful

**Comment by kevkevhd** [comment]
Sorry for the duplicate, any updates on this feature?

**Comment by Laiteux** [comment]
This might be relevant for anyone stumbling upon this issue or looking for this feature: https://github.com/sct/overseerr/issues/3028#issuecomment-1251577092
