### ISSUE TITLE
Idea: Migration wizard to import settings from Ombi

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#995]
#### Description
To make it easier for an admin to switch from Ombi, maybe we can consider a migration option to import existing settings from de ombi database and migrate it to Overseerr?

#### Desired Behavior
Extra option in the installation wizard to import an existing ombi database and migrate it to an Overseerr database <3

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by sct** [comment]
No plans for this. Sorry.
